In [170]:
import os
import json
import hashlib
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from umap import UMAP
import hdbscan
from sklearn.cluster import AgglomerativeClustering
from anytree import Node, RenderTree

warnings.filterwarnings("ignore")

In [172]:
df = pd.read_json("D:/git/Taxonomy_Buidling_Textual_Corpora/data/icecat_data_train.json")

# Work only with first 5000 rows from the beginning
df = df.iloc[:5000].copy()

print("Raw sample size:", len(df))

Raw sample size: 5000

In [173]:
def split_path(path):
    if not isinstance(path, str):
        return []
    parts = [p.strip() for p in path.split(">") if p.strip()]
    return parts

df["num_levels"] = df["pathlist_names"].apply(lambda x: len(split_path(x)))

print("Counts BEFORE cleaning:")
print(df["num_levels"].value_counts().sort_index())

Counts BEFORE cleaning:
num_levels
3    2883
4    2117
Name: count, dtype: int64

In [174]:
import pandas as pd

def make_3_and_4(path):
    parts = split_path(path)

    # default
    path_3 = None
    level_4 = None

    if len(parts) >= 3:
        path_3 = " > ".join(parts[:3])   # A > B > C
    if len(parts) >= 4:
        level_4 = parts[3]               # D (4th level)

    return pd.Series({"path_3": path_3, "level_4": level_4})

df[["path_3", "level_4"]] = df["pathlist_names"].apply(make_3_and_4)

print(df[["pathlist_names", "path_3", "level_4"]].head(10))

                                            pathlist_names  \
1072689  Computers & Electronics>Computers>PCs/Workstat...
906402   Computers & Electronics>Computers>Notebook Par...
411281   Computers & Electronics>Computer Cables>Fibre ...
425903   Computers & Electronics>Computers>Handheld Mob...
1047582  Computers & Electronics>Computers>PCs/Workstat...
904910   Computers & Electronics>Computers>Notebook Par...
157385   Computers & Electronics>Software>Software Lice...
934548   Computers & Electronics>Computers>Notebook Par...
876762   Computers & Electronics>Computers>Notebook Par...
397028   Computers & Electronics>Telecom & Navigation>M...

                                                    path_3  \
1072689  Computers & Electronics > Computers > PCs/Work...
906402   Computers & Electronics > Computers > Notebook...
411281   Computers & Electronics > Computer Cables > Fi...
425903   Computers & Electronics > Computers > Handheld...
1047582  Computers & Electronics > Computers > PCs/Work...
904910   Computers & Electronics > Computers > Notebook...
157385   Computers & Electronics > Software > Software ...
934548   Computers & Electronics > Computers > Notebook...
876762   Computers & Electronics > Computers > Notebook...
397028   Computers & Electronics > Telecom & Navigation...

                      level_4
1072689                  None
906402   Notebook Spare Parts
411281                   None
425903                   None
1047582                  None
904910   Notebook Spare Parts
157385                   None
934548   Notebook Spare Parts
876762   Notebook Spare Parts
397028                   None

In [175]:
print("Rows:", len(df))
print("Unique num_levels (original):")
print(df["num_levels"].value_counts().sort_index())

print("\nCheck how many have a 4th level stored:")
print(df["level_4"].notna().sum(), "rows with level_4")

Rows: 5000
Unique num_levels (original):
num_levels
3    2883
4    2117
Name: count, dtype: int64

Check how many have a 4th level stored:
2117 rows with level_4

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 1072689 to 1121736
Data columns (total 48 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       5000 non-null   object
 1   BrandInfo.BrandLocalName                    5000 non-null   object
 2   BrandInfo.BrandLogo                         4994 non-null   object
 3   BrandInfo.BrandName                         5000 non-null   object
 4   BrandLogo                                   4994 non-null   object
 5   BrandPartCode                               5000 non-null   object
 6   BulletPoints                                4654 non-null   object
 7   Category.CategoryID                         5000 non-null   int64
 8   Category.Name.Language                      5000 non-null   object
 9   Category.Name.Value                         5000 non-null   object
 10  Description.Disclaimer                      4440 non-null   object
 11  Description.ID                              4440 non-null   float64
 12  Description.LeafletPDFURL                   4440 non-null   object
 13  Description.LongDesc                        4440 non-null   object
 14  Description.LongProductName                 4440 non-null   object
 15  Description.ManualPDFSize                   4370 non-null   float64
 16  Description.ManualPDFURL                    4440 non-null   object
 17  Description.MiddleDesc                      4440 non-null   object
 18  Description.PDFSize                         4412 non-null   float64
 19  Description.URL                             4378 non-null   object
 20  Description.Updated                         4440 non-null   object
 21  EndOfLifeDate                               5000 non-null   object
 22  GTIN                                        5000 non-null   object
 23  IcecatId                                    5000 non-null   int64
 24  ProductFamily.ProductFamilyID               5000 non-null   int64
 25  ProductName                                 5000 non-null   object
 26  ProductSeries.SeriesID                      5000 non-null   int64
 27  ReleaseDate                                 5000 non-null   object
 28  SummaryDescription.LongSummaryDescription   5000 non-null   object
 29  SummaryDescription.ShortSummaryDescription  5000 non-null   object
 30  Title                                       5000 non-null   object
 31  Description.WarrantyInfo                    2654 non-null   object
 32  Description                                 560 non-null    object
 33  ProductFamily.Language                      1106 non-null   object
 34  ProductFamily.Value                         1106 non-null   object
 35  ProductSeries.Language                      718 non-null    object
 36  ProductSeries.Value                         718 non-null    object
 37  BulletPoints.BulletPointsId                 346 non-null    float64
 38  BulletPoints.Language                       346 non-null    object
 39  BulletPoints.Updated                        346 non-null    object
 40  BulletPoints.Values                         346 non-null    object
 41  VirtualCategory                             417 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                5000 non-null   object
 44  pathlist_names                              5000 non-null   object
 45  num_levels                                  5000 non-null   int64
 46  path_3                                      5000 non-null   object
 47  level_4                                     2117 non-null   object
dtypes: float64(5), int64(5), object(38)
memory usage: 1.9+ MB

In [177]:
# Extract A, B, C from path_3
df[["A", "B", "C"]] = (
    df["path_3"]
    .str.split(">", expand=True)
    .apply(lambda col: col.str.strip())
)

In [178]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...,3,Computers & Electronics > Computers > Handheld...,None,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations

In [179]:
# Basic Stats
print("Total products:", len(df))
print("Unique A-level:", df["A"].nunique())
print("Unique B-level:", df["B"].nunique())
print("Unique C-level:", df["C"].nunique())

Total products: 5000
Unique A-level: 1
Unique B-level: 17
Unique C-level: 160

In [180]:
#Distribution of A / B / C/
print("\nProducts per A-level:")
print(df["A"].value_counts())

print("\nProducts per B-level (top 10):")
print(df["B"].value_counts().head(20))

print("\nProducts per C-level (top 10):")
print(df["C"].value_counts().head(20))

print("\nProducts per C-level (bottom 10):")
print(df["C"].value_counts().tail(10))

Products per A-level:
A
Computers & Electronics    5000
Name: count, dtype: int64

Products per B-level (top 10):
B
Computers                           2202
Printers & Scanners                  368
Computer Components                  330
Warranty & Support                   318
Software                             296
Data Storage                         284
TVs & Monitors                       251
Computer Cables                      205
Telecom & Navigation                 189
Batteries & Power Supplies           141
Data Input Devices                   111
Consumer Audio & Video Equipment     110
Projectors                            73
Photo & Video Equipment               66
Networking                            47
Office Electronics                     7
Smart Wearables                        2
Name: count, dtype: int64

Products per C-level (top 10):
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
TVs                                76
Computer Monitors                  68
Networking Cables                  67
Print & Scan Accessories           64
Power Adapters & Inverters         63
Printing Equipment                 63
All-in-One PCs/Workstations        60
Mobile Phone Cases                 55
Antivirus Security Software        53
Flat Panel Spare Parts             42
Name: count, dtype: int64

Products per C-level (bottom 10):
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

In [181]:
# C-level Imbalance Quantiles
# (This shows how skewed leaf categories are)
prod_per_C = df["C"].value_counts()

print("\nC-level product quantiles:")
print(prod_per_C.quantile([0.1, 0.25, 0.5, 0.75, 0.9]))

C-level product quantiles:
0.10     1.0
0.25     2.0
0.50     5.0
0.75    14.0
0.90    60.3
Name: count, dtype: float64

In [182]:
# Basic counts
print("Total products:", len(df))
print("Unique A levels:", df["A"].nunique())
print("Unique B levels:", df["B"].nunique())
print("Unique C levels:", df["C"].nunique())

# Compute product counts
prod_A = df["A"].value_counts()
prod_B = df["B"].value_counts()
prod_C = df["C"].value_counts()

Total products: 5000
Unique A levels: 1
Unique B levels: 17
Unique C levels: 160

In [183]:
# Identify problematic A/B/C categories
# Very large categories (top 10)
print("\n🔥 TOP 10 LARGEST C categories:")
print(prod_C.head(10))

# Very small categories (bottom 10)
print("\n❗ BOTTOM 10 SMALLEST C categories:")
print(prod_C.tail(10))

# C categories with < 10 products
weak_C = prod_C[prod_C < 10]
print("\n❗ Weak C categories (<10 products):", len(weak_C))
print(weak_C.head(20))

# B categories with < 3 C children
C_children_per_B = df.groupby("B")["C"].nunique()
weak_B = C_children_per_B[C_children_per_B < 3]

print("\n❗ Weak B categories (<3 C children):", len(weak_B))
print(weak_B.head(20))

🔥 TOP 10 LARGEST C categories:
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
Name: count, dtype: int64

❗ BOTTOM 10 SMALLEST C categories:
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

❗ Weak C categories (<10 products): 107
C
Telephony Equipment                 9
Computer Utilities                  9
Mobile Device Chargers              8
Photographic Filmmaking Supplies    8
AV Extenders                        8
Portable Speakers                   7
Home Audio Sets                     7
Projector Accessories               7
DVD/Blu-Ray Players                 6
Flat Panel Mount Accessories        6
Thin Clients                        6
Projector Mounts                    6
Stylus Pens                         6
Mobile Phones                       6
Radios                              6
Flat Panel Floor Stands             6
KVM Cables                          6
Display Privacy Filters             6
Video Cable Adapters                6
Handheld Device Accessories         5
Name: count, dtype: int64

❗ Weak B categories (<3 C children): 2
B
Data Storage       2
Smart Wearables    2
Name: C, dtype: int64

In [184]:
#Identify dominant categories (too large)
# Very large C categories (skewing the distribution)
dominant_C = prod_C[prod_C > prod_C.quantile(0.95)]

print("\n🔥 Dominant C categories (>95th percentile):", len(dominant_C))
print(dominant_C)

🔥 Dominant C categories (>95th percentile): 8
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Name: count, dtype: int64

In [185]:
B_summary = (
    df.groupby(["A", "B"])
      .agg(num_products=("C", "count"),
           num_C=("C", "nunique"))
      .reset_index()
      .sort_values("num_products", ascending=False)
)

print(" B-level imbalance summary:")
print(B_summary.head(20))

 B-level imbalance summary:
                          A                                 B  num_products  \
3   Computers & Electronics                         Computers          2202
10  Computers & Electronics               Printers & Scanners           368
2   Computers & Electronics               Computer Components           330
16  Computers & Electronics                Warranty & Support           318
13  Computers & Electronics                          Software           296
6   Computers & Electronics                      Data Storage           284
14  Computers & Electronics                    TVs & Monitors           251
1   Computers & Electronics                   Computer Cables           205
15  Computers & Electronics              Telecom & Navigation           189
0   Computers & Electronics        Batteries & Power Supplies           141
5   Computers & Electronics                Data Input Devices           111
4   Computers & Electronics  Consumer Audio & Video Equipment           110
11  Computers & Electronics                        Projectors            73
9   Computers & Electronics           Photo & Video Equipment            66
7   Computers & Electronics                        Networking            47
8   Computers & Electronics                Office Electronics             7
12  Computers & Electronics                   Smart Wearables             2

    num_C
3      18
10      5
2       3
16      4
13      6
6       2
14     17
1      23
15     13
0      12
5       3
4      26
11      7
9       3
7      13
8       3
12      2

In [186]:
def report_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C=("C", "nunique"),
              num_products=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]
        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C']}")
            print(f"    #products (total under this B): {row['num_products']}")

In [187]:
report_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 12
    #products (total under this B): 141
  B: Computer Cables
    #C-level subcategories: 23
    #products (total under this B): 205
  B: Computer Components
    #C-level subcategories: 3
    #products (total under this B): 330
  B: Computers
    #C-level subcategories: 18
    #products (total under this B): 2202
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 26
    #products (total under this B): 110
  B: Data Input Devices
    #C-level subcategories: 3
    #products (total under this B): 111
  B: Data Storage
    #C-level subcategories: 2
    #products (total under this B): 284
  B: Networking
    #C-level subcategories: 13
    #products (total under this B): 47
  B: Office Electronics
    #C-level subcategories: 3
    #products (total under this B): 7
  B: Photo & Video Equipment
    #C-level subcategories: 3
    #products (total under this B): 66
  B: Printers & Scanners
    #C-level subcategories: 5
    #products (total under this B): 368
  B: Projectors
    #C-level subcategories: 7
    #products (total under this B): 73
  B: Smart Wearables
    #C-level subcategories: 2
    #products (total under this B): 2
  B: Software
    #C-level subcategories: 6
    #products (total under this B): 296
  B: TVs & Monitors
    #C-level subcategories: 17
    #products (total under this B): 251
  B: Telecom & Navigation
    #C-level subcategories: 13
    #products (total under this B): 189
  B: Warranty & Support
    #C-level subcategories: 4
    #products (total under this B): 318

In [188]:
def report_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products']} products)")

In [189]:
report_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Battery Chargers  (4 products)
    C: Household Batteries  (11 products)
    C: Notebook Power Tips  (2 products)
    C: Portable Device Management Carts & Cabinets  (1 products)
    C: Power Adapters & Inverters  (63 products)
    C: Power Banks  (4 products)
    C: Power Distribution Units (PDUs)  (11 products)
    C: Power Supply Units  (16 products)
    C: UPS Batteries  (3 products)
    C: UPS Battery Cabinets  (1 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
  B: Computer Cables
    C: Audio Cables  (3 products)
    C: Cable Interface/Gender Adapters  (20 products)
    C: Cable Protectors  (2 products)
    C: Coaxial Cables  (4 products)
    C: DVI Cables  (5 products)
    C: DisplayPort Cables  (3 products)
    C: Fibre Optic Cables  (29 products)
    C: FireWire Cables  (1 products)
    C: HDMI Cables  (11 products)
    C: InfiniBand Cables  (1 products)
    C: KVM Cables  (6 products)
    C: Lightning Cables  (3 products)
    C: Networking Cables  (67 products)
    C: Power Cables  (12 products)
    C: S-Video Cables  (1 products)
    C: SATA Cables  (5 products)
    C: SCART Cables  (1 products)
    C: SCSI Cables  (2 products)
    C: Serial Attached SCSI (SAS) Cables  (2 products)
    C: USB Cables  (14 products)
    C: VGA Cables  (2 products)
    C: Video Cable Adapters  (6 products)
    C: Wire Connectors  (5 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: Interface Components  (5 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Backpack PCs  (1 products)
    C: E-Book Reader Cases  (3 products)
    C: E-Book Readers  (1 products)
    C: Handheld Device Accessories  (5 products)
    C: Handheld Mobile Computer Spare Parts  (1 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PC/Workstation Barebones  (4 products)
    C: PCs/Workstations  (227 products)
    C: POS Systems  (5 products)
    C: Server Barebones  (10 products)
    C: Servers  (15 products)
    C: Stylus Pens  (6 products)
    C: Tablet Cases  (25 products)
    C: Tablet Spare Parts  (1 products)
    C: Tablets  (39 products)
    C: Thin Clients  (6 products)
  B: Consumer Audio & Video Equipment
    C: AV Extenders  (8 products)
    C: AV Receivers  (1 products)
    C: Audio Equipment Parts & Accessories  (23 products)
    C: CD Players  (2 products)
    C: Cassette Players  (1 products)
    C: Computer TV Tuners  (2 products)
    C: DVD/Blu-Ray Players  (6 products)
    C: Dictaphones  (4 products)
    C: Digital Media Players  (2 products)
    C: Docking Speakers  (1 products)
    C: Home Audio Sets  (7 products)
    C: Home Cinema Systems  (5 products)
    C: Loudspeakers  (5 products)
    C: MP3/MP4 Player Cases  (3 products)
    C: MP3/MP4 Players  (5 products)
    C: Portable DVD/Blu-Ray Players  (2 products)
    C: Portable Speakers  (7 products)
    C: Portable Stereo Systems  (1 products)
    C: Public Address (PA) Systems  (1 products)
    C: Radios  (6 products)
    C: Remote Controls  (4 products)
    C: Soundbar Speakers  (5 products)
    C: Speaker Sets  (4 products)
    C: USB Graphics Adapters  (1 products)
    C: Video Capturing Devices  (2 products)
    C: Video Switches  (2 products)
  B: Data Input Devices
    C: KVM Switches  (10 products)
    C: Keyboards  (85 products)
    C: Mice  (16 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
    C: Data Storage Mediums  (11 products)
  B: Networking
    C: ISDN Access Devices  (1 products)
    C: Network Antennas  (1 products)
    C: Network Extenders  (1 products)
    C: Network Media Converters  (3 products)
    C: Network Switch Components  (1 products)
    C: Network Switch Modules  (2 products)
    C: Network Switches  (15 products)
    C: Network Transceiver Modules  (12 products)
    C: Patch Panels  (1 products)
    C: PowerLine Network Adapters  (2 products)
    C: Remote Management Adapters  (1 products)
    C: WLAN Access Points  (3 products)
    C: Wireless Routers  (4 products)
  B: Office Electronics
    C: Calculators  (5 products)
    C: Fax Machines  (1 products)
    C: Laminator Pouches  (1 products)
  B: Photo & Video Equipment
    C: Camera Accessories  (19 products)
    C: Cameras & Camcorders  (39 products)
    C: Photographic Filmmaking Supplies  (8 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
    C: Scanning Equipment  (5 products)
  B: Projectors
    C: Data Projectors  (17 products)
    C: Projection Lenses  (3 products)
    C: Projection Screens  (25 products)
    C: Projector Accessories  (7 products)
    C: Projector Lamps  (11 products)
    C: Projector Mount Accessories  (4 products)
    C: Projector Mounts  (6 products)
  B: Smart Wearables
    C: Activity Trackers  (1 products)
    C: Sport Watch Accessories  (1 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Computer Utilities  (9 products)
    C: Multimedia Software  (5 products)
    C: Networking Software  (1 products)
    C: Operating Systems  (1 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Digital Photo Frames  (2 products)
    C: Display Privacy Filters  (6 products)
    C: Flat Panel Accessories  (2 products)
    C: Flat Panel Ceiling Mounts  (3 products)
    C: Flat Panel Desk Mounts  (4 products)
    C: Flat Panel Floor Stands  (6 products)
    C: Flat Panel Mount Accessories  (6 products)
    C: Flat Panel Spare Parts  (42 products)
    C: Flat Panel Wall Mounts  (10 products)
    C: Hospitality TVs  (2 products)
    C: Signage Displays  (14 products)
    C: Stereoscopic 3D Glasses  (2 products)
    C: TVs  (76 products)
    C: Touch Screen Monitors  (5 products)
    C: Touch Screen Overlays  (1 products)
    C: Video Splitters  (2 products)
  B: Telecom & Navigation
    C: Holders  (4 products)
    C: Mobile Device Chargers  (8 products)
    C: Mobile Device Keyboards  (10 products)
    C: Mobile Headsets  (12 products)
    C: Mobile Phone Cases  (55 products)
    C: Mobile Phone Spare Parts  (14 products)
    C: Mobile Phones  (6 products)
    C: Navigational Equipment  (3 products)
    C: Peripheral Device Cases  (1 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
    C: Telephony Equipment  (9 products)
    C: Two-Way Radios  (1 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Installation Services  (2 products)
    C: Maintenance & Support Fees  (1 products)
    C: Warranty & Support Extensions  (288 products)

In [190]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...,3,Computers & Electronics > Computers > Handheld...,None,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations

In [191]:
df[['ProductName',"BrandPartCode"]]

                                               ProductName   BrandPartCode
1072689                                       K31CD-IT049T    K31CD-IT049T
906402                                          686915-A41      686915-A41
411281   1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...           37745
425903                                             FA889AA     FA889AA#AC3
1047582                                                C30         109559U
...                                                    ...             ...
231002                                            490-BDZR        490-BDZR
978436                                      SIC1094057LCD0  SIC1094057LCD0
1101608          Elite Slice G2 with Microsoft Teams Rooms         6GV21PA
66861                                                 T300     T300.ADEUPK
1121736                             Powerware 9155-10-NT-0         1023113

[5000 rows x 2 columns]

In [192]:
def report_ABC_products(df):
    for a in df["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        dfA = df[df["A"] == a]

        for b in dfA["B"].unique():
            print(f"  B: {b}")
            dfB = dfA[dfA["B"] == b]

            for c in dfB["C"].unique():
                dfC = dfB[dfB["C"] == c]
                print(f"    C: {c}  ({len(dfC)} products)")
                
                # show top 10 product codes
                for code in dfC["ProductName"].fillna("").head(10):
                    print(f"        • {code}")

In [193]:
report_ABC_products(df)

A: Computers & Electronics
================================================================================
  B: Computers
    C: PCs/Workstations  (227 products)
        • K31CD-IT049T
        • C30
        • UN42-M031M
        • P310
        • 875-1303ng
        • 400 G6
        • M910q
        • 3 VR7RD-037US
        • 400 G4 + EliteDisplay E223
        • ProDesk 600 G3 Desktop Mini PC
    C: Notebook Parts & Accessories  (1019 products)
        • 686915-A41
        • 659501-BB1
        • 00HT024
        • 448002-001
        • Top Cover & Keyboard (Italy)
        • 25212106
        • SIC1085866LCD0
        • P000453890
        • SIC1099842LCD0
        • 25207264
    C: Handheld Mobile Computer Spare Parts  (1 products)
        • FA889AA
    C: Notebooks  (774 products)
        • V3-371-35U2
        • GE72 2QC(Apache)-209NL
        • P2510-M-54EH
        • GF72 8RE-062X
        • 15-ay045ns
        • GX531GX-ES016T
        • 460
        • 840 G5
        • R30-A-17G
        • UX310UF-FC002T
    C: Servers  (15 products)
        • x3550 M5
        • RD230
        • RX100 S7
        • R730
        • ThinkSystem ST550
        • RD450
        • RX300 S7
        • RS160
        • RX350 S8
        • TX100 S3
    C: Tablets  (39 products)
        • 510
        • 10.1
        • TF303K-1B031A
        • SM-T813N
        • 10
        • XE300TZC
        • SM-T677
        • S70G10-0N
        • Tab E8
        • SM-T713N
    C: All-in-One PCs/Workstations  (60 products)
        • C20-05
        • Z240ICGK-GC069X
        • 801
        • 27-xa0006nw
        • 24-f0098na
        • ET2311IUTH-BG006T
        • 20-c424nl
        • 24 2M-004RU
        • 23-q010in
        • 27-a254ng
    C: Tablet Cases  (25 products)
        • EFC-1H8SWEGSTA
        • SYFACILE101W
        • BC106578
        • CSGE2188BL
        • Versavu
        • APPIPC08G
        • VersaSleeve 7
        • VersaSleeve 7
        • 2043_WRKBK-IPAD2-BRN
        • TABZOO8PAN
    C: Server Barebones  (10 products)
        • SuperServer F627R3-RTB+
        • AS-2042G-TRF
        • ESPRIMO P557/E85+
        • Intel® Server System LADMP2312KXXX44
        • Superserver 5036I-IF
        • SYS-1029TP-DC0R
        • SYS-F617H6-FT+
        • Superserver 8017R-TF+
        • SuperServer 6026T-URF
        • P4308IP4LHJC
    C: Stylus Pens  (6 products)
        • AMM163US
        • 2 in 1 Styluspen
        • AMM01B
        • Stylus Pen Black
        • Accurate Stylus
        • AMM1214AU
    C: Handheld Device Accessories  (5 products)
        • BTBOUNCEOUTDOORD
        • Cradle f n30
        • Safety Camera Scrath Card
        • DLM2260/10
        • SmartTags
    C: Backpack PCs  (1 products)
        • P1000-001nl
    C: PC/Workstation Barebones  (4 products)
        • D34010WYK
        • Superserver 6015T-TV Twin
        • Revo Cube Pro
        • DS77U5
    C: POS Systems  (5 products)
        • RP2 Retail System Model 2030 (ENERGY STAR)
        • RP7 Retail System Model 7800
        • Engage One All-in-One Model 143
        • Pro x2 612 G2
        • RP 5810
    C: Thin Clients  (6 products)
        • t510 Flexible Thin Client (ENERGY STAR) Bundle
        • Z90S7
        • Z90DE7
        • 909716-54L
        • 100013839
        • 909703-21L
    C: E-Book Reader Cases  (3 products)
        • N905-BMP-2RD
        • Clara HD SleepCover
        • PRS-3LEATHCOVT
    C: Tablet Spare Parts  (1 products)
        • 747658-001
    C: E-Book Readers  (1 products)
        • Touch
  B: Computer Cables
    C: Fibre Optic Cables  (29 products)
        • 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue
        • 2m LC/SC Duplex 9/125
        • 1m LC/ST 62.5/125 Multimode Fibre Cable
        • 3m LC/LC Duplex 50/125 Multimode Fiber Patch Cable
        • 10m LC/LC Plenum-Rated 9/125 Simplex Single-Mode Fiber Patch Cable
        • 15m USA 10Gb LC/ST Duplex 50/125 Multimode Fiber Patch Cable
        • 5m Duplex MM Fiber Optic Cable LC-MTRJ
        • 5m LC/LC Simplex 9/125 Single-Mode Fiber Patch Cable - Red
        • RL2603
        • RL4109
    C: Networking Cables  (67 products)
        • 5m RJ-45 Cat6 UTP
        • 5m Cat6 UTP LSZH Network Patch Cable - Black
        • IGG310656
        • 7.6m RJ-45 M/M
        • Cat6a Ethernet Patch Cable - Shielded (STP) - 3 ft., Aqua
        • FB6625
        • Cat6 Patch Cable with Molded RJ45 Connectors - 20 ft. - Orange
        • Cat6 Ethernet Patch Cable with Snagless RJ45 Connectors - 5 ft., Red
        • 14ft Assembled Cat5E Crossover
        • Cat.5e U/UTP Patch Cable, 5.0m , Beige
    C: DisplayPort Cables  (3 products)
        • 175ft RapidRun
        • DisplayPort 1.1, 10m
        • DisplayPort™ 1.2 to HDMI™ 2.0 Active Cable 4K60Hz 3Meter M/M
    C: Power Cables  (12 products)
        • 3ft Computer 18 AWG Power Cord Extension
        • Standard Computer Power Extension Cord, 10A, 18 AWG (IEC-320-C14 to IEC-320-C13), Orange, 0.61 m
        • Heavy-Duty Power Extension Cord Lead Cable, 15A, 14AWG (IEC-320-C19 to IEC-320-C14), 0.61 m (2-ft.)
        • Heavy-Duty Power Extension Cord, 15A, 14 AWG (IEC-320-C14 to IEC-320-C13), Orange, 0.91 m
        • Universal Computer Power Cord Lead Cable, 10A, 18AWG (NEMA 5-15P to IEC-320-C13), 1.22 m (4-ft.)
        • 450-11930
        • High Quality Power Cord, C7 to 2pin Euro
        • 246959-081
        • Power Cord, Schuko - C13, 3x 0.75mm², Black, 1.8m
        • 728554-01L
    C: USB Cables  (14 products)
        • 37713
        • SB0005
        • 10.01.0204-BK
        • USB 2.0 Extension Cable
        • U330-15M
        • 2m FlexUSB 2.0 A/B Cable
        • 93621
        • MA117985
        • MA117976
        • USB-C Cable - M/M - 0.5 m - USB 2.0
    C: Cable Interface/Gender Adapters  (20 products)
        • USB 3.1 Gen 1 Right-Angle USB-C to Gigabit Ethernet Network Adapter - 10/100/1000 Mbps, Thunderbolt 3 Compatible, White
        • Mini-DisplayPort to HDMI Cable Adapter (M/M), 3.66 m (12-ft.)
        • 60051
        • IDATA USB-SER-2CT
        • HDMI 1.4 to DisplayPort 1.1 Adapter
        • USB Internal AT Motherboard Adapter 2-Port
        • 1 ft DVI-D to DVI-D & HDMI Splitter Cable - M/F
        • USB - Ethernet
        • High Density D-sub Adapter 15 pole Male to 15 pole Female
        • AB7871
    C: Video Cable Adapters  (6 products)
        • MINI DISPLAYPORT TO HDMI® CABLE
        • DisplayPort to VGA Cable, Displayport with Latches to HD-15 Adapter (M/M), 6-ft.
        • 35ft Plenum-Rated HD15 M/F UXGA Extension Cable w/ 3.5mm Audio
        • ICOC-DSP-H12-010
        • DVI Modul
        • 3m DVI-A M / HD15 M Cable
    C: Cable Protectors  (2 products)
        • 16329
        • HIFI Accessoire Vogels CABLE8W Cabletray
    C: HDMI Cables  (11 products)
        • 1.5m High Speed HDMI Cable – Ultra HD 4k x 2k HDMI Cable – HDMI to HDMI M/M
        • 3m High Speed HDMI® Cable with Ethernet - Ultra HD 4k x 2k HDMI Cable - HDMI to HDMI M/M
        • High Speed HDMI cable 1.5m
        • High Speed HDMI with Ethernet Extension Cable 4K 60Hz M / F 1.0 m
        • 93042
        • HDMI cable SWV2433W/10
        • ICOC-HDMI-4-050WH
        • 1.8m HDMI 1.4
        • 50181
        • Twistable HDMI cable 2.5m
    C: Wire Connectors  (5 products)
        • RJ45 Cat5 8x8 Modular Plug for Flat Stranded Cable 10pk
        • Low Profile Plug 2P + E 16A White IPW-SP16-WH9
        • C25PCM
        • RJ45 Cat5 8x8 Modular Plug for Flat Stranded Cable 25pk
        • 10.21.0503
    C: SCSI Cables  (2 products)
        • 470-11540
        • 6ft LVD/SE VHDCI .8mm 68M to SCSI-3 MD68M Cable with Ferrites
    C: SATA Cables  (5 products)
        • 19-in. 7Pin/7Pin
        • AK3415
        • CBL-0201L
        • 36in Go!Mod Molded Round 2-Device Ultra ATA133 EIDE Cable
        • 36 inch Round ATA 100/133 IDE Cable
    C: SCART Cables  (1 products)
        • Scart cable SWV2540T/10
    C: Lightning Cables  (3 products)
        • Uniquesync
        • A8121H92
        • 1m (3ft) Blue Apple 8-pin Lightning Connector to USB Cable for iPhone / iPod / iPad
    C: Coaxial Cables  (4 products)
        • PC/Video (UXGA) Runner Cable
        • Toslink M-M 1m SAVER
        • 10.26.2004
        • 75ft RG6
    C: VGA Cables  (2 products)
        • 125ft Plenum-Rated HD15 M/M UXGA Monitor/Projector Cable
        • 50ft Flexima HD15 M/M UXGA Monitor Cable
    C: KVM Cables  (6 products)
        • CBL0086 KVM cable 0.9 m
        • KVM Switch cable, PS/2 & AT/Serial
        • USB/PS2 Combo Cable Kit for NetController KVM Switches B040-Series and B042-Series, 6-ft.
        • F1D9017B06
        • 1.8m PS/2 KVM Cable
        • 3-in-1 Hi-Resolution PS/2 KVM Cable HD15 VGA M/F 15ft
    C: DVI Cables  (5 products)
        • DVI Connection Cable Dual Link
        • 5m DVI-D Single Link Cable - M/M
        • 5m DVI-I M/M Dual Link Digital/Analog Video Cable
        • 1.0m SonicWave™ DVI™ Digital Video Cable
        • Cable ZEN 6.6 ft (2m) DVI Digital Video Cable
    C: Serial Attached SCSI (SAS) Cables  (2 products)
        • 470-12371
        • S26361-F3210-L302
    C: Audio Cables  (3 products)
        • 80142
        • 1 ft Stereo Audio Cable - 3.5mm Male to 2x RCA Male
        • 3.5 mm - 3.5 mm 5m M/M
    C: InfiniBand Cables  (1 products)
        • MSA and TAA Compliant 10GBase-CU SFP+ to SFP+ Direct Attach Cable (Active Twinax, 10m)
    C: FireWire Cables  (1 products)
        • F007-015
    C: S-Video Cables  (1 products)
        • S-Video m/m 5.5m
  B: Software
    C: Software Licenses/Upgrades  (227 products)
        • 00D8199
        • MSS Cisco Firepower IDP Sensor Fiber
        • ScanMail Suite f/Microsoft Exchange, RNW, GOV, 14m, 501-750u
        • SLNA0079
        • PTNN0004
        • Enterprise Security f/Gateways, RNW, 751-1000u, 33m, ENG
        • SW-UPG-PC-S200-5-25
        • SafeSync for Business, RNW, 9m, 26-50u
        • Backup Exec 2010 Central Admin Server Option, v13.0, Rewards Band A UPG + Basic Maintenance, ML
        • Enterprise Security Suite, CUPG fr/ NS, EDU, 1Y, 26-50u, ML
    C: Antivirus Security Software  (53 products)
        • Norton Internet Security 2008 + Norton Antibot 1.0 (3 users)
        • Internet Security 2014, 3U, RNW, 1Y
        • Endpoint Antivirus  for Home  User 5 - 10
        • Mail Security 8340
        • Endpoint Security f/Business - Advanced, 10-14u, 3Y, Cross
        • File Security for Linux and FreeBSD User 2
        • Security f/Virtualization, Server, 5-9u, 1Y, Cross
        • Endpoint Security f/Business - Select, 15-19u, 1Y, GOV
        • Total Security
        • Security f/Mail Server, 25-49u, 3Y, Add
    C: Computer Utilities  (9 products)
        • 301N84410
        • WinZip 18 Pro, 50000-99999, EDU, ML
        • WinZip 16 Standard, 1u, Win, NL
        • WinZip 15 Standard, WIN, 2-9u
        • with Color Profiling RIP Software
        • Absolute Manage MDM, Prptl
        • WinZip Pro, MNT, 200-499u, 3y
        • 301N81140
        • Backup Exec 11d for Windows Servers Business Pack without support
    C: Multimedia Software  (5 products)
        • PaintShop Pro X6, NL/FR/IT
        • Roxio Toast 11 Titanium
        • CorelCAD, Win/Mac, 11-25u, ML
        • VideoStudio Pro Ultimate X9
        • DRAW Graphics Suite X5, H&S, 3u, Box
    C: Networking Software  (1 products)
        • VMware vCenter Server 5 Standard f/vSphere, 5H/I, 1Y
    C: Operating Systems  (1 products)
        • Microsoft Windows 7 Professional 64-Bit, SP1, DVD
  B: Telecom & Navigation
    C: Mobile Phone Spare Parts  (14 products)
        • GH59-12969A
        • Li-Ion 3.7v 1120mAh
        • AB563840CE
        • ZE551ML-6J
        • GH59-12841A
        • GH98-23340D
        • EEB-U20B
        • GH97-16565D
        • ZE600KL-6C
        • GH96-07236A
    C: Mobile Device Keyboards  (10 products)
        • 701428-331
        • I10REU-BBS
        • NP.KBD1A.00R
        • FRU04W2177
        • 920-006395
        • LC.KBD0A.007
        • EJ-CN920
        • FRU04W2175
        • 920-006268
        • 784194-091
    C: Smartphones  (34 products)
        • Sola
        • GSmart Roma RX
        • G398F
        • SM-A800
        • SM-G975F
        • SM-G950F
        • SM-J415F
        • SM-J200H
        • LMG710EM
        • Moto E4 Plus
    C: Mobile Phone Cases  (55 products)
        • Premium Flip TPU Case Apple iPhone 7, iPhone 8 Black
        • TAGE3163K
        • Sensation
        • EF-FS727L
        • PocketBook
        • 200102293
        • Saffiano Wallet Case Samsung Galaxy A8 (2018) Copper
        • TPUSA829T
        • ETUISMI8190
        • Excellent Wallet Case Samsung Galaxy A3 (2017) Jade Black
    C: Holders  (4 products)
        • GrabTab Fun with Food Collection
        • HA-E60IO
        • GrabTab Fun with Food Collection
        • BTAC-02
    C: Telephony Equipment  (9 products)
        • M3301GW/FR
        • SE8880B/12
        • D1101
        • D2152B/38
        • Sologic A801
        • S1202
        • D4502B/23
        • CPH0018A
        • CD2802W/DE
    C: Screen Protectors  (32 products)
        • TEM0002A
        • Vikuiti ADQC27
        • OSFTAG13.5L/P-SURFB
        • CANPSSD1100S
        • Vikuiti ADQC27
        • Vikuiti ADQC27
        • ET-FN910C
        • SONDSCW300S
        • Vikuiti ADQC27
        • SAMS5620LE
    C: Mobile Phones  (6 products)
        • Cookie (KP500)
        • GT-S5220
        • ROKR E8
        • KM570
        • KC910
        • CTE109BK/00
    C: Mobile Headsets  (12 products)
        • In-Ear Stereo Earbuds Green with In-line Microphone - handsfree, tangle free with flat cable design
        • Earhook Headphones SHS8100/98
        • Headphones with mic SHE5305WT/00
        • HA-SR185
        • Petit
        • HM3350
        • Headphones with mic SHL3265BL/00
        • HA-S31M-A
        • Pulse Escape
        • DR-V150iP
    C: Two-Way Radios  (1 products)
        • RC-6420 Walkie Talkie - Protalker PT-1078
    C: Mobile Device Chargers  (8 products)
        • Mini Car Charger 2xUSB 1A+2.1A
        • DLP2307/11
        • ACHTYPECK
        • ACHKIT10WMFIIPADW
        • CBRAR6100 Roller Car Charger
        • Type-C/Type-A In-Car Charger 3A
        • USB wall charger DLP2307/12
        • CARUSB10
    C: Navigational Equipment  (3 products)
        • Rider 400
        • 9UUA.001.22
        • NV-U51
    C: Peripheral Device Cases  (1 products)
        • 7"-9" In-Car DVD Player Case
  B: Printers & Scanners
    C: Printing Supplies  (215 products)
        • 106R03527
        • ML2250
        • OC301Y-FRC
        • 6015Y-FRC
        • TK18-XL-FRC
        • SV043A
        • Yellow Laser Toner - Ricoh 841507 - For Ricoh Aficio MP C 2051 / 2551
        • Fotopapier KC-18IL (18) Pak 18 vel
        • 32RAN006R01526
        • BR1100BK-INK-FRC
    C: Print & Scan Accessories  (64 products)
        • PA03753-K982
        • 40X8421
        • RK2-1992-000CN
        • RM1-2721-040CN
        • 675K78361
        • 500-Sheet Drawer for Lexmark T64x
        • RM1-1717-000CN
        • LaserJet 500-sheet Output Catch Tray
        • 724-10520
        • Epson SIDM Single Sheet Feeder 50 sheets for LQ-2090, LX-1170II, FX-1180/2190
    C: Printing Equipment  (63 products)
        • 6510DNI
        • MX511dhe
        • 4634 e
        • imageRUNNER ADVANCE 4245i
        • Epson PLQ-20 (240v)
        • C511dn
        • 7400V_DN
        • CS622de
        • T640dtn
        • 1801
    C: Printing Media  (21 products)
        • Everyday Inkjet Paper 80 g/m²-A4/210 x 297 mm/500 sht
        • Labels signalling hard-wearing A4 63,5x29,6 mm yellow strong adhesion film matt weatherpr. 675 pcs.
        • Velvet Fine Art Paper, DIN A2, 260g/m², 25 Sheets
        • 3" x 1", 5800/Roll
        • Cockle-free Heavyweight Coated Paper-610 mm x 30.5 m (24 in x 100 ft)
        • 1TYLAB10252DTP74
        • SureLab Pro Paper Glossy 285 10" 1roll
        • Computer labels continous 88.9x23.0 mm 1 row white paper matt 6000 pcs.
        • Q1408A
        • CHP235
    C: Scanning Equipment  (5 products)
        • Picture Saver PS410
        • ScanSnap S1300i Deluxe
        • ES-400
        • Scanjet 4370 Photo Scanner
        • scanjet 3530c digital flatbed scanner
  B: Batteries & Power Supplies
    C: UPS Batteries  (3 products)
        • 2U UPS Replacement 48VDC Battery Cartridge for select Tripp Lite SmartOnline UPS
        • External 240V Tower Battery Pack for use with select UPS Systems (BP240V787C-1PH)
        • APCRBC143
    C: Power Supply Units  (16 products)
        • RS-900-AAAA-A3
        • GX
        • PY.25008.002
        • TQXGE-700SAP
        • SP410-1D
        • PWR-242-AE
        • Dark Power Pro 10
        • PWS-2K04A-1R
        • PY.75008.005
        • AT-PWR05
    C: Power Adapters & Inverters  (63 products)
        • AK.065AP.13 compatible AC Adapter inc. mains cable
        • Powerpal
        • ALT28064A
        • Extra 90W/19V AC Adapter
        • 40Y7666
        • ALT28751A
        • PA3822E-1AC3
        • S26391-F478-L100
        • P000537790
        • AC Adapter, 15V DC, 5A, 75W, 3-Pin
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
        • 650VA 360W UPS
        • 9PX3000IRTN
        • Powerware 9355-8-NHS-15-32x9Ah
        • G55TUPSM100HS
        • Liebert NXC 30kVA
        • AVR Series 230V 550VA 300W Ultra-Compact Line-Interactive UPS with USB port, CEE7/7 Schuko Outlets
        • 5PX 3000VA 2U
        • Powerware 9355-8-NHS-33-64x9Ah
        • Evolution 1150 Tower
        • Powerware 9155-20-NLHS-26-4x7Ah
    C: Household Batteries  (11 products)
        • Lithium
        • 56666 101 402
        • Stamina Plus
        • -V364
        • SR44
        • 936847
        • CR123A
        • DL2016
        • Plus AAA 4 Pack
        • 56683 101 402
    C: Power Distribution Units (PDUs)  (11 products)
        • DIS Rack PDU, Safety Standard, 0U, input Schuko 230V 16A, outputs (9)Schuko
        • DIS Rack PDU, TripplePower, 0U/1U, input IEC 60309 230/400V 3x16A, outputs (6)C19
        • MPE Rack PDU, elementary, 0U, input Hardwired 230/400V 3x32A, outputs (48)C13
        • 8-Outlet French Power Distribution Unit
        • T982F3-F-SL-0
        • APS3-058
        • PDPM138H-R
        • 9PXEBM180RT
        • NSYAPU19UK7
        • Geist rPDU, basic, 0U, input IEC60309 230V 16A, outputs (20)C13 | (4)C19
    C: Power Banks  (4 products)
        • P27QC10P60-BK
        • Freepower Dual 7800
        • Emergency Micro-USB Powerpack
        • PowerBank  6000
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
        • GXT3/4 - Socket for GXT4-72VBATTE external battery cabinet
    C: Battery Chargers  (4 products)
        • PLA8031A
        • PLA8011A
        • UCC8014A
        • ACK-DC90
    C: UPS Battery Cabinets  (1 products)
        • Easy 3S
    C: Notebook Power Tips  (2 products)
        • PT-3H
        • PT-3O
    C: Portable Device Management Carts & Cabinets  (1 products)
        • 48-Device USB Charging Station Cabinet with Sync for iPad and Android Tablets, Wall-Mount and Cart Options, White
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
        • VN247H
        • E243
        • MG28UQ
        • ProLite E1908WSV-S1 19" LCD
        • 22MK400H-B
        • AMILO Display L 3220W
        • 227E6EDSD/57
        • LCD monitor, LED backlight 17S4LSB/00
        • 17S4LSB/10
        • S19B350N
    C: TVs  (76 products)
        • HG40EB690QB
        • 42LA641S
        • UE46EH5000K
        • 43PUS6503/12 Refurb Grade B
        • UE40ES7000S
        • 32W1733DG
        • KDL-32EX725
        • LCD TV - Bravia KDL-22S5500
        • KDL-32R403C
        • 37" LCD Widescreen Flat TV Pixel Plus
    C: Flat Panel Mount Accessories  (6 products)
        • AEC012018
        • Large AV Accessory Shelf
        • FSBI2B
        • BT8390-WFK2
        • Wall Display Side Cover Accessory
        • KRA225S
    C: Display Privacy Filters  (6 products)
        • Privacy Filter for 31.5" Widescreen Monitor
        • OSFNB2WPI13L-HP810
        • Privacy and Protection Cover for Laptop/Notebook Screen Size 14.0'' 16:9
        • 4Z10K85320
        • OSFNB2WPI13.3-TPX380

In [194]:
# Compute metrics
products_per_AB = df.groupby(["A", "B"]).size()
C_children_per_AB = df.groupby(["A", "B"])["C"].nunique()

# Combine
ab_summary = pd.DataFrame({
    "products_in_AB": products_per_AB,
    "n_C_children": C_children_per_AB
})

# Sort by product count descending (like your example)
ab_summary = ab_summary.sort_values("products_in_AB", ascending=False).head(10)

print(ab_summary)

                                                    products_in_AB  \
A                       B
Computers & Electronics Computers                             2202
                        Printers & Scanners                    368
                        Computer Components                    330
                        Warranty & Support                     318
                        Software                               296
                        Data Storage                           284
                        TVs & Monitors                         251
                        Computer Cables                        205
                        Telecom & Navigation                   189
                        Batteries & Power Supplies             141

                                                    n_C_children
A                       B
Computers & Electronics Computers                             18
                        Printers & Scanners                    5
                        Computer Components                    3
                        Warranty & Support                     4
                        Software                               6
                        Data Storage                           2
                        TVs & Monitors                        17
                        Computer Cables                       23
                        Telecom & Navigation                  13
                        Batteries & Power Supplies            12

In [195]:
prod_per_C = df["C"].value_counts()
prod_per_C

C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
                                 ...
USB Graphics Adapters               1
Two-Way Radios                      1
UPS Battery Cabinets                1
AV Receivers                        1
S-Video Cables                      1
Name: count, Length: 160, dtype: int64

In [196]:
#Keep only C categories with > 20 products
valid_C = prod_per_C[prod_per_C >= 20].index
df = df[df["C"].isin(valid_C)].copy()

In [197]:
print("Remaining rows:", len(df))
print("Unique C after filtering:", df["C"].nunique())
print("Min products per C (should be >20):", df["C"].value_counts().min())

Remaining rows: 4382
Unique C after filtering: 32
Min products per C (should be >20): 20

In [198]:
#final A-B summary
def print_final_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C_under_B=("C", "nunique"),
              num_products_under_B=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]

        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C_under_B']}")
            print(f"    #products (under this B): {row['num_products_under_B']}")

In [199]:
print_final_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 2
    #products (under this B): 87
  B: Computer Cables
    #C-level subcategories: 3
    #products (under this B): 116
  B: Computer Components
    #C-level subcategories: 2
    #products (under this B): 325
  B: Computers
    #C-level subcategories: 6
    #products (under this B): 2144
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 23
  B: Data Input Devices
    #C-level subcategories: 1
    #products (under this B): 85
  B: Data Storage
    #C-level subcategories: 1
    #products (under this B): 273
  B: Photo & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 39
  B: Printers & Scanners
    #C-level subcategories: 4
    #products (under this B): 363
  B: Projectors
    #C-level subcategories: 1
    #products (under this B): 25
  B: Software
    #C-level subcategories: 2
    #products (under this B): 280
  B: TVs & Monitors
    #C-level subcategories: 3
    #products (under this B): 186
  B: Telecom & Navigation
    #C-level subcategories: 3
    #products (under this B): 121
  B: Warranty & Support
    #C-level subcategories: 2
    #products (under this B): 315

In [200]:
def print_final_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products_under_C")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products_under_C']} products)")
                
print_final_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Power Adapters & Inverters  (63 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
  B: Computer Cables
    C: Cable Interface/Gender Adapters  (20 products)
    C: Fibre Optic Cables  (29 products)
    C: Networking Cables  (67 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PCs/Workstations  (227 products)
    C: Tablet Cases  (25 products)
    C: Tablets  (39 products)
  B: Consumer Audio & Video Equipment
    C: Audio Equipment Parts & Accessories  (23 products)
  B: Data Input Devices
    C: Keyboards  (85 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
  B: Photo & Video Equipment
    C: Cameras & Camcorders  (39 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
  B: Projectors
    C: Projection Screens  (25 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Flat Panel Spare Parts  (42 products)
    C: TVs  (76 products)
  B: Telecom & Navigation
    C: Mobile Phone Cases  (55 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Warranty & Support Extensions  (288 products)

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4382 entries, 1072689 to 1121736
Data columns (total 51 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       4382 non-null   object
 1   BrandInfo.BrandLocalName                    4382 non-null   object
 2   BrandInfo.BrandLogo                         4379 non-null   object
 3   BrandInfo.BrandName                         4382 non-null   object
 4   BrandLogo                                   4379 non-null   object
 5   BrandPartCode                               4382 non-null   object
 6   BulletPoints                                4088 non-null   object
 7   Category.CategoryID                         4382 non-null   int64
 8   Category.Name.Language                      4382 non-null   object
 9   Category.Name.Value                         4382 non-null   object
 10  Description.Disclaimer                      3884 non-null   object
 11  Description.ID                              3884 non-null   float64
 12  Description.LeafletPDFURL                   3884 non-null   object
 13  Description.LongDesc                        3884 non-null   object
 14  Description.LongProductName                 3884 non-null   object
 15  Description.ManualPDFSize                   3818 non-null   float64
 16  Description.ManualPDFURL                    3884 non-null   object
 17  Description.MiddleDesc                      3884 non-null   object
 18  Description.PDFSize                         3858 non-null   float64
 19  Description.URL                             3829 non-null   object
 20  Description.Updated                         3884 non-null   object
 21  EndOfLifeDate                               4382 non-null   object
 22  GTIN                                        4382 non-null   object
 23  IcecatId                                    4382 non-null   int64
 24  ProductFamily.ProductFamilyID               4382 non-null   int64
 25  ProductName                                 4382 non-null   object
 26  ProductSeries.SeriesID                      4382 non-null   int64
 27  ReleaseDate                                 4382 non-null   object
 28  SummaryDescription.LongSummaryDescription   4382 non-null   object
 29  SummaryDescription.ShortSummaryDescription  4382 non-null   object
 30  Title                                       4382 non-null   object
 31  Description.WarrantyInfo                    2225 non-null   object
 32  Description                                 498 non-null    object
 33  ProductFamily.Language                      1072 non-null   object
 34  ProductFamily.Value                         1072 non-null   object
 35  ProductSeries.Language                      705 non-null    object
 36  ProductSeries.Value                         705 non-null    object
 37  BulletPoints.BulletPointsId                 294 non-null    float64
 38  BulletPoints.Language                       294 non-null    object
 39  BulletPoints.Updated                        294 non-null    object
 40  BulletPoints.Values                         294 non-null    object
 41  VirtualCategory                             416 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                4382 non-null   object
 44  pathlist_names                              4382 non-null   object
 45  num_levels                                  4382 non-null   int64
 46  path_3                                      4382 non-null   object
 47  level_4                                     2042 non-null   object
 48  A                                           4382 non-null   object
 49  B                                           4382 non-null   object
 50  C                                           4382 non-null   object
dtypes: float64(5), int64(5), object(41)
memory usage: 1.7+ MB

In [202]:
#columns to keep
cols_needed = [
    "Brand",
    "BrandPartCode",
    "ProductName",
    "Description.LongProductName",
    "SummaryDescription.LongSummaryDescription",
    "Description.LongDesc",
    "A", "B", "C",
    "path_3"   # <-- Needed for evaluation
]

In [203]:
df_clean = df[cols_needed].copy()

In [204]:
# Build raw metadata text

def build_metadata(row):
    parts = []

    if pd.notna(row["Brand"]):
        parts.append(row["Brand"])

    if pd.notna(row["BrandPartCode"]):
        parts.append(row["BrandPartCode"])
        
    if pd.notna(row["ProductName"]):
        parts.append(row["ProductName"])

    if pd.notna(row["Description.LongProductName"]):
        parts.append(row["Description.LongProductName"])

    if pd.notna(row["SummaryDescription.LongSummaryDescription"]):
        parts.append(row["SummaryDescription.LongSummaryDescription"])

    if pd.notna(row["Description.LongDesc"]):
        parts.append(row["Description.LongDesc"])

    return " ".join(parts)

df_clean["metadata_text"] = df_clean.apply(build_metadata, axis=1)

In [205]:
df_clean.head(3)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...

In [206]:
import re

def clean_text(t):
    if not isinstance(t, str):
        return ""

    t = re.sub(r"<[^>]+>", " ", t)          # remove HTML tags
    t = re.sub(r"\s+", " ", t)              # collapse spaces
    t = t.replace("\xa0", " ")              # remove non-breaking
    t = t.strip()

    return t

df_clean["metadata_text_clean"] = df_clean["metadata_text"].apply(clean_text)

In [207]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...

In [208]:
#check the average length of metadata_clean_text
df_clean["meta_len"] = df_clean["metadata_text_clean"].apply(lambda x: len(str(x)))

print(df_clean["meta_len"].describe())

count     4382.000000
mean      1318.927887
std       1831.572922
min         29.000000
25%        236.000000
50%        626.000000
75%       1759.750000
max      27361.000000
Name: meta_len, dtype: float64

In [209]:
# This creates a new column telling YAKE exactly how many keywords to extract for each product.
def decide_top_k(meta_len):
    if meta_len < 150:
        return 5
    elif meta_len < 500:
        return 10
    elif meta_len < 1500:
        return 15
    elif meta_len < 3000:
        return 20
    elif meta_len < 8000:
        return 30
    else:
        return 50

df_clean["yake_k"] = df_clean["meta_len"].apply(decide_top_k)

In [210]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,1840,20
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,2905,20
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,201,10

In [211]:
#Extract YAKE keywords per row
import yake

kw_extractor = yake.KeywordExtractor(
    n=1,             # extract unigrams
    dedupLim=0.9,    # reduce duplicates
    dedupFunc="seq"
)

def extract_yake(text, k):
    try:
        kws = kw_extractor.extract_keywords(text)
        return [kw for kw, score in kws[:k]]
    except:
        return []

df_clean["yake_keywords"] = df_clean.apply(
    lambda row: extract_yake(row["metadata_text_clean"], row["yake_k"]),
    axis=1
)

In [212]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30,"[ASUS, Intel, Windows, Core, Graphics, Cache, ..."
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10,"[Keyboard, Belgium, backlight, cable, includes..."
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,1840,20,"[Duplex, Blue, Fiber, Single-Mode, Patch, Plen..."
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,2905,20,"[Lenovo, Intel, Xeon, Cache, Windows, Professi..."
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,201,10,"[Israel, Keyboard, includes, cable, compatibil..."

In [213]:
def yake_list_to_text(kws):
    if isinstance(kws, list):
        # join phrases with space; or use ", ".join(kws) if you prefer
        return " ".join(str(k).strip() for k in kws if isinstance(k, str))
    elif pd.isna(kws):
        return ""
    else:
        return str(kws)

df_clean["yake_text"] = df_clean["yake_keywords"].apply(yake_list_to_text)
df_clean[["metadata_text_clean", "yake_keywords", "yake_text"]].head(3)

# metadata_text_clean → full raw description (for comparison / ablation later)
# yake_keywords → list of extracted phrases
# yake_text → compact keyword string we’ll embed

,metadata_text_clean,yake_keywords,yake_text
1072689,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,"[ASUS, Intel, Windows, Core, Graphics, Cache, ...",ASUS Intel Windows Core Graphics Cache RAM Eth...
906402,HP 686915-A41 686915-A41 Keyboard in midnight ...,"[Keyboard, Belgium, backlight, cable, includes...",Keyboard Belgium backlight cable includes comp...
411281,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,"[Duplex, Blue, Fiber, Single-Mode, Patch, Plen...",Duplex Blue Fiber Single-Mode Patch Plenum-Rat...

In [214]:
df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords,yake_text
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30,"[ASUS, Intel, Windows, Core, Graphics, Cache, ...",ASUS Intel Windows Core Graphics Cache RAM Eth...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10,"[Keyboard, Belgium, backlight, cable, includes...",Keyboard Belgium backlight cable includes comp...

In [215]:
from sentence_transformers import SentenceTransformer
import numpy as np

# 1) Load a light, fast model (same family we used before)
st_model = SentenceTransformer("all-MiniLM-L6-v2")

# 2) Take the YAKE-based keyword text
texts_for_embed = df_clean["yake_text"].fillna("").tolist()

# 3) Encode into embeddings (L2-normalized)
embeddings = st_model.encode(
    texts_for_embed,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

embeddings.shape

Batches:   0%|          | 0/69 [00:00<?, ?it/s]

(4382, 384)

In [216]:
from umap import UMAP

umap_model = UMAP(
    n_neighbors=15,        # local structure
    min_dist=0.0,          # tight clusters
    n_components=25,       # richer density structure
    metric="cosine",       # BEST for normalized embeddings
    random_state=42
)

reduced = umap_model.fit_transform(embeddings)
reduced.shape

(4382, 25)

In [217]:
import hdbscan

clusterer_C = hdbscan.HDBSCAN(
    min_cluster_size=20,   # matches your filtered C ≥ 20 idea
    min_samples=1,         # allow fine-grained clusters
    metric="euclidean",    # MUST BE euclidean after UMAP
    cluster_selection_method="eom"
)

df_clean["C_id"] = clusterer_C.fit_predict(reduced)
df_clean["C_id"].value_counts().head(20)

C_id
-1     380
 9     354
 45    190
 21    123
 38    113
 5      90
 3      88
 8      85
 27     85
 16     84
 62     77
 41     77
 77     75
 76     75
 44     73
 79     72
 66     67
 51     65
 17     63
 31     63
Name: count, dtype: int64

In [218]:
# #  Drop HDBSCAN noise before naming
# df_clean = df_clean[df_clean["C_id"] != -1].copy()
# #removing noise

In [219]:
df_clean

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords,yake_text,C_id
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30,"[ASUS, Intel, Windows, Core, Graphics, Cache, ...",ASUS Intel Windows Core Graphics Cache RAM Eth...,66
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10,"[Keyboard, Belgium, backlight, cable, includes...",Keyboard Belgium backlight cable includes comp...,49
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,1840,20,"[Duplex, Blue, Fiber, Single-Mode, Patch, Plen...",Duplex Blue Fiber Single-Mode Patch Plenum-Rat...,48
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,2905,20,"[Lenovo, Intel, Xeon, Cache, Windows, Professi...",Lenovo Intel Xeon Cache Windows Professional Q...,77
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,201,10,"[Israel, Keyboard, includes, cable, compatibil...",Israel Keyboard includes cable compatibility H...,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231002,DELL,490-BDZR,490-BDZR,Radeon Pro WX 2100 2 GB 1 DP 2 mDP (Precision),"DELL 490-BDZR. Graphics processor family: AMD,...",The new Radeon™ Pro WX 2100 graphics card is t...,Computers & Electronics,Computer Components,System Components,Computers & Electronics > Computer Components ...,DELL 490-BDZR 490-BDZR Radeon Pro WX 2100 2 GB...,DELL 490-BDZR 490-BDZR Radeon Pro WX 2100 2 GB...,765,15,"[DELL, Pro, Precision, Radeon, Graphics, memor...",DELL Pro Precision Radeon Graphics memory mDP ...,22
978436,Toshiba,SIC1094057LCD0,SIC1094057LCD0,Satellite A660 15.6 replacement laptop LCD screen,Toshiba SIC1094057LCD0. Type: Display. Display...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,Toshiba SIC1094057LCD0 SIC1094057LCD0 Satellit...,Toshiba SIC1094057LCD0 SIC1094057LCD0 Satellit...,221,10,"[Satellite, LCD, Toshiba, Display, replacement...",Satellite LCD Toshiba Display replacement comp...,3
1101608,HP,6GV21PA,Elite Slice G2 with Microsoft Teams Rooms,None,HP Elite Slice G2 with Microsoft Teams Rooms,None,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,HP 6GV21PA Elite Slice G2 with Microsoft Teams...,HP 6GV21PA Elite Slice G2 with Microsoft Teams...,97,5,"[Slice, Microsoft, Teams, Elite, Rooms]",Slice Microsoft Teams Elite Rooms,45
66861,LG,T300.ADEUPK,T300,None,"LG T300. Display diagonal: 6.1 cm (2.4""), Disp...",None,Computers & Electronics,Telecom & Navigation,Smartphones,Computers & Electronics > Telecom & Navigation...,LG T300.ADEUPK T300 LG T300. Display diagonal:...,LG T300.ADEUPK T300 LG T300. Display diagonal:...,294,10,"[Display, Rear, Single, TFT, SIM, camera, reso...",Display Rear Single TFT SIM camera resolution ...,51
1121736,Eaton,1023113,Powerware 9155-10-NT-0,9155-10-NT-0,Eaton Powerware 9155-10-NT-0. Output power cap...,The Eaton 9155 UPS provides premium online bac...,Computers & Electronics,Batteries & Power Supplies,Uninterruptible Power Supplies (UPSs),Computers & Electronics > Batteries & Power Su...,Eaton 1023113 Powerware 9155-10-NT-0 9155-10-N...,Eaton 1023113 Powerware 9155-10-NT-0 9155-10-N...,1723,20,"[Powerware, power, Eaton, battery, Output, fac...",Powerware power Eaton battery Output factor UP...,31

In [220]:
# After you compute df_clean["C_id"] with HDBSCAN:
print("All cluster IDs:", sorted(df_clean["C_id"].unique()))
print(df_clean["C_id"].value_counts().head(10))
#354 product descriptions
#Cluster ID 9 contains 354 rows from your dataframe.
#354 product descriptions as in 354 reords (yaketext 354) which is all clustered as cid 9

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
C_id
-1     380
 9     354
 45    190
 21    123
 38    113
 5      90
 3      88
 8      85
 27     85
 16     84
Name: count, dtype: int64

In [221]:
def make_evidence(subdf, max_chars=1200, max_items=25):
    """
    Build a compact textual summary for one cluster:
    - use yake_text (already compressed)
    - take up to max_items examples
    - truncate total length to max_chars
    """
    items = []
    for txt in subdf["yake_text"].fillna("").tolist():
        t = txt.strip()
        if not t:
            continue
        items.append("- " + t[:160])   # short snippet per product
        if len(items) >= max_items:
            break

    blob = "\n".join(items)
    return blob[:max_chars]

In [222]:
import subprocess
import hashlib

def run_llm(prompt, model="llama3.2"):
    cmd = ["ollama", "run", model]
    result = subprocess.run(
        cmd,
        input=prompt.encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    stderr_text = result.stderr.decode("utf-8", errors="ignore")
    if stderr_text.strip():
        print("⚠ Ollama stderr:\n", stderr_text)
    stdout_text = result.stdout.decode("utf-8", errors="ignore")
    return stdout_text

label_cache = {}

def cached_llm_label(prompt, max_words=4, model="llama3.2"):
    key = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
    if key in label_cache:
        return label_cache[key]

    raw = run_llm(prompt, model=model)
    # take only first few words, strip punctuation
    label = " ".join(raw.strip().split()[:max_words])
    label_cache[key] = label
    return label

In [223]:
import re

def clean_cluster_name(name: str, max_words: int = 3) -> str:
    if not isinstance(name, str):
        return ""

    name = name.strip()
    name = re.sub(r"\b\d+[\.\)]\s*", " ", name)           # remove "1." / "2)"
    name = re.sub(r"[^A-Za-z0-9&/+ ]+", " ", name)        # keep safe chars
    name = re.sub(r"\s+", " ", name).strip()              # collapse spaces

    tokens = name.split(" ")
    tokens = [t for t in tokens if t not in {"&", "/", "-", "|"}]

    if not tokens:
        return ""

    tokens = tokens[:max_words]
    return " ".join(tokens)


C_name_map = {}
unique_cids = sorted(df_clean["C_id"].unique())
print("All cluster IDs:", unique_cids)

for cid in unique_cids:
    subdf = df_clean[df_clean["C_id"] == cid]

    blob = make_evidence(subdf, max_chars=1200, max_items=25)
    if not blob.strip():
        print(f"C_id {cid} → EMPTY, assigning 'Other Category'")
        C_name_map[cid] = "Other Category"
        continue

    prompt = f"""
[SYSTEM]
Your task is to assign a clean, generic product category name.
Max 3 words. No brands. No specs. No punctuation. Only the category type.
[USER]
Here are example products from one cluster:

{blob}

Respond with ONLY the final 3-word-maximum category name. No explanations.
"""

    raw_label = cached_llm_label(prompt, max_words=6)
    cleaned_label = clean_cluster_name(raw_label, max_words=3)

    if not cleaned_label:
        cleaned_label = "Other Category"

    C_name_map[cid] = cleaned_label
    print(f"C_id {cid} :  '{cleaned_label}'")

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸ ⠴ ⠦ ⠦ ⠇ ⠏ ⠏ ⠙ ⠙ ⠸ ⠸ ⠴ ⠦ ⠦ ⠧ ⠇ ⠏ ⠋ ⠙ ⠸ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠋ ⠋ ⠹ ⠸ ⠸ ⠼ ⠴ ⠦ ⠧ ⠏ ⠋ ⠋ ⠹ ⠹ ⠼ ⠴ ⠴ ⠧ ⠇ ⠏ ⠋ ⠋ ⠹ ⠸ ⠸ ⠴ ⠦ ⠧ ⠇ ⠏ ⠋ ⠙ ⠙ ⠸ ⠸ ⠴ ⠦ ⠦ ⠇ ⠇ ⠋ ⠙ ⠹ ⠸ ⠸ ⠴ ⠦ ⠦ ⠇
C_id -1 :  'Computer Hardware and'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 0 :  'Laptop Screen Replacement'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 1 :  'Display Tablet Computers'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 2 :  'Laptop Screen Replacement'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 3 :  'Satellite LCD Screen'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 4 :  'Rechargeable Laptop Batteries'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 5 :  'Laptop Screen Replacement'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 6 :  'Computing and Electronics'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 7 :  'Camera Equipment'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 8 :  'Computer Memory Modules'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 9 :  'Office Supplies'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 10 :  'Antivirus Software'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 11 :  'Security Information Systems'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
C_id 12 :  'Computer Storage Devices'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 13 :  'Laptop Computer Adapters'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
C_id 14 :  'Laptop Screen Replacement'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 15 :  'Computer Server Support'
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
C_id 16 :  'Computer Hard Drives'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 17 :  'Computer Processors'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 18 :  'Computer Hardware Components'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 19 :  'Power Supplies'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 20 :  'Storage Network Devices'
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
C_id 21 :  'External Hard Drives'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 22 :  'Graphics Card Adapters'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 23 :  'Personal In Ear'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 24 :  'Computer Peripherals'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
C_id 25 :  'Cybersecurity Software Solutions'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 26 :  'Security Product Software'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 27 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 28 :  'Portable Power Batteries'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 29 :  'Security Solutions'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 30 :  'Security Software Solutions'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 31 :  'Data Center Cabinets'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 32 :  'Computer Components'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
C_id 33 :  'Product Support Services'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 34 :  'Service Phone Support'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 35 :  'Computer Peripherals Accessories'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 36 :  'Computer Accessories Cases'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 37 :  'Computer Components'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 38 :  'Computer Hardware Parts'
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
C_id 39 :  'Viewable Projection Screens'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 40 :  'Screen Phone Protectors'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 41 :  'Tablet Computer Accessories'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 42 :  'Laptop Processors'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 43 :  'Computer Hardware Products'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 44 :  'Computer Gaming Hardware'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 45 :  'Computer Monitors'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 46 :  'Print Equipment Services'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 47 :  'Computer Hardware and'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
C_id 48 :  'Fiber Optic Cables'
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
C_id 49 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 50 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 51 :  'Electronics Consumer Devices'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 52 :  'Computer Monitor Covers'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 53 :  'Display LCD Panels'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 54 :  'Electronics Laptops Computers'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠸
C_id 55 :  'Computer Hardware Services'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 56 :  'Product Maintenance and'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 57 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 58 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 59 :  'Portable Computing Devices'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 60 :  'Laptop Computer Hardware'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 61 :  'Computer Hardware'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
C_id 62 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 63 :  'Computer Keyboards'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 64 :  'Networking Cabling Products'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠸ ⠼
C_id 65 :  'Computer Network Cables'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 66 :  'Personal Computing Devices'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 67 :  'Laptops and Computers'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴
C_id 68 :  'Electronics Computer Laptops'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 69 :  'Laptops and Desktops'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 70 :  'Electronics Computer Laptops'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 71 :  'Computer Hardware Components'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 72 :  'Computer Hardware Components'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 73 :  'Electronics Computer Devices'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸ ⠼
C_id 74 :  'Laptops and Tablets'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
C_id 75 :  'Laptop Computer Accessories'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 76 :  'Computer Hardware'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 77 :  'Computer Desktop Systems'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 78 :  'Computer Peripherals'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 79 :  'Portable Laptops'

In [226]:
# Attach ONLY the clean name
df_clean["C_name"] = df_clean["C_id"].map(C_name_map)

# (Optional) check
df_clean[["C_id", "C", "C_name"]].head(20)

         C_id                              C                      C_name
1072689    66               PCs/Workstations  Personal Computing Devices
906402     49   Notebook Parts & Accessories          Computer Keyboards
411281     48             Fibre Optic Cables          Fiber Optic Cables
1047582    77               PCs/Workstations    Computer Desktop Systems
904910     49   Notebook Parts & Accessories          Computer Keyboards
157385     15     Software Licenses/Upgrades     Computer Server Support
934548     62   Notebook Parts & Accessories          Computer Keyboards
876762     38   Notebook Parts & Accessories     Computer Hardware Parts
1041385     9              Printing Supplies             Office Supplies
273638     45              Computer Monitors           Computer Monitors
288146     12           Data Storage Devices    Computer Storage Devices
973610     49   Notebook Parts & Accessories          Computer Keyboards
513341     33  Warranty & Support Extensions    Product Support Services
659426     79                      Notebooks            Portable Laptops
1034218     9              Printing Supplies             Office Supplies
500253     15  Warranty & Support Extensions     Computer Server Support
926103     62   Notebook Parts & Accessories          Computer Keyboards
483648     55  Warranty & Support Extensions  Computer Hardware Services
659246     44                      Notebooks    Computer Gaming Hardware
745446     78                      Notebooks        Computer Peripherals

In [227]:
df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords,yake_text,C_id,C_name
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30,"[ASUS, Intel, Windows, Core, Graphics, Cache, ...",ASUS Intel Windows Core Graphics Cache RAM Eth...,66,Personal Computing Devices
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10,"[Keyboard, Belgium, backlight, cable, includes...",Keyboard Belgium backlight cable includes comp...,49,Computer Keyboards

In [228]:
# C → B: cluster C-centroids into B_id
from sklearn.cluster import AgglomerativeClustering
import numpy as np

# 1. Compute centroids for each C_id
valid_cids = sorted(df_clean["C_id"].unique())

C_centroids = []
C_labels = []

for cid in valid_cids:
    idx = df_clean["C_id"] == cid
    C_centroids.append(reduced[idx].mean(axis=0))   # centroid in UMAP space
    C_labels.append(cid)

C_centroids = np.vstack(C_centroids)

# 2. Agglomerative clustering on C-centroids → B-level groups
agg_B = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.0,   # you can tune 0.8–1.2 later
    linkage="ward"
)

B_ids = agg_B.fit_predict(C_centroids)

# 3. Map C_id → B_id and attach to df_clean
C_to_B = dict(zip(C_labels, B_ids))
df_clean["B_id"] = df_clean["C_id"].map(lambda c: C_to_B.get(c, -1))

print(df_clean[["C_id", "C_name", "B_id"]].head())
df_clean["B_id"].value_counts().head()

         C_id                      C_name  B_id
1072689    66  Personal Computing Devices    28
906402     49          Computer Keyboards    10
411281     48          Fiber Optic Cables     4
1047582    77    Computer Desktop Systems     7
904910     49          Computer Keyboards    10

B_id
43    380
41    354
14    232
8     216
6     155
Name: count, dtype: int64

In [229]:
import re

# if not already defined, reuse this cleaner:
def clean_cluster_name(name: str, max_words: int = 3) -> str:
    if not isinstance(name, str):
        return ""

    name = name.strip()
    name = re.sub(r"\b\d+[\.\)]\s*", " ", name)          # remove "1." / "2)"
    name = re.sub(r"[^A-Za-z0-9&/+ ]+", " ", name)       # keep safe chars
    name = re.sub(r"\s+", " ", name).strip()

    tokens = [t for t in name.split(" ") if t not in {"&", "/", "-", "|"}]
    if not tokens:
        return ""

    tokens = tokens[:max_words]
    return " ".join(tokens)


def name_B_clusters(df):
    B_name_map = {}

    for bid in sorted(df["B_id"].unique()):
        if bid == -1:
            continue

        c_names = (
            df.loc[df["B_id"] == bid, "C_name"]
              .dropna()
              .unique()
              .tolist()
        )
        if not c_names:
            B_name_map[bid] = "Other Category"
            continue

        sample_names = ", ".join(c_names[:15])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of C-level category names and must assign
a concise B-level group name.

STRICT RULES:
- Maximum 3 words.
- No brand names.
- Generic, in English.
- Single line with ONLY the category name.

[USER]
Here are C-level subcategories:

{sample_names}

Respond with ONLY the 3-word-maximum B-level category name.
"""

        raw_label = cached_llm_label(prompt, max_words=6)
        cleaned_label = clean_cluster_name(raw_label, max_words=3)
        if not cleaned_label:
            cleaned_label = "Other Category"

        B_name_map[bid] = cleaned_label
        print(f"B_id {bid} : '{cleaned_label}'")

    return B_name_map


B_name_map = name_B_clusters(df_clean)
df_clean["B_name"] = df_clean["B_id"].map(B_name_map)

df_clean[["C_id", "C_name", "B_id", "B_name"]].head(15)

⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧
B_id 0 : 'Information Security'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
B_id 1 : 'Phone Case Accessories'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
B_id 2 : 'Desktop Computing Products'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
B_id 3 : 'IT Help Desk'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 4 : 'Computer Network Equipment'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 5 : 'Computer Display Products'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 6 : 'Computer and Mobile'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 7 : 'Desktop Computers'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 8 : 'Display Technology Products'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 9 : 'Electronics Computer'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 10 : 'Input and Output'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 11 : 'Consumer Electronics'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
B_id 12 : 'Mobile Computing Hardware'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
B_id 13 : 'Cybersecurity Product Software'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
B_id 14 : 'Storage Devices and'
B_id 15 : 'Input and Output'
B_id 16 : 'Input and Output'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 17 : 'Peripherals and Accessories'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
B_id 18 : 'Computer Equipment Services'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 19 : 'Gaming Computer Systems'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 20 : 'Mobile Computing Components'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 21 : 'Server Racks and'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
B_id 22 : 'Server Technical Support'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 23 : 'Peripherals and Devices'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 24 : 'Mobile Accessories'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 25 : 'Electronics Industry'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 26 : 'Peripherals and Devices'
B_id 27 : 'Peripherals and Devices'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 28 : 'Computer Hardware Components'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
B_id 29 : 'Computer Components'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 30 : 'Computer Graphics Accessories'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 31 : 'Tablet Computing Devices'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 32 : 'In Ear Monitors'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
B_id 33 : 'Display Technology Products'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 34 : 'Microprocessor Units'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠸
B_id 35 : 'Computer Display Repairs'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
B_id 36 : 'Computer Security Solutions'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 37 : 'Computer Power Supplies'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 38 : 'Input/Output Devices'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
B_id 39 : 'Portable Power Supplies'
B_id 40 : 'Computer Display Repairs'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
B_id 41 : 'Stationery and Office'
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
B_id 42 : 'Digital Camera Accessories'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠸
B_id 43 : 'Computer Equipment Category'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 44 : 'Portable Electronics'
B_id 45 : 'Computer Display Repairs'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 46 : 'Storage Solutions'
B_id 47 : 'Computer Display Repairs'

         C_id                      C_name  B_id                        B_name
1072689    66  Personal Computing Devices    28  Computer Hardware Components
906402     49          Computer Keyboards    10              Input and Output
411281     48          Fiber Optic Cables     4    Computer Network Equipment
1047582    77    Computer Desktop Systems     7             Desktop Computers
904910     49          Computer Keyboards    10              Input and Output
157385     15     Computer Server Support    22      Server Technical Support
934548     62          Computer Keyboards    15              Input and Output
876762     38     Computer Hardware Parts    17   Peripherals and Accessories
1041385     9             Office Supplies    41         Stationery and Office
273638     45           Computer Monitors     8   Display Technology Products
288146     12    Computer Storage Devices    46             Storage Solutions
973610     49          Computer Keyboards    10              Input and Output
513341     33    Product Support Services     3                  IT Help Desk
659426     79            Portable Laptops     6           Computer and Mobile
1034218     9             Office Supplies    41         Stationery and Office

In [230]:
df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords,yake_text,C_id,C_name,B_id,B_name
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,3657,30,"[ASUS, Intel, Windows, Core, Graphics, Cache, ...",ASUS Intel Windows Core Graphics Cache RAM Eth...,66,Personal Computing Devices,28,Computer Hardware Components
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,299,10,"[Keyboard, Belgium, backlight, cable, includes...",Keyboard Belgium backlight cable includes comp...,49,Computer Keyboards,10,Input and Output

In [231]:
from sklearn.cluster import AgglomerativeClustering
import numpy as np

valid_bids = [b for b in sorted(df_clean["B_id"].unique()) if b != -1]

B_centroids = []
B_labels = []

for bid in valid_bids:
    idx = (df_clean["B_id"] == bid)
    B_centroids.append(reduced[idx].mean(axis=0))   # UMAP centroid
    B_labels.append(bid)

B_centroids = np.vstack(B_centroids)

agg_A = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.2,   # you can tune 1.0–1.5 later
    linkage="ward"
)

A_ids = agg_A.fit_predict(B_centroids)

B_to_A = dict(zip(B_labels, A_ids))
df_clean["A_id"] = df_clean["B_id"].map(lambda b: B_to_A.get(b, -1))

df_clean[["A_id", "B_id", "B_name"]].head()
df_clean["A_id"].value_counts().head()

A_id
20    380
19    354
3     275
5     265
25    216
Name: count, dtype: int64

In [232]:
def name_A_clusters(df):
    A_name_map = {}

    for aid in sorted(df["A_id"].unique()):
        if aid == -1:
            continue

        b_names = (
            df.loc[df["A_id"] == aid, "B_name"]
              .dropna()
              .unique()
              .tolist()
        )
        if not b_names:
            A_name_map[aid] = "Other Group"
            continue

        sample_names = ", ".join(b_names[:15])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of B-level category names and must assign
a concise A-level (top-level) group name.

STRICT RULES:
- Maximum 3 words.
- No brand names.
- Generic, in English.
- Single line with ONLY the category name.

[USER]
Here are B-level categories:

{sample_names}

Respond with ONLY the 3-word-maximum A-level category name.
"""

        raw_label = cached_llm_label(prompt, max_words=6)
        cleaned_label = clean_cluster_name(raw_label, max_words=3)
        if not cleaned_label:
            cleaned_label = "Other Group"

        A_name_map[aid] = cleaned_label
        print(f"A_id {aid} : '{cleaned_label}'")

    return A_name_map


A_name_map = name_A_clusters(df_clean)
df_clean["A_name"] = df_clean["A_id"].map(A_name_map)

df_clean[["A_id", "A_name", "B_id", "B_name", "C_id", "C_name"]].head(20)

⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸ ⠴ ⠦
A_id 0 : 'Mobile Computing Hardware'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
A_id 1 : 'Computer and Technology'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
A_id 2 : 'Computer Peripherals'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
A_id 3 : 'Storage and Organization'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 4 : 'Display Repair Services'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 5 : 'Computer Hardware Products'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
A_id 6 : 'Computing Hardware'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
A_id 7 : 'Camera Equipment'
A_id 8 : 'Display Repair Services'
A_id 9 : 'Display Repair Services'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 10 : 'Consumer Electronics'
⚠ Ollama stderr:
 ⠙ ⠙
A_id 11 : 'Computing and Gadgets'
⚠ Ollama stderr:
 ⠙ ⠙
A_id 12 : 'Ear Monitoring Systems'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 13 : 'Security Software Solutions'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 14 : 'Personal Mobile Devices'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 15 : 'Computer Components'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
A_id 16 : 'Computer Peripherals'
A_id 17 : 'Display Repair Services'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 18 : 'Computer Hardware Components'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 19 : 'Office Supplies'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
A_id 20 : 'Computing Hardware'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 21 : 'Display Devices'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 22 : 'Electronics Accessories'
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
A_id 23 : 'Battery Charging Solutions'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
A_id 24 : 'Computer Peripherals'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
A_id 25 : 'Electronics Equipment'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 26 : 'Information Security'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 27 : 'Electronics Hardware'
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠸
A_id 28 : 'Computer Accessories'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
A_id 29 : 'Accessories for Phones'
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
A_id 30 : 'Personal Computing Devices'
A_id 31 : 'Electronics Equipment'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 32 : 'Data Exchange Standards'
A_id 33 : 'Data Exchange Standards'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 34 : 'Network Infrastructure'
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 35 : 'Electronics Equipment'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 36 : 'Electronics and Gadgets'
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
A_id 37 : 'Cybersecurity and Protection'
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 38 : 'Server Hardware Support'
A_id 39 : 'Data Exchange Standards'
A_id 40 : 'Computer Accessories'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 41 : 'Computer Server Systems'
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 42 : 'Computer Hardware'

,A_id,A_name,B_id,B_name,C_id,C_name
1072689,24,Computer Peripherals,28,Computer Hardware Components,66,Personal Computing Devices
906402,39,Data Exchange Standards,10,Input and Output,49,Computer Keyboards
411281,34,Network Infrastructure,4,Computer Network Equipment,48,Fiber Optic Cables
1047582,30,Personal Computing Devices,7,Desktop Computers,77,Computer Desktop Systems
904910,39,Data Exchange Standards,10,Input and Output,49,Computer Keyboards
157385,38,Server Hardware Support,22,Server Technical Support,15,Computer Server Support
934548,33,Data Exchange Standards,15,Input and Output,62,Computer Keyboards
876762,16,Computer Peripherals,17,Peripherals and Accessories,38,Computer Hardware Parts
1041385,19,Office Supplies,41,Stationery and Office,9,Office Supplies
273638,25,Electronics Equipment,8,Display Technology Products,45,Computer Monitors
288146,3,Storage and Organization,46,Storage Solutions,12,Computer Storage Devices
973610,39,Data Exchange Standards,10,Input and Output,49,Computer Keyboards
513341,1,Computer and Technology,3,IT Help Desk,33,Product Support Services
659426,35,Electronics Equipment,6,Computer and Mobile,79,Portable Laptops
1034218,19,Office Supplies,41,Stationery and Office,9,Office Supplies
500253,38,Server Hardware Support,22,Server Technical Support,15,Computer Server Support
926103,33,Data Exchange Standards,15,Input and Output,62,Computer Keyboards
483648,1,Computer and Technology,18,Computer Equipment Services,55,Computer Hardware Services
659246,42,Computer Hardware,19,Gaming Computer Systems,44,Computer Gaming Hardware
745446,35,Electronics Equipment,6,Computer and Mobile,78,Computer Peripherals

In [233]:
hierarchy = (
    df_clean
      .dropna(subset=["A_name", "B_name", "C_name"])
      .groupby(["A_name", "B_name", "C_name"])
      .size()
      .reset_index(name="num_products")
      .sort_values(["A_name", "B_name", "num_products"],
                   ascending=[True, True, False])
)

hierarchy.head(30)   # inspect

,A_name,B_name,C_name,num_products
2,Accessories for Phones,Phone Case Accessories,Tablet Computer Accessories,77
0,Accessories for Phones,Phone Case Accessories,Computer Accessories Cases,35
1,Accessories for Phones,Phone Case Accessories,Screen Phone Protectors,30
3,Battery Charging Solutions,Portable Power Supplies,Rechargeable Laptop Batteries,38
4,Camera Equipment,Digital Camera Accessories,Camera Equipment,36
5,Computer Accessories,Peripherals and Devices,Computer Components,83
6,Computer Components,Microprocessor Units,Computer Processors,63
7,Computer Hardware,Gaming Computer Systems,Computer Gaming Hardware,73
8,Computer Hardware Components,Computer Power Supplies,Power Supplies,43
10,Computer Hardware Products,Desktop Computing Products,Laptop Computer Accessories,50
9,Computer Hardware Products,Desktop Computing Products,Computer Hardware,40
11,Computer Hardware Products,Desktop Computing Products,Laptops and Tablets,30
12,Computer Hardware Products,Electronics Computer,Computer Hardware Components,46
14,Computer Hardware Products,Electronics Computer,Electronics Computer Devices,43
13,Computer Hardware Products,Electronics Computer,Computer Hardware Products,29
15,Computer Hardware Products,Electronics Computer,Electronics Computer Laptops,27
16,Computer Peripherals,Computer Graphics Accessories,Graphics Card Adapters,40
19,Computer Peripherals,Computer Hardware Components,Personal Computing Devices,67
18,Computer Peripherals,Computer Hardware Components,Laptops and Desktops,35
17,Computer Peripherals,Computer Hardware Components,Laptops and Computers,24
20,Computer Peripherals,Peripherals and Accessories,Computer Hardware Parts,113
21,Computer Peripherals,Peripherals and Devices,Computer Hardware Components,50
22,Computer Server Systems,Server Racks and,Data Center Cabinets,63
25,Computer and Technology,Computer Equipment Services,Product Maintenance and,33
24,Computer and Technology,Computer Equipment Services,Print Equipment Services,31
23,Computer and Technology,Computer Equipment Services,Computer Hardware Services,27
27,Computer and Technology,IT Help Desk,Product Support Services,42
28,Computer and Technology,IT Help Desk,Service Phone Support,39
26,Computer and Technology,IT Help Desk,Computer Hardware and,31
29,Computing Hardware,Computer Equipment Category,Computer Hardware and,380

In [234]:
from anytree import Node, RenderTree

# 1) Take unique A–B–C rows from your 'hierarchy' df
unique_paths = (
    hierarchy[["A_name", "B_name", "C_name", "num_products"]]
    .dropna()
    .drop_duplicates()
)

# 2) Create root (rename if you like)
root = Node("Computers & Electronics")

# 3) Cache to avoid recreating nodes
node_cache = {}   # keys: ("A", A_name), ("B", A_name, B_name), ("C", A_name, B_name, C_name)

for _, row in unique_paths.iterrows():
    a = row["A_name"]
    b = row["B_name"]
    c = row["C_name"]
    n = row["num_products"]

    # ---- A level ----
    a_key = ("A", a)
    if a_key not in node_cache:
        node_cache[a_key] = Node(a, parent=root)
    a_node = node_cache[a_key]

    # ---- B level ----
    b_key = ("B", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)
    b_node = node_cache[b_key]

    # ---- C level (with counts) ----
    c_key = ("C", a, b, c)
    if c_key not in node_cache:
        label_c = f"{c} ({n} products)"
        node_cache[c_key] = Node(label_c, parent=b_node)

# 4) Pretty-print tree
for pre, _, node in RenderTree(root):
    print(f"{pre}{node.name}")

Computers & Electronics
├── Accessories for Phones
│   └── Phone Case Accessories
│       ├── Tablet Computer Accessories (77 products)
│       ├── Computer Accessories Cases (35 products)
│       └── Screen Phone Protectors (30 products)
├── Battery Charging Solutions
│   └── Portable Power Supplies
│       └── Rechargeable Laptop Batteries (38 products)
├── Camera Equipment
│   └── Digital Camera Accessories
│       └── Camera Equipment (36 products)
├── Computer Accessories
│   └── Peripherals and Devices
│       └── Computer Components (83 products)
├── Computer Components
│   └── Microprocessor Units
│       └── Computer Processors (63 products)
├── Computer Hardware
│   └── Gaming Computer Systems
│       └── Computer Gaming Hardware (73 products)
├── Computer Hardware Components
│   └── Computer Power Supplies
│       └── Power Supplies (43 products)
├── Computer Hardware Products
│   ├── Desktop Computing Products
│   │   ├── Laptop Computer Accessories (50 products)
│   │   ├── Computer Hardware (40 products)
│   │   └── Laptops and Tablets (30 products)
│   └── Electronics Computer
│       ├── Computer Hardware Components (46 products)
│       ├── Electronics Computer Devices (43 products)
│       ├── Computer Hardware Products (29 products)
│       └── Electronics Computer Laptops (27 products)
├── Computer Peripherals
│   ├── Computer Graphics Accessories
│   │   └── Graphics Card Adapters (40 products)
│   ├── Computer Hardware Components
│   │   ├── Personal Computing Devices (67 products)
│   │   ├── Laptops and Desktops (35 products)
│   │   └── Laptops and Computers (24 products)
│   ├── Peripherals and Accessories
│   │   └── Computer Hardware Parts (113 products)
│   └── Peripherals and Devices
│       └── Computer Hardware Components (50 products)
├── Computer Server Systems
│   └── Server Racks and
│       └── Data Center Cabinets (63 products)
├── Computer and Technology
│   ├── Computer Equipment Services
│   │   ├── Product Maintenance and (33 products)
│   │   ├── Print Equipment Services (31 products)
│   │   └── Computer Hardware Services (27 products)
│   └── IT Help Desk
│       ├── Product Support Services (42 products)
│       ├── Service Phone Support (39 products)
│       └── Computer Hardware and (31 products)
├── Computing Hardware
│   ├── Computer Equipment Category
│   │   └── Computer Hardware and (380 products)
│   └── Input/Output Devices
│       └── Computer Peripherals (25 products)
├── Computing and Gadgets
│   └── Portable Electronics
│       └── Portable Power Batteries (39 products)
├── Consumer Electronics
│   └── Electronics Industry
│       └── Computing and Electronics (20 products)
├── Cybersecurity and Protection
│   └── Information Security
│       ├── Security Solutions (56 products)
│       ├── Security Software Solutions (44 products)
│       └── Security Information Systems (20 products)
├── Data Exchange Standards
│   └── Input and Output
│       └── Computer Keyboards (319 products)
├── Display Devices
│   └── Computer Display Products
│       ├── Display LCD Panels (33 products)
│       └── Computer Monitor Covers (20 products)
├── Display Repair Services
│   └── Computer Display Repairs
│       └── Laptop Screen Replacement (203 products)
├── Ear Monitoring Systems
│   └── In Ear Monitors
│       └── Personal In Ear (23 products)
├── Electronics Accessories
│   └── Mobile Accessories
│       └── Laptop Computer Adapters (24 products)
├── Electronics Equipment
│   ├── Computer and Mobile
│   │   ├── Portable Laptops (72 products)
│   │   ├── Computer Peripherals (31 products)
│   │   ├── Electronics Laptops Computers (28 products)
│   │   └── Electronics Computer Laptops (24 products)
│   └── Display Technology Products
│       ├── Computer Monitors (190 products)
│       ├── Satellite LCD Screen (88 products)
│       └── Viewable Projection Screens (26 products)
├── Electronics Hardware
│   └── Computer Components
│       └── Computer Memory Modules (85 products)
├── Electronics and Gadgets
│   └── Consumer Electronics
│       └── Electronics Consumer Devices (65 products)
├── Information Security
│   └── Cybersecurity Product Software
│       ├── Security Product Software (61 products)
│       └── Cybersecurity Software Solutions (40 products)
├── Mobile Computing Hardware
│   ├── Mobile Computing Components
│   │   └── Laptop Processors (49 products)
│   └── Mobile Computing Hardware
│       ├── Portable Computing Devices (42 products)
│       └── Laptop Computer Hardware (30 products)
├── Network Infrastructure
│   └── Computer Network Equipment
│       ├── Networking Cabling Products (38 products)
│       ├── Fiber Optic Cables (32 products)
│       ├── Computer Peripherals Accessories (28 products)
│       └── Computer Network Cables (26 products)
├── Office Supplies
│   └── Stationery and Office
│       └── Office Supplies (354 products)
├── Personal Computing Devices
│   └── Desktop Computers
│       ├── Computer Desktop Systems (75 products)
│       └── Computer Hardware (75 products)
├── Personal Mobile Devices
│   └── Tablet Computing Devices
│       └── Display Tablet Computers (38 products)
├── Security Software Solutions
│   └── Computer Security Solutions
│       └── Antivirus Software (22 products)
├── Server Hardware Support
│   └── Server Technical Support
│       └── Computer Server Support (44 products)
└── Storage and Organization
    ├── Storage Devices and
    │   ├── External Hard Drives (123 products)
    │   ├── Computer Hard Drives (84 products)
    │   └── Storage Network Devices (25 products)
    └── Storage Solutions
        └── Computer Storage Devices (43 products)

In [235]:
from anytree import Node, RenderTree

# 1) Take unique A–B–C rows
unique_paths = (
    hierarchy[["A_name", "B_name", "C_name", "num_products"]]
    .dropna()
    .drop_duplicates()
)

# 2) We create multiple A-nodes directly (no global root)
roots = {}     # {A_name : Node}

node_cache = {}  # prevent duplicates

for _, row in unique_paths.iterrows():
    a = row["A_name"]
    b = row["B_name"]
    c = row["C_name"]
    n = row["num_products"]

    # ---- A level (each A is its own root) ----
    if a not in roots:
        roots[a] = Node(a)
    a_node = roots[a]

    # ---- B level ----
    b_key = ("B", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)
    b_node = node_cache[b_key]

    # ---- C level ----
    c_key = ("C", a, b, c)
    if c_key not in node_cache:
        label_c = f"{c} ({n} products)"
        node_cache[c_key] = Node(label_c, parent=b_node)

# 3) Print each A-tree separately
for a, root_node in roots.items():
    print(f"\n=== {a} ===")
    for pre, _, node in RenderTree(root_node):
        print(f"{pre}{node.name}")

=== Accessories for Phones ===
Accessories for Phones
└── Phone Case Accessories
    ├── Tablet Computer Accessories (77 products)
    ├── Computer Accessories Cases (35 products)
    └── Screen Phone Protectors (30 products)

=== Battery Charging Solutions ===
Battery Charging Solutions
└── Portable Power Supplies
    └── Rechargeable Laptop Batteries (38 products)

=== Camera Equipment ===
Camera Equipment
└── Digital Camera Accessories
    └── Camera Equipment (36 products)

=== Computer Accessories ===
Computer Accessories
└── Peripherals and Devices
    └── Computer Components (83 products)

=== Computer Components ===
Computer Components
└── Microprocessor Units
    └── Computer Processors (63 products)

=== Computer Hardware ===
Computer Hardware
└── Gaming Computer Systems
    └── Computer Gaming Hardware (73 products)

=== Computer Hardware Components ===
Computer Hardware Components
└── Computer Power Supplies
    └── Power Supplies (43 products)

=== Computer Hardware Products ===
Computer Hardware Products
├── Desktop Computing Products
│   ├── Laptop Computer Accessories (50 products)
│   ├── Computer Hardware (40 products)
│   └── Laptops and Tablets (30 products)
└── Electronics Computer
    ├── Computer Hardware Components (46 products)
    ├── Electronics Computer Devices (43 products)
    ├── Computer Hardware Products (29 products)
    └── Electronics Computer Laptops (27 products)

=== Computer Peripherals ===
Computer Peripherals
├── Computer Graphics Accessories
│   └── Graphics Card Adapters (40 products)
├── Computer Hardware Components
│   ├── Personal Computing Devices (67 products)
│   ├── Laptops and Desktops (35 products)
│   └── Laptops and Computers (24 products)
├── Peripherals and Accessories
│   └── Computer Hardware Parts (113 products)
└── Peripherals and Devices
    └── Computer Hardware Components (50 products)

=== Computer Server Systems ===
Computer Server Systems
└── Server Racks and
    └── Data Center Cabinets (63 products)

=== Computer and Technology ===
Computer and Technology
├── Computer Equipment Services
│   ├── Product Maintenance and (33 products)
│   ├── Print Equipment Services (31 products)
│   └── Computer Hardware Services (27 products)
└── IT Help Desk
    ├── Product Support Services (42 products)
    ├── Service Phone Support (39 products)
    └── Computer Hardware and (31 products)

=== Computing Hardware ===
Computing Hardware
├── Computer Equipment Category
│   └── Computer Hardware and (380 products)
└── Input/Output Devices
    └── Computer Peripherals (25 products)

=== Computing and Gadgets ===
Computing and Gadgets
└── Portable Electronics
    └── Portable Power Batteries (39 products)

=== Consumer Electronics ===
Consumer Electronics
└── Electronics Industry
    └── Computing and Electronics (20 products)

=== Cybersecurity and Protection ===
Cybersecurity and Protection
└── Information Security
    ├── Security Solutions (56 products)
    ├── Security Software Solutions (44 products)
    └── Security Information Systems (20 products)

=== Data Exchange Standards ===
Data Exchange Standards
└── Input and Output
    └── Computer Keyboards (319 products)

=== Display Devices ===
Display Devices
└── Computer Display Products
    ├── Display LCD Panels (33 products)
    └── Computer Monitor Covers (20 products)

=== Display Repair Services ===
Display Repair Services
└── Computer Display Repairs
    └── Laptop Screen Replacement (203 products)

=== Ear Monitoring Systems ===
Ear Monitoring Systems
└── In Ear Monitors
    └── Personal In Ear (23 products)

=== Electronics Accessories ===
Electronics Accessories
└── Mobile Accessories
    └── Laptop Computer Adapters (24 products)

=== Electronics Equipment ===
Electronics Equipment
├── Computer and Mobile
│   ├── Portable Laptops (72 products)
│   ├── Computer Peripherals (31 products)
│   ├── Electronics Laptops Computers (28 products)
│   └── Electronics Computer Laptops (24 products)
└── Display Technology Products
    ├── Computer Monitors (190 products)
    ├── Satellite LCD Screen (88 products)
    └── Viewable Projection Screens (26 products)

=== Electronics Hardware ===
Electronics Hardware
└── Computer Components
    └── Computer Memory Modules (85 products)

=== Electronics and Gadgets ===
Electronics and Gadgets
└── Consumer Electronics
    └── Electronics Consumer Devices (65 products)

=== Information Security ===
Information Security
└── Cybersecurity Product Software
    ├── Security Product Software (61 products)
    └── Cybersecurity Software Solutions (40 products)

=== Mobile Computing Hardware ===
Mobile Computing Hardware
├── Mobile Computing Components
│   └── Laptop Processors (49 products)
└── Mobile Computing Hardware
    ├── Portable Computing Devices (42 products)
    └── Laptop Computer Hardware (30 products)

=== Network Infrastructure ===
Network Infrastructure
└── Computer Network Equipment
    ├── Networking Cabling Products (38 products)
    ├── Fiber Optic Cables (32 products)
    ├── Computer Peripherals Accessories (28 products)
    └── Computer Network Cables (26 products)

=== Office Supplies ===
Office Supplies
└── Stationery and Office
    └── Office Supplies (354 products)

=== Personal Computing Devices ===
Personal Computing Devices
└── Desktop Computers
    ├── Computer Desktop Systems (75 products)
    └── Computer Hardware (75 products)

=== Personal Mobile Devices ===
Personal Mobile Devices
└── Tablet Computing Devices
    └── Display Tablet Computers (38 products)

=== Security Software Solutions ===
Security Software Solutions
└── Computer Security Solutions
    └── Antivirus Software (22 products)

=== Server Hardware Support ===
Server Hardware Support
└── Server Technical Support
    └── Computer Server Support (44 products)

=== Storage and Organization ===
Storage and Organization
├── Storage Devices and
│   ├── External Hard Drives (123 products)
│   ├── Computer Hard Drives (84 products)
│   └── Storage Network Devices (25 products)
└── Storage Solutions
    └── Computer Storage Devices (43 products)

In [236]:
# =============== PRETTY ASCII TREE PRINTER ===============

def print_ascii_tree(hierarchy_df):
    """
    hierarchy_df must have columns: A_name, B_name, C_name, num_products
    """
    
    # Step 1: group hierarchy by A
    A_groups = hierarchy_df.groupby("A_name")

    for A_name, dfA in A_groups:
        print(f"\n{A_name}")

        # Create a prefix for A-level children
        A_prefix = ""

        # Step 2: group B under each A
        B_groups = dfA.groupby("B_name")

        B_names = list(B_groups.groups.keys())
        last_B = B_names[-1]

        for B_name, dfB in B_groups:
            is_last_B = (B_name == last_B)
            B_connector = "└──" if is_last_B else "├──"
            print(f"{A_prefix}{B_connector} {B_name}")

            # prefix for C under this B
            C_prefix = "    " if is_last_B else "│   "

            # Step 3: C-level
            C_rows = dfB[["C_name", "num_products"]].values.tolist()
            last_C = C_rows[-1]

            for C_name, num_products in C_rows:
                is_last_C = (C_name == last_C[0])
                C_connector = "└──" if is_last_C else "├──"
                print(f"{A_prefix}{C_prefix}{C_connector} {C_name} ({num_products})")

In [237]:
print_ascii_tree(hierarchy)

Accessories for Phones
└── Phone Case Accessories
    ├── Tablet Computer Accessories (77)
    ├── Computer Accessories Cases (35)
    └── Screen Phone Protectors (30)

Battery Charging Solutions
└── Portable Power Supplies
    └── Rechargeable Laptop Batteries (38)

Camera Equipment
└── Digital Camera Accessories
    └── Camera Equipment (36)

Computer Accessories
└── Peripherals and Devices
    └── Computer Components (83)

Computer Components
└── Microprocessor Units
    └── Computer Processors (63)

Computer Hardware
└── Gaming Computer Systems
    └── Computer Gaming Hardware (73)

Computer Hardware Components
└── Computer Power Supplies
    └── Power Supplies (43)

Computer Hardware Products
├── Desktop Computing Products
│   ├── Laptop Computer Accessories (50)
│   ├── Computer Hardware (40)
│   └── Laptops and Tablets (30)
└── Electronics Computer
    ├── Computer Hardware Components (46)
    ├── Electronics Computer Devices (43)
    ├── Computer Hardware Products (29)
    └── Electronics Computer Laptops (27)

Computer Peripherals
├── Computer Graphics Accessories
│   └── Graphics Card Adapters (40)
├── Computer Hardware Components
│   ├── Personal Computing Devices (67)
│   ├── Laptops and Desktops (35)
│   └── Laptops and Computers (24)
├── Peripherals and Accessories
│   └── Computer Hardware Parts (113)
└── Peripherals and Devices
    └── Computer Hardware Components (50)

Computer Server Systems
└── Server Racks and
    └── Data Center Cabinets (63)

Computer and Technology
├── Computer Equipment Services
│   ├── Product Maintenance and (33)
│   ├── Print Equipment Services (31)
│   └── Computer Hardware Services (27)
└── IT Help Desk
    ├── Product Support Services (42)
    ├── Service Phone Support (39)
    └── Computer Hardware and (31)

Computing Hardware
├── Computer Equipment Category
│   └── Computer Hardware and (380)
└── Input/Output Devices
    └── Computer Peripherals (25)

Computing and Gadgets
└── Portable Electronics
    └── Portable Power Batteries (39)

Consumer Electronics
└── Electronics Industry
    └── Computing and Electronics (20)

Cybersecurity and Protection
└── Information Security
    ├── Security Solutions (56)
    ├── Security Software Solutions (44)
    └── Security Information Systems (20)

Data Exchange Standards
└── Input and Output
    └── Computer Keyboards (319)

Display Devices
└── Computer Display Products
    ├── Display LCD Panels (33)
    └── Computer Monitor Covers (20)

Display Repair Services
└── Computer Display Repairs
    └── Laptop Screen Replacement (203)

Ear Monitoring Systems
└── In Ear Monitors
    └── Personal In Ear (23)

Electronics Accessories
└── Mobile Accessories
    └── Laptop Computer Adapters (24)

Electronics Equipment
├── Computer and Mobile
│   ├── Portable Laptops (72)
│   ├── Computer Peripherals (31)
│   ├── Electronics Laptops Computers (28)
│   └── Electronics Computer Laptops (24)
└── Display Technology Products
    ├── Computer Monitors (190)
    ├── Satellite LCD Screen (88)
    └── Viewable Projection Screens (26)

Electronics Hardware
└── Computer Components
    └── Computer Memory Modules (85)

Electronics and Gadgets
└── Consumer Electronics
    └── Electronics Consumer Devices (65)

Information Security
└── Cybersecurity Product Software
    ├── Security Product Software (61)
    └── Cybersecurity Software Solutions (40)

Mobile Computing Hardware
├── Mobile Computing Components
│   └── Laptop Processors (49)
└── Mobile Computing Hardware
    ├── Portable Computing Devices (42)
    └── Laptop Computer Hardware (30)

Network Infrastructure
└── Computer Network Equipment
    ├── Networking Cabling Products (38)
    ├── Fiber Optic Cables (32)
    ├── Computer Peripherals Accessories (28)
    └── Computer Network Cables (26)

Office Supplies
└── Stationery and Office
    └── Office Supplies (354)

Personal Computing Devices
└── Desktop Computers
    ├── Computer Desktop Systems (75)
    └── Computer Hardware (75)

Personal Mobile Devices
└── Tablet Computing Devices
    └── Display Tablet Computers (38)

Security Software Solutions
└── Computer Security Solutions
    └── Antivirus Software (22)

Server Hardware Support
└── Server Technical Support
    └── Computer Server Support (44)

Storage and Organization
├── Storage Devices and
│   ├── External Hard Drives (123)
│   ├── Computer Hard Drives (84)
│   └── Storage Network Devices (25)
└── Storage Solutions
    └── Computer Storage Devices (43)

In [238]:
#Check cosine similarity between path_3 and predicted taxonomy( how similar they are)

In [240]:
# Normalize all labels (gold + predicted)
import re

def normalize_text(s):
    if not isinstance(s, str):
        return ""
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9 ]+", " ", s)
    s = re.sub(r"\s+", " ", s)
    return s.strip()

# Gold
df_clean["gold_A_norm"] = df_clean["A"].apply(normalize_text)
df_clean["gold_B_norm"] = df_clean["B"].apply(normalize_text)
df_clean["gold_C_norm"] = df_clean["C"].apply(normalize_text)

# Predicted
df_clean["pred_A_norm"] = df_clean["A_name"].apply(normalize_text)
df_clean["pred_B_norm"] = df_clean["B_name"].apply(normalize_text)
df_clean["pred_C_norm"] = df_clean["C_name"].apply(normalize_text)

# Full path (gold vs discovered)
df_clean["gold_path_norm"] = df_clean["path_3"].apply(normalize_text)
df_clean["pred_path_norm"] = (
    (df_clean["A_name"].fillna("") + " > " +
     df_clean["B_name"].fillna("") + " > " +
     df_clean["C_name"].fillna(""))
    .apply(normalize_text)
)

In [241]:
#Load MiniLM and define helper for cosine
from sentence_transformers import SentenceTransformer
import numpy as np

st = SentenceTransformer("all-MiniLM-L6-v2")

def mean_cosine_sim(texts_gold, texts_pred):
    gold_emb = st.encode(texts_gold, normalize_embeddings=True)
    pred_emb = st.encode(texts_pred, normalize_embeddings=True)
    cos = np.sum(gold_emb * pred_emb, axis=1)   # dot product = cosine
    return float(cos.mean())

In [242]:
# Cosine similarity for A, B, C, full path
cos_A = mean_cosine_sim(
    df_clean["gold_A_norm"].tolist(),
    df_clean["pred_A_norm"].tolist()
)

cos_B = mean_cosine_sim(
    df_clean["gold_B_norm"].tolist(),
    df_clean["pred_B_norm"].tolist()
)

cos_C = mean_cosine_sim(
    df_clean["gold_C_norm"].tolist(),
    df_clean["pred_C_norm"].tolist()
)

cos_path = mean_cosine_sim(
    df_clean["gold_path_norm"].tolist(),
    df_clean["pred_path_norm"].tolist()
)

print("A-level cosine similarity:", cos_A)
print("B-level cosine similarity:", cos_B)
print("C-level cosine similarity:", cos_C)
print("Full-path cosine similarity:", cos_path)

A-level cosine similarity: 0.5126641392707825
B-level cosine similarity: 0.48224878311157227
C-level cosine similarity: 0.47320079803466797
Full-path cosine similarity: 0.5201599597930908

In [243]:
#purity / NMI are to check how well your HDBSCAN C-clusters line up with the original C-level labels (ignoring the LLM names).
# Think:
# C_id = discovered cluster from HDBSCAN
# C = gold C-level from original taxonomy

from sklearn.metrics import normalized_mutual_info_score
import numpy as np

# Keep only rows that have both a cluster and a gold C-level
df_eval = df_clean.dropna(subset=["C_id", "C"]).copy()

# If any -1 noise still exists, drop it for evaluation
df_eval = df_eval[df_eval["C_id"] != -1].copy()

y_clusters = df_eval["C_id"].astype(int).to_numpy()
y_gold_C  = df_eval["C"].astype(str).to_numpy()

In [244]:
def cluster_purity(y_true, y_pred):
    """
    y_true: gold labels (here: C)
    y_pred: discovered clusters (here: C_id)
    """
    # unique clusters
    clusters = np.unique(y_pred)
    N = len(y_pred)
    correct = 0

    for c in clusters:
        idx = (y_pred == c)
        if not np.any(idx):
            continue
        # gold labels inside this cluster
        labels, counts = np.unique(y_true[idx], return_counts=True)
        correct += counts.max()   # majority label count

    return correct / N

purity_C = cluster_purity(y_gold_C, y_clusters)
print("C-level cluster purity:", purity_C)
# Cluster Purity = “How clean is each cluster inside?”
# Your purity: 0.826 (~82.6%)
# Purity checks within each discovered HDBSCAN cluster:
# “If I look inside cluster X, do most products belong to the same gold C-level category?”
# For example:
# Cluster 9 has 354 products
# Suppose 290 of them are “Laptop Screens” (majority)
# Purity contribution = 290 / 354

C-level cluster purity: 0.8255872063968016

In [245]:
nmi_C = normalized_mutual_info_score(y_gold_C, y_clusters)
print("C-level NMI (gold C vs C_id):", nmi_C)
#It measures how close the entire clustering assignment is to the gold categories.
# @“How well does the entire clustering structure match the gold taxonomy

C-level NMI (gold C vs C_id): 0.6672069526713204

In [246]:
#BERTSCORE

In [247]:
# Normalize gold labels
df_clean["gold_A"] = df_clean["A"].fillna("").astype(str).str.strip()
df_clean["gold_B"] = df_clean["B"].fillna("").astype(str).str.strip()
df_clean["gold_C"] = df_clean["C"].fillna("").astype(str).str.strip()

# Normalize predicted labels
df_clean["pred_A"] = df_clean["A_name"].fillna("").astype(str).str.strip()
df_clean["pred_B"] = df_clean["B_name"].fillna("").astype(str).str.strip()
df_clean["pred_C"] = df_clean["C_name"].fillna("").astype(str).str.strip()

# Build gold path and predicted path
df_clean["gold_path"] = (
    df_clean["gold_A"] + " > " +
    df_clean["gold_B"] + " > " +
    df_clean["gold_C"]
)

df_clean["pred_path"] = (
    df_clean["pred_A"] + " > " +
    df_clean["pred_B"] + " > " +
    df_clean["pred_C"]
)

In [248]:
from bert_score import score as bertscore_score

def compute_bertscore(refs, cands, model_type="roberta-large"):
    # Replace any empty strings with "none"
    refs = ["none" if not r.strip() else r for r in refs]
    cands = ["none" if not c.strip() else c for c in cands]

    P, R, F1 = bertscore_score(
        cands,  # candidates
        refs,   # references (gold)
        model_type="bert-base-uncased",
        lang="en",
        rescale_with_baseline=False
    )
    return float(P.mean()), float(R.mean()), float(F1.mean())

In [249]:
gold_A = df_clean["gold_A"].tolist()
pred_A = df_clean["pred_A"].tolist()

gold_B = df_clean["gold_B"].tolist()
pred_B = df_clean["pred_B"].tolist()

gold_C = df_clean["gold_C"].tolist()
pred_C = df_clean["pred_C"].tolist()

gold_path = df_clean["gold_path"].tolist()
pred_path = df_clean["pred_path"].tolist()

In [250]:
print(" A-level BERTScore:")
print(compute_bertscore(gold_A, pred_A))

print("\n B-level BERTScore:")
print(compute_bertscore(gold_B, pred_B))

print("\n C-level BERTScore:")
print(compute_bertscore(gold_C, pred_C))

print("\n Full-path BERTScore:")
print(compute_bertscore(gold_path, pred_path))

 A-level BERTScore:
(0.5946646332740784, 0.5597482919692993, 0.5757115483283997)

 B-level BERTScore:
(0.5408266186714172, 0.6198215484619141, 0.5741963386535645)

 C-level BERTScore:
(0.598725438117981, 0.5848424434661865, 0.589326798915863)

 Full-path BERTScore:
(0.6769204139709473, 0.6764034032821655, 0.6758546829223633)

In [251]:
#how similar is our generated tree to the test data

In [252]:
df_test = pd.read_json("D:/git/Taxonomy_Buidling_Textual_Corpora/data/icecat_data_test.json")

# Work only with first 5000 rows from the beginning
df_test = df_test.iloc[:2000].copy()

print("Raw sample size:", len(df_test))

Raw sample size: 2000

In [253]:
df_test.head(2)

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
500081,Fujitsu,,https://images.icecat.biz/img/brand/thumb/15_b...,Fujitsu,https://images.icecat.biz/img/brand/thumb/15_b...,FSP:G-SW3Z560PRE0S,[],788,EN,Warranty & Support Extensions,...,None,None,NaN,None,None,None,None,NaN,2833>839>788,Computers & Electronics>Warranty & Support>War...
741063,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,5KM83PA,None,151,EN,Notebooks,...,EN,13,1268560.0,EN,2018-10-21 21:55:51,"[Windows 10 Home 64-bit, Intel® Core™ i7-8565U...","[{'VirtualCategoryID': 329, 'UNCATID': '432115...",NaN,2833>150>151,Computers & Electronics>Computers>Notebooks

In [254]:
# From TRAIN (df_clean)
import numpy as np

# centroids in UMAP space, one vector per C_id
valid_cids = sorted(df_clean["C_id"].unique())
C_centroids = []
C_labels = []

for cid in valid_cids:
    idx = df_clean["C_id"] == cid
    C_centroids.append(df_clean.loc[idx, "umap_1":"umap_2"].to_numpy().mean(axis=0) 
                       if "umap_1" in df_clean.columns
                       else reduced[idx].mean(axis=0))
    C_labels.append(cid)

C_centroids = np.vstack(C_centroids)  # shape (#C_clusters, 2) if UMAP(2D)
C_labels = np.array(C_labels)

# Build mappings for B, A based on TRAIN
C_to_B = dict(zip(df_clean["C_id"], df_clean["B_id"]))
B_to_A = dict(zip(df_clean["B_id"], df_clean["A_id"]))

B_name_map = dict(zip(df_clean["B_id"], df_clean["B_name"]))
A_name_map = dict(zip(df_clean["A_id"], df_clean["A_name"]))

In [255]:
df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,...,gold_path_norm,pred_path_norm,gold_A,gold_B,gold_C,pred_A,pred_B,pred_C,gold_path,pred_path
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,...,computers electronics computers pcs workstations,computer peripherals computer hardware compone...,Computers & Electronics,Computers,PCs/Workstations,Computer Peripherals,Computer Hardware Components,Personal Computing Devices,Computers & Electronics > Computers > PCs/Work...,Computer Peripherals > Computer Hardware Compo...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,...,computers electronics computers notebook parts...,data exchange standards input and output compu...,Computers & Electronics,Computers,Notebook Parts & Accessories,Data Exchange Standards,Input and Output,Computer Keyboards,Computers & Electronics > Computers > Notebook...,Data Exchange Standards > Input and Output > C...

In [256]:
def split_path(path):
    if not isinstance(path, str):
        return []
    parts = [p.strip() for p in path.split(">") if p.strip()]
    return parts

df_test["num_levels"] = df_test["pathlist_names"].apply(lambda x: len(split_path(x)))

print("Counts BEFORE cleaning:")
print(df_test["num_levels"].value_counts().sort_index())

Counts BEFORE cleaning:
num_levels
3    1198
4     802
Name: count, dtype: int64

In [257]:
import pandas as pd

def make_3_and_4(path):
    parts = split_path(path)

    # default
    path_3 = None
    level_4 = None

    if len(parts) >= 3:
        path_3 = " > ".join(parts[:3])   # A > B > C
    if len(parts) >= 4:
        level_4 = parts[3]               # D (4th level)

    return pd.Series({"path_3": path_3, "level_4": level_4})

df_test[["path_3", "level_4"]] = df_test["pathlist_names"].apply(make_3_and_4)

print(df_test[["pathlist_names", "path_3", "level_4"]].head(10))

                                            pathlist_names  \
500081   Computers & Electronics>Warranty & Support>War...
741063         Computers & Electronics>Computers>Notebooks
1091454  Computers & Electronics>Computers>PCs/Workstat...
522928   Computers & Electronics>Computer Cables>Networ...
479478   Computers & Electronics>Warranty & Support>War...
449642   Computers & Electronics>Data Storage>Data Stor...
1024163  Computers & Electronics>Consumer Audio & Video...
31904    Computers & Electronics>Printers & Scanners>Pr...
360523   Computers & Electronics>Telecom & Navigation>M...
675402         Computers & Electronics>Computers>Notebooks

                                                    path_3  \
500081   Computers & Electronics > Warranty & Support >...
741063     Computers & Electronics > Computers > Notebooks
1091454  Computers & Electronics > Computers > PCs/Work...
522928   Computers & Electronics > Computer Cables > Ne...
479478   Computers & Electronics > Warranty & Support >...
449642   Computers & Electronics > Data Storage > Data ...
1024163  Computers & Electronics > Consumer Audio & Vid...
31904    Computers & Electronics > Printers & Scanners ...
360523   Computers & Electronics > Telecom & Navigation...
675402     Computers & Electronics > Computers > Notebooks

                      level_4
500081                   None
741063                   None
1091454                  None
522928                   None
479478                   None
449642   Internal Hard Drives
1024163            Headphones
31904         Trays & Feeders
360523                   None
675402                   None

In [258]:
print("Rows:", len(df))
print("Unique num_levels (original):")
print(df_test["num_levels"].value_counts().sort_index())

print("\nCheck how many have a 4th level stored:")
print(df_test["level_4"].notna().sum(), "rows with level_4")

Rows: 4382
Unique num_levels (original):
num_levels
3    1198
4     802
Name: count, dtype: int64

Check how many have a 4th level stored:
802 rows with level_4

In [260]:
# Extract A, B, C from path_3
df_test[["A", "B", "C"]] = (
    df_test["path_3"]
    .str.split(">", expand=True)
    .apply(lambda col: col.str.strip())
)

In [261]:
df_test.head(2)

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
500081,Fujitsu,,https://images.icecat.biz/img/brand/thumb/15_b...,Fujitsu,https://images.icecat.biz/img/brand/thumb/15_b...,FSP:G-SW3Z560PRE0S,[],788,EN,Warranty & Support Extensions,...,None,NaN,2833>839>788,Computers & Electronics>Warranty & Support>War...,3,Computers & Electronics > Warranty & Support >...,None,Computers & Electronics,Warranty & Support,Warranty & Support Extensions
741063,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,5KM83PA,None,151,EN,Notebooks,...,"[{'VirtualCategoryID': 329, 'UNCATID': '432115...",NaN,2833>150>151,Computers & Electronics>Computers>Notebooks,3,Computers & Electronics > Computers > Notebooks,None,Computers & Electronics,Computers,Notebooks

In [262]:
#columns to keep
cols_needed = [
    "Brand",
    "BrandPartCode",
    "ProductName",
    "Description.LongProductName",
    "SummaryDescription.LongSummaryDescription",
    "Description.LongDesc",
    "A", "B", "C",
    "path_3"   # <-- Needed for evaluation
]

In [263]:
df_test = df_test[cols_needed].copy()

In [264]:
# Build raw metadata text

def build_metadata(row):
    parts = []

    if pd.notna(row["Brand"]):
        parts.append(row["Brand"])

    if pd.notna(row["BrandPartCode"]):
        parts.append(row["BrandPartCode"])
        
    if pd.notna(row["ProductName"]):
        parts.append(row["ProductName"])

    if pd.notna(row["Description.LongProductName"]):
        parts.append(row["Description.LongProductName"])

    if pd.notna(row["SummaryDescription.LongSummaryDescription"]):
        parts.append(row["SummaryDescription.LongSummaryDescription"])

    if pd.notna(row["Description.LongDesc"]):
        parts.append(row["Description.LongDesc"])

    return " ".join(parts)

df_test["metadata_text"] = df_test.apply(build_metadata, axis=1)

In [265]:
df_test

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text
500081,Fujitsu,FSP:G-SW3Z560PRE0S,FSP:G-SW3Z560PRE0S,"SP 3y TS Sub & Upgr, 9x5, 4h Rm Rt f/ CS200c A...",Fujitsu FSP:G-SW3Z560PRE0S. Number of years: 3...,In times of growing complexity and decreasing ...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Fujitsu FSP:G-SW3Z560PRE0S FSP:G-SW3Z560PRE0S ...
741063,HP,5KM83PA,13-ap0023tu,"Intel® Core™ i7-8565U (1.8 GHz), 16GB DDR4-SDR...",HP Spectre x360 13-ap0023tu. Product type: Hyb...,<b>Revolutionary battery life on a convertible...,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,HP 5KM83PA 13-ap0023tu Intel® Core™ i7-8565U (...
1091454,HP,4NG33EA,880-156nf,None,HP OMEN 880-156nf. Processor frequency: 3.2 GH...,None,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,HP 4NG33EA 880-156nf HP OMEN 880-156nf. Proces...
522928,C2G,83061,1m Cat5e Non-Booted Unshielded (UTP) Network P...,Cat5E Assembled UTP Patch Cable Green 1m,C2G 1m Cat5e Non-Booted Unshielded (UTP) Netwo...,Perfect for your home office or a large instal...,Computers & Electronics,Computer Cables,Networking Cables,Computers & Electronics > Computer Cables > Ne...,C2G 83061 1m Cat5e Non-Booted Unshielded (UTP)...
479478,Lenovo,5PS0A14091,5PS0A14091,3YR Onsite + Keep Your Drive,"Lenovo 5PS0A14091. Number of years: 3 year(s),...",Lenovo offers a comprehensive portfolio of val...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Lenovo 5PS0A14091 5PS0A14091 3YR Onsite + Keep...
...,...,...,...,...,...,...,...,...,...,...,...
859244,QNAP,TS-1635AX-4G/48TB-IWPRO,TS-1635AX-4G/48TB-IWPRO 16 Bay NAS,Marvell ARMADA 8040 ARMv8 Cortex-A72 quad-core...,QNAP TS-1635AX-4G/48TB-IWPRO 16 Bay NAS. Insta...,The TS-1635AX is powered by a Marvell® ARMADA®...,Computers & Electronics,Data Storage,Data Storage Devices,Computers & Electronics > Data Storage > Data ...,QNAP TS-1635AX-4G/48TB-IWPRO TS-1635AX-4G/48TB...
7400,Eaton,PW104BA0UA67,Powerware ePDU Basic 0U 16A C13 x 16,Powerware ePDU Basic 0U 16A C13 x 16,Eaton Powerware ePDU Basic 0U 16A C13 x 16. Ra...,Defining a ePDU<br>\r\n-Enclosure based Power ...,Computers & Electronics,Batteries & Power Supplies,Power Distribution Units (PDUs),Computers & Electronics > Batteries & Power Su...,Eaton PW104BA0UA67 Powerware ePDU Basic 0U 16A...
895533,Lenovo,FRU04Y0249,04Y0249,Keyboard (Portuguese),Lenovo 04Y0249. Type: Keyboard. Keyboard langu...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,Lenovo FRU04Y0249 04Y0249 Keyboard (Portuguese...
1034773,Samsung,CLXR838XK,CLXR838XK,"Toner Cartridge, Black, Laser, 30000 pages",Samsung CLXR838XK. Black toner page yield: 300...,Genuine Samsung black imaging unit for CLX-8380nd,Computers & Electronics,Printers & Scanners,Printing Supplies,Computers & Electronics > Printers & Scanners ...,"Samsung CLXR838XK CLXR838XK Toner Cartridge, B..."
826946,Kaspersky Lab,KL4863XARDJ,"Endpoint Security f/Business - Select, 100-149...","Endpoint Security for Business - Select, 100-1...",Kaspersky Lab Endpoint Security f/Business - S...,<b>Kaspersky Endpoint Security for Business Se...,Computers & Electronics,Software,Antivirus Security Software,Computers & Electronics > Software > Antivirus...,Kaspersky Lab KL4863XARDJ Endpoint Security f/...

In [266]:
import re

def clean_text(t):
    if not isinstance(t, str):
        return ""

    t = re.sub(r"<[^>]+>", " ", t)          # remove HTML tags
    t = re.sub(r"\s+", " ", t)              # collapse spaces
    t = t.replace("\xa0", " ")              # remove non-breaking
    t = t.strip()

    return t

df_test["metadata_text_clean"] = df_test["metadata_text"].apply(clean_text)

In [267]:
df_test.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean
500081,Fujitsu,FSP:G-SW3Z560PRE0S,FSP:G-SW3Z560PRE0S,"SP 3y TS Sub & Upgr, 9x5, 4h Rm Rt f/ CS200c A...",Fujitsu FSP:G-SW3Z560PRE0S. Number of years: 3...,In times of growing complexity and decreasing ...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Fujitsu FSP:G-SW3Z560PRE0S FSP:G-SW3Z560PRE0S ...,Fujitsu FSP:G-SW3Z560PRE0S FSP:G-SW3Z560PRE0S ...
741063,HP,5KM83PA,13-ap0023tu,"Intel® Core™ i7-8565U (1.8 GHz), 16GB DDR4-SDR...",HP Spectre x360 13-ap0023tu. Product type: Hyb...,<b>Revolutionary battery life on a convertible...,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,HP 5KM83PA 13-ap0023tu Intel® Core™ i7-8565U (...,HP 5KM83PA 13-ap0023tu Intel® Core™ i7-8565U (...

In [268]:
df_test["meta_len"] = df_test["metadata_text_clean"].apply(lambda x: len(str(x)))
df_test["meta_len"].describe()

count     2000.000000
mean      1392.246000
std       1989.771436
min         29.000000
25%        253.500000
50%        679.500000
75%       1832.250000
max      21716.000000
Name: meta_len, dtype: float64

In [269]:
def decide_top_k(meta_len):
    if meta_len < 150:
        return 5
    elif meta_len < 500:
        return 10
    elif meta_len < 1500:
        return 15
    elif meta_len < 3000:
        return 20
    elif meta_len < 8000:
        return 30
    else:
        return 50

df_test["yake_k"] = df_test["meta_len"].apply(decide_top_k)

In [270]:
import yake

kw_extractor = yake.KeywordExtractor(n=1, dedupLim=0.9, dedupFunc="seq")

def extract_yake(text, k):
    try:
        kws = kw_extractor.extract_keywords(text)
        return [kw for kw, score in kws[:k]]
    except:
        return []

df_test["yake_keywords"] = df_test.apply(
    lambda row: extract_yake(row["metadata_text_clean"], row["yake_k"]),
    axis=1
)

In [271]:
def yake_list_to_text(kws):
    if isinstance(kws, list):
        return " ".join(str(k).strip() for k in kws if isinstance(k, str))
    return ""

df_test["yake_text"] = df_test["yake_keywords"].apply(yake_list_to_text)

In [272]:
df_test.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,meta_len,yake_k,yake_keywords,yake_text
500081,Fujitsu,FSP:G-SW3Z560PRE0S,FSP:G-SW3Z560PRE0S,"SP 3y TS Sub & Upgr, 9x5, 4h Rm Rt f/ CS200c A...",Fujitsu FSP:G-SW3Z560PRE0S. Number of years: 3...,In times of growing complexity and decreasing ...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Fujitsu FSP:G-SW3Z560PRE0S FSP:G-SW3Z560PRE0S ...,Fujitsu FSP:G-SW3Z560PRE0S FSP:G-SW3Z560PRE0S ...,1855,20,"[FSP, Fujitsu, Upgr, Advanced, EMEIA, support,...",FSP Fujitsu Upgr Advanced EMEIA support time S...
741063,HP,5KM83PA,13-ap0023tu,"Intel® Core™ i7-8565U (1.8 GHz), 16GB DDR4-SDR...",HP Spectre x360 13-ap0023tu. Product type: Hyb...,<b>Revolutionary battery life on a convertible...,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,HP 5KM83PA 13-ap0023tu Intel® Core™ i7-8565U (...,HP 5KM83PA 13-ap0023tu Intel® Core™ i7-8565U (...,1138,15,"[IPS, Touch, WLAN, Bluetooth, Core, Intel, UHD...",IPS Touch WLAN Bluetooth Core Intel UHD SSD Pr...

In [273]:
from sentence_transformers import SentenceTransformer

st_model = SentenceTransformer("all-MiniLM-L6-v2")

test_emb = st_model.encode(
    df_test["yake_text"].fillna("").tolist(),
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [275]:
import numpy as np

# 1️⃣ Make sure you still have TRAIN embeddings (same order as df_clean)
# If you don't, recompute exactly like before:
# st_model = SentenceTransformer("all-MiniLM-L6-v2")
# embeddings = st_model.encode(
#     df_clean["yake_text"].fillna("").tolist(),
#     batch_size=64,
#     show_progress_bar=True,
#     convert_to_numpy=True,
#     normalize_embeddings=True
# )

train_emb = embeddings          # shape (N_train, 384)

# 2️⃣ Recompute C-level centroids in *embedding* space, NOT UMAP space
valid_cids = sorted(df_clean["C_id"].unique())
C_centroids = []
C_labels = []

for cid in valid_cids:
    idx = (df_clean["C_id"] == cid).to_numpy()
    C_centroids.append(train_emb[idx].mean(axis=0))   # mean in 384-d space
    C_labels.append(cid)

C_centroids = np.vstack(C_centroids)   # shape (K, 384)
C_labels = np.array(C_labels)

# 3️⃣ Nearest-centroid assignment for TEST (also 384-d, already normalized)
# test_emb you already computed from df_test["yake_text"]
similarity = np.dot(test_emb, C_centroids.T)   # (N_test, K)

test_pred_C_id_index = np.argmax(similarity, axis=1)
index_to_cid = {i: cid for i, cid in enumerate(C_labels)}

df_test["pred_C_id"] = [index_to_cid[i] for i in test_pred_C_id_index]

df_test[["pred_C_id"]].head()

         pred_C_id
500081          15
741063          78
1091454         60
522928          64
479478          55

In [276]:
df_test["pred_B_id"]   = df_test["pred_C_id"].map(C_to_B)
df_test["pred_A_id"]   = df_test["pred_B_id"].map(B_to_A)
df_test["pred_C_name"] = df_test["pred_C_id"].map(C_name_map)
df_test["pred_B_name"] = df_test["pred_B_id"].map(B_name_map)
df_test["pred_A_name"] = df_test["pred_A_id"].map(A_name_map)

In [277]:
df_test

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,...,meta_len,yake_k,yake_keywords,yake_text,pred_C_id,pred_B_id,pred_A_id,pred_C_name,pred_B_name,pred_A_name
500081,Fujitsu,FSP:G-SW3Z560PRE0S,FSP:G-SW3Z560PRE0S,"SP 3y TS Sub & Upgr, 9x5, 4h Rm Rt f/ CS200c A...",Fujitsu FSP:G-SW3Z560PRE0S. Number of years: 3...,In times of growing complexity and decreasing ...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,...,1855,20,"[FSP, Fujitsu, Upgr, Advanced, EMEIA, support,...",FSP Fujitsu Upgr Advanced EMEIA support time S...,15,22,38,Computer Server Support,Server Technical Support,Server Hardware Support
741063,HP,5KM83PA,13-ap0023tu,"Intel® Core™ i7-8565U (1.8 GHz), 16GB DDR4-SDR...",HP Spectre x360 13-ap0023tu. Product type: Hyb...,<b>Revolutionary battery life on a convertible...,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,...,1138,15,"[IPS, Touch, WLAN, Bluetooth, Core, Intel, UHD...",IPS Touch WLAN Bluetooth Core Intel UHD SSD Pr...,78,6,35,Computer Peripherals,Computer and Mobile,Electronics Equipment
1091454,HP,4NG33EA,880-156nf,None,HP OMEN 880-156nf. Processor frequency: 3.2 GH...,None,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,...,560,15,"[OMEN, Processor, Internal, model, memory, Int...",OMEN Processor Internal model memory Intel Cor...,60,12,0,Laptop Computer Hardware,Mobile Computing Hardware,Mobile Computing Hardware
522928,C2G,83061,1m Cat5e Non-Booted Unshielded (UTP) Network P...,Cat5E Assembled UTP Patch Cable Green 1m,C2G 1m Cat5e Non-Booted Unshielded (UTP) Netwo...,Perfect for your home office or a large instal...,Computers & Electronics,Computer Cables,Networking Cables,Computers & Electronics > Computer Cables > Ne...,...,692,15,"[UTP, Unshielded, Patch, Green, Cable, Cables,...",UTP Unshielded Patch Green Cable Cables Assemb...,64,4,34,Networking Cabling Products,Computer Network Equipment,Network Infrastructure
479478,Lenovo,5PS0A14091,5PS0A14091,3YR Onsite + Keep Your Drive,"Lenovo 5PS0A14091. Number of years: 3 year(s),...",Lenovo offers a comprehensive portfolio of val...,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,...,1900,20,"[Lenovo, Business, Service, Day, repair, Produ...",Lenovo Business Service Day repair Product Ons...,55,18,1,Computer Hardware Services,Computer Equipment Services,Computer and Technology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859244,QNAP,TS-1635AX-4G/48TB-IWPRO,TS-1635AX-4G/48TB-IWPRO 16 Bay NAS,Marvell ARMADA 8040 ARMv8 Cortex-A72 quad-core...,QNAP TS-1635AX-4G/48TB-IWPRO 16 Bay NAS. Insta...,The TS-1635AX is powered by a Marvell® ARMADA®...,Computers & Electronics,Data Storage,Data Storage Devices,Computers & Electronics > Data Storage > Data ...,...,6006,30,"[NAS, storage, QNAP, data, expansion, Supporte...",NAS storage QNAP data expansion Supported driv...,20,14,3,Storage Network Devices,Storage Devices and,Storage and Organization
7400,Eaton,PW104BA0UA67,Powerware ePDU Basic 0U 16A C13 x 16,Powerware ePDU Basic 0U 16A C13 x 16,Eaton Powerware ePDU Basic 0U 16A C13 x 16. Ra...,Defining a ePDU<br>\r\n-Enclosure based Power ...,Computers & Electronics,Batteries & Power Supplies,Power Distribution Units (PDUs),Computers & Electronics > Batteries & Power Su...,...,1332,15,"[Powerware, Eaton, Basic, ePDU, Power, IEC, da...",Powerware Eaton Basic ePDU Power IEC data Rack...,31,21,41,Data Center Cabinets,Server Racks and,Computer Server Systems
895533,Lenovo,FRU04Y0249,04Y0249,Keyboard (Portuguese),Lenovo 04Y0249. Type: Keyboard. Keyboard langu...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,...,186,10,"[Lenovo, Portuguese, Keyboard, compatibility, ...",Lenovo Portuguese Keyboard compatibility Type ...,62,15,33,Computer Keyboards,Input and Output,Data Exchange Standards
1034773,Samsung,CLXR838XK,CLXR838XK,"Toner Cartridge, Black, Laser, 30000 pages",Samsung CLXR838XK. Black toner page yield: 300...,Genuine Samsung black imaging unit for CLX-8380nd,Computers & Electronics,Printers & Scanners,Printing Supplies,Computers & Electronics > Printers & Scanners ...,...,228,10,"[Laser, Cartridge, Black, Samsung, Toner, Prin...",Laser Cartridge Black Samsung Toner Printing Q...,9,41,19,Office Supplies,Stationery and Office,Office Supplies
826946,Kaspersky Lab,KL4863XARDJ,"Endpoint Security f/Business - Select, 100-149...","Endpoint Security for Business - Select, 100-1...",Kaspersky Lab Endpoint Security f/Business - S...,<b>Kaspersky Endpoint Security for Business Se...,Computers & Electronics,Software,Antivirus Security Software,Computers & Electronics > Software > Antivirus...,...,14089,50,"[Security, Kaspersky, Business, Endpoint, Sele...",Security Kaspersky Business Endpoint Select co...,10,36,13,Antivirus Software,Computer Security Solutions,Security Software Solutions

In [278]:
# Gold labels from test
df_test["gold_A"]    = df_test["A"].fillna("").astype(str)
df_test["gold_B"]    = df_test["B"].fillna("").astype(str)
df_test["gold_C"]    = df_test["C"].fillna("").astype(str)
df_test["gold_path"] = df_test["path_3"].fillna("").astype(str)

# Predicted labels from your trained taxonomy
df_test["pred_A"] = df_test["pred_A_name"].fillna("").astype(str)
df_test["pred_B"] = df_test["pred_B_name"].fillna("").astype(str)
df_test["pred_C"] = df_test["pred_C_name"].fillna("").astype(str)

# Build predicted full path string (A > B > C)
df_test["pred_path"] = (
    df_test["pred_A"] + " > " +
    df_test["pred_B"] + " > " +
    df_test["pred_C"]
).str.replace(r"\s+>\s+$", "", regex=True)  # just in case of trailing " >"

In [279]:
df_test[["gold_A","gold_B","gold_C","gold_path",
         "pred_A","pred_B","pred_C","pred_path"]].head(10)

,gold_A,gold_B,gold_C,gold_path,pred_A,pred_B,pred_C,pred_path
500081,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Server Hardware Support,Server Technical Support,Computer Server Support,Server Hardware Support > Server Technical Sup...
741063,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,Electronics Equipment,Computer and Mobile,Computer Peripherals,Electronics Equipment > Computer and Mobile > ...
1091454,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Mobile Computing Hardware,Mobile Computing Hardware,Laptop Computer Hardware,Mobile Computing Hardware > Mobile Computing H...
522928,Computers & Electronics,Computer Cables,Networking Cables,Computers & Electronics > Computer Cables > Ne...,Network Infrastructure,Computer Network Equipment,Networking Cabling Products,Network Infrastructure > Computer Network Equi...
479478,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,Computers & Electronics > Warranty & Support >...,Computer and Technology,Computer Equipment Services,Computer Hardware Services,Computer and Technology > Computer Equipment S...
449642,Computers & Electronics,Data Storage,Data Storage Devices,Computers & Electronics > Data Storage > Data ...,Storage and Organization,Storage Devices and,External Hard Drives,Storage and Organization > Storage Devices and...
1024163,Computers & Electronics,Consumer Audio & Video Equipment,Audio Equipment Parts & Accessories,Computers & Electronics > Consumer Audio & Vid...,Ear Monitoring Systems,In Ear Monitors,Personal In Ear,Ear Monitoring Systems > In Ear Monitors > Per...
31904,Computers & Electronics,Printers & Scanners,Print & Scan Accessories,Computers & Electronics > Printers & Scanners ...,Office Supplies,Stationery and Office,Office Supplies,Office Supplies > Stationery and Office > Offi...
360523,Computers & Electronics,Telecom & Navigation,Mobile Phone Cases,Computers & Electronics > Telecom & Navigation...,Accessories for Phones,Phone Case Accessories,Tablet Computer Accessories,Accessories for Phones > Phone Case Accessorie...
675402,Computers & Electronics,Computers,Notebooks,Computers & Electronics > Computers > Notebooks,Computer Hardware Products,Electronics Computer,Electronics Computer Devices,Computer Hardware Products > Electronics Compu...

In [280]:
from sentence_transformers import SentenceTransformer
import numpy as np

st_eval = SentenceTransformer("all-MiniLM-L6-v2")

def mean_cosine_sim(refs, cands, model):
    refs  = [r if isinstance(r, str) else "" for r in refs]
    cands = [c if isinstance(c, str) else "" for c in cands]

    emb_ref  = model.encode(refs,  normalize_embeddings=True, convert_to_numpy=True)
    emb_cand = model.encode(cands, normalize_embeddings=True, convert_to_numpy=True)

    cos = np.sum(emb_ref * emb_cand, axis=1)   # dot product = cosine (L2-normalized)
    return float(cos.mean())

A_cos   = mean_cosine_sim(df_test["gold_A"],   df_test["pred_A"],   st_eval)
B_cos   = mean_cosine_sim(df_test["gold_B"],   df_test["pred_B"],   st_eval)
C_cos   = mean_cosine_sim(df_test["gold_C"],   df_test["pred_C"],   st_eval)
path_cos= mean_cosine_sim(df_test["gold_path"],df_test["pred_path"],st_eval)

print("TEST A-level cosine:",   A_cos)
print("TEST B-level cosine:",   B_cos)
print("TEST C-level cosine:",   C_cos)
print("TEST full-path cosine:", path_cos)

TEST A-level cosine: 0.47374793887138367
TEST B-level cosine: 0.47490885853767395
TEST C-level cosine: 0.46893489360809326
TEST full-path cosine: 0.5668718814849854

In [281]:
print("TEST A-level BERTScore:")
print(compute_bertscore(df_test["gold_A"].tolist(),
                        df_test["pred_A"].tolist()))

print("\nTEST B-level BERTScore:")
print(compute_bertscore(df_test["gold_B"].tolist(),
                        df_test["pred_B"].tolist()))

print("\nTEST C-level BERTScore:")
print(compute_bertscore(df_test["gold_C"].tolist(),
                        df_test["pred_C"].tolist()))

print("\nTEST Full-path BERTScore:")
print(compute_bertscore(df_test["gold_path"].tolist(),
                        df_test["pred_path"].tolist()))

TEST A-level BERTScore:
(0.5846969485282898, 0.5558198690414429, 0.5690906047821045)

TEST B-level BERTScore:
(0.5508848428726196, 0.6262550950050354, 0.5830051302909851)

TEST C-level BERTScore:
(0.5956989526748657, 0.5861158967018127, 0.5884203910827637)

TEST Full-path BERTScore:
(0.6752740740776062, 0.6738330125808716, 0.6738173365592957)

In [282]:
import pandas as pd

# Make sure these exist on df_test:
# A, B, C, path_3 (gold from Icecat)
# pred_A_name, pred_B_name, pred_C_name (from your nearest-centroid mapping)

df_test["gold_A"]   = df_test["A"].fillna("").astype(str)
df_test["gold_B"]   = df_test["B"].fillna("").astype(str)
df_test["gold_C"]   = df_test["C"].fillna("").astype(str)
df_test["gold_path"] = df_test["path_3"].fillna("").astype(str)

df_test["pred_A"]   = df_test["pred_A_name"].fillna("").astype(str)
df_test["pred_B"]   = df_test["pred_B_name"].fillna("").astype(str)
df_test["pred_C"]   = df_test["pred_C_name"].fillna("").astype(str)

df_test["pred_path"] = (
    "Computers & Electronics > "
    + df_test["pred_A"]
    + " > "
    + df_test["pred_B"]
    + " > "
    + df_test["pred_C"]
)

In [283]:
from sentence_transformers import SentenceTransformer
import numpy as np

st_eval = SentenceTransformer("all-MiniLM-L6-v2")

def mean_cosine(gold_list, pred_list):
    gold_emb = st_eval.encode(gold_list, normalize_embeddings=True)
    pred_emb = st_eval.encode(pred_list, normalize_embeddings=True)
    cos = np.sum(gold_emb * pred_emb, axis=1)
    return float(cos.mean())

gold_A   = df_test["gold_A"].tolist()
gold_B   = df_test["gold_B"].tolist()
gold_C   = df_test["gold_C"].tolist()
gold_path = df_test["gold_path"].tolist()

pred_A   = df_test["pred_A"].tolist()
pred_B   = df_test["pred_B"].tolist()
pred_C   = df_test["pred_C"].tolist()
pred_path = df_test["pred_path"].tolist()

print("TEST A-level cosine:",   mean_cosine(gold_A,   pred_A))
print("TEST B-level cosine:",   mean_cosine(gold_B,   pred_B))
print("TEST C-level cosine:",   mean_cosine(gold_C,   pred_C))
print("TEST full-path cosine:", mean_cosine(gold_path, pred_path))

TEST A-level cosine: 0.47374793887138367
TEST B-level cosine: 0.47490885853767395
TEST C-level cosine: 0.46893489360809326
TEST full-path cosine: 0.6354767680168152

In [284]:
print("TEST A-level BERTScore:")
print(compute_bertscore(gold_A, pred_A))

print("\nTEST B-level BERTScore:")
print(compute_bertscore(gold_B, pred_B))

print("\nTEST C-level BERTScore:")
print(compute_bertscore(gold_C, pred_C))

print("\nTEST Full-path BERTScore:")
print(compute_bertscore(gold_path, pred_path))

TEST A-level BERTScore:
(0.5846969485282898, 0.5558198690414429, 0.5690906047821045)

TEST B-level BERTScore:
(0.5508848428726196, 0.6262550950050354, 0.5830051302909851)

TEST C-level BERTScore:
(0.5956989526748657, 0.5861158967018127, 0.5884203910827637)

TEST Full-path BERTScore:
(0.7505324482917786, 0.8047842383384705, 0.775732159614563)