In [4]:
import os
import json
import hashlib
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from umap import UMAP
import hdbscan
from sklearn.cluster import AgglomerativeClustering
from anytree import Node, RenderTree

warnings.filterwarnings("ignore")

In [5]:
df = pd.read_json("D:/git/Taxonomy_Buidling_Textual_Corpora/data/icecat_data_train.json")

# Work only with first 5000 rows from the beginning
df = df.iloc[:5000].copy()

print("Raw sample size:", len(df))

Raw sample size: 5000

In [6]:
def split_path(path):
    if not isinstance(path, str):
        return []
    parts = [p.strip() for p in path.split(">") if p.strip()]
    return parts

df["num_levels"] = df["pathlist_names"].apply(lambda x: len(split_path(x)))

print("Counts BEFORE cleaning:")
print(df["num_levels"].value_counts().sort_index())

Counts BEFORE cleaning:
num_levels
3    2883
4    2117
Name: count, dtype: int64

In [7]:
import pandas as pd

def make_3_and_4(path):
    parts = split_path(path)

    # default
    path_3 = None
    level_4 = None

    if len(parts) >= 3:
        path_3 = " > ".join(parts[:3])   # A > B > C
    if len(parts) >= 4:
        level_4 = parts[3]               # D (4th level)

    return pd.Series({"path_3": path_3, "level_4": level_4})

df[["path_3", "level_4"]] = df["pathlist_names"].apply(make_3_and_4)

print(df[["pathlist_names", "path_3", "level_4"]].head(10))

                                            pathlist_names  \
1072689  Computers & Electronics>Computers>PCs/Workstat...
906402   Computers & Electronics>Computers>Notebook Par...
411281   Computers & Electronics>Computer Cables>Fibre ...
425903   Computers & Electronics>Computers>Handheld Mob...
1047582  Computers & Electronics>Computers>PCs/Workstat...
904910   Computers & Electronics>Computers>Notebook Par...
157385   Computers & Electronics>Software>Software Lice...
934548   Computers & Electronics>Computers>Notebook Par...
876762   Computers & Electronics>Computers>Notebook Par...
397028   Computers & Electronics>Telecom & Navigation>M...

                                                    path_3  \
1072689  Computers & Electronics > Computers > PCs/Work...
906402   Computers & Electronics > Computers > Notebook...
411281   Computers & Electronics > Computer Cables > Fi...
425903   Computers & Electronics > Computers > Handheld...
1047582  Computers & Electronics > Computers > PCs/Work...
904910   Computers & Electronics > Computers > Notebook...
157385   Computers & Electronics > Software > Software ...
934548   Computers & Electronics > Computers > Notebook...
876762   Computers & Electronics > Computers > Notebook...
397028   Computers & Electronics > Telecom & Navigation...

                      level_4
1072689                  None
906402   Notebook Spare Parts
411281                   None
425903                   None
1047582                  None
904910   Notebook Spare Parts
157385                   None
934548   Notebook Spare Parts
876762   Notebook Spare Parts
397028                   None

In [8]:
print("Rows:", len(df))
print("Unique num_levels (original):")
print(df["num_levels"].value_counts().sort_index())

print("\nCheck how many have a 4th level stored:")
print(df["level_4"].notna().sum(), "rows with level_4")

Rows: 5000
Unique num_levels (original):
num_levels
3    2883
4    2117
Name: count, dtype: int64

Check how many have a 4th level stored:
2117 rows with level_4

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 1072689 to 1121736
Data columns (total 48 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       5000 non-null   object
 1   BrandInfo.BrandLocalName                    5000 non-null   object
 2   BrandInfo.BrandLogo                         4994 non-null   object
 3   BrandInfo.BrandName                         5000 non-null   object
 4   BrandLogo                                   4994 non-null   object
 5   BrandPartCode                               5000 non-null   object
 6   BulletPoints                                4654 non-null   object
 7   Category.CategoryID                         5000 non-null   int64
 8   Category.Name.Language                      5000 non-null   object
 9   Category.Name.Value                         5000 non-null   object
 10  Description.Disclaimer                      4440 non-null   object
 11  Description.ID                              4440 non-null   float64
 12  Description.LeafletPDFURL                   4440 non-null   object
 13  Description.LongDesc                        4440 non-null   object
 14  Description.LongProductName                 4440 non-null   object
 15  Description.ManualPDFSize                   4370 non-null   float64
 16  Description.ManualPDFURL                    4440 non-null   object
 17  Description.MiddleDesc                      4440 non-null   object
 18  Description.PDFSize                         4412 non-null   float64
 19  Description.URL                             4378 non-null   object
 20  Description.Updated                         4440 non-null   object
 21  EndOfLifeDate                               5000 non-null   object
 22  GTIN                                        5000 non-null   object
 23  IcecatId                                    5000 non-null   int64
 24  ProductFamily.ProductFamilyID               5000 non-null   int64
 25  ProductName                                 5000 non-null   object
 26  ProductSeries.SeriesID                      5000 non-null   int64
 27  ReleaseDate                                 5000 non-null   object
 28  SummaryDescription.LongSummaryDescription   5000 non-null   object
 29  SummaryDescription.ShortSummaryDescription  5000 non-null   object
 30  Title                                       5000 non-null   object
 31  Description.WarrantyInfo                    2654 non-null   object
 32  Description                                 560 non-null    object
 33  ProductFamily.Language                      1106 non-null   object
 34  ProductFamily.Value                         1106 non-null   object
 35  ProductSeries.Language                      718 non-null    object
 36  ProductSeries.Value                         718 non-null    object
 37  BulletPoints.BulletPointsId                 346 non-null    float64
 38  BulletPoints.Language                       346 non-null    object
 39  BulletPoints.Updated                        346 non-null    object
 40  BulletPoints.Values                         346 non-null    object
 41  VirtualCategory                             417 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                5000 non-null   object
 44  pathlist_names                              5000 non-null   object
 45  num_levels                                  5000 non-null   int64
 46  path_3                                      5000 non-null   object
 47  level_4                                     2117 non-null   object
dtypes: float64(5), int64(5), object(38)
memory usage: 1.9+ MB

In [10]:
# Extract A, B, C from path_3
df[["A", "B", "C"]] = (
    df["path_3"]
    .str.split(">", expand=True)
    .apply(lambda col: col.str.strip())
)

In [11]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...,3,Computers & Electronics > Computers > Handheld...,None,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations

In [12]:
# Basic Stats
print("Total products:", len(df))
print("Unique A-level:", df["A"].nunique())
print("Unique B-level:", df["B"].nunique())
print("Unique C-level:", df["C"].nunique())

Total products: 5000
Unique A-level: 1
Unique B-level: 17
Unique C-level: 160

In [13]:
#Distribution of A / B / C/
print("\nProducts per A-level:")
print(df["A"].value_counts())

print("\nProducts per B-level (top 10):")
print(df["B"].value_counts().head(20))

print("\nProducts per C-level (top 10):")
print(df["C"].value_counts().head(20))

print("\nProducts per C-level (bottom 10):")
print(df["C"].value_counts().tail(10))

Products per A-level:
A
Computers & Electronics    5000
Name: count, dtype: int64

Products per B-level (top 10):
B
Computers                           2202
Printers & Scanners                  368
Computer Components                  330
Warranty & Support                   318
Software                             296
Data Storage                         284
TVs & Monitors                       251
Computer Cables                      205
Telecom & Navigation                 189
Batteries & Power Supplies           141
Data Input Devices                   111
Consumer Audio & Video Equipment     110
Projectors                            73
Photo & Video Equipment               66
Networking                            47
Office Electronics                     7
Smart Wearables                        2
Name: count, dtype: int64

Products per C-level (top 10):
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
TVs                                76
Computer Monitors                  68
Networking Cables                  67
Print & Scan Accessories           64
Power Adapters & Inverters         63
Printing Equipment                 63
All-in-One PCs/Workstations        60
Mobile Phone Cases                 55
Antivirus Security Software        53
Flat Panel Spare Parts             42
Name: count, dtype: int64

Products per C-level (bottom 10):
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

In [14]:
# C-level Imbalance Quantiles
# (This shows how skewed leaf categories are)
prod_per_C = df["C"].value_counts()

print("\nC-level product quantiles:")
print(prod_per_C.quantile([0.1, 0.25, 0.5, 0.75, 0.9]))

C-level product quantiles:
0.10     1.0
0.25     2.0
0.50     5.0
0.75    14.0
0.90    60.3
Name: count, dtype: float64

In [15]:
# Basic counts
print("Total products:", len(df))
print("Unique A levels:", df["A"].nunique())
print("Unique B levels:", df["B"].nunique())
print("Unique C levels:", df["C"].nunique())

# Compute product counts
prod_A = df["A"].value_counts()
prod_B = df["B"].value_counts()
prod_C = df["C"].value_counts()

Total products: 5000
Unique A levels: 1
Unique B levels: 17
Unique C levels: 160

In [16]:
# Identify problematic A/B/C categories
# Very large categories (top 10)
print("\n🔥 TOP 10 LARGEST C categories:")
print(prod_C.head(10))

# Very small categories (bottom 10)
print("\n❗ BOTTOM 10 SMALLEST C categories:")
print(prod_C.tail(10))

# C categories with < 10 products
weak_C = prod_C[prod_C < 10]
print("\n❗ Weak C categories (<10 products):", len(weak_C))
print(weak_C.head(20))

# B categories with < 3 C children
C_children_per_B = df.groupby("B")["C"].nunique()
weak_B = C_children_per_B[C_children_per_B < 3]

print("\n❗ Weak B categories (<3 C children):", len(weak_B))
print(weak_B.head(20))

🔥 TOP 10 LARGEST C categories:
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
Name: count, dtype: int64

❗ BOTTOM 10 SMALLEST C categories:
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

❗ Weak C categories (<10 products): 107
C
Telephony Equipment                 9
Computer Utilities                  9
Mobile Device Chargers              8
Photographic Filmmaking Supplies    8
AV Extenders                        8
Portable Speakers                   7
Home Audio Sets                     7
Projector Accessories               7
DVD/Blu-Ray Players                 6
Flat Panel Mount Accessories        6
Thin Clients                        6
Projector Mounts                    6
Stylus Pens                         6
Mobile Phones                       6
Radios                              6
Flat Panel Floor Stands             6
KVM Cables                          6
Display Privacy Filters             6
Video Cable Adapters                6
Handheld Device Accessories         5
Name: count, dtype: int64

❗ Weak B categories (<3 C children): 2
B
Data Storage       2
Smart Wearables    2
Name: C, dtype: int64

In [17]:
#Identify dominant categories (too large)
# Very large C categories (skewing the distribution)
dominant_C = prod_C[prod_C > prod_C.quantile(0.95)]

print("\n🔥 Dominant C categories (>95th percentile):", len(dominant_C))
print(dominant_C)

🔥 Dominant C categories (>95th percentile): 8
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Name: count, dtype: int64

In [18]:
B_summary = (
    df.groupby(["A", "B"])
      .agg(num_products=("C", "count"),
           num_C=("C", "nunique"))
      .reset_index()
      .sort_values("num_products", ascending=False)
)

print(" B-level imbalance summary:")
print(B_summary.head(20))

 B-level imbalance summary:
                          A                                 B  num_products  \
3   Computers & Electronics                         Computers          2202
10  Computers & Electronics               Printers & Scanners           368
2   Computers & Electronics               Computer Components           330
16  Computers & Electronics                Warranty & Support           318
13  Computers & Electronics                          Software           296
6   Computers & Electronics                      Data Storage           284
14  Computers & Electronics                    TVs & Monitors           251
1   Computers & Electronics                   Computer Cables           205
15  Computers & Electronics              Telecom & Navigation           189
0   Computers & Electronics        Batteries & Power Supplies           141
5   Computers & Electronics                Data Input Devices           111
4   Computers & Electronics  Consumer Audio & Video Equipment           110
11  Computers & Electronics                        Projectors            73
9   Computers & Electronics           Photo & Video Equipment            66
7   Computers & Electronics                        Networking            47
8   Computers & Electronics                Office Electronics             7
12  Computers & Electronics                   Smart Wearables             2

    num_C
3      18
10      5
2       3
16      4
13      6
6       2
14     17
1      23
15     13
0      12
5       3
4      26
11      7
9       3
7      13
8       3
12      2

In [19]:
def report_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C=("C", "nunique"),
              num_products=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]
        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C']}")
            print(f"    #products (total under this B): {row['num_products']}")

In [20]:
report_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 12
    #products (total under this B): 141
  B: Computer Cables
    #C-level subcategories: 23
    #products (total under this B): 205
  B: Computer Components
    #C-level subcategories: 3
    #products (total under this B): 330
  B: Computers
    #C-level subcategories: 18
    #products (total under this B): 2202
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 26
    #products (total under this B): 110
  B: Data Input Devices
    #C-level subcategories: 3
    #products (total under this B): 111
  B: Data Storage
    #C-level subcategories: 2
    #products (total under this B): 284
  B: Networking
    #C-level subcategories: 13
    #products (total under this B): 47
  B: Office Electronics
    #C-level subcategories: 3
    #products (total under this B): 7
  B: Photo & Video Equipment
    #C-level subcategories: 3
    #products (total under this B): 66
  B: Printers & Scanners
    #C-level subcategories: 5
    #products (total under this B): 368
  B: Projectors
    #C-level subcategories: 7
    #products (total under this B): 73
  B: Smart Wearables
    #C-level subcategories: 2
    #products (total under this B): 2
  B: Software
    #C-level subcategories: 6
    #products (total under this B): 296
  B: TVs & Monitors
    #C-level subcategories: 17
    #products (total under this B): 251
  B: Telecom & Navigation
    #C-level subcategories: 13
    #products (total under this B): 189
  B: Warranty & Support
    #C-level subcategories: 4
    #products (total under this B): 318

In [21]:
def report_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products']} products)")

In [22]:
report_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Battery Chargers  (4 products)
    C: Household Batteries  (11 products)
    C: Notebook Power Tips  (2 products)
    C: Portable Device Management Carts & Cabinets  (1 products)
    C: Power Adapters & Inverters  (63 products)
    C: Power Banks  (4 products)
    C: Power Distribution Units (PDUs)  (11 products)
    C: Power Supply Units  (16 products)
    C: UPS Batteries  (3 products)
    C: UPS Battery Cabinets  (1 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
  B: Computer Cables
    C: Audio Cables  (3 products)
    C: Cable Interface/Gender Adapters  (20 products)
    C: Cable Protectors  (2 products)
    C: Coaxial Cables  (4 products)
    C: DVI Cables  (5 products)
    C: DisplayPort Cables  (3 products)
    C: Fibre Optic Cables  (29 products)
    C: FireWire Cables  (1 products)
    C: HDMI Cables  (11 products)
    C: InfiniBand Cables  (1 products)
    C: KVM Cables  (6 products)
    C: Lightning Cables  (3 products)
    C: Networking Cables  (67 products)
    C: Power Cables  (12 products)
    C: S-Video Cables  (1 products)
    C: SATA Cables  (5 products)
    C: SCART Cables  (1 products)
    C: SCSI Cables  (2 products)
    C: Serial Attached SCSI (SAS) Cables  (2 products)
    C: USB Cables  (14 products)
    C: VGA Cables  (2 products)
    C: Video Cable Adapters  (6 products)
    C: Wire Connectors  (5 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: Interface Components  (5 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Backpack PCs  (1 products)
    C: E-Book Reader Cases  (3 products)
    C: E-Book Readers  (1 products)
    C: Handheld Device Accessories  (5 products)
    C: Handheld Mobile Computer Spare Parts  (1 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PC/Workstation Barebones  (4 products)
    C: PCs/Workstations  (227 products)
    C: POS Systems  (5 products)
    C: Server Barebones  (10 products)
    C: Servers  (15 products)
    C: Stylus Pens  (6 products)
    C: Tablet Cases  (25 products)
    C: Tablet Spare Parts  (1 products)
    C: Tablets  (39 products)
    C: Thin Clients  (6 products)
  B: Consumer Audio & Video Equipment
    C: AV Extenders  (8 products)
    C: AV Receivers  (1 products)
    C: Audio Equipment Parts & Accessories  (23 products)
    C: CD Players  (2 products)
    C: Cassette Players  (1 products)
    C: Computer TV Tuners  (2 products)
    C: DVD/Blu-Ray Players  (6 products)
    C: Dictaphones  (4 products)
    C: Digital Media Players  (2 products)
    C: Docking Speakers  (1 products)
    C: Home Audio Sets  (7 products)
    C: Home Cinema Systems  (5 products)
    C: Loudspeakers  (5 products)
    C: MP3/MP4 Player Cases  (3 products)
    C: MP3/MP4 Players  (5 products)
    C: Portable DVD/Blu-Ray Players  (2 products)
    C: Portable Speakers  (7 products)
    C: Portable Stereo Systems  (1 products)
    C: Public Address (PA) Systems  (1 products)
    C: Radios  (6 products)
    C: Remote Controls  (4 products)
    C: Soundbar Speakers  (5 products)
    C: Speaker Sets  (4 products)
    C: USB Graphics Adapters  (1 products)
    C: Video Capturing Devices  (2 products)
    C: Video Switches  (2 products)
  B: Data Input Devices
    C: KVM Switches  (10 products)
    C: Keyboards  (85 products)
    C: Mice  (16 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
    C: Data Storage Mediums  (11 products)
  B: Networking
    C: ISDN Access Devices  (1 products)
    C: Network Antennas  (1 products)
    C: Network Extenders  (1 products)
    C: Network Media Converters  (3 products)
    C: Network Switch Components  (1 products)
    C: Network Switch Modules  (2 products)
    C: Network Switches  (15 products)
    C: Network Transceiver Modules  (12 products)
    C: Patch Panels  (1 products)
    C: PowerLine Network Adapters  (2 products)
    C: Remote Management Adapters  (1 products)
    C: WLAN Access Points  (3 products)
    C: Wireless Routers  (4 products)
  B: Office Electronics
    C: Calculators  (5 products)
    C: Fax Machines  (1 products)
    C: Laminator Pouches  (1 products)
  B: Photo & Video Equipment
    C: Camera Accessories  (19 products)
    C: Cameras & Camcorders  (39 products)
    C: Photographic Filmmaking Supplies  (8 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
    C: Scanning Equipment  (5 products)
  B: Projectors
    C: Data Projectors  (17 products)
    C: Projection Lenses  (3 products)
    C: Projection Screens  (25 products)
    C: Projector Accessories  (7 products)
    C: Projector Lamps  (11 products)
    C: Projector Mount Accessories  (4 products)
    C: Projector Mounts  (6 products)
  B: Smart Wearables
    C: Activity Trackers  (1 products)
    C: Sport Watch Accessories  (1 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Computer Utilities  (9 products)
    C: Multimedia Software  (5 products)
    C: Networking Software  (1 products)
    C: Operating Systems  (1 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Digital Photo Frames  (2 products)
    C: Display Privacy Filters  (6 products)
    C: Flat Panel Accessories  (2 products)
    C: Flat Panel Ceiling Mounts  (3 products)
    C: Flat Panel Desk Mounts  (4 products)
    C: Flat Panel Floor Stands  (6 products)
    C: Flat Panel Mount Accessories  (6 products)
    C: Flat Panel Spare Parts  (42 products)
    C: Flat Panel Wall Mounts  (10 products)
    C: Hospitality TVs  (2 products)
    C: Signage Displays  (14 products)
    C: Stereoscopic 3D Glasses  (2 products)
    C: TVs  (76 products)
    C: Touch Screen Monitors  (5 products)
    C: Touch Screen Overlays  (1 products)
    C: Video Splitters  (2 products)
  B: Telecom & Navigation
    C: Holders  (4 products)
    C: Mobile Device Chargers  (8 products)
    C: Mobile Device Keyboards  (10 products)
    C: Mobile Headsets  (12 products)
    C: Mobile Phone Cases  (55 products)
    C: Mobile Phone Spare Parts  (14 products)
    C: Mobile Phones  (6 products)
    C: Navigational Equipment  (3 products)
    C: Peripheral Device Cases  (1 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
    C: Telephony Equipment  (9 products)
    C: Two-Way Radios  (1 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Installation Services  (2 products)
    C: Maintenance & Support Fees  (1 products)
    C: Warranty & Support Extensions  (288 products)

In [23]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...,3,Computers & Electronics > Computers > Handheld...,None,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations

In [24]:
df[['ProductName',"BrandPartCode"]]

                                               ProductName   BrandPartCode
1072689                                       K31CD-IT049T    K31CD-IT049T
906402                                          686915-A41      686915-A41
411281   1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...           37745
425903                                             FA889AA     FA889AA#AC3
1047582                                                C30         109559U
...                                                    ...             ...
231002                                            490-BDZR        490-BDZR
978436                                      SIC1094057LCD0  SIC1094057LCD0
1101608          Elite Slice G2 with Microsoft Teams Rooms         6GV21PA
66861                                                 T300     T300.ADEUPK
1121736                             Powerware 9155-10-NT-0         1023113

[5000 rows x 2 columns]

In [25]:
def report_ABC_products(df):
    for a in df["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        dfA = df[df["A"] == a]

        for b in dfA["B"].unique():
            print(f"  B: {b}")
            dfB = dfA[dfA["B"] == b]

            for c in dfB["C"].unique():
                dfC = dfB[dfB["C"] == c]
                print(f"    C: {c}  ({len(dfC)} products)")
                
                # show top 10 product codes
                for code in dfC["ProductName"].fillna("").head(10):
                    print(f"        • {code}")

In [26]:
report_ABC_products(df)

A: Computers & Electronics
================================================================================
  B: Computers
    C: PCs/Workstations  (227 products)
        • K31CD-IT049T
        • C30
        • UN42-M031M
        • P310
        • 875-1303ng
        • 400 G6
        • M910q
        • 3 VR7RD-037US
        • 400 G4 + EliteDisplay E223
        • ProDesk 600 G3 Desktop Mini PC
    C: Notebook Parts & Accessories  (1019 products)
        • 686915-A41
        • 659501-BB1
        • 00HT024
        • 448002-001
        • Top Cover & Keyboard (Italy)
        • 25212106
        • SIC1085866LCD0
        • P000453890
        • SIC1099842LCD0
        • 25207264
    C: Handheld Mobile Computer Spare Parts  (1 products)
        • FA889AA
    C: Notebooks  (774 products)
        • V3-371-35U2
        • GE72 2QC(Apache)-209NL
        • P2510-M-54EH
        • GF72 8RE-062X
        • 15-ay045ns
        • GX531GX-ES016T
        • 460
        • 840 G5
        • R30-A-17G
        • UX310UF-FC002T
    C: Servers  (15 products)
        • x3550 M5
        • RD230
        • RX100 S7
        • R730
        • ThinkSystem ST550
        • RD450
        • RX300 S7
        • RS160
        • RX350 S8
        • TX100 S3
    C: Tablets  (39 products)
        • 510
        • 10.1
        • TF303K-1B031A
        • SM-T813N
        • 10
        • XE300TZC
        • SM-T677
        • S70G10-0N
        • Tab E8
        • SM-T713N
    C: All-in-One PCs/Workstations  (60 products)
        • C20-05
        • Z240ICGK-GC069X
        • 801
        • 27-xa0006nw
        • 24-f0098na
        • ET2311IUTH-BG006T
        • 20-c424nl
        • 24 2M-004RU
        • 23-q010in
        • 27-a254ng
    C: Tablet Cases  (25 products)
        • EFC-1H8SWEGSTA
        • SYFACILE101W
        • BC106578
        • CSGE2188BL
        • Versavu
        • APPIPC08G
        • VersaSleeve 7
        • VersaSleeve 7
        • 2043_WRKBK-IPAD2-BRN
        • TABZOO8PAN
    C: Server Barebones  (10 products)
        • SuperServer F627R3-RTB+
        • AS-2042G-TRF
        • ESPRIMO P557/E85+
        • Intel® Server System LADMP2312KXXX44
        • Superserver 5036I-IF
        • SYS-1029TP-DC0R
        • SYS-F617H6-FT+
        • Superserver 8017R-TF+
        • SuperServer 6026T-URF
        • P4308IP4LHJC
    C: Stylus Pens  (6 products)
        • AMM163US
        • 2 in 1 Styluspen
        • AMM01B
        • Stylus Pen Black
        • Accurate Stylus
        • AMM1214AU
    C: Handheld Device Accessories  (5 products)
        • BTBOUNCEOUTDOORD
        • Cradle f n30
        • Safety Camera Scrath Card
        • DLM2260/10
        • SmartTags
    C: Backpack PCs  (1 products)
        • P1000-001nl
    C: PC/Workstation Barebones  (4 products)
        • D34010WYK
        • Superserver 6015T-TV Twin
        • Revo Cube Pro
        • DS77U5
    C: POS Systems  (5 products)
        • RP2 Retail System Model 2030 (ENERGY STAR)
        • RP7 Retail System Model 7800
        • Engage One All-in-One Model 143
        • Pro x2 612 G2
        • RP 5810
    C: Thin Clients  (6 products)
        • t510 Flexible Thin Client (ENERGY STAR) Bundle
        • Z90S7
        • Z90DE7
        • 909716-54L
        • 100013839
        • 909703-21L
    C: E-Book Reader Cases  (3 products)
        • N905-BMP-2RD
        • Clara HD SleepCover
        • PRS-3LEATHCOVT
    C: Tablet Spare Parts  (1 products)
        • 747658-001
    C: E-Book Readers  (1 products)
        • Touch
  B: Computer Cables
    C: Fibre Optic Cables  (29 products)
        • 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue
        • 2m LC/SC Duplex 9/125
        • 1m LC/ST 62.5/125 Multimode Fibre Cable
        • 3m LC/LC Duplex 50/125 Multimode Fiber Patch Cable
        • 10m LC/LC Plenum-Rated 9/125 Simplex Single-Mode Fiber Patch Cable
        • 15m USA 10Gb LC/ST Duplex 50/125 Multimode Fiber Patch Cable
        • 5m Duplex MM Fiber Optic Cable LC-MTRJ
        • 5m LC/LC Simplex 9/125 Single-Mode Fiber Patch Cable - Red
        • RL2603
        • RL4109
    C: Networking Cables  (67 products)
        • 5m RJ-45 Cat6 UTP
        • 5m Cat6 UTP LSZH Network Patch Cable - Black
        • IGG310656
        • 7.6m RJ-45 M/M
        • Cat6a Ethernet Patch Cable - Shielded (STP) - 3 ft., Aqua
        • FB6625
        • Cat6 Patch Cable with Molded RJ45 Connectors - 20 ft. - Orange
        • Cat6 Ethernet Patch Cable with Snagless RJ45 Connectors - 5 ft., Red
        • 14ft Assembled Cat5E Crossover
        • Cat.5e U/UTP Patch Cable, 5.0m , Beige
    C: DisplayPort Cables  (3 products)
        • 175ft RapidRun
        • DisplayPort 1.1, 10m
        • DisplayPort™ 1.2 to HDMI™ 2.0 Active Cable 4K60Hz 3Meter M/M
    C: Power Cables  (12 products)
        • 3ft Computer 18 AWG Power Cord Extension
        • Standard Computer Power Extension Cord, 10A, 18 AWG (IEC-320-C14 to IEC-320-C13), Orange, 0.61 m
        • Heavy-Duty Power Extension Cord Lead Cable, 15A, 14AWG (IEC-320-C19 to IEC-320-C14), 0.61 m (2-ft.)
        • Heavy-Duty Power Extension Cord, 15A, 14 AWG (IEC-320-C14 to IEC-320-C13), Orange, 0.91 m
        • Universal Computer Power Cord Lead Cable, 10A, 18AWG (NEMA 5-15P to IEC-320-C13), 1.22 m (4-ft.)
        • 450-11930
        • High Quality Power Cord, C7 to 2pin Euro
        • 246959-081
        • Power Cord, Schuko - C13, 3x 0.75mm², Black, 1.8m
        • 728554-01L
    C: USB Cables  (14 products)
        • 37713
        • SB0005
        • 10.01.0204-BK
        • USB 2.0 Extension Cable
        • U330-15M
        • 2m FlexUSB 2.0 A/B Cable
        • 93621
        • MA117985
        • MA117976
        • USB-C Cable - M/M - 0.5 m - USB 2.0
    C: Cable Interface/Gender Adapters  (20 products)
        • USB 3.1 Gen 1 Right-Angle USB-C to Gigabit Ethernet Network Adapter - 10/100/1000 Mbps, Thunderbolt 3 Compatible, White
        • Mini-DisplayPort to HDMI Cable Adapter (M/M), 3.66 m (12-ft.)
        • 60051
        • IDATA USB-SER-2CT
        • HDMI 1.4 to DisplayPort 1.1 Adapter
        • USB Internal AT Motherboard Adapter 2-Port
        • 1 ft DVI-D to DVI-D & HDMI Splitter Cable - M/F
        • USB - Ethernet
        • High Density D-sub Adapter 15 pole Male to 15 pole Female
        • AB7871
    C: Video Cable Adapters  (6 products)
        • MINI DISPLAYPORT TO HDMI® CABLE
        • DisplayPort to VGA Cable, Displayport with Latches to HD-15 Adapter (M/M), 6-ft.
        • 35ft Plenum-Rated HD15 M/F UXGA Extension Cable w/ 3.5mm Audio
        • ICOC-DSP-H12-010
        • DVI Modul
        • 3m DVI-A M / HD15 M Cable
    C: Cable Protectors  (2 products)
        • 16329
        • HIFI Accessoire Vogels CABLE8W Cabletray
    C: HDMI Cables  (11 products)
        • 1.5m High Speed HDMI Cable – Ultra HD 4k x 2k HDMI Cable – HDMI to HDMI M/M
        • 3m High Speed HDMI® Cable with Ethernet - Ultra HD 4k x 2k HDMI Cable - HDMI to HDMI M/M
        • High Speed HDMI cable 1.5m
        • High Speed HDMI with Ethernet Extension Cable 4K 60Hz M / F 1.0 m
        • 93042
        • HDMI cable SWV2433W/10
        • ICOC-HDMI-4-050WH
        • 1.8m HDMI 1.4
        • 50181
        • Twistable HDMI cable 2.5m
    C: Wire Connectors  (5 products)
        • RJ45 Cat5 8x8 Modular Plug for Flat Stranded Cable 10pk
        • Low Profile Plug 2P + E 16A White IPW-SP16-WH9
        • C25PCM
        • RJ45 Cat5 8x8 Modular Plug for Flat Stranded Cable 25pk
        • 10.21.0503
    C: SCSI Cables  (2 products)
        • 470-11540
        • 6ft LVD/SE VHDCI .8mm 68M to SCSI-3 MD68M Cable with Ferrites
    C: SATA Cables  (5 products)
        • 19-in. 7Pin/7Pin
        • AK3415
        • CBL-0201L
        • 36in Go!Mod Molded Round 2-Device Ultra ATA133 EIDE Cable
        • 36 inch Round ATA 100/133 IDE Cable
    C: SCART Cables  (1 products)
        • Scart cable SWV2540T/10
    C: Lightning Cables  (3 products)
        • Uniquesync
        • A8121H92
        • 1m (3ft) Blue Apple 8-pin Lightning Connector to USB Cable for iPhone / iPod / iPad
    C: Coaxial Cables  (4 products)
        • PC/Video (UXGA) Runner Cable
        • Toslink M-M 1m SAVER
        • 10.26.2004
        • 75ft RG6
    C: VGA Cables  (2 products)
        • 125ft Plenum-Rated HD15 M/M UXGA Monitor/Projector Cable
        • 50ft Flexima HD15 M/M UXGA Monitor Cable
    C: KVM Cables  (6 products)
        • CBL0086 KVM cable 0.9 m
        • KVM Switch cable, PS/2 & AT/Serial
        • USB/PS2 Combo Cable Kit for NetController KVM Switches B040-Series and B042-Series, 6-ft.
        • F1D9017B06
        • 1.8m PS/2 KVM Cable
        • 3-in-1 Hi-Resolution PS/2 KVM Cable HD15 VGA M/F 15ft
    C: DVI Cables  (5 products)
        • DVI Connection Cable Dual Link
        • 5m DVI-D Single Link Cable - M/M
        • 5m DVI-I M/M Dual Link Digital/Analog Video Cable
        • 1.0m SonicWave™ DVI™ Digital Video Cable
        • Cable ZEN 6.6 ft (2m) DVI Digital Video Cable
    C: Serial Attached SCSI (SAS) Cables  (2 products)
        • 470-12371
        • S26361-F3210-L302
    C: Audio Cables  (3 products)
        • 80142
        • 1 ft Stereo Audio Cable - 3.5mm Male to 2x RCA Male
        • 3.5 mm - 3.5 mm 5m M/M
    C: InfiniBand Cables  (1 products)
        • MSA and TAA Compliant 10GBase-CU SFP+ to SFP+ Direct Attach Cable (Active Twinax, 10m)
    C: FireWire Cables  (1 products)
        • F007-015
    C: S-Video Cables  (1 products)
        • S-Video m/m 5.5m
  B: Software
    C: Software Licenses/Upgrades  (227 products)
        • 00D8199
        • MSS Cisco Firepower IDP Sensor Fiber
        • ScanMail Suite f/Microsoft Exchange, RNW, GOV, 14m, 501-750u
        • SLNA0079
        • PTNN0004
        • Enterprise Security f/Gateways, RNW, 751-1000u, 33m, ENG
        • SW-UPG-PC-S200-5-25
        • SafeSync for Business, RNW, 9m, 26-50u
        • Backup Exec 2010 Central Admin Server Option, v13.0, Rewards Band A UPG + Basic Maintenance, ML
        • Enterprise Security Suite, CUPG fr/ NS, EDU, 1Y, 26-50u, ML
    C: Antivirus Security Software  (53 products)
        • Norton Internet Security 2008 + Norton Antibot 1.0 (3 users)
        • Internet Security 2014, 3U, RNW, 1Y
        • Endpoint Antivirus  for Home  User 5 - 10
        • Mail Security 8340
        • Endpoint Security f/Business - Advanced, 10-14u, 3Y, Cross
        • File Security for Linux and FreeBSD User 2
        • Security f/Virtualization, Server, 5-9u, 1Y, Cross
        • Endpoint Security f/Business - Select, 15-19u, 1Y, GOV
        • Total Security
        • Security f/Mail Server, 25-49u, 3Y, Add
    C: Computer Utilities  (9 products)
        • 301N84410
        • WinZip 18 Pro, 50000-99999, EDU, ML
        • WinZip 16 Standard, 1u, Win, NL
        • WinZip 15 Standard, WIN, 2-9u
        • with Color Profiling RIP Software
        • Absolute Manage MDM, Prptl
        • WinZip Pro, MNT, 200-499u, 3y
        • 301N81140
        • Backup Exec 11d for Windows Servers Business Pack without support
    C: Multimedia Software  (5 products)
        • PaintShop Pro X6, NL/FR/IT
        • Roxio Toast 11 Titanium
        • CorelCAD, Win/Mac, 11-25u, ML
        • VideoStudio Pro Ultimate X9
        • DRAW Graphics Suite X5, H&S, 3u, Box
    C: Networking Software  (1 products)
        • VMware vCenter Server 5 Standard f/vSphere, 5H/I, 1Y
    C: Operating Systems  (1 products)
        • Microsoft Windows 7 Professional 64-Bit, SP1, DVD
  B: Telecom & Navigation
    C: Mobile Phone Spare Parts  (14 products)
        • GH59-12969A
        • Li-Ion 3.7v 1120mAh
        • AB563840CE
        • ZE551ML-6J
        • GH59-12841A
        • GH98-23340D
        • EEB-U20B
        • GH97-16565D
        • ZE600KL-6C
        • GH96-07236A
    C: Mobile Device Keyboards  (10 products)
        • 701428-331
        • I10REU-BBS
        • NP.KBD1A.00R
        • FRU04W2177
        • 920-006395
        • LC.KBD0A.007
        • EJ-CN920
        • FRU04W2175
        • 920-006268
        • 784194-091
    C: Smartphones  (34 products)
        • Sola
        • GSmart Roma RX
        • G398F
        • SM-A800
        • SM-G975F
        • SM-G950F
        • SM-J415F
        • SM-J200H
        • LMG710EM
        • Moto E4 Plus
    C: Mobile Phone Cases  (55 products)
        • Premium Flip TPU Case Apple iPhone 7, iPhone 8 Black
        • TAGE3163K
        • Sensation
        • EF-FS727L
        • PocketBook
        • 200102293
        • Saffiano Wallet Case Samsung Galaxy A8 (2018) Copper
        • TPUSA829T
        • ETUISMI8190
        • Excellent Wallet Case Samsung Galaxy A3 (2017) Jade Black
    C: Holders  (4 products)
        • GrabTab Fun with Food Collection
        • HA-E60IO
        • GrabTab Fun with Food Collection
        • BTAC-02
    C: Telephony Equipment  (9 products)
        • M3301GW/FR
        • SE8880B/12
        • D1101
        • D2152B/38
        • Sologic A801
        • S1202
        • D4502B/23
        • CPH0018A
        • CD2802W/DE
    C: Screen Protectors  (32 products)
        • TEM0002A
        • Vikuiti ADQC27
        • OSFTAG13.5L/P-SURFB
        • CANPSSD1100S
        • Vikuiti ADQC27
        • Vikuiti ADQC27
        • ET-FN910C
        • SONDSCW300S
        • Vikuiti ADQC27
        • SAMS5620LE
    C: Mobile Phones  (6 products)
        • Cookie (KP500)
        • GT-S5220
        • ROKR E8
        • KM570
        • KC910
        • CTE109BK/00
    C: Mobile Headsets  (12 products)
        • In-Ear Stereo Earbuds Green with In-line Microphone - handsfree, tangle free with flat cable design
        • Earhook Headphones SHS8100/98
        • Headphones with mic SHE5305WT/00
        • HA-SR185
        • Petit
        • HM3350
        • Headphones with mic SHL3265BL/00
        • HA-S31M-A
        • Pulse Escape
        • DR-V150iP
    C: Two-Way Radios  (1 products)
        • RC-6420 Walkie Talkie - Protalker PT-1078
    C: Mobile Device Chargers  (8 products)
        • Mini Car Charger 2xUSB 1A+2.1A
        • DLP2307/11
        • ACHTYPECK
        • ACHKIT10WMFIIPADW
        • CBRAR6100 Roller Car Charger
        • Type-C/Type-A In-Car Charger 3A
        • USB wall charger DLP2307/12
        • CARUSB10
    C: Navigational Equipment  (3 products)
        • Rider 400
        • 9UUA.001.22
        • NV-U51
    C: Peripheral Device Cases  (1 products)
        • 7"-9" In-Car DVD Player Case
  B: Printers & Scanners
    C: Printing Supplies  (215 products)
        • 106R03527
        • ML2250
        • OC301Y-FRC
        • 6015Y-FRC
        • TK18-XL-FRC
        • SV043A
        • Yellow Laser Toner - Ricoh 841507 - For Ricoh Aficio MP C 2051 / 2551
        • Fotopapier KC-18IL (18) Pak 18 vel
        • 32RAN006R01526
        • BR1100BK-INK-FRC
    C: Print & Scan Accessories  (64 products)
        • PA03753-K982
        • 40X8421
        • RK2-1992-000CN
        • RM1-2721-040CN
        • 675K78361
        • 500-Sheet Drawer for Lexmark T64x
        • RM1-1717-000CN
        • LaserJet 500-sheet Output Catch Tray
        • 724-10520
        • Epson SIDM Single Sheet Feeder 50 sheets for LQ-2090, LX-1170II, FX-1180/2190
    C: Printing Equipment  (63 products)
        • 6510DNI
        • MX511dhe
        • 4634 e
        • imageRUNNER ADVANCE 4245i
        • Epson PLQ-20 (240v)
        • C511dn
        • 7400V_DN
        • CS622de
        • T640dtn
        • 1801
    C: Printing Media  (21 products)
        • Everyday Inkjet Paper 80 g/m²-A4/210 x 297 mm/500 sht
        • Labels signalling hard-wearing A4 63,5x29,6 mm yellow strong adhesion film matt weatherpr. 675 pcs.
        • Velvet Fine Art Paper, DIN A2, 260g/m², 25 Sheets
        • 3" x 1", 5800/Roll
        • Cockle-free Heavyweight Coated Paper-610 mm x 30.5 m (24 in x 100 ft)
        • 1TYLAB10252DTP74
        • SureLab Pro Paper Glossy 285 10" 1roll
        • Computer labels continous 88.9x23.0 mm 1 row white paper matt 6000 pcs.
        • Q1408A
        • CHP235
    C: Scanning Equipment  (5 products)
        • Picture Saver PS410
        • ScanSnap S1300i Deluxe
        • ES-400
        • Scanjet 4370 Photo Scanner
        • scanjet 3530c digital flatbed scanner
  B: Batteries & Power Supplies
    C: UPS Batteries  (3 products)
        • 2U UPS Replacement 48VDC Battery Cartridge for select Tripp Lite SmartOnline UPS
        • External 240V Tower Battery Pack for use with select UPS Systems (BP240V787C-1PH)
        • APCRBC143
    C: Power Supply Units  (16 products)
        • RS-900-AAAA-A3
        • GX
        • PY.25008.002
        • TQXGE-700SAP
        • SP410-1D
        • PWR-242-AE
        • Dark Power Pro 10
        • PWS-2K04A-1R
        • PY.75008.005
        • AT-PWR05
    C: Power Adapters & Inverters  (63 products)
        • AK.065AP.13 compatible AC Adapter inc. mains cable
        • Powerpal
        • ALT28064A
        • Extra 90W/19V AC Adapter
        • 40Y7666
        • ALT28751A
        • PA3822E-1AC3
        • S26391-F478-L100
        • P000537790
        • AC Adapter, 15V DC, 5A, 75W, 3-Pin
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
        • 650VA 360W UPS
        • 9PX3000IRTN
        • Powerware 9355-8-NHS-15-32x9Ah
        • G55TUPSM100HS
        • Liebert NXC 30kVA
        • AVR Series 230V 550VA 300W Ultra-Compact Line-Interactive UPS with USB port, CEE7/7 Schuko Outlets
        • 5PX 3000VA 2U
        • Powerware 9355-8-NHS-33-64x9Ah
        • Evolution 1150 Tower
        • Powerware 9155-20-NLHS-26-4x7Ah
    C: Household Batteries  (11 products)
        • Lithium
        • 56666 101 402
        • Stamina Plus
        • -V364
        • SR44
        • 936847
        • CR123A
        • DL2016
        • Plus AAA 4 Pack
        • 56683 101 402
    C: Power Distribution Units (PDUs)  (11 products)
        • DIS Rack PDU, Safety Standard, 0U, input Schuko 230V 16A, outputs (9)Schuko
        • DIS Rack PDU, TripplePower, 0U/1U, input IEC 60309 230/400V 3x16A, outputs (6)C19
        • MPE Rack PDU, elementary, 0U, input Hardwired 230/400V 3x32A, outputs (48)C13
        • 8-Outlet French Power Distribution Unit
        • T982F3-F-SL-0
        • APS3-058
        • PDPM138H-R
        • 9PXEBM180RT
        • NSYAPU19UK7
        • Geist rPDU, basic, 0U, input IEC60309 230V 16A, outputs (20)C13 | (4)C19
    C: Power Banks  (4 products)
        • P27QC10P60-BK
        • Freepower Dual 7800
        • Emergency Micro-USB Powerpack
        • PowerBank  6000
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
        • GXT3/4 - Socket for GXT4-72VBATTE external battery cabinet
    C: Battery Chargers  (4 products)
        • PLA8031A
        • PLA8011A
        • UCC8014A
        • ACK-DC90
    C: UPS Battery Cabinets  (1 products)
        • Easy 3S
    C: Notebook Power Tips  (2 products)
        • PT-3H
        • PT-3O
    C: Portable Device Management Carts & Cabinets  (1 products)
        • 48-Device USB Charging Station Cabinet with Sync for iPad and Android Tablets, Wall-Mount and Cart Options, White
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
        • VN247H
        • E243
        • MG28UQ
        • ProLite E1908WSV-S1 19" LCD
        • 22MK400H-B
        • AMILO Display L 3220W
        • 227E6EDSD/57
        • LCD monitor, LED backlight 17S4LSB/00
        • 17S4LSB/10
        • S19B350N
    C: TVs  (76 products)
        • HG40EB690QB
        • 42LA641S
        • UE46EH5000K
        • 43PUS6503/12 Refurb Grade B
        • UE40ES7000S
        • 32W1733DG
        • KDL-32EX725
        • LCD TV - Bravia KDL-22S5500
        • KDL-32R403C
        • 37" LCD Widescreen Flat TV Pixel Plus
    C: Flat Panel Mount Accessories  (6 products)
        • AEC012018
        • Large AV Accessory Shelf
        • FSBI2B
        • BT8390-WFK2
        • Wall Display Side Cover Accessory
        • KRA225S
    C: Display Privacy Filters  (6 products)
        • Privacy Filter for 31.5" Widescreen Monitor
        • OSFNB2WPI13L-HP810
        • Privacy and Protection Cover for Laptop/Notebook Screen Size 14.0'' 16:9
        • 4Z10K85320
        • OSFNB2WPI13.3-TPX380

In [27]:
# Compute metrics
products_per_AB = df.groupby(["A", "B"]).size()
C_children_per_AB = df.groupby(["A", "B"])["C"].nunique()

# Combine
ab_summary = pd.DataFrame({
    "products_in_AB": products_per_AB,
    "n_C_children": C_children_per_AB
})

# Sort by product count descending (like your example)
ab_summary = ab_summary.sort_values("products_in_AB", ascending=False).head(10)

print(ab_summary)

                                                    products_in_AB  \
A                       B
Computers & Electronics Computers                             2202
                        Printers & Scanners                    368
                        Computer Components                    330
                        Warranty & Support                     318
                        Software                               296
                        Data Storage                           284
                        TVs & Monitors                         251
                        Computer Cables                        205
                        Telecom & Navigation                   189
                        Batteries & Power Supplies             141

                                                    n_C_children
A                       B
Computers & Electronics Computers                             18
                        Printers & Scanners                    5
                        Computer Components                    3
                        Warranty & Support                     4
                        Software                               6
                        Data Storage                           2
                        TVs & Monitors                        17
                        Computer Cables                       23
                        Telecom & Navigation                  13
                        Batteries & Power Supplies            12

In [28]:
prod_per_C = df["C"].value_counts()
prod_per_C

C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
                                 ...
USB Graphics Adapters               1
Two-Way Radios                      1
UPS Battery Cabinets                1
AV Receivers                        1
S-Video Cables                      1
Name: count, Length: 160, dtype: int64

In [29]:
#Keep only C categories with > 20 products
valid_C = prod_per_C[prod_per_C >= 20].index
df = df[df["C"].isin(valid_C)].copy()

In [30]:
print("Remaining rows:", len(df))
print("Unique C after filtering:", df["C"].nunique())
print("Min products per C (should be >20):", df["C"].value_counts().min())

Remaining rows: 4382
Unique C after filtering: 32
Min products per C (should be >20): 20

In [31]:
#final A-B summary
def print_final_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C_under_B=("C", "nunique"),
              num_products_under_B=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]

        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C_under_B']}")
            print(f"    #products (under this B): {row['num_products_under_B']}")

In [32]:
print_final_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 2
    #products (under this B): 87
  B: Computer Cables
    #C-level subcategories: 3
    #products (under this B): 116
  B: Computer Components
    #C-level subcategories: 2
    #products (under this B): 325
  B: Computers
    #C-level subcategories: 6
    #products (under this B): 2144
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 23
  B: Data Input Devices
    #C-level subcategories: 1
    #products (under this B): 85
  B: Data Storage
    #C-level subcategories: 1
    #products (under this B): 273
  B: Photo & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 39
  B: Printers & Scanners
    #C-level subcategories: 4
    #products (under this B): 363
  B: Projectors
    #C-level subcategories: 1
    #products (under this B): 25
  B: Software
    #C-level subcategories: 2
    #products (under this B): 280
  B: TVs & Monitors
    #C-level subcategories: 3
    #products (under this B): 186
  B: Telecom & Navigation
    #C-level subcategories: 3
    #products (under this B): 121
  B: Warranty & Support
    #C-level subcategories: 2
    #products (under this B): 315

In [33]:
def print_final_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products_under_C")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products_under_C']} products)")
                
print_final_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Power Adapters & Inverters  (63 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
  B: Computer Cables
    C: Cable Interface/Gender Adapters  (20 products)
    C: Fibre Optic Cables  (29 products)
    C: Networking Cables  (67 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PCs/Workstations  (227 products)
    C: Tablet Cases  (25 products)
    C: Tablets  (39 products)
  B: Consumer Audio & Video Equipment
    C: Audio Equipment Parts & Accessories  (23 products)
  B: Data Input Devices
    C: Keyboards  (85 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
  B: Photo & Video Equipment
    C: Cameras & Camcorders  (39 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
  B: Projectors
    C: Projection Screens  (25 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Flat Panel Spare Parts  (42 products)
    C: TVs  (76 products)
  B: Telecom & Navigation
    C: Mobile Phone Cases  (55 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Warranty & Support Extensions  (288 products)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4382 entries, 1072689 to 1121736
Data columns (total 51 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       4382 non-null   object
 1   BrandInfo.BrandLocalName                    4382 non-null   object
 2   BrandInfo.BrandLogo                         4379 non-null   object
 3   BrandInfo.BrandName                         4382 non-null   object
 4   BrandLogo                                   4379 non-null   object
 5   BrandPartCode                               4382 non-null   object
 6   BulletPoints                                4088 non-null   object
 7   Category.CategoryID                         4382 non-null   int64
 8   Category.Name.Language                      4382 non-null   object
 9   Category.Name.Value                         4382 non-null   object
 10  Description.Disclaimer                      3884 non-null   object
 11  Description.ID                              3884 non-null   float64
 12  Description.LeafletPDFURL                   3884 non-null   object
 13  Description.LongDesc                        3884 non-null   object
 14  Description.LongProductName                 3884 non-null   object
 15  Description.ManualPDFSize                   3818 non-null   float64
 16  Description.ManualPDFURL                    3884 non-null   object
 17  Description.MiddleDesc                      3884 non-null   object
 18  Description.PDFSize                         3858 non-null   float64
 19  Description.URL                             3829 non-null   object
 20  Description.Updated                         3884 non-null   object
 21  EndOfLifeDate                               4382 non-null   object
 22  GTIN                                        4382 non-null   object
 23  IcecatId                                    4382 non-null   int64
 24  ProductFamily.ProductFamilyID               4382 non-null   int64
 25  ProductName                                 4382 non-null   object
 26  ProductSeries.SeriesID                      4382 non-null   int64
 27  ReleaseDate                                 4382 non-null   object
 28  SummaryDescription.LongSummaryDescription   4382 non-null   object
 29  SummaryDescription.ShortSummaryDescription  4382 non-null   object
 30  Title                                       4382 non-null   object
 31  Description.WarrantyInfo                    2225 non-null   object
 32  Description                                 498 non-null    object
 33  ProductFamily.Language                      1072 non-null   object
 34  ProductFamily.Value                         1072 non-null   object
 35  ProductSeries.Language                      705 non-null    object
 36  ProductSeries.Value                         705 non-null    object
 37  BulletPoints.BulletPointsId                 294 non-null    float64
 38  BulletPoints.Language                       294 non-null    object
 39  BulletPoints.Updated                        294 non-null    object
 40  BulletPoints.Values                         294 non-null    object
 41  VirtualCategory                             416 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                4382 non-null   object
 44  pathlist_names                              4382 non-null   object
 45  num_levels                                  4382 non-null   int64
 46  path_3                                      4382 non-null   object
 47  level_4                                     2042 non-null   object
 48  A                                           4382 non-null   object
 49  B                                           4382 non-null   object
 50  C                                           4382 non-null   object
dtypes: float64(5), int64(5), object(41)
memory usage: 1.7+ MB

In [35]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
904910,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,659501-BB1,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories

In [36]:
#columns to keep
cols_needed = [
    "Brand",
    "BrandPartCode",
    "ProductName",
    "Description.LongProductName",
    "SummaryDescription.LongSummaryDescription",
    "Description.LongDesc",
    "A", "B", "C",
    "path_3"   # <-- Needed for evaluation
]

In [37]:
df_clean = df[cols_needed].copy()

In [38]:
# Build raw metadata text

def build_metadata(row):
    parts = []

    if pd.notna(row["Brand"]):
        parts.append(row["Brand"])

    if pd.notna(row["BrandPartCode"]):
        parts.append(row["BrandPartCode"])
        
    if pd.notna(row["ProductName"]):
        parts.append(row["ProductName"])

    if pd.notna(row["Description.LongProductName"]):
        parts.append(row["Description.LongProductName"])

    if pd.notna(row["SummaryDescription.LongSummaryDescription"]):
        parts.append(row["SummaryDescription.LongSummaryDescription"])

    if pd.notna(row["Description.LongDesc"]):
        parts.append(row["Description.LongDesc"])

    return " ".join(parts)

df_clean["metadata_text"] = df_clean.apply(build_metadata, axis=1)

In [39]:
df_clean

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...
...,...,...,...,...,...,...,...,...,...,...,...
231002,DELL,490-BDZR,490-BDZR,Radeon Pro WX 2100 2 GB 1 DP 2 mDP (Precision),"DELL 490-BDZR. Graphics processor family: AMD,...",The new Radeon™ Pro WX 2100 graphics card is t...,Computers & Electronics,Computer Components,System Components,Computers & Electronics > Computer Components ...,DELL 490-BDZR 490-BDZR Radeon Pro WX 2100 2 GB...
978436,Toshiba,SIC1094057LCD0,SIC1094057LCD0,Satellite A660 15.6 replacement laptop LCD screen,Toshiba SIC1094057LCD0. Type: Display. Display...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,Toshiba SIC1094057LCD0 SIC1094057LCD0 Satellit...
1101608,HP,6GV21PA,Elite Slice G2 with Microsoft Teams Rooms,None,HP Elite Slice G2 with Microsoft Teams Rooms,None,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,HP 6GV21PA Elite Slice G2 with Microsoft Teams...
66861,LG,T300.ADEUPK,T300,None,"LG T300. Display diagonal: 6.1 cm (2.4""), Disp...",None,Computers & Electronics,Telecom & Navigation,Smartphones,Computers & Electronics > Telecom & Navigation...,LG T300.ADEUPK T300 LG T300. Display diagonal:...
1121736,Eaton,1023113,Powerware 9155-10-NT-0,9155-10-NT-0,Eaton Powerware 9155-10-NT-0. Output power cap...,The Eaton 9155 UPS provides premium online bac...,Computers & Electronics,Batteries & Power Supplies,Uninterruptible Power Supplies (UPSs),Computers & Electronics > Batteries & Power Su...,Eaton 1023113 Powerware 9155-10-NT-0 9155-10-N...

In [40]:
import re

def clean_text(t):
    if not isinstance(t, str):
        return ""

    t = re.sub(r"<[^>]+>", " ", t)          # remove HTML tags
    t = re.sub(r"\s+", " ", t)              # collapse spaces
    t = t.replace("\xa0", " ")              # remove non-breaking
    t = t.strip()

    return t

df_clean["metadata_text_clean"] = df_clean["metadata_text"].apply(clean_text)

In [41]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...

In [42]:
from sentence_transformers import SentenceTransformer

texts = df_clean["metadata_text_clean"].fillna("").tolist()

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(
    texts,
    batch_size=256,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/18 [00:00<?, ?it/s]

In [43]:
from umap import UMAP

umap = UMAP(
    n_neighbors=15,
    min_dist=0.0,
    n_components=25,
    metric="cosine",
    random_state=42
)

reduced = umap.fit_transform(embeddings)

In [44]:
import hdbscan

clusterer_C = hdbscan.HDBSCAN(
    min_cluster_size=20,   # consistent with your min 20 products per C
    min_samples=1,
    metric="euclidean"
)

df_clean["C_id"] = clusterer_C.fit_predict(reduced)

print("All cluster IDs:", sorted(df_clean["C_id"].unique()))

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]

In [45]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,C_id
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,45
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,75
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,33
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,10
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,75

In [46]:
cluster_counts = df_clean["C_id"].value_counts().sort_values(ascending=False)

print(cluster_counts)

C_id
 14    361
-1     212
 10    181
 69    162
 45    158
      ...
 55     20
 12     20
 7      20
 46     20
 39     20
Name: count, Length: 78, dtype: int64

In [47]:
summary = (
    df_clean.groupby("C_id")
            .size()
            .reset_index(name="num_products")
            .sort_values("num_products", ascending=False)
)

print(summary)

    C_id  num_products
15    14           361
0     -1           212
11    10           181
70    69           162
46    45           158
..   ...           ...
8      7            20
44    43            20
47    46            20
13    12            20
56    55            20

[78 rows x 2 columns]

In [48]:
def make_evidence(subdf, max_chars=2000, max_items=30):
    items = []
    for txt in subdf["metadata_text_clean"].fillna("").tolist():
        t = txt.strip()
        if not t:
            continue
        items.append("- " + t[:200])
        if len(items) >= max_items:
            break

    blob = "\n".join(items)
    return blob[:max_chars]

In [49]:
import subprocess
import hashlib

def run_llm(prompt, model="llama3.2"):
    cmd = ["ollama", "run", model]
    result = subprocess.run(
        cmd,
        input=prompt.encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    stderr_text = result.stderr.decode("utf-8", errors="ignore")
    if stderr_text.strip():
        print("⚠ Ollama stderr:\n", stderr_text)
    stdout_text = result.stdout.decode("utf-8", errors="ignore")
    return stdout_text

label_cache = {}

def cached_llm_label(prompt, max_words=4, model="llama3.2"):
    key = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
    if key in label_cache:
        return label_cache[key]

    raw = run_llm(prompt, model=model)
    label = " ".join(raw.strip().split()[:max_words])
    label_cache[key] = label
    return label

In [50]:
C_name_map = {}
unique_cids = sorted(df_clean["C_id"].unique())
print("All cluster IDs:", unique_cids)

for cid in unique_cids:
    if cid == -1:   # skip noise
        continue

    subdf = df_clean[df_clean["C_id"] == cid]
    blob = make_evidence(subdf, max_chars=1000, max_items=30)

    if not blob:
        print(f"C_id {cid} → EMPTY SKIP")
        continue

    prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You receive a group of similar products and must assign a concise C-level category name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English
- Describing the type of product, not features.

[USER]
Here is a product group:

{blob}

Please respond with ONLY the category name. No explanation, no punctuation, no quotes.
"""

    label = cached_llm_label(prompt, max_words=4)
    C_name_map[cid] = label

    print(f"C_id {cid} → {label}")

df_clean["C_name"] = df_clean["C_id"].map(C_name_map)

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠧ ⠇ ⠏ ⠋ ⠙ ⠹ ⠸ ⠼ ⠴ ⠦ ⠦ ⠇ ⠇ ⠏ ⠋ ⠙ ⠸ ⠸ ⠼ ⠴ ⠦ ⠇ ⠏ ⠏ ⠙ ⠙ ⠸ ⠼ ⠼ ⠦ ⠦ ⠧ ⠏ ⠏ ⠋ ⠹ ⠸ ⠼ ⠴ ⠦ ⠦ ⠇ ⠇ ⠋ ⠙ ⠙ ⠸ ⠼ ⠴ ⠴ ⠧ ⠧ ⠏ ⠋ ⠙ ⠙ ⠸ ⠸ ⠼ ⠴ ⠧
C_id 0 → Replacement Laptop Screens
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 1 → Replacement Laptop Display Screen
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 2 → Antivirus Software
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 3 → Laptops
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
C_id 4 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 5 → Replacement Laptop Screen
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 6 → Computer Hardware Warranty and
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 7 → Computer Hardware Repair Plans
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
C_id 8 → Laptop motherboards
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 9 → Endpoint Antivirus Software
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
C_id 10 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 11 → Graphics Cards
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 12 → Backup software Zip software
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 13 → Projection Screen
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 14 → Colour Toner Cartridges
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 15 → Extended Hardware Maintenance Services
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
C_id 16 → Onsite Printer Hardware Support
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 17 → Hardware Support
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 18 → Enterprise Security Solutions
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 19 → Headphones
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠴
C_id 20 → Extended Warranty Services
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 21 → Computer Server Maintenance and
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 22 → Network Security Appliances
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 23 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 24 → Personal accessories
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 25 → Hard Disk Drives
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
C_id 26 → Laptop Displays
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
C_id 27 → Symantec Endpoint Security Panda
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼ ⠴
C_id 28 → Cloud Security Software
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 29 → Computer Networking Cables
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠼
C_id 30 → laptop
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
C_id 31 → Desktop Computers Laptop Computers
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 32 → Ethernet Cables
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
C_id 33 → Fiber Optic Cables
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 34 → Notebooks
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 35 → Display Monitors
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 36 → CPUs
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼ ⠼
C_id 37 → Computer Hard Disk Drives
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 38 → Video Cameras Full HD
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 39 → Acer Keyboards
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠴
C_id 40 → Case PC Enclosures
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸ ⠴
C_id 41 → Data Center Cabinets
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 42 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 43 → Computer Hard Drives
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 44 → Personal Computing Accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 45 → Laptop Computers
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 46 → laptops
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 47 → Tablets
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 48 → Mobile Computer Motherboards
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 49 → Computer Motherboards
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
C_id 50 → Fujitsu Spare Parts or
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 51 → Laptop Batteries
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠴
C_id 52 → Graphics Cards
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 53 → Server Chassis Motherboards Storage
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸ ⠴
C_id 54 → USB flash drives
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 55 → Laptop Replacement Displays
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 56 → Portable Power Adapters
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 57 → Computer Input Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 58 → Computer RAM
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 59 → Computer RAM
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 60 → External Hard Drives External
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 61 → Laptop accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 62 → Lenovo Keyboards
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 63 → Computer Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 64 → Computer Hardware Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 65 → Computer Keyboards
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 66 → High Performance Server Storage
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼ ⠴
C_id 67 → Storage Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 68 → Desktop Computer
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 69 → Portable Notebooks
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 70 → Toshiba Laptop Screens
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 71 → Toshiba Laptop Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 72 → Laptop LCD Screens
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 73 → Toshiba Laptop Components
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 74 → Toshiba Laptop Keyboard
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 75 → HP Laptop Keyboards
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 76 → HP Laptop Top Cover

In [51]:
# Cluster C → B (B_id) and name B clusters
# Cluster C centroids into B clusters
from sklearn.cluster import AgglomerativeClustering
import numpy as np

# 1. Compute centroids for each C_id (exclude noise -1)
valid_cids = [c for c in df_clean["C_id"].unique() if c != -1]

C_centroids = []
C_labels = []

for cid in valid_cids:
    idx = df_clean["C_id"] == cid
    C_centroids.append(reduced[idx].mean(axis=0))   # 'reduced' = UMAP output
    C_labels.append(cid)

C_centroids = np.vstack(C_centroids)

# 2. Cluster centroids into B-level groups
agg_B = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.0
)
B_ids = agg_B.fit_predict(C_centroids)

# 3. Map C_id → B_id
C_to_B = dict(zip(C_labels, B_ids))
df_clean["B_id"] = df_clean["C_id"].map(lambda c: C_to_B.get(c, -1))

print(df_clean[["C_id", "C_name", "B_id"]].head())

         C_id               C_name  B_id
1072689    45     Laptop Computers     3
906402     75  HP Laptop Keyboards    20
411281     33   Fiber Optic Cables     8
1047582    10              Laptops    31
904910     75  HP Laptop Keyboards    20

In [52]:
# Name each B_id using LLaMA (using its C_names)
def name_B_clusters(df):
    B_name_map = {}
    for bid in sorted(df["B_id"].unique()):
        if bid == -1:
            continue
        names = df.loc[df["B_id"] == bid, "C_name"].dropna().unique().tolist()
        sample_names = ", ".join(names[:10])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of C-level subcategories and must assign a concise B-level group name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English.

[USER]
Subcategories:
{sample_names}

Respond with ONLY the B-level category name."""
        label = cached_llm_label(prompt, max_words=4)
        B_name_map[bid] = label
        print(f"B_id {bid} → {label}")
    return B_name_map

B_name_map = name_B_clusters(df_clean)
df_clean["B_name"] = df_clean["B_id"].map(B_name_map)

⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼ ⠴ ⠦
B_id 0 → Laptop Display and Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 1 → Endpoint Protection Solutions
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 2 → Computer Equipment Maintenance
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 3 → Portable Computers
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 4 → Server Support Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
B_id 5 → Computer Hardware Components
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
B_id 6 → Warranty and Support Services
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 7 → Laptop Display Components
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 8 → Computer Network Cables
⚠ Ollama stderr:
 ⠋ ⠹ ⠸
B_id 9 → Digital Storage Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 10 → Laptop peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 11 → Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 12 → Personal Computer Cases
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 13 → Home Theater Display
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
B_id 14 → Portable Power Sources
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
B_id 15 → Electronics Components
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 16 → Memory Upgrades
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
B_id 17 → Computer Hardware Components
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼ ⠴
B_id 18 → Personal Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
B_id 19 → Portable Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠼
B_id 20 → Laptop Accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
B_id 21 → Portable Computer Input Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
B_id 22 → Hard Disk Storage
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸ ⠼ ⠦
B_id 23 → Server Storage Solutions
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸ ⠼
B_id 24 → Computer Hardware Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
B_id 25 → Portable Display Replacements
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴
B_id 26 → Computer Furniture
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
B_id 27 → Display Replacement Screens
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
B_id 28 → Computer Security
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠼
B_id 29 → Portable Computer
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 30 → High Definition Video
B_id 31 → Portable Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 32 → Portable Computer Display
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 33 → Audio Headwear
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 34 → Portable Electronic Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 35 → Portable Charging Accessories
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 36 → Computer Maintenance Services
B_id 37 → Portable Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 38 → Endpoint Security Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 39 → Computer Processors
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 40 → Computer Motherboard Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 41 → Personal items
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
B_id 42 → Data Management Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 43 → Computer Hardware
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
B_id 44 → Computer Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
B_id 45 → Computer Monitors
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
B_id 46 → Computer Maintenance
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 47 → Office Supplies
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 48 → Computer Displays
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 49 → Information Security Management
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
B_id 50 → Input Accessories
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
B_id 51 → Input Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 52 → Storage Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 53 → Firewall Systems
B_id 54 → Portable Computing Devices

In [53]:
# 1. Compute centroids for each B_id
# Cluster B → A (A_id) and name A clusters
# Cluster B centroids into A groups
valid_bids = [b for b in df_clean["B_id"].unique() if b != -1]

B_centroids = []
B_labels = []

for bid in valid_bids:
    idx = df_clean["B_id"] == bid
    B_centroids.append(reduced[idx].mean(axis=0))
    B_labels.append(bid)

B_centroids = np.vstack(B_centroids)

# 2. Agglomerative clustering for A
agg_A = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.2
)
A_ids = agg_A.fit_predict(B_centroids)

# 3. Map B_id → A_id
B_to_A = dict(zip(B_labels, A_ids))
df_clean["A_id"] = df_clean["B_id"].map(lambda b: B_to_A.get(b, -1))

print(df_clean[["A_id", "B_id", "B_name"]].head())

         A_id  B_id                      B_name
1072689    31     3          Portable Computers
906402     40    20          Laptop Accessories
411281     35     8     Computer Network Cables
1047582    29    31  Portable Computing Devices
904910     40    20          Laptop Accessories

In [54]:
def name_A_clusters(df):
    A_name_map = {}
    for aid in sorted(df["A_id"].unique()):
        if aid == -1:
            continue
        names = df.loc[df["A_id"] == aid, "B_name"].dropna().unique().tolist()
        sample_names = ", ".join(names[:10])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of B-level categories and must assign a concise A-level (top level) group name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English.

[USER]
Subcategories:
{sample_names}

Respond with ONLY the A-level category name."""
        label = cached_llm_label(prompt, max_words=4)
        A_name_map[aid] = label
        print(f"A_id {aid} → {label}")
    return A_name_map

A_name_map = name_A_clusters(df_clean)
df_clean["A_name"] = df_clean["A_id"].map(A_name_map)

⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴ ⠴
A_id 0 → Computer Hardware Support
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 1 → Electronics and Entertainment
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
A_id 2 → Data Storage Solutions
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 3 → Network Security
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 4 → Computer Hardware
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 5 → Computer Accessories
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 6 → Audio/Video Equipment
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
A_id 7 → Computer Input Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 8 → Customer Service
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
A_id 9 → Information Management
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 10 → Laptop Monitor
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 11 → Display Component Parts
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
A_id 12 → Electronics Components
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
A_id 13 → Cybersecurity Solutions
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 14 → Personal Electronics
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
A_id 15 → Portable Power Chargers
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 16 → Technology Support Services
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 17 → Electronics
A_id 18 → Personal Electronics
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 19 → Computing Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 20 → Computer Peripherals
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 21 → Computer Peripherals
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 22 → Battery Chargers
A_id 23 → Computer Peripherals
A_id 24 → Personal Electronics
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 25 → Mobile Device Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 26 → Computer Peripherals
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 27 → Personal Accessories
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 28 → Display Screens
A_id 29 → Personal Electronics
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
A_id 30 → Information Technology Management
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
A_id 31 → Portable Electronic Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 32 → Electronics
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
A_id 33 → Computer Hardware Upgrades
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
A_id 34 → Network Threat Protection
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 35 → Networking Equipment
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
A_id 36 → Digital Visual Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 37 → Office Supplies
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
A_id 38 → Computer Hardware
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
A_id 39 → Office Materials
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
A_id 40 → Computer Peripherals
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 41 → Headwear Accessories
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
A_id 42 → Electronics
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 43 → Display and Electronics
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
A_id 44 → Electronic Parts
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
A_id 45 → Computing Equipment
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
A_id 46 → Cybersecurity Management
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 47 → Mobile Displays
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 48 → Input Devices

In [55]:
# Group by discovered A/B/C names and count products
grouped = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

def print_discovered_hierarchy(df_g):
    for a in df_g["A_name"].dropna().unique():
        print(f"A: {a}")
        print("=" * 80)
        tempA = df_g[df_g["A_name"] == a]

        for b in tempA["B_name"].dropna().unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B_name"] == b]

            for _, row in tempB.iterrows():
                c = row["C_name"]
                n = row["num_products"]
                print(f"    C: {c}  ({n} products)")
        print("\n")

print_discovered_hierarchy(grouped)

A: Audio/Video Equipment
================================================================================
  B: Home Theater Display
    C: Projection Screen  (25 products)


A: Battery Chargers
================================================================================
  B: Portable Power Sources
    C: Laptop Batteries  (83 products)


A: Computer Accessories
================================================================================
  B: Computer Peripherals
    C: Acer Keyboards  (20 products)


A: Computer Hardware
================================================================================
  B: Computer Hardware Components
    C: Server Chassis Motherboards Storage  (36 products)
    C: Graphics Cards  (31 products)
  B: Computer Processors
    C: CPUs  (77 products)
  B: Personal Computer Cases
    C: Case PC Enclosures  (33 products)


A: Computer Hardware Support
================================================================================
  B: Computer Maintenance
    C: Hardware Support  (24 products)
  B: Server Support Services
    C: Extended Warranty Services  (49 products)
    C: Computer Server Maintenance and  (46 products)


A: Computer Hardware Upgrades
================================================================================
  B: Memory Upgrades
    C: Computer RAM  (55 products)


A: Computer Input Devices
================================================================================
  B: Portable Computer Input Devices
    C: Toshiba Laptop Keyboard  (27 products)


A: Computer Peripherals
================================================================================
  B: Computer Hardware Components
    C: Computer Motherboards  (54 products)
    C: Personal Computing Accessories  (29 products)
    C: Mobile Computer Motherboards  (28 products)
    C: Fujitsu Spare Parts or  (22 products)
  B: Input Accessories
    C: Computer Input Devices  (30 products)
  B: Laptop Accessories
    C: HP Laptop Keyboards  (41 products)
    C: HP Laptop Top Cover  (41 products)
  B: Laptop peripherals
    C: Lenovo Keyboards  (58 products)
    C: Laptop accessories  (46 products)


A: Computing Devices
================================================================================
  B: Personal Computing Devices
    C: Notebooks  (140 products)
    C: Desktop Computers Laptop Computers  (31 products)


A: Computing Equipment
================================================================================
  B: Digital Storage Devices
    C: External Hard Drives External  (50 products)
    C: USB flash drives  (35 products)


A: Customer Service
================================================================================
  B: Warranty and Support Services
    C: Computer Hardware Warranty and  (27 products)


A: Cybersecurity Management
================================================================================
  B: Information Security Management
    C: Enterprise Security Solutions  (56 products)


A: Cybersecurity Solutions
================================================================================
  B: Computer Security
    C: Antivirus Software  (55 products)


A: Data Storage Solutions
================================================================================
  B: Hard Disk Storage
    C: Computer Hard Disk Drives  (59 products)
    C: Computer Hard Drives  (20 products)
  B: Server Storage Solutions
    C: High Performance Server Storage  (39 products)
    C: Storage Devices  (36 products)
  B: Storage Devices
    C: Hard Disk Drives  (35 products)


A: Digital Visual Displays
================================================================================
  B: Computer Displays
    C: Display Monitors  (148 products)


A: Display Component Parts
================================================================================
  B: Laptop Display Components
    C: Toshiba Laptop Displays  (63 products)
    C: Toshiba Laptop Screens  (22 products)
    C: Laptop Replacement Displays  (20 products)


A: Display Screens
================================================================================
  B: Computer Monitors
    C: Laptop Displays  (59 products)


A: Display and Electronics
================================================================================
  B: Laptop Display and Components
    C: Toshiba Laptop Components  (37 products)
    C: Laptop LCD Screens  (35 products)


A: Electronic Parts
================================================================================
  B: Electronics Components
    C: Computer Hardware Components  (37 products)
    C: Computer Displays  (21 products)


A: Electronics
================================================================================
  B: Computer Motherboard Components
    C: Laptop motherboards  (26 products)
  B: Computing Devices
    C: Portable Notebooks  (162 products)
    C: Desktop Computer  (31 products)
  B: Portable Computer
    C: laptop  (66 products)


A: Electronics Components
================================================================================
  B: Computer Hardware
    C: Graphics Cards  (33 products)


A: Electronics and Entertainment
================================================================================
  B: High Definition Video
    C: Video Cameras Full HD  (34 products)
  B: Portable Electronic Devices
    C: Tablets  (54 products)
    C: laptops  (20 products)


A: Headwear Accessories
================================================================================
  B: Audio Headwear
    C: Headphones  (23 products)


A: Information Management
================================================================================
  B: Data Management Software
    C: Backup software Zip software  (20 products)


A: Information Technology Management
================================================================================
  B: Computer Equipment Maintenance
    C: Onsite Printer Hardware Support  (73 products)
    C: Extended Hardware Maintenance Services  (41 products)


A: Input Devices
================================================================================
  B: Input Devices
    C: Computer Keyboards  (87 products)


A: Laptop Monitor
================================================================================
  B: Portable Computer Display
    C: Replacement Laptop Screen  (36 products)


A: Mobile Device Displays
================================================================================
  B: Display Replacement Screens
    C: Replacement Laptop Display Screen  (39 products)


A: Mobile Displays
================================================================================
  B: Portable Display Replacements
    C: Replacement Laptop Screens  (51 products)


A: Network Security
================================================================================
  B: Endpoint Protection Solutions
    C: Symantec Endpoint Security Panda  (54 products)
    C: Cloud Security Software  (21 products)
  B: Firewall Systems
    C: Network Security Appliances  (30 products)


A: Network Threat Protection
================================================================================
  B: Endpoint Security Software
    C: Endpoint Antivirus Software  (21 products)


A: Networking Equipment
================================================================================
  B: Computer Network Cables
    C: Computer Networking Cables  (65 products)
    C: Fiber Optic Cables  (30 products)
    C: Ethernet Cables  (21 products)


A: Office Materials
================================================================================
  B: Office Supplies
    C: Colour Toner Cartridges  (361 products)


A: Office Supplies
================================================================================
  B: Computer Furniture
    C: Data Center Cabinets  (55 products)


A: Personal Accessories
================================================================================
  B: Personal items
    C: Personal accessories  (146 products)


A: Personal Electronics
================================================================================
  B: Portable Computing Devices
    C: Laptops  (426 products)


A: Portable Electronic Devices
================================================================================
  B: Portable Computers
    C: Laptop Computers  (158 products)
    C: Laptops  (24 products)


A: Portable Power Chargers
================================================================================
  B: Portable Charging Accessories
    C: Portable Power Adapters  (62 products)


A: Technology Support Services
================================================================================
  B: Computer Maintenance Services
    C: Computer Hardware Repair Plans  (20 products)

In [56]:
from anytree import Node, RenderTree

# Take unique combinations to avoid duplicate nodes
unique_paths = (
    df_clean[["A_name", "B_name", "C_name"]]
    .dropna()
    .drop_duplicates()
)

# Root node for the discovered taxonomy
root = Node("Computers & Electronics")

# Cache for created nodes to avoid re-creating them
node_cache = {}   # keys like ("A", A_name), ("B", A_name, B_name), ("C", A_name, B_name, C_name)

for _, row in unique_paths.iterrows():
    a = row["A_name"]
    b = row["B_name"]
    c = row["C_name"]

    # A level
    a_key = ("A", a)
    if a_key not in node_cache:
        node_cache[a_key] = Node(a, parent=root)

    a_node = node_cache[a_key]

    # B level
    b_key = ("B", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)

    b_node = node_cache[b_key]

    # C level
    c_key = ("C", a, b, c)
    if c_key not in node_cache:
        node_cache[c_key] = Node(c, parent=b_node)

# Pretty-print the tree
for pre, _, node in RenderTree(root):
    print(f"{pre}{node.name}")

Computers & Electronics
├── Portable Electronic Devices
│   └── Portable Computers
│       ├── Laptop Computers
│       └── Laptops
├── Computer Peripherals
│   ├── Laptop Accessories
│   │   ├── HP Laptop Keyboards
│   │   └── HP Laptop Top Cover
│   ├── Laptop peripherals
│   │   ├── Laptop accessories
│   │   └── Lenovo Keyboards
│   ├── Input Accessories
│   │   └── Computer Input Devices
│   └── Computer Hardware Components
│       ├── Personal Computing Accessories
│       ├── Fujitsu Spare Parts or
│       ├── Mobile Computer Motherboards
│       └── Computer Motherboards
├── Networking Equipment
│   └── Computer Network Cables
│       ├── Fiber Optic Cables
│       ├── Ethernet Cables
│       └── Computer Networking Cables
├── Personal Electronics
│   └── Portable Computing Devices
│       └── Laptops
├── Data Storage Solutions
│   ├── Server Storage Solutions
│   │   ├── High Performance Server Storage
│   │   └── Storage Devices
│   ├── Storage Devices
│   │   └── Hard Disk Drives
│   └── Hard Disk Storage
│       ├── Computer Hard Drives
│       └── Computer Hard Disk Drives
├── Electronic Parts
│   └── Electronics Components
│       ├── Computer Hardware Components
│       └── Computer Displays
├── Office Materials
│   └── Office Supplies
│       └── Colour Toner Cartridges
├── Digital Visual Displays
│   └── Computer Displays
│       └── Display Monitors
├── Computing Equipment
│   └── Digital Storage Devices
│       ├── USB flash drives
│       └── External Hard Drives External
├── Information Technology Management
│   └── Computer Equipment Maintenance
│       ├── Extended Hardware Maintenance Services
│       └── Onsite Printer Hardware Support
├── Computer Hardware Support
│   ├── Server Support Services
│   │   ├── Computer Server Maintenance and
│   │   └── Extended Warranty Services
│   └── Computer Maintenance
│       └── Hardware Support
├── Electronics
│   ├── Portable Computer
│   │   └── laptop
│   ├── Computing Devices
│   │   ├── Portable Notebooks
│   │   └── Desktop Computer
│   └── Computer Motherboard Components
│       └── Laptop motherboards
├── Input Devices
│   └── Input Devices
│       └── Computer Keyboards
├── Headwear Accessories
│   └── Audio Headwear
│       └── Headphones
├── Network Security
│   ├── Firewall Systems
│   │   └── Network Security Appliances
│   └── Endpoint Protection Solutions
│       ├── Symantec Endpoint Security Panda
│       └── Cloud Security Software
├── Display Screens
│   └── Computer Monitors
│       └── Laptop Displays
├── Display and Electronics
│   └── Laptop Display and Components
│       ├── Toshiba Laptop Components
│       └── Laptop LCD Screens
├── Mobile Device Displays
│   └── Display Replacement Screens
│       └── Replacement Laptop Display Screen
├── Cybersecurity Management
│   └── Information Security Management
│       └── Enterprise Security Solutions
├── Electronics Components
│   └── Computer Hardware
│       └── Graphics Cards
├── Electronics and Entertainment
│   ├── Portable Electronic Devices
│   │   ├── Tablets
│   │   └── laptops
│   └── High Definition Video
│       └── Video Cameras Full HD
├── Computer Hardware
│   ├── Computer Hardware Components
│   │   ├── Server Chassis Motherboards Storage
│   │   └── Graphics Cards
│   ├── Computer Processors
│   │   └── CPUs
│   └── Personal Computer Cases
│       └── Case PC Enclosures
├── Mobile Displays
│   └── Portable Display Replacements
│       └── Replacement Laptop Screens
├── Computing Devices
│   └── Personal Computing Devices
│       ├── Notebooks
│       └── Desktop Computers Laptop Computers
├── Battery Chargers
│   └── Portable Power Sources
│       └── Laptop Batteries
├── Computer Hardware Upgrades
│   └── Memory Upgrades
│       └── Computer RAM
├── Display Component Parts
│   └── Laptop Display Components
│       ├── Toshiba Laptop Screens
│       ├── Laptop Replacement Displays
│       └── Toshiba Laptop Displays
├── Portable Power Chargers
│   └── Portable Charging Accessories
│       └── Portable Power Adapters
├── Personal Accessories
│   └── Personal items
│       └── Personal accessories
├── Office Supplies
│   └── Computer Furniture
│       └── Data Center Cabinets
├── Computer Accessories
│   └── Computer Peripherals
│       └── Acer Keyboards
├── Cybersecurity Solutions
│   └── Computer Security
│       └── Antivirus Software
├── Network Threat Protection
│   └── Endpoint Security Software
│       └── Endpoint Antivirus Software
├── Information Management
│   └── Data Management Software
│       └── Backup software Zip software
├── Audio/Video Equipment
│   └── Home Theater Display
│       └── Projection Screen
├── Technology Support Services
│   └── Computer Maintenance Services
│       └── Computer Hardware Repair Plans
├── Laptop Monitor
│   └── Portable Computer Display
│       └── Replacement Laptop Screen
├── Computer Input Devices
│   └── Portable Computer Input Devices
│       └── Toshiba Laptop Keyboard
└── Customer Service
    └── Warranty and Support Services
        └── Computer Hardware Warranty and

In [57]:
# Build clean A/B/C summary
abc_df = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

abc_df

,A_name,B_name,C_name,num_products
0,Audio/Video Equipment,Home Theater Display,Projection Screen,25
1,Battery Chargers,Portable Power Sources,Laptop Batteries,83
2,Computer Accessories,Computer Peripherals,Acer Keyboards,20
4,Computer Hardware,Computer Hardware Components,Server Chassis Motherboards Storage,36
3,Computer Hardware,Computer Hardware Components,Graphics Cards,31
...,...,...,...,...
68,Personal Electronics,Portable Computing Devices,Laptops,426
69,Portable Electronic Devices,Portable Computers,Laptop Computers,158
70,Portable Electronic Devices,Portable Computers,Laptops,24
71,Portable Power Chargers,Portable Charging Accessories,Portable Power Adapters,62
72,Technology Support Services,Computer Maintenance Services,Computer Hardware Repair Plans,20

In [58]:
df_clean["A_name"]
df_clean["B_name"]
df_clean["C_name"]

1072689                      Laptop Computers
906402                    HP Laptop Keyboards
411281                     Fiber Optic Cables
1047582                               Laptops
904910                    HP Laptop Keyboards
                          ...
231002                         Graphics Cards
978436                Toshiba Laptop Displays
1101608    Desktop Computers Laptop Computers
66861                                 Tablets
1121736                  Data Center Cabinets
Name: C_name, Length: 4382, dtype: object

In [59]:
# Unique A levels
A_levels = sorted(abc_df["A_name"].unique())
print("A-level categories:")
for a in A_levels:
    print(" -", a)

# Unique B levels
B_levels = sorted(abc_df["B_name"].unique())
print("\nB-level categories:")
for b in B_levels:
    print(" -", b)

# Unique C levels
C_levels = sorted(abc_df["C_name"].unique())
print("\nC-level categories:")
for c in C_levels:
    print(" -", c)

A-level categories:
 - Audio/Video Equipment
 - Battery Chargers
 - Computer Accessories
 - Computer Hardware
 - Computer Hardware Support
 - Computer Hardware Upgrades
 - Computer Input Devices
 - Computer Peripherals
 - Computing Devices
 - Computing Equipment
 - Customer Service
 - Cybersecurity Management
 - Cybersecurity Solutions
 - Data Storage Solutions
 - Digital Visual Displays
 - Display Component Parts
 - Display Screens
 - Display and Electronics
 - Electronic Parts
 - Electronics
 - Electronics Components
 - Electronics and Entertainment
 - Headwear Accessories
 - Information Management
 - Information Technology Management
 - Input Devices
 - Laptop Monitor
 - Mobile Device Displays
 - Mobile Displays
 - Network Security
 - Network Threat Protection
 - Networking Equipment
 - Office Materials
 - Office Supplies
 - Personal Accessories
 - Personal Electronics
 - Portable Electronic Devices
 - Portable Power Chargers
 - Technology Support Services

B-level categories:
 - Audio Headwear
 - Computer Displays
 - Computer Equipment Maintenance
 - Computer Furniture
 - Computer Hardware
 - Computer Hardware Components
 - Computer Maintenance
 - Computer Maintenance Services
 - Computer Monitors
 - Computer Motherboard Components
 - Computer Network Cables
 - Computer Peripherals
 - Computer Processors
 - Computer Security
 - Computing Devices
 - Data Management Software
 - Digital Storage Devices
 - Display Replacement Screens
 - Electronics Components
 - Endpoint Protection Solutions
 - Endpoint Security Software
 - Firewall Systems
 - Hard Disk Storage
 - High Definition Video
 - Home Theater Display
 - Information Security Management
 - Input Accessories
 - Input Devices
 - Laptop Accessories
 - Laptop Display Components
 - Laptop Display and Components
 - Laptop peripherals
 - Memory Upgrades
 - Office Supplies
 - Personal Computer Cases
 - Personal Computing Devices
 - Personal items
 - Portable Charging Accessories
 - Portable Computer
 - Portable Computer Display
 - Portable Computer Input Devices
 - Portable Computers
 - Portable Computing Devices
 - Portable Display Replacements
 - Portable Electronic Devices
 - Portable Power Sources
 - Server Storage Solutions
 - Server Support Services
 - Storage Devices
 - Warranty and Support Services

C-level categories:
 - Acer Keyboards
 - Antivirus Software
 - Backup software Zip software
 - CPUs
 - Case PC Enclosures
 - Cloud Security Software
 - Colour Toner Cartridges
 - Computer Displays
 - Computer Hard Disk Drives
 - Computer Hard Drives
 - Computer Hardware Components
 - Computer Hardware Repair Plans
 - Computer Hardware Warranty and
 - Computer Input Devices
 - Computer Keyboards
 - Computer Motherboards
 - Computer Networking Cables
 - Computer RAM
 - Computer Server Maintenance and
 - Data Center Cabinets
 - Desktop Computer
 - Desktop Computers Laptop Computers
 - Display Monitors
 - Endpoint Antivirus Software
 - Enterprise Security Solutions
 - Ethernet Cables
 - Extended Hardware Maintenance Services
 - Extended Warranty Services
 - External Hard Drives External
 - Fiber Optic Cables
 - Fujitsu Spare Parts or
 - Graphics Cards
 - HP Laptop Keyboards
 - HP Laptop Top Cover
 - Hard Disk Drives
 - Hardware Support
 - Headphones
 - High Performance Server Storage
 - Laptop Batteries
 - Laptop Computers
 - Laptop Displays
 - Laptop LCD Screens
 - Laptop Replacement Displays
 - Laptop accessories
 - Laptop motherboards
 - Laptops
 - Lenovo Keyboards
 - Mobile Computer Motherboards
 - Network Security Appliances
 - Notebooks
 - Onsite Printer Hardware Support
 - Personal Computing Accessories
 - Personal accessories
 - Portable Notebooks
 - Portable Power Adapters
 - Projection Screen
 - Replacement Laptop Display Screen
 - Replacement Laptop Screen
 - Replacement Laptop Screens
 - Server Chassis Motherboards Storage
 - Storage Devices
 - Symantec Endpoint Security Panda
 - Tablets
 - Toshiba Laptop Components
 - Toshiba Laptop Displays
 - Toshiba Laptop Keyboard
 - Toshiba Laptop Screens
 - USB flash drives
 - Video Cameras Full HD
 - laptop
 - laptops

In [60]:
print("A count:", abc_df["A_name"].nunique())
print("B count:", abc_df["B_name"].nunique())
print("C count:", abc_df["C_name"].nunique())

A count: 39
B count: 50
C count: 71

In [61]:
grouped = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

In [62]:
import re

def normalize_label(s):
    if not isinstance(s, str):
        return s
    s = s.strip()
    s = re.sub(r"\s+", " ", s)
    # basic title-case
    s = s.title()
    return s

df_clean["A_name_norm"] = df_clean["A_name"].apply(normalize_label)
df_clean["B_name_norm"] = df_clean["B_name"].apply(normalize_label)
df_clean["C_name_norm"] = df_clean["C_name"].apply(normalize_label)

grouped_norm = (
    df_clean
    .groupby(["A_name_norm", "B_name_norm", "C_name_norm"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name_norm", "B_name_norm", "num_products"], ascending=[True, True, False])
)

In [63]:
grouped_norm.to_csv("discovered_taxonomy_ABC_clean.csv", index=False)

In [64]:
df_clean["A_super"] = "Computers & Electronics"
from anytree import Node, RenderTree

# Select only unique combinations to avoid duplicate nodes
unique_paths = (
    df_clean[["A_super", "A_name", "B_name", "C_name"]]
    .dropna()
    .drop_duplicates()
)

# Create super-root
root = Node("Computers & Electronics")

# Cache to avoid duplicate nodes
node_cache = {}   # keys: ("A_super"), ("A_name", A_name), ("B_name", A_name, B_name), ...

for _, row in unique_paths.iterrows():
    a_super = row["A_super"]                # always Computers & Electronics
    a = row["A_name"]                       # discovered A
    b = row["B_name"]                       # discovered B
    c = row["C_name"]                       # discovered C

    # A_super level (root)
    super_key = ("A_super", a_super)
    if super_key not in node_cache:
        node_cache[super_key] = Node(a_super)
    super_node = node_cache[super_key]

    # A_name level
    a_key = ("A_name", a_super, a)
    if a_key not in node_cache:
        node_cache[a_key] = Node(a, parent=super_node)
    a_node = node_cache[a_key]

    # B_name level
    b_key = ("B_name", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)
    b_node = node_cache[b_key]

    # C_name level
    c_key = ("C_name", a, b, c)
    if c_key not in node_cache:
        node_cache[c_key] = Node(c, parent=b_node)

# Print the hierarchy
for pre, _, node in RenderTree(super_node):
    print(f"{pre}{node.name}")

Computers & Electronics
├── Portable Electronic Devices
│   └── Portable Computers
│       ├── Laptop Computers
│       └── Laptops
├── Computer Peripherals
│   ├── Laptop Accessories
│   │   ├── HP Laptop Keyboards
│   │   └── HP Laptop Top Cover
│   ├── Laptop peripherals
│   │   ├── Laptop accessories
│   │   └── Lenovo Keyboards
│   ├── Input Accessories
│   │   └── Computer Input Devices
│   └── Computer Hardware Components
│       ├── Personal Computing Accessories
│       ├── Fujitsu Spare Parts or
│       ├── Mobile Computer Motherboards
│       └── Computer Motherboards
├── Networking Equipment
│   └── Computer Network Cables
│       ├── Fiber Optic Cables
│       ├── Ethernet Cables
│       └── Computer Networking Cables
├── Personal Electronics
│   └── Portable Computing Devices
│       └── Laptops
├── Data Storage Solutions
│   ├── Server Storage Solutions
│   │   ├── High Performance Server Storage
│   │   └── Storage Devices
│   ├── Storage Devices
│   │   └── Hard Disk Drives
│   └── Hard Disk Storage
│       ├── Computer Hard Drives
│       └── Computer Hard Disk Drives
├── Electronic Parts
│   └── Electronics Components
│       ├── Computer Hardware Components
│       └── Computer Displays
├── Office Materials
│   └── Office Supplies
│       └── Colour Toner Cartridges
├── Digital Visual Displays
│   └── Computer Displays
│       └── Display Monitors
├── Computing Equipment
│   └── Digital Storage Devices
│       ├── USB flash drives
│       └── External Hard Drives External
├── Information Technology Management
│   └── Computer Equipment Maintenance
│       ├── Extended Hardware Maintenance Services
│       └── Onsite Printer Hardware Support
├── Computer Hardware Support
│   ├── Server Support Services
│   │   ├── Computer Server Maintenance and
│   │   └── Extended Warranty Services
│   └── Computer Maintenance
│       └── Hardware Support
├── Electronics
│   ├── Portable Computer
│   │   └── laptop
│   ├── Computing Devices
│   │   ├── Portable Notebooks
│   │   └── Desktop Computer
│   └── Computer Motherboard Components
│       └── Laptop motherboards
├── Input Devices
│   └── Input Devices
│       └── Computer Keyboards
├── Headwear Accessories
│   └── Audio Headwear
│       └── Headphones
├── Network Security
│   ├── Firewall Systems
│   │   └── Network Security Appliances
│   └── Endpoint Protection Solutions
│       ├── Symantec Endpoint Security Panda
│       └── Cloud Security Software
├── Display Screens
│   └── Computer Monitors
│       └── Laptop Displays
├── Display and Electronics
│   └── Laptop Display and Components
│       ├── Toshiba Laptop Components
│       └── Laptop LCD Screens
├── Mobile Device Displays
│   └── Display Replacement Screens
│       └── Replacement Laptop Display Screen
├── Cybersecurity Management
│   └── Information Security Management
│       └── Enterprise Security Solutions
├── Electronics Components
│   └── Computer Hardware
│       └── Graphics Cards
├── Electronics and Entertainment
│   ├── Portable Electronic Devices
│   │   ├── Tablets
│   │   └── laptops
│   └── High Definition Video
│       └── Video Cameras Full HD
├── Computer Hardware
│   ├── Computer Hardware Components
│   │   ├── Server Chassis Motherboards Storage
│   │   └── Graphics Cards
│   ├── Computer Processors
│   │   └── CPUs
│   └── Personal Computer Cases
│       └── Case PC Enclosures
├── Mobile Displays
│   └── Portable Display Replacements
│       └── Replacement Laptop Screens
├── Computing Devices
│   └── Personal Computing Devices
│       ├── Notebooks
│       └── Desktop Computers Laptop Computers
├── Battery Chargers
│   └── Portable Power Sources
│       └── Laptop Batteries
├── Computer Hardware Upgrades
│   └── Memory Upgrades
│       └── Computer RAM
├── Display Component Parts
│   └── Laptop Display Components
│       ├── Toshiba Laptop Screens
│       ├── Laptop Replacement Displays
│       └── Toshiba Laptop Displays
├── Portable Power Chargers
│   └── Portable Charging Accessories
│       └── Portable Power Adapters
├── Personal Accessories
│   └── Personal items
│       └── Personal accessories
├── Office Supplies
│   └── Computer Furniture
│       └── Data Center Cabinets
├── Computer Accessories
│   └── Computer Peripherals
│       └── Acer Keyboards
├── Cybersecurity Solutions
│   └── Computer Security
│       └── Antivirus Software
├── Network Threat Protection
│   └── Endpoint Security Software
│       └── Endpoint Antivirus Software
├── Information Management
│   └── Data Management Software
│       └── Backup software Zip software
├── Audio/Video Equipment
│   └── Home Theater Display
│       └── Projection Screen
├── Technology Support Services
│   └── Computer Maintenance Services
│       └── Computer Hardware Repair Plans
├── Laptop Monitor
│   └── Portable Computer Display
│       └── Replacement Laptop Screen
├── Computer Input Devices
│   └── Portable Computer Input Devices
│       └── Toshiba Laptop Keyboard
└── Customer Service
    └── Warranty and Support Services
        └── Computer Hardware Warranty and

In [65]:
# Build a clean summary A/B/C table with product counts
taxonomy_summary = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

taxonomy_summary.head(20)

,A_name,B_name,C_name,num_products
0,Audio/Video Equipment,Home Theater Display,Projection Screen,25
1,Battery Chargers,Portable Power Sources,Laptop Batteries,83
2,Computer Accessories,Computer Peripherals,Acer Keyboards,20
4,Computer Hardware,Computer Hardware Components,Server Chassis Motherboards Storage,36
3,Computer Hardware,Computer Hardware Components,Graphics Cards,31
5,Computer Hardware,Computer Processors,CPUs,77
6,Computer Hardware,Personal Computer Cases,Case PC Enclosures,33
7,Computer Hardware Support,Computer Maintenance,Hardware Support,24
9,Computer Hardware Support,Server Support Services,Extended Warranty Services,49
8,Computer Hardware Support,Server Support Services,Computer Server Maintenance and,46
10,Computer Hardware Upgrades,Memory Upgrades,Computer RAM,55
11,Computer Input Devices,Portable Computer Input Devices,Toshiba Laptop Keyboard,27
12,Computer Peripherals,Computer Hardware Components,Computer Motherboards,54
15,Computer Peripherals,Computer Hardware Components,Personal Computing Accessories,29
14,Computer Peripherals,Computer Hardware Components,Mobile Computer Motherboards,28
13,Computer Peripherals,Computer Hardware Components,Fujitsu Spare Parts or,22
16,Computer Peripherals,Input Accessories,Computer Input Devices,30
17,Computer Peripherals,Laptop Accessories,HP Laptop Keyboards,41
18,Computer Peripherals,Laptop Accessories,HP Laptop Top Cover,41
20,Computer Peripherals,Laptop peripherals,Lenovo Keyboards,58

In [66]:
import pandas as pd

# 1) Safety check (optional – just to be sure)
required_cols = ["A", "B", "C", "A_name", "B_name", "C_name"]
missing = [c for c in required_cols if c not in df_clean.columns]
print("Missing columns:", missing)

Missing columns: []

In [67]:
# 2) Build GOLDEN path: from original Icecat A, B, C
df_clean["gold_path"] = (
    df_clean["A"].fillna("").str.strip() + " > " +
    df_clean["B"].fillna("").str.strip() + " > " +
    df_clean["C"].fillna("").str.strip()
)

# 3) Build PREDICTED path: from discovered A_name, B_name, C_name
df_clean["predicted_path"] = (
    df_clean["A_name"].fillna("").str.strip() + " > " +
    df_clean["B_name"].fillna("").str.strip() + " > " +
    df_clean["C_name"].fillna("").str.strip()
)

# 4) (Optional but useful later) normalized lowercase versions
def normalize_path_col(s):
    return (
        s.fillna("")
         .str.strip()
         .str.lower()
         .str.replace(r"\s+", " ", regex=True)
    )

df_clean["gold_path_norm"] = normalize_path_col(df_clean["gold_path"])
df_clean["predicted_path_norm"] = normalize_path_col(df_clean["predicted_path"])

# 5) Quick sanity check
import pandas as pd

pd.set_option("display.max_colwidth", None)

df_clean[["BrandPartCode", "ProductName", "gold_path", "predicted_path"]].head(20)

# df_clean[["BrandPartCode","ProductName", "gold_path", "predicted_path"]].head(10)

,BrandPartCode,ProductName,gold_path,predicted_path
1072689,K31CD-IT049T,K31CD-IT049T,Computers & Electronics > Computers > PCs/Workstations,Portable Electronic Devices > Portable Computers > Laptop Computers
906402,686915-A41,686915-A41,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop Accessories > HP Laptop Keyboards
411281,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue,Computers & Electronics > Computer Cables > Fibre Optic Cables,Networking Equipment > Computer Network Cables > Fiber Optic Cables
1047582,109559U,C30,Computers & Electronics > Computers > PCs/Workstations,Personal Electronics > Portable Computing Devices > Laptops
904910,659501-BB1,659501-BB1,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop Accessories > HP Laptop Keyboards
157385,00D8199,00D8199,Computers & Electronics > Software > Software Licenses/Upgrades,Data Storage Solutions > Server Storage Solutions > High Performance Server Storage
934548,FRU00HT024,00HT024,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop peripherals > Laptop accessories
876762,448002-001,448002-001,Computers & Electronics > Computers > Notebook Parts & Accessories,Electronic Parts > Electronics Components > Computer Hardware Components
1041385,106R03527,106R03527,Computers & Electronics > Printers & Scanners > Printing Supplies,Office Materials > Office Supplies > Colour Toner Cartridges
273638,90LMGF001T01041K,VN247H,Computers & Electronics > TVs & Monitors > Computer Monitors,Digital Visual Displays > Computer Displays > Display Monitors
288146,DT150/64GB,64GB USB flash drive (2.0) - Red & Black,Computers & Electronics > Data Storage > Data Storage Devices,Computing Equipment > Digital Storage Devices > USB flash drives
973610,900818-061,Top Cover & Keyboard (Italy),Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop Accessories > HP Laptop Top Cover
513341,H7J36A4#YZL,H7J36A4#YZL,Computers & Electronics > Warranty & Support > Warranty & Support Extensions,Information Technology Management > Computer Equipment Maintenance > Extended Hardware Maintenance Services
659426,NX.MPGEH.057,V3-371-35U2,Computers & Electronics > Computers > Notebooks,Personal Electronics > Portable Computing Devices > Laptops
1034218,V7ML2250,ML2250,Computers & Electronics > Printers & Scanners > Printing Supplies,Office Materials > Office Supplies > Colour Toner Cartridges
500253,FSP:G-SW5I060PRE0S,FSP:G-SW5I060PRE0S,Computers & Electronics > Warranty & Support > Warranty & Support Extensions,Computer Hardware Support > Server Support Services > Computer Server Maintenance and
926103,25212106,25212106,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop peripherals > Lenovo Keyboards
483648,01-SSC-2175,01-SSC-2175,Computers & Electronics > Warranty & Support > Warranty & Support Extensions,Computer Hardware Support > Computer Maintenance > Hardware Support
659246,GE72 2QC-209NL,GE72 2QC(Apache)-209NL,Computers & Electronics > Computers > Notebooks,Electronics > Portable Computer > laptop
745446,NX.VGAEY.002,P2510-M-54EH,Computers & Electronics > Computers > Notebooks,Personal Electronics > Portable Computing Devices > Laptops

In [68]:
row_id = 1072689   # or any index
print("GOLD:", df_clean.loc[row_id, "gold_path"])
print("PRED:", df_clean.loc[row_id, "predicted_path"])

GOLD: Computers & Electronics > Computers > PCs/Workstations
PRED: Portable Electronic Devices > Portable Computers > Laptop Computers

In [69]:
sample = df_clean.sample(5)[["BrandPartCode", "gold_path", "predicted_path"]]
print(sample.to_string(index=False))

 BrandPartCode                                                                         gold_path                                                                           predicted_path
      A7187320                 Computers & Electronics > Computer Components > System Components                              Computer Hardware Upgrades > Memory Upgrades > Computer RAM
SIC1200724LCD0                Computers & Electronics > Computers > Notebook Parts & Accessories Mobile Device Displays > Display Replacement Screens > Replacement Laptop Display Screen
  50.TAXV7.001                Computers & Electronics > Computers > Notebook Parts & Accessories     Computer Peripherals > Computer Hardware Components > Personal Computing Accessories
RN214/2TBWDRED                     Computers & Electronics > Data Storage > Data Storage Devices            Computing Equipment > Digital Storage Devices > External Hard Drives External
    463953-001 Computers & Electronics > Batteries & Power Supplies > Power Adapters & Inverters        Portable Power Chargers > Portable Charging Accessories > Portable Power Adapters

In [70]:
df_clean["exact_match"] = (df_clean["gold_path_norm"] == df_clean["predicted_path_norm"]).astype(int)
exact_acc = df_clean["exact_match"].mean()
print("Exact match accuracy:", exact_acc)

Exact match accuracy: 0.0

In [71]:
df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,...,A_name,A_name_norm,B_name_norm,C_name_norm,A_super,gold_path,predicted_path,gold_path_norm,predicted_path_norm,exact_match
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10","ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black","<b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.",Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Workstations,...,Portable Electronic Devices,Portable Electronic Devices,Portable Computers,Laptop Computers,Computers & Electronics,Computers & Electronics > Computers > PCs/Workstations,Portable Electronic Devices > Portable Computers > Laptop Computers,computers & electronics > computers > pcs/workstations,portable electronic devices > portable computers > laptop computers,0
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable),"HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6",,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook Parts & Accessories,...,Computer Peripherals,Computer Peripherals,Laptop Accessories,Hp Laptop Keyboards,Computers & Electronics,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop Accessories > HP Laptop Keyboards,computers & electronics > computers > notebook parts & accessories,computer peripherals > laptop accessories > hp laptop keyboards,0

In [72]:
print(df_clean.columns.tolist())

['Brand', 'BrandPartCode', 'ProductName', 'Description.LongProductName', 'SummaryDescription.LongSummaryDescription', 'Description.LongDesc', 'A', 'B', 'C', 'path_3', 'metadata_text', 'metadata_text_clean', 'C_id', 'C_name', 'B_id', 'B_name', 'A_id', 'A_name', 'A_name_norm', 'B_name_norm', 'C_name_norm', 'A_super', 'gold_path', 'predicted_path', 'gold_path_norm', 'predicted_path_norm', 'exact_match']

In [73]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

df_clean.head(2)

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,C_id,C_name,B_id,B_name,A_id,A_name,A_name_norm,B_name_norm,C_name_norm,A_super,gold_path,predicted_path,gold_path_norm,predicted_path_norm,exact_match
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10","ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black","<b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.",Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Workstations,"ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10 ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.","ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10 ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black Smart Multimedia Performance VivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. Ultra-Realistic 4K/UHD Visuals VivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory. Expansive Audio, tuned by experts A mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD. Windows 10 Home Windows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. SuperSpeed USB 3.1 transmission VivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. Ultra-fast connectivity With wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables. ASUS desktops – Most recommended Windows desktop brand Innovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability. Trust worthy quality and reliability ASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.",45,Laptop Computers,3,Portable Computers,31,Portable Electronic Devices,Portable Electronic Devices,Portable Computers,Laptop Computers,Computers & Electronics,Computers & Electronics > Computers > PCs/Workstations,Portable Electronic Devices > Portable Computers > Laptop Computers,computers & electronics > computers > pcs/workstations,portable electronic devices > portable computers > laptop computers,0
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable),"HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6",,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook Parts & Accessories,"HP 686915-A41 686915-A41 Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable) HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6","HP 686915-A41 686915-A41 Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable) HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6",75,HP Laptop Keyboards,20,Laptop Accessories,40,Computer Peripherals,Computer Peripherals,Laptop Accessories,Hp Laptop Keyboards,Computers & Electronics,Computers & Electronics > Computers > Notebook Parts & Accessories,Computer Peripherals > Laptop Accessories > HP Laptop Keyboards,computers & electronics > computers > notebook parts & accessories,computer peripherals > laptop accessories > hp laptop keyboards,0

In [74]:
[x for x in ["B_name", "C_name"] if x not in df_clean.columns]

[]

In [75]:
print([col for col in df_clean.columns if "name" in col.lower()])

['ProductName', 'Description.LongProductName', 'C_name', 'B_name', 'A_name', 'A_name_norm', 'B_name_norm', 'C_name_norm']

In [76]:
print(df_clean.columns.tolist())

['Brand', 'BrandPartCode', 'ProductName', 'Description.LongProductName', 'SummaryDescription.LongSummaryDescription', 'Description.LongDesc', 'A', 'B', 'C', 'path_3', 'metadata_text', 'metadata_text_clean', 'C_id', 'C_name', 'B_id', 'B_name', 'A_id', 'A_name', 'A_name_norm', 'B_name_norm', 'C_name_norm', 'A_super', 'gold_path', 'predicted_path', 'gold_path_norm', 'predicted_path_norm', 'exact_match']

In [77]:
import re

def clean_text(t):
    if not isinstance(t, str):
        return ""
    t = t.lower().strip()
    t = re.sub(r"<.*?>", "", t)  # remove html
    t = re.sub(r"[^a-z0-9 &/-]+", " ", t)  # keep safe chars
    t = re.sub(r"\s+", " ", t)  # collapse spaces
    return t.strip()

df_clean["gold_A_norm"] = df_clean["A"].apply(clean_text)
df_clean["gold_B_norm"] = df_clean["B"].apply(clean_text)
df_clean["gold_C_norm"] = df_clean["C"].apply(clean_text)

df_clean["pred_A_norm2"] = df_clean["A_name"].apply(clean_text)
df_clean["pred_B_norm2"] = df_clean["B_name"].apply(clean_text)
df_clean["pred_C_norm2"] = df_clean["C_name"].apply(clean_text)

df_clean["gold_path_norm2"] = df_clean["gold_path"].apply(clean_text)
df_clean["pred_path_norm2"] = df_clean["predicted_path"].apply(clean_text)

In [78]:
from sentence_transformers import SentenceTransformer
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
#Cosine similarity function
from numpy import dot
from numpy.linalg import norm

def cosine_sim(a, b):
    if not a or not b:
        return 0.0
    va = embedder.encode(a, normalize_embeddings=True)
    vb = embedder.encode(b, normalize_embeddings=True)
    return float(np.clip(dot(va, vb), -1.0, 1.0))

In [80]:
#Compute similarities for each level
df_clean["sim_A"] = df_clean.apply(lambda r: cosine_sim(r["gold_A_norm"], r["pred_A_norm2"]), axis=1)
df_clean["sim_B"] = df_clean.apply(lambda r: cosine_sim(r["gold_B_norm"], r["pred_B_norm2"]), axis=1)
df_clean["sim_C"] = df_clean.apply(lambda r: cosine_sim(r["gold_C_norm"], r["pred_C_norm2"]), axis=1)
df_clean["sim_path"] = df_clean.apply(lambda r: cosine_sim(r["gold_path_norm2"], r["pred_path_norm2"]), axis=1)

In [81]:
# summary metrics
print("=== SEMANTIC SIMILARITY RESULTS ===")
print("A-level similarity :", df_clean["sim_A"].mean())
print("B-level similarity :", df_clean["sim_B"].mean())
print("C-level similarity :", df_clean["sim_C"].mean())
print("Full path similarity:", df_clean["sim_path"].mean())

=== SEMANTIC SIMILARITY RESULTS ===
A-level similarity : 0.4673789543669717
B-level similarity : 0.46804986411275445
C-level similarity : 0.499410021474176
Full path similarity: 0.5366901835135092

In [82]:
!pip install bert-score

Requirement already satisfied: bert-score in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (0.3.13)
Requirement already satisfied: torch>=1.0.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (2.2.1)
Requirement already satisfied: pandas>=1.0.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (2.2.1)
Requirement already satisfied: transformers>=3.0.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (4.38.2)
Requirement already satisfied: numpy in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (1.26.4)
Requirement already satisfied: requests in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (2.32.5)
Requirement already satisfied: tqdm>=4.31.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (4.66.2)
Requirement already satisfied: matplotlib in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (3.10.7)
Requirement already satisfied: packaging>=20.9 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from bert-score) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from pandas>=1.0.1->bert-score) (2025.2)
Requirement already satisfied: six>=1.5 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.17.0)
Requirement already satisfied: filelock in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (3.20.0)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (4.15.0)
Requirement already satisfied: sympy in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (1.14.0)
Requirement already satisfied: networkx in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (3.5)
Requirement already satisfied: jinja2 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (3.1.6)
Requirement already satisfied: fsspec in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from torch>=1.0.0->bert-score) (2023.10.0)
Requirement already satisfied: colorama in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from tqdm>=4.31.1->bert-score) (0.4.6)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from transformers>=3.0.0->bert-score) (0.36.0)
Requirement already satisfied: pyyaml>=5.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from transformers>=3.0.0->bert-score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from transformers>=3.0.0->bert-score) (2025.11.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from transformers>=3.0.0->bert-score) (0.15.2)
Requirement already satisfied: safetensors>=0.4.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from transformers>=3.0.0->bert-score) (0.6.2)
Requirement already satisfied: MarkupSafe>=2.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from jinja2->torch>=1.0.0->bert-score) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (1.4.9)
Requirement already satisfied: pillow>=8 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (12.0.0)
Requirement already satisfied: pyparsing>=3 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from matplotlib->bert-score) (3.2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from requests->bert-score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from requests->bert-score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from requests->bert-score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from requests->bert-score) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\git\taxonomy_buidling_textual_corpora\.venv\lib\site-packages (from sympy->torch>=1.0.0->bert-score) (1.3.0)

In [85]:
import re
import pandas as pd

def norm_label(s):
    if pd.isna(s):
        return ""
    s = str(s).lower()
    # keep alphanum + basic punctuation, collapse spaces
    s = re.sub(r"[^a-z0-9\s&/+>-]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

# gold labels (from original Icecat A/B/C)
df_clean["gold_A_norm"] = df_clean["A"].apply(norm_label)
df_clean["gold_B_norm"] = df_clean["B"].apply(norm_label)
df_clean["gold_C_norm"] = df_clean["C"].apply(norm_label)

# predicted labels (just alias your *_name_norm columns)
df_clean["pred_A_norm"] = df_clean["A_name_norm"]
df_clean["pred_B_norm"] = df_clean["B_name_norm"]
df_clean["pred_C_norm"] = df_clean["C_name_norm"]

In [91]:
from bert_score import score as bertscore_score
import numpy as np
import torch

def bertscore_for_pairs(refs, cands, lang="en", model_type=None):
    """
    refs, cands: list of strings (same length)
    returns: mean (P, R, F1) as floats
    """
    # bert-score expects (cands, refs)
    P, R, F1 = bertscore_score(
        cands,
        refs,
        lang=lang,
        rescale_with_baseline=False,
        model_type="bert-base-uncased"  # can be None = default, or e.g. "microsoft/deberta-base-mnli"
    )
    return float(P.mean()), float(R.mean()), float(F1.mean())

In [92]:
# A/B/C level text (these names should exist already)
gold_A = df_clean["gold_A_norm"].fillna("").tolist()
pred_A = df_clean["pred_A_norm"].fillna("").tolist()

gold_B = df_clean["gold_B_norm"].fillna("").tolist()
pred_B = df_clean["pred_B_norm"].fillna("").tolist()

gold_C = df_clean["gold_C_norm"].fillna("").tolist()
pred_C = df_clean["pred_C_norm"].fillna("").tolist()

# FULL PATH level  👉 use *predicted_path_norm* here
gold_path = df_clean["gold_path_norm"].fillna("").tolist()
pred_path = df_clean["predicted_path_norm"].fillna("").tolist()

In [94]:
print([c for c in df_clean.columns if "path" in c.lower()])

['path_3', 'gold_path', 'predicted_path', 'gold_path_norm', 'predicted_path_norm', 'gold_path_norm2', 'pred_path_norm2', 'sim_path']

In [95]:
print("=== BERTSCORE RESULTS ===")

P_A, R_A, F1_A = bertscore_for_pairs(gold_A, pred_A)
print("A-level BERTScore  :", F1_A)

P_B, R_B, F1_B = bertscore_for_pairs(gold_B, pred_B)
print("B-level BERTScore  :", F1_B)

P_C, R_C, F1_C = bertscore_for_pairs(gold_C, pred_C)
print("C-level BERTScore  :", F1_C)

P_P, R_P, F1_P = bertscore_for_pairs(gold_path, pred_path)
print("Full-path BERTScore:", F1_P)

=== BERTSCORE RESULTS ===

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

A-level BERTScore  : 0.5429518818855286

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

B-level BERTScore  : 0.5740715265274048

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

C-level BERTScore  : 0.5821545124053955
Full-path BERTScore: 0.6870360374450684

In [96]:
print(bertscore_for_pairs(gold_A, pred_A))
print(bertscore_for_pairs(gold_B, pred_B))
print(bertscore_for_pairs(gold_C, pred_C))
print(bertscore_for_pairs(gold_path, pred_path))

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

(0.5714355111122131, 0.5190519094467163, 0.5429518818855286)

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

(0.5515875816345215, 0.6064782738685608, 0.5740715265274048)

Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.
Warning: Empty candidate sentence detected; setting raw BERTscores to 0.

(0.5918578505516052, 0.5779465436935425, 0.5821545124053955)
(0.6993327140808105, 0.6786849498748779, 0.6870360374450684)