In [19]:
import os
import json
import hashlib
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from umap import UMAP
import hdbscan
from sklearn.cluster import AgglomerativeClustering
from anytree import Node, RenderTree

warnings.filterwarnings("ignore")

In [20]:
df = pd.read_json("D:/git/Taxonomy_Buidling_Textual_Corpora/data/icecat_data_train.json")

# Work only with first 5000 rows from the beginning
df = df.iloc[:5000].copy()

print("Raw sample size:", len(df))

Raw sample size: 5000

In [21]:
def split_path(path):
    if not isinstance(path, str):
        return []
    parts = [p.strip() for p in path.split(">") if p.strip()]
    return parts

df["num_levels"] = df["pathlist_names"].apply(lambda x: len(split_path(x)))

print("Counts BEFORE cleaning:")
print(df["num_levels"].value_counts().sort_index())

Counts BEFORE cleaning:
num_levels
3    2883
4    2117
Name: count, dtype: int64

In [22]:
import pandas as pd

def make_3_and_4(path):
    parts = split_path(path)

    # default
    path_3 = None
    level_4 = None

    if len(parts) >= 3:
        path_3 = " > ".join(parts[:3])   # A > B > C
    if len(parts) >= 4:
        level_4 = parts[3]               # D (4th level)

    return pd.Series({"path_3": path_3, "level_4": level_4})

df[["path_3", "level_4"]] = df["pathlist_names"].apply(make_3_and_4)

print(df[["pathlist_names", "path_3", "level_4"]].head(10))

                                            pathlist_names  \
1072689  Computers & Electronics>Computers>PCs/Workstat...
906402   Computers & Electronics>Computers>Notebook Par...
411281   Computers & Electronics>Computer Cables>Fibre ...
425903   Computers & Electronics>Computers>Handheld Mob...
1047582  Computers & Electronics>Computers>PCs/Workstat...
904910   Computers & Electronics>Computers>Notebook Par...
157385   Computers & Electronics>Software>Software Lice...
934548   Computers & Electronics>Computers>Notebook Par...
876762   Computers & Electronics>Computers>Notebook Par...
397028   Computers & Electronics>Telecom & Navigation>M...

                                                    path_3  \
1072689  Computers & Electronics > Computers > PCs/Work...
906402   Computers & Electronics > Computers > Notebook...
411281   Computers & Electronics > Computer Cables > Fi...
425903   Computers & Electronics > Computers > Handheld...
1047582  Computers & Electronics > Computers > PCs/Work...
904910   Computers & Electronics > Computers > Notebook...
157385   Computers & Electronics > Software > Software ...
934548   Computers & Electronics > Computers > Notebook...
876762   Computers & Electronics > Computers > Notebook...
397028   Computers & Electronics > Telecom & Navigation...

                      level_4
1072689                  None
906402   Notebook Spare Parts
411281                   None
425903                   None
1047582                  None
904910   Notebook Spare Parts
157385                   None
934548   Notebook Spare Parts
876762   Notebook Spare Parts
397028                   None

In [23]:
print("Rows:", len(df))
print("Unique num_levels (original):")
print(df["num_levels"].value_counts().sort_index())

print("\nCheck how many have a 4th level stored:")
print(df["level_4"].notna().sum(), "rows with level_4")

Rows: 5000
Unique num_levels (original):
num_levels
3    2883
4    2117
Name: count, dtype: int64

Check how many have a 4th level stored:
2117 rows with level_4

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 1072689 to 1121736
Data columns (total 48 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       5000 non-null   object
 1   BrandInfo.BrandLocalName                    5000 non-null   object
 2   BrandInfo.BrandLogo                         4994 non-null   object
 3   BrandInfo.BrandName                         5000 non-null   object
 4   BrandLogo                                   4994 non-null   object
 5   BrandPartCode                               5000 non-null   object
 6   BulletPoints                                4654 non-null   object
 7   Category.CategoryID                         5000 non-null   int64
 8   Category.Name.Language                      5000 non-null   object
 9   Category.Name.Value                         5000 non-null   object
 10  Description.Disclaimer                      4440 non-null   object
 11  Description.ID                              4440 non-null   float64
 12  Description.LeafletPDFURL                   4440 non-null   object
 13  Description.LongDesc                        4440 non-null   object
 14  Description.LongProductName                 4440 non-null   object
 15  Description.ManualPDFSize                   4370 non-null   float64
 16  Description.ManualPDFURL                    4440 non-null   object
 17  Description.MiddleDesc                      4440 non-null   object
 18  Description.PDFSize                         4412 non-null   float64
 19  Description.URL                             4378 non-null   object
 20  Description.Updated                         4440 non-null   object
 21  EndOfLifeDate                               5000 non-null   object
 22  GTIN                                        5000 non-null   object
 23  IcecatId                                    5000 non-null   int64
 24  ProductFamily.ProductFamilyID               5000 non-null   int64
 25  ProductName                                 5000 non-null   object
 26  ProductSeries.SeriesID                      5000 non-null   int64
 27  ReleaseDate                                 5000 non-null   object
 28  SummaryDescription.LongSummaryDescription   5000 non-null   object
 29  SummaryDescription.ShortSummaryDescription  5000 non-null   object
 30  Title                                       5000 non-null   object
 31  Description.WarrantyInfo                    2654 non-null   object
 32  Description                                 560 non-null    object
 33  ProductFamily.Language                      1106 non-null   object
 34  ProductFamily.Value                         1106 non-null   object
 35  ProductSeries.Language                      718 non-null    object
 36  ProductSeries.Value                         718 non-null    object
 37  BulletPoints.BulletPointsId                 346 non-null    float64
 38  BulletPoints.Language                       346 non-null    object
 39  BulletPoints.Updated                        346 non-null    object
 40  BulletPoints.Values                         346 non-null    object
 41  VirtualCategory                             417 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                5000 non-null   object
 44  pathlist_names                              5000 non-null   object
 45  num_levels                                  5000 non-null   int64
 46  path_3                                      5000 non-null   object
 47  level_4                                     2117 non-null   object
dtypes: float64(5), int64(5), object(38)
memory usage: 1.9+ MB

In [25]:
# Extract A, B, C from path_3
df[["A", "B", "C"]] = (
    df["path_3"]
    .str.split(">", expand=True)
    .apply(lambda col: col.str.strip())
)

In [26]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...,3,Computers & Electronics > Computers > Handheld...,None,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations

In [27]:
# Basic Stats
print("Total products:", len(df))
print("Unique A-level:", df["A"].nunique())
print("Unique B-level:", df["B"].nunique())
print("Unique C-level:", df["C"].nunique())

Total products: 5000
Unique A-level: 1
Unique B-level: 17
Unique C-level: 160

In [30]:
#Distribution of A / B / C/
print("\nProducts per A-level:")
print(df["A"].value_counts())

print("\nProducts per B-level (top 10):")
print(df["B"].value_counts().head(20))

print("\nProducts per C-level (top 10):")
print(df["C"].value_counts().head(20))

print("\nProducts per C-level (bottom 10):")
print(df["C"].value_counts().tail(10))

Products per A-level:
A
Computers & Electronics    5000
Name: count, dtype: int64

Products per B-level (top 10):
B
Computers                           2202
Printers & Scanners                  368
Computer Components                  330
Warranty & Support                   318
Software                             296
Data Storage                         284
TVs & Monitors                       251
Computer Cables                      205
Telecom & Navigation                 189
Batteries & Power Supplies           141
Data Input Devices                   111
Consumer Audio & Video Equipment     110
Projectors                            73
Photo & Video Equipment               66
Networking                            47
Office Electronics                     7
Smart Wearables                        2
Name: count, dtype: int64

Products per C-level (top 10):
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
TVs                                76
Computer Monitors                  68
Networking Cables                  67
Print & Scan Accessories           64
Power Adapters & Inverters         63
Printing Equipment                 63
All-in-One PCs/Workstations        60
Mobile Phone Cases                 55
Antivirus Security Software        53
Flat Panel Spare Parts             42
Name: count, dtype: int64

Products per C-level (bottom 10):
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

In [ ]:
# C-level Imbalance Quantiles
# (This shows how skewed leaf categories are)
prod_per_C = df["C"].value_counts()

print("\nC-level product quantiles:")
print(prod_per_C.quantile([0.1, 0.25, 0.5, 0.75, 0.9]))

C-level product quantiles:
0.10     1.0
0.25     2.0
0.50     5.0
0.75    14.0
0.90    60.3
Name: count, dtype: float64

In [32]:
# Basic counts
print("Total products:", len(df))
print("Unique A levels:", df["A"].nunique())
print("Unique B levels:", df["B"].nunique())
print("Unique C levels:", df["C"].nunique())

# Compute product counts
prod_A = df["A"].value_counts()
prod_B = df["B"].value_counts()
prod_C = df["C"].value_counts()

Total products: 5000
Unique A levels: 1
Unique B levels: 17
Unique C levels: 160

In [34]:
# Identify problematic A/B/C categories
# Very large categories (top 10)
print("\n🔥 TOP 10 LARGEST C categories:")
print(prod_C.head(10))

# Very small categories (bottom 10)
print("\n❗ BOTTOM 10 SMALLEST C categories:")
print(prod_C.tail(10))

# C categories with < 10 products
weak_C = prod_C[prod_C < 10]
print("\n❗ Weak C categories (<10 products):", len(weak_C))
print(weak_C.head(20))

# B categories with < 3 C children
C_children_per_B = df.groupby("B")["C"].nunique()
weak_B = C_children_per_B[C_children_per_B < 3]

print("\n❗ Weak B categories (<3 C children):", len(weak_B))
print(weak_B.head(20))

🔥 TOP 10 LARGEST C categories:
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Keyboards                          85
Chassis Components                 84
Name: count, dtype: int64

❗ BOTTOM 10 SMALLEST C categories:
C
SCART Cables                                         1
Fax Machines                                         1
Sport Watch Accessories                              1
Network Switch Components                            1
Uninterruptible Power Supplies (UPSs) Accessories    1
USB Graphics Adapters                                1
Two-Way Radios                                       1
UPS Battery Cabinets                                 1
AV Receivers                                         1
S-Video Cables                                       1
Name: count, dtype: int64

❗ Weak C categories (<10 products): 107
C
Telephony Equipment                 9
Computer Utilities                  9
Mobile Device Chargers              8
Photographic Filmmaking Supplies    8
AV Extenders                        8
Portable Speakers                   7
Home Audio Sets                     7
Projector Accessories               7
DVD/Blu-Ray Players                 6
Flat Panel Mount Accessories        6
Thin Clients                        6
Projector Mounts                    6
Stylus Pens                         6
Mobile Phones                       6
Radios                              6
Flat Panel Floor Stands             6
KVM Cables                          6
Display Privacy Filters             6
Video Cable Adapters                6
Handheld Device Accessories         5
Name: count, dtype: int64

❗ Weak B categories (<3 C children): 2
B
Data Storage       2
Smart Wearables    2
Name: C, dtype: int64

In [35]:
#Identify dominant categories (too large)
# Very large C categories (skewing the distribution)
dominant_C = prod_C[prod_C > prod_C.quantile(0.95)]

print("\n🔥 Dominant C categories (>95th percentile):", len(dominant_C))
print(dominant_C)

🔥 Dominant C categories (>95th percentile): 8
C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
PCs/Workstations                  227
Software Licenses/Upgrades        227
Printing Supplies                 215
Name: count, dtype: int64

In [37]:
B_summary = (
    df.groupby(["A", "B"])
      .agg(num_products=("C", "count"),
           num_C=("C", "nunique"))
      .reset_index()
      .sort_values("num_products", ascending=False)
)

print(" B-level imbalance summary:")
print(B_summary.head(20))

 B-level imbalance summary:
                          A                                 B  num_products  \
3   Computers & Electronics                         Computers          2202
10  Computers & Electronics               Printers & Scanners           368
2   Computers & Electronics               Computer Components           330
16  Computers & Electronics                Warranty & Support           318
13  Computers & Electronics                          Software           296
6   Computers & Electronics                      Data Storage           284
14  Computers & Electronics                    TVs & Monitors           251
1   Computers & Electronics                   Computer Cables           205
15  Computers & Electronics              Telecom & Navigation           189
0   Computers & Electronics        Batteries & Power Supplies           141
5   Computers & Electronics                Data Input Devices           111
4   Computers & Electronics  Consumer Audio & Video Equipment           110
11  Computers & Electronics                        Projectors            73
9   Computers & Electronics           Photo & Video Equipment            66
7   Computers & Electronics                        Networking            47
8   Computers & Electronics                Office Electronics             7
12  Computers & Electronics                   Smart Wearables             2

    num_C
3      18
10      5
2       3
16      4
13      6
6       2
14     17
1      23
15     13
0      12
5       3
4      26
11      7
9       3
7      13
8       3
12      2

In [38]:
def report_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C=("C", "nunique"),
              num_products=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]
        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C']}")
            print(f"    #products (total under this B): {row['num_products']}")

In [39]:
report_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 12
    #products (total under this B): 141
  B: Computer Cables
    #C-level subcategories: 23
    #products (total under this B): 205
  B: Computer Components
    #C-level subcategories: 3
    #products (total under this B): 330
  B: Computers
    #C-level subcategories: 18
    #products (total under this B): 2202
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 26
    #products (total under this B): 110
  B: Data Input Devices
    #C-level subcategories: 3
    #products (total under this B): 111
  B: Data Storage
    #C-level subcategories: 2
    #products (total under this B): 284
  B: Networking
    #C-level subcategories: 13
    #products (total under this B): 47
  B: Office Electronics
    #C-level subcategories: 3
    #products (total under this B): 7
  B: Photo & Video Equipment
    #C-level subcategories: 3
    #products (total under this B): 66
  B: Printers & Scanners
    #C-level subcategories: 5
    #products (total under this B): 368
  B: Projectors
    #C-level subcategories: 7
    #products (total under this B): 73
  B: Smart Wearables
    #C-level subcategories: 2
    #products (total under this B): 2
  B: Software
    #C-level subcategories: 6
    #products (total under this B): 296
  B: TVs & Monitors
    #C-level subcategories: 17
    #products (total under this B): 251
  B: Telecom & Navigation
    #C-level subcategories: 13
    #products (total under this B): 189
  B: Warranty & Support
    #C-level subcategories: 4
    #products (total under this B): 318

In [40]:
def report_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products']} products)")

In [41]:
report_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Battery Chargers  (4 products)
    C: Household Batteries  (11 products)
    C: Notebook Power Tips  (2 products)
    C: Portable Device Management Carts & Cabinets  (1 products)
    C: Power Adapters & Inverters  (63 products)
    C: Power Banks  (4 products)
    C: Power Distribution Units (PDUs)  (11 products)
    C: Power Supply Units  (16 products)
    C: UPS Batteries  (3 products)
    C: UPS Battery Cabinets  (1 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
  B: Computer Cables
    C: Audio Cables  (3 products)
    C: Cable Interface/Gender Adapters  (20 products)
    C: Cable Protectors  (2 products)
    C: Coaxial Cables  (4 products)
    C: DVI Cables  (5 products)
    C: DisplayPort Cables  (3 products)
    C: Fibre Optic Cables  (29 products)
    C: FireWire Cables  (1 products)
    C: HDMI Cables  (11 products)
    C: InfiniBand Cables  (1 products)
    C: KVM Cables  (6 products)
    C: Lightning Cables  (3 products)
    C: Networking Cables  (67 products)
    C: Power Cables  (12 products)
    C: S-Video Cables  (1 products)
    C: SATA Cables  (5 products)
    C: SCART Cables  (1 products)
    C: SCSI Cables  (2 products)
    C: Serial Attached SCSI (SAS) Cables  (2 products)
    C: USB Cables  (14 products)
    C: VGA Cables  (2 products)
    C: Video Cable Adapters  (6 products)
    C: Wire Connectors  (5 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: Interface Components  (5 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Backpack PCs  (1 products)
    C: E-Book Reader Cases  (3 products)
    C: E-Book Readers  (1 products)
    C: Handheld Device Accessories  (5 products)
    C: Handheld Mobile Computer Spare Parts  (1 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PC/Workstation Barebones  (4 products)
    C: PCs/Workstations  (227 products)
    C: POS Systems  (5 products)
    C: Server Barebones  (10 products)
    C: Servers  (15 products)
    C: Stylus Pens  (6 products)
    C: Tablet Cases  (25 products)
    C: Tablet Spare Parts  (1 products)
    C: Tablets  (39 products)
    C: Thin Clients  (6 products)
  B: Consumer Audio & Video Equipment
    C: AV Extenders  (8 products)
    C: AV Receivers  (1 products)
    C: Audio Equipment Parts & Accessories  (23 products)
    C: CD Players  (2 products)
    C: Cassette Players  (1 products)
    C: Computer TV Tuners  (2 products)
    C: DVD/Blu-Ray Players  (6 products)
    C: Dictaphones  (4 products)
    C: Digital Media Players  (2 products)
    C: Docking Speakers  (1 products)
    C: Home Audio Sets  (7 products)
    C: Home Cinema Systems  (5 products)
    C: Loudspeakers  (5 products)
    C: MP3/MP4 Player Cases  (3 products)
    C: MP3/MP4 Players  (5 products)
    C: Portable DVD/Blu-Ray Players  (2 products)
    C: Portable Speakers  (7 products)
    C: Portable Stereo Systems  (1 products)
    C: Public Address (PA) Systems  (1 products)
    C: Radios  (6 products)
    C: Remote Controls  (4 products)
    C: Soundbar Speakers  (5 products)
    C: Speaker Sets  (4 products)
    C: USB Graphics Adapters  (1 products)
    C: Video Capturing Devices  (2 products)
    C: Video Switches  (2 products)
  B: Data Input Devices
    C: KVM Switches  (10 products)
    C: Keyboards  (85 products)
    C: Mice  (16 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
    C: Data Storage Mediums  (11 products)
  B: Networking
    C: ISDN Access Devices  (1 products)
    C: Network Antennas  (1 products)
    C: Network Extenders  (1 products)
    C: Network Media Converters  (3 products)
    C: Network Switch Components  (1 products)
    C: Network Switch Modules  (2 products)
    C: Network Switches  (15 products)
    C: Network Transceiver Modules  (12 products)
    C: Patch Panels  (1 products)
    C: PowerLine Network Adapters  (2 products)
    C: Remote Management Adapters  (1 products)
    C: WLAN Access Points  (3 products)
    C: Wireless Routers  (4 products)
  B: Office Electronics
    C: Calculators  (5 products)
    C: Fax Machines  (1 products)
    C: Laminator Pouches  (1 products)
  B: Photo & Video Equipment
    C: Camera Accessories  (19 products)
    C: Cameras & Camcorders  (39 products)
    C: Photographic Filmmaking Supplies  (8 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
    C: Scanning Equipment  (5 products)
  B: Projectors
    C: Data Projectors  (17 products)
    C: Projection Lenses  (3 products)
    C: Projection Screens  (25 products)
    C: Projector Accessories  (7 products)
    C: Projector Lamps  (11 products)
    C: Projector Mount Accessories  (4 products)
    C: Projector Mounts  (6 products)
  B: Smart Wearables
    C: Activity Trackers  (1 products)
    C: Sport Watch Accessories  (1 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Computer Utilities  (9 products)
    C: Multimedia Software  (5 products)
    C: Networking Software  (1 products)
    C: Operating Systems  (1 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Digital Photo Frames  (2 products)
    C: Display Privacy Filters  (6 products)
    C: Flat Panel Accessories  (2 products)
    C: Flat Panel Ceiling Mounts  (3 products)
    C: Flat Panel Desk Mounts  (4 products)
    C: Flat Panel Floor Stands  (6 products)
    C: Flat Panel Mount Accessories  (6 products)
    C: Flat Panel Spare Parts  (42 products)
    C: Flat Panel Wall Mounts  (10 products)
    C: Hospitality TVs  (2 products)
    C: Signage Displays  (14 products)
    C: Stereoscopic 3D Glasses  (2 products)
    C: TVs  (76 products)
    C: Touch Screen Monitors  (5 products)
    C: Touch Screen Overlays  (1 products)
    C: Video Splitters  (2 products)
  B: Telecom & Navigation
    C: Holders  (4 products)
    C: Mobile Device Chargers  (8 products)
    C: Mobile Device Keyboards  (10 products)
    C: Mobile Headsets  (12 products)
    C: Mobile Phone Cases  (55 products)
    C: Mobile Phone Spare Parts  (14 products)
    C: Mobile Phones  (6 products)
    C: Navigational Equipment  (3 products)
    C: Peripheral Device Cases  (1 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
    C: Telephony Equipment  (9 products)
    C: Two-Way Radios  (1 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Installation Services  (2 products)
    C: Maintenance & Support Fees  (1 products)
    C: Warranty & Support Extensions  (288 products)

In [42]:
def report_ABC_products(df):
    for a in df["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        dfA = df[df["A"] == a]

        for b in dfA["B"].unique():
            print(f"  B: {b}")
            dfB = dfA[dfA["B"] == b]

            for c in dfB["C"].unique():
                dfC = dfB[dfB["C"] == c]
                print(f"    C: {c}  ({len(dfC)} products)")
                
                # show top 10 product codes
                for code in dfC["BrandPartCode"].fillna("").head(10):
                    print(f"        • {code}")

In [43]:
report_ABC_products(df)

A: Computers & Electronics
================================================================================
  B: Computers
    C: PCs/Workstations  (227 products)
        • K31CD-IT049T
        • 109559U
        • UN42-M031M
        • 30AT0066MB
        • 6PV24EA
        • 7HX46UT
        • 10MV002XUS
        • AEGIS 3 VR7RD-037US
        • 2ED43PA-E223
        • 1HK88EA
    C: Notebook Parts & Accessories  (1019 products)
        • 686915-A41
        • 659501-BB1
        • FRU00HT024
        • 448002-001
        • 900818-061
        • 25212106
        • SIC1085866LCD0
        • P000453890
        • SIC1099842LCD0
        • 25207264
    C: Handheld Mobile Computer Spare Parts  (1 products)
        • FA889AA#AC3
    C: Notebooks  (774 products)
        • NX.MPGEH.057
        • GE72 2QC-209NL
        • NX.VGAEY.002
        • 9S7-179E22-062
        • X8M21EA
        • GX531GX-ES016T
        • 20EMA008AU
        • 3JX62EA
        • PT343E-0NC05GGR
        • UX310UF-FC002T
    C: Servers  (15 products)
        • 5463M2G
        • SUB12GE
        • VFY:R1007SC040IN
        • CTCTW
        • 7X10A03PNA
        • 70DA0002EA
        • VFY:R3007SC030IN
        • 70TGR001EA
        • VFY:R3508SC011IN
        • VFY:T1003SC020IN
    C: Tablets  (39 products)
        • 80U10005MH
        • GT-P7510FKDITV
        • 90NK01B1-M00600
        • SM-T813NZDE
        • KTAT305-T64-1TJC
        • XE300TZC-K01MY
        • SM-T677NZWAITV
        • S70G10-0N
        • ZA3W0014SE
        • SM-T713NZKEBTU
    C: All-in-One PCs/Workstations  (60 products)
        • F0B3004JUK
        • Z240ICGK-GC069X
        • PW.SHSE2.014
        • 5QW01EA
        • 4RT84EA
        • ET2311IUTH-BG006T
        • 4RT63EA
        • 9S6-AE9111-004
        • M1Q83AA
        • 1GV32EA
    C: Tablet Cases  (25 products)
        • EFC-1H8SWEGSTA
        • SYFACILE101W
        • BC106578
        • CSGE2188BL
        • THZ597EU
        • APPIPC08G
        • 90XB001P-BSL030
        • 90XB001P-BSL020
        • 2043
        • TABZOO8PAN
    C: Server Barebones  (10 products)
        • SYS-F627R3-RTB+
        • AS -2042G-TRF
        • S26361-K1444-V400
        • LADMP2312KXXX44
        • SYS-5036I-IF
        • SYS-1029TP-DC0R
        • SYS-F617H6-FT+
        • SYS-8017R-TF+
        • SYS-6026T-URF
        • P4308IP4LHJC
    C: Stylus Pens  (6 products)
        • AMM163US
        • 000449.01
        • AMM01BUS
        • STY01UF
        • NP.STY1A.004
        • AMM1214AU
    C: Handheld Device Accessories  (5 products)
        • BTBOUNCEOUTDOORD
        • CC.N3002.006
        • 9G00.000
        • DLM2260/10
        • 1261-6193
    C: Backpack PCs  (1 products)
        • 2WC83EA
    C: PC/Workstation Barebones  (4 products)
        • BOXD34010WYK2
        • SYS-6015T-TV
        • DT.VRNEG.001
        • DS77U5
    C: POS Systems  (5 products)
        • J8F53PA
        • T0F02EA#ABH
        • 2VR01EA
        • Y6A83EA#ABB
        • W5X58UT
    C: Thin Clients  (6 products)
        • BE4S21AA1
        • 909682-01L
        • 909714-01L
        • 909716-54L
        • 100013839
        • 909703-21L
    C: E-Book Reader Cases  (3 products)
        • N905-BMP-2RD
        • N249-AC-BK-E-PU
        • PRS-3LEATHCOVT
    C: Tablet Spare Parts  (1 products)
        • 747658-001
    C: E-Book Readers  (1 products)
        • N905-KDN-B
  B: Computer Cables
    C: Fibre Optic Cables  (29 products)
        • 37745
        • 33351
        • 85072
        • 37377
        • 37724
        • 21685
        • FIBLCMT5
        • 33458
        • RL2603
        • RL4109
    C: Networking Cables  (67 products)
        • IK8905
        • 82458
        • IGG310656
        • V7N2C6-25F-BLKS
        • C6ASPAT3AQ
        • FB6625
        • C6PATCH20OR
        • N6PATCH5RD
        • 24638
        • 805414
    C: DisplayPort Cables  (3 products)
        • 60125
        • 84204
        • CAC-1073
    C: Power Cables  (12 products)
        • 03120
        • P004-002-AOR
        • P047-002
        • P005-003-AOR
        • P006-004
        • 450-11930
        • 112160
        • 246959-081
        • 5019584
        • 728554-01L
    C: USB Cables  (14 products)
        • USBDATA06MUSBK
        • SB0005
        • 10.01.0204-BK
        • CCUSBAMAF18-V1
        • U330-15M
        • 81586
        • 93621
        • MA117985
        • MA117976
        • USB2CC50CM
    C: Cable Interface/Gender Adapters  (20 products)
        • U436-06N-GBW-RA
        • P586-012-HDMI
        • 60051
        • IDATA USB-SER-2CT
        • CAC-1330
        • 13403
        • DVISPL1DH
        • 90-XB3900CA00040
        • AB9055
        • AB7871
    C: Video Cable Adapters  (6 products)
        • CBLMDPHD6FT-1E
        • P581-006-VGA
        • 40688
        • ICOC-DSP-H12-010
        • S26361-F2421-L400
        • 81207
    C: Cable Protectors  (2 products)
        • 16329
        • CABLE8W
    C: HDMI Cables  (11 products)
        • HDMM150CM
        • HDMM3MHS
        • EM9642
        • ICOC HDMI2-4-EXT010
        • 93042
        • SWV2433W/10
        • ICOC-HDMI-4-050WH
        • PSICC-HDMI4F-6
        • 50181
        • EM9132
    C: Wire Connectors  (5 products)
        • 01931
        • IPW-SP16-WH9
        • C25PCM
        • 01939
        • 10.21.0503
    C: SCSI Cables  (2 products)
        • 470-11540
        • 28295
    C: SATA Cables  (5 products)
        • P943-19I
        • AK3415
        • CBL-0201L
        • 50041
        • IDE100RND36
    C: SCART Cables  (1 products)
        • SWV2540T/10
    C: Lightning Cables  (3 products)
        • IFUSLR-WH3
        • A8121H92
        • USBLT1MBL
    C: Coaxial Cables  (4 products)
        • 87004
        • 202-85
        • 10.26.2004
        • 29136
    C: VGA Cables  (2 products)
        • 40260
        • 28247
    C: KVM Cables  (6 products)
        • CBL0086
        • SV16EM10
        • P780-006
        • F1D9017B06
        • 591010
        • 21958
    C: DVI Cables  (5 products)
        • V7DVIB-1.8M-BLK
        • DVIDSMM5M
        • 29528
        • 40295
        • ZENDVI2
    C: Serial Attached SCSI (SAS) Cables  (2 products)
        • 470-12371
        • S26361-F3210-L302
    C: Audio Cables  (3 products)
        • 80142
        • MU1MMRCA
        • 80119
    C: InfiniBand Cables  (1 products)
        • SFP10GADAC10M-LEG
    C: FireWire Cables  (1 products)
        • F007-015
    C: S-Video Cables  (1 products)
        • SVIDEOMM18
  B: Software
    C: Software Licenses/Upgrades  (227 products)
        • 00D8199
        • MSS-CFIDPF-ADD-1G-1Y
        • SS00733414
        • SLNA0079
        • PTNN0004
        • GP00215333
        • SW-UPG-PC-S200-5-25
        • BU00302296
        • 20090712
        • EA00192615
    C: Antivirus Security Software  (53 products)
        • 13743997
        • A12IS14MBR
        • EAVB-C2B5
        • 10744985
        • KL4867XAKTW
        • LFS-N2A2-EDU
        • KL4251XAEFW
        • KL4863XAMFC
        • TMKS-181
        • KL4313XAPTH
    C: Computer Utilities  (9 products)
        • 301N84410
        • LCWZ18PROMLAM
        • WZ16STNLMBEU
        • LCWZ15STDMLA
        • CH224A
        • 0A35067
        • LCWZPROMLMNT3F
        • 301N81140
        • 10759452
    C: Multimedia Software  (5 products)
        • PSPX6MLMBEU
        • 247010EU
        • LCCCADMLPCMB
        • VSPRX9ULMLMBEU
        • CDHSX5DEMB
    C: Networking Software  (1 products)
        • 0C19577
    C: Operating Systems  (1 products)
        • B0S24AV
  B: Telecom & Navigation
    C: Mobile Phone Spare Parts  (14 products)
        • GH59-12969A
        • MBI0103A
        • AB563840CE
        • 90AZ00A5-R7A100
        • GH59-12841A
        • GH98-23340D
        • EEB-U20BBUG
        • GH97-16565D
        • 90AZ00M7-R7A010
        • GH96-07236A
    C: Mobile Device Keyboards  (10 products)
        • 701428-331
        • I10REU-BBS
        • NP.KBD1A.00R
        • FRU04W2177
        • 920-006395
        • LC.KBD0A.007
        • EJ-CN920AFEGAE
        • FRU04W2175
        • 920-006268
        • 784194-091
    C: Smartphones  (34 products)
        • 1261-8982
        • 2Q001-ROX00-390S
        • SM-G398FZKDE28
        • SM-A800FZDETUR
        • SM-G975FZWATUR
        • SM-G950FZVAXEH
        • SM-J415FZKPBTU
        • SM-J200HZWDDKR
        • LMG710EM.ANEUBL
        • PA700021SE
    C: Mobile Phone Cases  (55 products)
        • MP-44006
        • TAGE3163K
        • SENSATIONIPHX65F
        • EF-FS727LWEGWW
        • GS4PB-BLK
        • 200102293
        • MP-86587
        • TPUSA829T
        • ETUISMI8190
        • MP-55216
    C: Holders  (4 products)
        • 1262438293
        • HA-E60IO
        • 1262438247
        • BTAC-02
    C: Telephony Equipment  (9 products)
        • M3301GW/FR
        • SE8880B/12
        • D1101_B
        • D2152B/38
        • 10003066
        • S1202
        • D4502B/23
        • CPH0018A
        • CD2802W/DE
    C: Screen Protectors  (32 products)
        • TEM0002A
        • 1026172
        • OSFTAG13.5L/P-SURFB
        • CANPSSD1100S
        • 1004070
        • 1004591
        • ET-FN910CTEGWW
        • SONDSCW300S
        • 1007629
        • SAMS5620LE
    C: Mobile Phones  (6 products)
        • KP500-AESPVB
        • GT-S5220ZWR
        • SM1244AB1F1
        • KM570.ADEUBL
        • KC910
        • CTE109BK/00
    C: Mobile Headsets  (12 products)
        • HA130-GRN-21EC
        • SHS8100/98
        • SHE5305WT/00
        • HA-SR185-W-J
        • BTPETITTWSB
        • BHM3350EBEC
        • SHL3265BL/00
        • HAS31MAE
        • 5012786036888
        • DRV150IPB
    C: Two-Way Radios  (1 products)
        • RC-6420
    C: Mobile Device Chargers  (8 products)
        • 440-40
        • DLP2307/11
        • ACHTYPECK
        • ACHKIT10WMFIIPADW
        • CBRAR6100
        • DR5026A
        • DLP2307/12
        • CARUSB10
    C: Navigational Equipment  (3 products)
        • 1GE0.002.02
        • 9UUA.001.22
        • NV-U51
    C: Peripheral Device Cases  (1 products)
        • PDVK9
  B: Printers & Scanners
    C: Printing Supplies  (215 products)
        • 106R03527
        • V7ML2250
        • OC301Y-FRC
        • 6015Y-FRC
        • TK18-XL-FRC
        • SV043A
        • 73074DK
        • 7740A001
        • 32RAN006R01526
        • BR1100BK-INK-FRC
    C: Print & Scan Accessories  (64 products)
        • PA03753-K982
        • 40X8421
        • RK2-1992-000CN
        • RM1-2721-040CN
        • 675K78361
        • 20G0890
        • RM1-1717-000CN
        • T0F27A
        • 724-10520
        • C12C806392
    C: Printing Equipment  (63 products)
        • 6510_DNI
        • 35S5784W
        • D4J78B#601
        • 8030B005
        • C11C560021DA
        • 44951604
        • 7400V_DN
        • 42C0091
        • LMA:20G0501
        • 1102NF3NL0
    C: Printing Media  (21 products)
        • CHP610
        • 8031
        • C13S042096
        • 52210204
        • CG886A
        • 1TYLAB10252DTP74
        • C13S045439
        • 8210
        • Q1408A
        • CHP235
    C: Scanning Equipment  (5 products)
        • 1992882
        • PA03643-B011
        • B11B226201
        • L1970A
        • Q2907A
  B: Batteries & Power Supplies
    C: UPS Batteries  (3 products)
        • RBC49-2U
        • BP240V787C-1PH
        • RBC143
    C: Power Supply Units  (16 products)
        • RS-900-AAAA-A3
        • RS550-ACAAE3-EU
        • PY.25008.002
        • TQXGE-700SAP
        • PWS-0061
        • PWR-242-AE
        • BN204
        • PWS-2K04A-1R
        • PY.75008.005
        • AT-PWR05-30
    C: Power Adapters & Inverters  (63 products)
        • 2P-AK.065AP.13
        • POWERPAL
        • ALT28064A
        • 957-1039P-101
        • 40Y7666
        • ALT28751A
        • PA3822E-1AC3
        • S26391-F478-L100
        • P000537790
        • PA3378E-1ACA
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
        • 110525203
        • 9PX3000IRTN
        • 1024313
        • G55TUPSM100HS
        • LI60301A0001B00
        • AVRX550UD
        • 5PX3000IRT2UAU
        • 1024317
        • 68454
        • 1026635
    C: Household Batteries  (11 products)
        • FUJ:CP473761-XX
        • 56666 101 402
        • 6AM6-B1D
        • 364.101.401
        • SR44NB1A
        • 936847
        • 6205301401
        • DU-DL2016
        • MN2400-X4
        • 56683 101 402
    C: Power Distribution Units (PDUs)  (11 products)
        • 033180091
        • 036005061
        • MPE-1762
        • 333285
        • T982F3-F-SL-015
        • APS3-058
        • PDPM138H-R
        • 9PXEBM180RT
        • NSYAPU19UK7
        • VP7551
    C: Power Banks  (4 products)
        • P27QC10P60-BK
        • FREEPOWER7800W
        • 57918101441
        • 420-19
    C: Uninterruptible Power Supplies (UPSs) Accessories  (1 products)
        • GXT3CONN72V
    C: Battery Chargers  (4 products)
        • PLA8031A
        • PLA8011A
        • UCC8014A
        • 6216B003
    C: UPS Battery Cabinets  (1 products)
        • E3SOPT007
    C: Notebook Power Tips  (2 products)
        • PT-3H
        • PT-3O
    C: Portable Device Management Carts & Cabinets  (1 products)
        • CS48USBW
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
        • 90LMGF001T01041K
        • 7MQ82AA
        • MG28UQ
        • E1908WSV-S1
        • 22MK400H-B
        • S26361-K1295-V181
        • 227E6EDSD/57
        • 17S4LSB/00
        • 17S4LSB/10
        • LS19B350NS
    C: TVs  (76 products)
        • HG40EB690QBXXU
        • 42LA641S
        • UE46EH5000KXXU
        • 43PUS6503/12/R/B
        • UE40ES7000SXXC
        • 32W1733DG
        • KDL-32EX725BAEP
        • KDL-22S5500
        • KDL32R403CBAEP
        • 37PF7320/10
    C: Flat Panel Mount Accessories  (6 products)
        • AEC012018
        • BT7032/B
        • FSBI2B
        • BT8390-WFK2
        • FCAC06B
        • KRA225S
    C: Display Privacy Filters  (6 products)
        • 7100119016
        • OSFNB2WPI13L-HP810
        • SSP54UF
        • 4Z10K85320
        • OSFNB2WPI13.3-TPX380
        • OSFT4WAD9.7L/P-TAB50
    C: Flat Panel Spare Parts  (42 products)
        • 55.L61V2.013
        • 55.L75VE.002
        • 55.C2H0J.002
        • 55.L980E.004
        • 55.LFM0J.003
        • 55.LKR0Q.004
        • 55.LDW0Q.008
        • 55.LF40B.018
        • 55.LAU0J.009
        • 55.LQW0B.008
    C: Flat Panel Wall Mounts  (10 products)
        • ICA-LCD 2900WH
        • WMN4277S
        • 37079
        • RXT2
        • BT8430
        • 100013412
        • IGG314654
        • 00132032
        • PSMH2685
        • PPC130/SI
    C: Signage Displays  (14 products)
        • 43SE3C
        • LH43QMNEBGC/UE
        • LS40BHZNS
        • M4213CC-BA
        • FWD-48W600P
        • 49SL5E-H
        • 42LS53A
        • LS550UCM-EF
        • LH49DCHPLGC
        • E554
    C: Touch Screen Overlays  (1 products)
        • PT-1155-CA10
    C: Video Splitters  (2 products)
        • IDATA-EX-DL344
        • B118-008-UHD
    C: Touch Screen Monitors  (5 products)
        • 47WT30MS-B
        • BDT5571VM/06
        • T1732MSC-WAG
        • T2381W
        • TF3237MSC-B1AG
    C: Flat Panel Floor Stands  (6 products)
        • 64551631
        • 62612012
        • SCETAU
        • 64353711
        • L7010PNLSTANDB
        • CFW140/WE
    C: Digital Photo Frames  (2 products)
        • 21350
        • 9FF2CWO/00
    C: Hospitality TVs  (2 products)
        • 46MV732G
        • 37LT380H
    C: Flat Panel Ceiling Mounts  (3 products)
        • FHP18110B
        • RPA171
        • SNCA-CEILING
    C: Stereoscopic 3D Glasses  (2 products)
        • SSG-4100GB/ZD
        • JZ.K0100.003
    C: Flat Panel Accessories  (2 products)
        • PBI55-H
        • VG-SCFM55CM/XC
    C: Flat Panel Desk Mounts  (4 products)
        • K1P200B
        • 8507882
        • 58.182
        • FPMA-D1030D-4
  B: Data Storage
    C: Data Storage Devices  (273 products)
        • DT150/64GB
        • 644TP
        • FTS:ETVSA4A-L
        • FRU03T6721
        • D8F35AV
        • DU-Z08GCAN3-R
        • HDTC715EK3CA
        • HXMU032DC-GB2
        • 400-25626
        • S26361-F5525-L480
    C: Data Storage Mediums  (11 products)
        • 3200338
        • 94797
        • 97970
        • 96159
        • 43721
        • 43753
        • BNE25A
        • PDV-184N
        • 100DMR47RS4T2UC
        • 2DVM60EXM-BT
  B: Warranty & Support
    C: Warranty & Support Extensions  (288 products)
        • H7J36A4#YZL
        • FSP:G-SW5I060PRE0S
        • 01-SSC-2175
        • UN410E
        • UT431E
        • H7J36A3#TT5
        • H7KJ7E
        • UL642PE
        • SV.WPRA0.A09
        • 2355878
    C: IT Support Services  (27 products)
        • U0P47E
        • UY899E
        • 890-16238
        • U0P43E
        • U1Q28E
        • HT755E
        • 890-14585
        • U6Z32E
        • U7D00E
        • 890-18530
    C: Installation Services  (2 products)
        • PRF0013-10000S
        • KEY140EU-VEK
    C: Maintenance & Support Fees  (1 products)
        • 2YGLD-MXS5120
  B: Data Input Devices
    C: Keyboards  (85 products)
        • 90200343
        • 724718-151
        • 51J0380
        • 31P8959
        • 920-004103
        • FRU39M7020
        • 628688-331
        • HX-KB1BL1-NO/A2
        • 90XB03H0-BKB010
        • SLIMKEYC
    C: Mice  (16 products)
        • JM-A4900
        • 910-004351
        • 49041
        • C08-282
        • 90-XB3B00MU00010
        • S26381-K467-L100
        • APPHT8B
        • H3T50AA#AC3
        • M-6650
        • IM 1600-WT-WBW
    C: KVM Switches  (10 products)
        • SV431DVGAU2A
        • NOTECONS02
        • B072-008-1A
        • SC4UAD-001
        • F1DS102JEA
        • KVM-0820
        • A7485895
        • SV831DUTP
        • DKVM-4U
        • SC280-001
  B: Consumer Audio & Video Equipment
    C: Audio Equipment Parts & Accessories  (23 products)
        • EP-EV-NM-BLK/LGY
        • SHL5505GB/28
        • HED155
        • MDRRF995RK
        • 4BX31AA
        • HA-EBX85-B
        • ORACO-ERM11-GBA01
        • 939-001535
        • SHO9555/10
        • MDR-EX300SLW
    C: AV Extenders  (8 products)
        • 89364
        • 590991
        • 08147
        • SKYVISION WS100
        • BHDBT-K-E3SPI-L
        • B160-001-VSI
        • 999-9560-001
        • 29224
    C: Radios  (6 products)
        • 50060656
        • TR-54BLUEMK2
        • AE2160/79
        • 50049989A1
        • RR70PDOGS2
        • 50050654
    C: MP3/MP4 Players  (5 products)
        • SA3VBE04RN/02
        • YPQ2JAW
        • SA2124/02
        • SA2111/02
        • SA2114/02
    C: Soundbar Speakers  (5 products)
        • HTL3120/12
        • HW-MS6501
        • 0MN008
        • HW-R650/TK
        • HTL6145C/12
    C: Home Cinema Systems  (5 products)
        • DAV-F300
        • HT-E350/XN
        • BDVE300
        • MCD179/12
        • HT462DZ
    C: MP3/MP4 Player Cases  (3 products)
        • DLA66073D/10
        • SPK-A1679
        • DLA67540D/10
    C: Portable Speakers  (7 products)
        • BT14V
        • BT02NR
        • SRSX11/BLUE
        • SK-1513
        • EO-SG930CLEGAE
        • 984-000373
        • D9J19AA
    C: Remote Controls  (4 products)
        • AK59-00074A
        • PQWRHQ0FDB
        • RM-AV2500T
        • MC.JG211.004
    C: Cassette Players  (1 products)
        • M570VS
    C: Public Address (PA) Systems  (1 products)
        • 111151120030
    C: Digital Media Players  (2 products)
        • 34651
        • 98243
    C: Loudspeakers  (5 products)
        • DS9860W/10
        • SRS-P7
        • SPA2100/12
        • GTKXB90B
        • GP-S2000
    C: Home Audio Sets  (7 products)
        • XL-B710 (BK)
        • CMT-A50
        • UXL5V
        • CMT-S20
        • UX-G300
        • UX-G650
        • FWM377/05
    C: Video Switches  (2 products)
        • B119-2X2
        • 08336
    C: Portable DVD/Blu-Ray Players  (2 products)
        • DVP-FX730P
        • DP571T
    C: DVD/Blu-Ray Players  (6 products)
        • HR650
        • BDP2800/12
        • DVD-SH873
        • DVDR3360H/31
        • DVP3600/12
        • BDX4350KE
    C: CD Players  (2 products)

In [46]:
# Compute metrics
products_per_AB = df.groupby(["A", "B"]).size()
C_children_per_AB = df.groupby(["A", "B"])["C"].nunique()

# Combine
ab_summary = pd.DataFrame({
    "products_in_AB": products_per_AB,
    "n_C_children": C_children_per_AB
})

# Sort by product count descending (like your example)
ab_summary = ab_summary.sort_values("products_in_AB", ascending=False).head(10)

print(ab_summary)

                                                    products_in_AB  \
A                       B
Computers & Electronics Computers                             2202
                        Printers & Scanners                    368
                        Computer Components                    330
                        Warranty & Support                     318
                        Software                               296
                        Data Storage                           284
                        TVs & Monitors                         251
                        Computer Cables                        205
                        Telecom & Navigation                   189
                        Batteries & Power Supplies             141

                                                    n_C_children
A                       B
Computers & Electronics Computers                             18
                        Printers & Scanners                    5
                        Computer Components                    3
                        Warranty & Support                     4
                        Software                               6
                        Data Storage                           2
                        TVs & Monitors                        17
                        Computer Cables                       23
                        Telecom & Navigation                  13
                        Batteries & Power Supplies            12

In [48]:
prod_per_C = df["C"].value_counts()
prod_per_C

C
Notebook Parts & Accessories     1019
Notebooks                         774
Warranty & Support Extensions     288
Data Storage Devices              273
System Components                 241
                                 ...
USB Graphics Adapters               1
Two-Way Radios                      1
UPS Battery Cabinets                1
AV Receivers                        1
S-Video Cables                      1
Name: count, Length: 160, dtype: int64

In [54]:
#Keep only C categories with > 10 products
valid_C = prod_per_C[prod_per_C >= 20].index
df = df[df["C"].isin(valid_C)].copy()

In [56]:
print("Remaining rows:", len(df))
print("Unique C after filtering:", df["C"].nunique())
print("Min products per C (should be >20):", df["C"].value_counts().min())

Remaining rows: 4382
Unique C after filtering: 32
Min products per C (should be >20): 20

In [57]:
#final A-B summary
def print_final_AB(df):
    grouped = (
        df.groupby(["A", "B"])
          .agg(
              num_C_under_B=("C", "nunique"),
              num_products_under_B=("C", "size")
          )
          .reset_index()
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        temp = grouped[grouped["A"] == a]

        for _, row in temp.iterrows():
            print(f"  B: {row['B']}")
            print(f"    #C-level subcategories: {row['num_C_under_B']}")
            print(f"    #products (under this B): {row['num_products_under_B']}")

In [58]:
print_final_AB(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    #C-level subcategories: 2
    #products (under this B): 87
  B: Computer Cables
    #C-level subcategories: 3
    #products (under this B): 116
  B: Computer Components
    #C-level subcategories: 2
    #products (under this B): 325
  B: Computers
    #C-level subcategories: 6
    #products (under this B): 2144
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 23
  B: Data Input Devices
    #C-level subcategories: 1
    #products (under this B): 85
  B: Data Storage
    #C-level subcategories: 1
    #products (under this B): 273
  B: Photo & Video Equipment
    #C-level subcategories: 1
    #products (under this B): 39
  B: Printers & Scanners
    #C-level subcategories: 4
    #products (under this B): 363
  B: Projectors
    #C-level subcategories: 1
    #products (under this B): 25
  B: Software
    #C-level subcategories: 2
    #products (under this B): 280
  B: TVs & Monitors
    #C-level subcategories: 3
    #products (under this B): 186
  B: Telecom & Navigation
    #C-level subcategories: 3
    #products (under this B): 121
  B: Warranty & Support
    #C-level subcategories: 2
    #products (under this B): 315

In [59]:
def print_final_ABC(df):
    grouped = (
        df.groupby(["A", "B", "C"])
          .size()
          .reset_index(name="num_products_under_C")
    )

    for a in grouped["A"].unique():
        print(f"\nA: {a}")
        print("="*80)
        tempA = grouped[grouped["A"] == a]

        for b in tempA["B"].unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B"] == b]

            for _, row in tempB.iterrows():
                print(f"    C: {row['C']}  ({row['num_products_under_C']} products)")
                
print_final_ABC(df)

A: Computers & Electronics
================================================================================
  B: Batteries & Power Supplies
    C: Power Adapters & Inverters  (63 products)
    C: Uninterruptible Power Supplies (UPSs)  (24 products)
  B: Computer Cables
    C: Cable Interface/Gender Adapters  (20 products)
    C: Fibre Optic Cables  (29 products)
    C: Networking Cables  (67 products)
  B: Computer Components
    C: Chassis Components  (84 products)
    C: System Components  (241 products)
  B: Computers
    C: All-in-One PCs/Workstations  (60 products)
    C: Notebook Parts & Accessories  (1019 products)
    C: Notebooks  (774 products)
    C: PCs/Workstations  (227 products)
    C: Tablet Cases  (25 products)
    C: Tablets  (39 products)
  B: Consumer Audio & Video Equipment
    C: Audio Equipment Parts & Accessories  (23 products)
  B: Data Input Devices
    C: Keyboards  (85 products)
  B: Data Storage
    C: Data Storage Devices  (273 products)
  B: Photo & Video Equipment
    C: Cameras & Camcorders  (39 products)
  B: Printers & Scanners
    C: Print & Scan Accessories  (64 products)
    C: Printing Equipment  (63 products)
    C: Printing Media  (21 products)
    C: Printing Supplies  (215 products)
  B: Projectors
    C: Projection Screens  (25 products)
  B: Software
    C: Antivirus Security Software  (53 products)
    C: Software Licenses/Upgrades  (227 products)
  B: TVs & Monitors
    C: Computer Monitors  (68 products)
    C: Flat Panel Spare Parts  (42 products)
    C: TVs  (76 products)
  B: Telecom & Navigation
    C: Mobile Phone Cases  (55 products)
    C: Screen Protectors  (32 products)
    C: Smartphones  (34 products)
  B: Warranty & Support
    C: IT Support Services  (27 products)
    C: Warranty & Support Extensions  (288 products)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4382 entries, 1072689 to 1121736
Data columns (total 51 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Brand                                       4382 non-null   object
 1   BrandInfo.BrandLocalName                    4382 non-null   object
 2   BrandInfo.BrandLogo                         4379 non-null   object
 3   BrandInfo.BrandName                         4382 non-null   object
 4   BrandLogo                                   4379 non-null   object
 5   BrandPartCode                               4382 non-null   object
 6   BulletPoints                                4088 non-null   object
 7   Category.CategoryID                         4382 non-null   int64
 8   Category.Name.Language                      4382 non-null   object
 9   Category.Name.Value                         4382 non-null   object
 10  Description.Disclaimer                      3884 non-null   object
 11  Description.ID                              3884 non-null   float64
 12  Description.LeafletPDFURL                   3884 non-null   object
 13  Description.LongDesc                        3884 non-null   object
 14  Description.LongProductName                 3884 non-null   object
 15  Description.ManualPDFSize                   3818 non-null   float64
 16  Description.ManualPDFURL                    3884 non-null   object
 17  Description.MiddleDesc                      3884 non-null   object
 18  Description.PDFSize                         3858 non-null   float64
 19  Description.URL                             3829 non-null   object
 20  Description.Updated                         3884 non-null   object
 21  EndOfLifeDate                               4382 non-null   object
 22  GTIN                                        4382 non-null   object
 23  IcecatId                                    4382 non-null   int64
 24  ProductFamily.ProductFamilyID               4382 non-null   int64
 25  ProductName                                 4382 non-null   object
 26  ProductSeries.SeriesID                      4382 non-null   int64
 27  ReleaseDate                                 4382 non-null   object
 28  SummaryDescription.LongSummaryDescription   4382 non-null   object
 29  SummaryDescription.ShortSummaryDescription  4382 non-null   object
 30  Title                                       4382 non-null   object
 31  Description.WarrantyInfo                    2225 non-null   object
 32  Description                                 498 non-null    object
 33  ProductFamily.Language                      1072 non-null   object
 34  ProductFamily.Value                         1072 non-null   object
 35  ProductSeries.Language                      705 non-null    object
 36  ProductSeries.Value                         705 non-null    object
 37  BulletPoints.BulletPointsId                 294 non-null    float64
 38  BulletPoints.Language                       294 non-null    object
 39  BulletPoints.Updated                        294 non-null    object
 40  BulletPoints.Values                         294 non-null    object
 41  VirtualCategory                             416 non-null    object
 42  SummaryDescription                          0 non-null      float64
 43  pathlist_ids                                4382 non-null   object
 44  pathlist_names                              4382 non-null   object
 45  num_levels                                  4382 non-null   int64
 46  path_3                                      4382 non-null   object
 47  level_4                                     2042 non-null   object
 48  A                                           4382 non-null   object
 49  B                                           4382 non-null   object
 50  C                                           4382 non-null   object
dtypes: float64(5), int64(5), object(41)
memory usage: 1.7+ MB

In [61]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names,num_levels,path_3,level_4,A,B,C
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...,3,Computers & Electronics > Computer Cables > Fi...,None,Computers & Electronics,Computer Cables,Fibre Optic Cables
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...,3,Computers & Electronics > Computers > PCs/Work...,None,Computers & Electronics,Computers,PCs/Workstations
904910,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,659501-BB1,[],2509,EN,Notebook Spare Parts,...,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...,4,Computers & Electronics > Computers > Notebook...,Notebook Spare Parts,Computers & Electronics,Computers,Notebook Parts & Accessories

In [71]:
#columns to keep
cols_needed = [
    "Brand",
    "BrandPartCode",
    "ProductName",
    "Description.LongProductName",
    "SummaryDescription.LongSummaryDescription",
    "Description.LongDesc",
    "A", "B", "C",
    "path_3"   # <-- Needed for evaluation
]

In [72]:
df_clean = df[cols_needed].copy()

In [73]:
# Build raw metadata text

def build_metadata(row):
    parts = []

    if pd.notna(row["Brand"]):
        parts.append(row["Brand"])

    if pd.notna(row["BrandPartCode"]):
        parts.append(row["BrandPartCode"])
        
    if pd.notna(row["ProductName"]):
        parts.append(row["ProductName"])

    if pd.notna(row["Description.LongProductName"]):
        parts.append(row["Description.LongProductName"])

    if pd.notna(row["SummaryDescription.LongSummaryDescription"]):
        parts.append(row["SummaryDescription.LongSummaryDescription"])

    if pd.notna(row["Description.LongDesc"]):
        parts.append(row["Description.LongDesc"])

    return " ".join(parts)

df_clean["metadata_text"] = df_clean.apply(build_metadata, axis=1)

In [74]:
df_clean

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...
...,...,...,...,...,...,...,...,...,...,...,...
231002,DELL,490-BDZR,490-BDZR,Radeon Pro WX 2100 2 GB 1 DP 2 mDP (Precision),"DELL 490-BDZR. Graphics processor family: AMD,...",The new Radeon™ Pro WX 2100 graphics card is t...,Computers & Electronics,Computer Components,System Components,Computers & Electronics > Computer Components ...,DELL 490-BDZR 490-BDZR Radeon Pro WX 2100 2 GB...
978436,Toshiba,SIC1094057LCD0,SIC1094057LCD0,Satellite A660 15.6 replacement laptop LCD screen,Toshiba SIC1094057LCD0. Type: Display. Display...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,Toshiba SIC1094057LCD0 SIC1094057LCD0 Satellit...
1101608,HP,6GV21PA,Elite Slice G2 with Microsoft Teams Rooms,None,HP Elite Slice G2 with Microsoft Teams Rooms,None,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,HP 6GV21PA Elite Slice G2 with Microsoft Teams...
66861,LG,T300.ADEUPK,T300,None,"LG T300. Display diagonal: 6.1 cm (2.4""), Disp...",None,Computers & Electronics,Telecom & Navigation,Smartphones,Computers & Electronics > Telecom & Navigation...,LG T300.ADEUPK T300 LG T300. Display diagonal:...
1121736,Eaton,1023113,Powerware 9155-10-NT-0,9155-10-NT-0,Eaton Powerware 9155-10-NT-0. Output power cap...,The Eaton 9155 UPS provides premium online bac...,Computers & Electronics,Batteries & Power Supplies,Uninterruptible Power Supplies (UPSs),Computers & Electronics > Batteries & Power Su...,Eaton 1023113 Powerware 9155-10-NT-0 9155-10-N...

In [75]:
import re

def clean_text(t):
    if not isinstance(t, str):
        return ""

    t = re.sub(r"<[^>]+>", " ", t)          # remove HTML tags
    t = re.sub(r"\s+", " ", t)              # collapse spaces
    t = t.replace("\xa0", " ")              # remove non-breaking
    t = t.strip()

    return t

df_clean["metadata_text_clean"] = df_clean["metadata_text"].apply(clean_text)

In [76]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...

In [77]:
from sentence_transformers import SentenceTransformer

texts = df_clean["metadata_text_clean"].fillna("").tolist()

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(
    texts,
    batch_size=256,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches:   0%|          | 0/18 [00:00<?, ?it/s]

In [78]:
from umap import UMAP

umap = UMAP(
    n_neighbors=15,
    min_dist=0.0,
    n_components=25,
    metric="cosine",
    random_state=42
)

reduced = umap.fit_transform(embeddings)

In [79]:
import hdbscan

clusterer_C = hdbscan.HDBSCAN(
    min_cluster_size=20,   # consistent with your min 20 products per C
    min_samples=1,
    metric="euclidean"
)

df_clean["C_id"] = clusterer_C.fit_predict(reduced)

print("All cluster IDs:", sorted(df_clean["C_id"].unique()))

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]

In [80]:
df_clean.head()

,Brand,BrandPartCode,ProductName,Description.LongProductName,SummaryDescription.LongSummaryDescription,Description.LongDesc,A,B,C,path_3,metadata_text,metadata_text_clean,C_id
1072689,ASUS,K31CD-IT049T,K31CD-IT049T,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,<b>Smart Multimedia Performance</b><br>\nVivoP...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,ASUS K31CD-IT049T K31CD-IT049T Intel Core i7-6...,45
906402,HP,686915-A41,686915-A41,Keyboard in midnight black finish with backlig...,HP 686915-A41. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 686915-A41 686915-A41 Keyboard in midnight ...,HP 686915-A41 686915-A41 Keyboard in midnight ...,75
411281,C2G,37745,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Get the performance you demand at a price that...,Computers & Electronics,Computer Cables,Fibre Optic Cables,Computers & Electronics > Computer Cables > Fi...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,C2G 37745 1m ST/SC Plenum-Rated 9/125 Duplex S...,33
1047582,Lenovo,109559U,C30,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",Lenovo ThinkStation C30. Processor frequency: ...,The C30 builds on its award-winning design as ...,Computers & Electronics,Computers,PCs/Workstations,Computers & Electronics > Computers > PCs/Work...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,Lenovo 109559U C30 Intel Xeon E5-2620 (15M Cac...,10
904910,HP,659501-BB1,659501-BB1,Keyboard in ash black for use in Israel (inclu...,HP 659501-BB1. Type: Keyboard. Keyboard langua...,,Computers & Electronics,Computers,Notebook Parts & Accessories,Computers & Electronics > Computers > Notebook...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,HP 659501-BB1 659501-BB1 Keyboard in ash black...,75

In [81]:
cluster_counts = df_clean["C_id"].value_counts().sort_values(ascending=False)

print(cluster_counts)

C_id
 14    361
-1     212
 10    181
 69    162
 45    158
      ...
 55     20
 12     20
 7      20
 46     20
 39     20
Name: count, Length: 78, dtype: int64

In [82]:
summary = (
    df_clean.groupby("C_id")
            .size()
            .reset_index(name="num_products")
            .sort_values("num_products", ascending=False)
)

print(summary)

    C_id  num_products
15    14           361
0     -1           212
11    10           181
70    69           162
46    45           158
..   ...           ...
8      7            20
44    43            20
47    46            20
13    12            20
56    55            20

[78 rows x 2 columns]

In [85]:
def make_evidence(subdf, max_chars=1000, max_items=30):
    items = []
    for txt in subdf["metadata_text_clean"].fillna("").tolist():
        t = txt.strip()
        if not t:
            continue
        items.append("- " + t[:200])
        if len(items) >= max_items:
            break

    blob = "\n".join(items)
    return blob[:max_chars]

In [86]:
import subprocess
import hashlib

def run_llm(prompt, model="llama3.2"):
    cmd = ["ollama", "run", model]
    result = subprocess.run(
        cmd,
        input=prompt.encode("utf-8"),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    stderr_text = result.stderr.decode("utf-8", errors="ignore")
    if stderr_text.strip():
        print("⚠ Ollama stderr:\n", stderr_text)
    stdout_text = result.stdout.decode("utf-8", errors="ignore")
    return stdout_text

label_cache = {}

def cached_llm_label(prompt, max_words=4, model="llama3.2"):
    key = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
    if key in label_cache:
        return label_cache[key]

    raw = run_llm(prompt, model=model)
    label = " ".join(raw.strip().split()[:max_words])
    label_cache[key] = label
    return label

In [88]:
C_name_map = {}
unique_cids = sorted(df_clean["C_id"].unique())
print("All cluster IDs:", unique_cids)

for cid in unique_cids:
    if cid == -1:   # skip noise
        continue

    subdf = df_clean[df_clean["C_id"] == cid]
    blob = make_evidence(subdf, max_chars=1000, max_items=30)

    if not blob:
        print(f"C_id {cid} → EMPTY SKIP")
        continue

    prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You receive a group of similar products and must assign a concise C-level category name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English
- Describing the type of product, not features.

[USER]
Here is a product group:

{blob}

Please respond with ONLY the category name. No explanation, no punctuation, no quotes.
"""

    label = cached_llm_label(prompt, max_words=4)
    C_name_map[cid] = label

    print(f"C_id {cid} → {label}")

df_clean["C_name"] = df_clean["C_id"].map(C_name_map)

All cluster IDs: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠼ ⠦
C_id 0 → Laptop displays
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 1 → Laptop Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
C_id 2 → Antivirus Software for Businesses
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 3 → laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼ ⠴
C_id 4 → Laptop Computers
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
C_id 5 → Laptop display replacements
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
C_id 6 → Extended Warranty Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 7 → Hardware Maintenance and Repair
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
C_id 8 → Lenovo Notebooks Motherboards
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
C_id 9 → Endpoint Antivirus Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴
C_id 10 → Laptop/Desktop Computers
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
C_id 11 → Graphics Processors
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
C_id 12 → Backup Software Compression Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸ ⠴
C_id 13 → Large Format Display Screens
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴
C_id 14 → Colour Toner Cartridges
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 15 → Extended Service and Support
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
C_id 16 → Hardware Repair Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 17 → Computer Hardware Support Services
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
C_id 18 → Security Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 19 → Headphones
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 20 → Extended Warranty Programs
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 21 → Fujitsu Premium Support Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 22 → Cyber Security Solutions
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
C_id 23 → Portable Laptops
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
C_id 24 → - Phone Cases -
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠼
C_id 25 → HDD Hard Drives
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 26 → Laptop Screens
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
C_id 27 → Security Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 28 → Endpoint Security Software
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
C_id 29 → Network Cables and Adapters
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 30 → Gaming Laptops
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
C_id 31 → Desktops Notebooks Gaming Pavilions
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
C_id 32 → Ethernet Cables
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 33 → Fiber Optic Cables
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
C_id 34 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 35 → Computer Monitors
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 36 → Computer Processors
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
C_id 37 → Hard Disk Drives
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
C_id 38 → Digital Cameras
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠼
C_id 39 → Acer Keyboards
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸ ⠴
C_id 40 → Computer Case
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 41 → - Stand Alone Racks
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
C_id 42 → Laptop
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 43 → Hard Disk Drives
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
C_id 44 → Acer Laptop Accessories
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
C_id 45 → Laptops
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 46 → Laptops
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
C_id 47 → Tablets and E-readers
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
C_id 48 → Computer motherboards for laptops
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
C_id 49 → Computer Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 50 → Fujitsu Replacement Parts for
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 51 → Laptop Batteries
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
C_id 52 → Graphics Cards
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠴
C_id 53 → Server Motherboards
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸ ⠼
C_id 54 → Portable USB Flash Drives
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
C_id 55 → Laptop displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 56 → Laptop Power Adapters
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 57 → Computer Accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼ ⠼
C_id 58 → PC Server RAM
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
C_id 59 → Server RAM Components
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸ ⠼
C_id 60 → External Hard Drives
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼ ⠴
C_id 61 → ThinkPad Keyboard Sleeves and
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸ ⠴
C_id 62 → Computer Keyboards
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼ ⠴
C_id 63 → Display Accessories
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼ ⠼
C_id 64 → Computer Components
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 65 → Computer Keyboards
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼ ⠼ ⠦
C_id 66 → Computer Server Hardware
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸ ⠼
C_id 67 → External Hard Drives and
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 68 → Desktop Computers
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸ ⠼
C_id 69 → Portable Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠴
C_id 70 → Laptop Displays
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 71 → Laptop Display Screens
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 72 → Laptop display replacement screens
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 73 → Computer Components
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
C_id 74 → Toshiba Laptop Keyboard
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 75 → Portable Keyboards
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
C_id 76 → Laptop Top Cover Keyboards

In [91]:
# Cluster C → B (B_id) and name B clusters
# Cluster C centroids into B clusters
from sklearn.cluster import AgglomerativeClustering
import numpy as np

# 1. Compute centroids for each C_id (exclude noise -1)
valid_cids = [c for c in df_clean["C_id"].unique() if c != -1]

C_centroids = []
C_labels = []

for cid in valid_cids:
    idx = df_clean["C_id"] == cid
    C_centroids.append(reduced[idx].mean(axis=0))   # 'reduced' = UMAP output
    C_labels.append(cid)

C_centroids = np.vstack(C_centroids)

# 2. Cluster centroids into B-level groups
agg_B = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.0
)
B_ids = agg_B.fit_predict(C_centroids)

# 3. Map C_id → B_id
C_to_B = dict(zip(C_labels, B_ids))
df_clean["B_id"] = df_clean["C_id"].map(lambda c: C_to_B.get(c, -1))

print(df_clean[["C_id", "C_name", "B_id"]].head())

         C_id                    C_name  B_id
1072689    45                   Laptops     3
906402     75        Portable Keyboards    20
411281     33        Fiber Optic Cables     8
1047582    10  Laptop/Desktop Computers    31
904910     75        Portable Keyboards    20

In [92]:
# Name each B_id using LLaMA (using its C_names)
def name_B_clusters(df):
    B_name_map = {}
    for bid in sorted(df["B_id"].unique()):
        if bid == -1:
            continue
        names = df.loc[df["B_id"] == bid, "C_name"].dropna().unique().tolist()
        sample_names = ", ".join(names[:10])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of C-level subcategories and must assign a concise B-level group name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English.

[USER]
Subcategories:
{sample_names}

Respond with ONLY the B-level category name."""
        label = cached_llm_label(prompt, max_words=4)
        B_name_map[bid] = label
        print(f"B_id {bid} → {label}")
    return B_name_map

B_name_map = name_B_clusters(df_clean)
df_clean["B_name"] = df_clean["B_id"].map(B_name_map)

⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼ ⠼
B_id 0 → Display Replacement Screens
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 1 → Endpoint Security Solutions
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
B_id 2 → Service and Maintenance Options
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 3 → Portable Personal Computers
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 4 → Post-Warranty Maintenance Plans
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 5 → Laptop Computer Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 6 → Product Maintenance Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 7 → Portable Computer Screens
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 8 → Network Cable Products
⚠ Ollama stderr:
 ⠋ ⠹ ⠸
B_id 9 → Portable Storage Devices
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
B_id 10 → Computer Input Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
B_id 11 → Personal Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹
B_id 12 → Desktop Computer Enclosures
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
B_id 13 → Visual Display Systems
⚠ Ollama stderr:
 ⠋ ⠙
B_id 14 → Power Supplies
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 15 → Electronics Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
B_id 16 → Computer Memory
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 17 → Computer Hardware Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 18 → Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 19 → Personal Computing Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
B_id 20 → Mobile Input Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 21 → Computer Input Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 22 → Storage Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 23 → Storage Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 24 → Computer Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 25 → Computer Monitors
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 26 → Desk Stands
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
B_id 27 → Display Technology
⚠ Ollama stderr:
 ⠋ ⠹
B_id 28 → Business Cyber Security Solutions
⚠ Ollama stderr:
 ⠙ ⠹
B_id 29 → Portable Gaming Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 30 → Portable Photography Equipment
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 31 → Personal Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 32 → Computer Monitors
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
B_id 33 → Audio Headgear
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠼
B_id 34 → Portable Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
B_id 35 → Computer Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 36 → Computer Hardware Maintenance
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 37 → Portable Computers
⚠ Ollama stderr:
 ⠙ ⠙
B_id 38 → Endpoint Security Solutions
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
B_id 39 → Computer Hardware
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
B_id 40 → Computer Components
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 41 → Device Accessories
⚠ Ollama stderr:
 ⠋ ⠹
B_id 42 → Data Management Solutions
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
B_id 43 → Computer Graphics Hardware
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
B_id 44 → Computer Input Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 45 → Computer Displays
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
B_id 46 → IT Hardware Maintenance
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠸
B_id 47 → Office Supplies
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 48 → Display Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 49 → Computer Security
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 50 → Hardware Peripherals
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
B_id 51 → Input Devices
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
B_id 52 → External Storage Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
B_id 53 → Information Protection Systems
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
B_id 54 → Personal Computers

In [ ]:
# 1. Compute centroids for each B_id
# Cluster B → A (A_id) and name A clusters
# Cluster B centroids into A groups
valid_bids = [b for b in df_clean["B_id"].unique() if b != -1]

B_centroids = []
B_labels = []

for bid in valid_bids:
    idx = df_clean["B_id"] == bid
    B_centroids.append(reduced[idx].mean(axis=0))
    B_labels.append(bid)

B_centroids = np.vstack(B_centroids)

# 2. Agglomerative clustering for A
agg_A = AgglomerativeClustering(
    n_clusters=None,
    distance_threshold=1.2
)
A_ids = agg_A.fit_predict(B_centroids)

# 3. Map B_id → A_id
B_to_A = dict(zip(B_labels, A_ids))
df_clean["A_id"] = df_clean["B_id"].map(lambda b: B_to_A.get(b, -1))

print(df_clean[["A_id", "B_id", "B_name"]].head())

         A_id  B_id                       B_name
1072689    31     3  Portable Personal Computers
906402     40    20         Mobile Input Devices
411281     35     8       Network Cable Products
1047582    29    31   Personal Computing Devices
904910     40    20         Mobile Input Devices

In [94]:
def name_A_clusters(df):
    A_name_map = {}
    for aid in sorted(df["A_id"].unique()):
        if aid == -1:
            continue
        names = df.loc[df["A_id"] == aid, "B_name"].dropna().unique().tolist()
        sample_names = ", ".join(names[:10])

        prompt = f"""
[SYSTEM]
You are an expert in product taxonomy.
You see a list of B-level categories and must assign a concise A-level (top level) group name.
The name MUST be:
- At most 4 words
- Generic (no brand names)
- In English.

[USER]
Subcategories:
{sample_names}

Respond with ONLY the A-level category name."""
        label = cached_llm_label(prompt, max_words=4)
        A_name_map[aid] = label
        print(f"A_id {aid} → {label}")
    return A_name_map

A_name_map = name_A_clusters(df_clean)
df_clean["A_name"] = df_clean["A_id"].map(A_name_map)

⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸ ⠴
A_id 0 → Technical Support Services
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 1 → Mobile Electronics Accessories
⚠ Ollama stderr:
 ⠋ ⠙ ⠹
A_id 2 → External Data Storage
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 3 → Security Information Management
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠸
A_id 4 → Computer Hardware and Cases
⚠ Ollama stderr:
 ⠋ ⠙ ⠸ ⠼
A_id 5 → Computer Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
A_id 6 → Display Technology
A_id 7 → Computer Peripherals
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 8 → Product Service Management
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
A_id 9 → Information Systems
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠸
A_id 10 → Display Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
A_id 11 → Mobile Computing Devices
⚠ Ollama stderr:
 ⠋ ⠙ ⠹ ⠸
A_id 12 → Computer Graphics Equipment
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 13 → Information Technology
⚠ Ollama stderr:
 ⠋ ⠹ ⠸ ⠼
A_id 14 → Laptops
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 15 → Input/Output Devices
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 16 → Computing Equipment Care
⚠ Ollama stderr:
 ⠋ ⠙ ⠹
A_id 17 → Hardware
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 18 → Computing Equipment
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 19 → Electronics
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 20 → Computer Hardware
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 21 → Computer Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 22 → Electrical Components
A_id 23 → Hardware
⚠ Ollama stderr:
 ⠙ ⠙ ⠹
A_id 24 → Computing Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 25 → Electronics Display
A_id 26 → Computer Peripherals
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 27 → Accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 28 → Computer Monitors
A_id 29 → Computing Equipment
⚠ Ollama stderr:
 ⠙ ⠹ ⠹
A_id 30 → Maintenance Services
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠸
A_id 31 → Laptops
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 32 → Handheld Electronic Devices
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 33 → Computer Components
⚠ Ollama stderr:
 ⠙ ⠹ ⠸ ⠼
A_id 34 → Network Security Systems
⚠ Ollama stderr:
 ⠙ ⠹ ⠹ ⠸
A_id 35 → Cable Communication
⚠ Ollama stderr:
 ⠙ ⠙ ⠸
A_id 36 → Electronics Display
⚠ Ollama stderr:
 ⠋ ⠹ ⠸
A_id 37 → Desk Organizers
⚠ Ollama stderr:
 ⠙ ⠙ ⠹ ⠼
A_id 38 → Computer Components
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠼
A_id 39 → Stationery
⚠ Ollama stderr:
 ⠋ ⠙ ⠸
A_id 40 → Input Devices for Mobile
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 41 → Headphones
A_id 42 → Computing Equipment
⚠ Ollama stderr:
 ⠋ ⠹ ⠹ ⠼
A_id 43 → Monitor Accessories
⚠ Ollama stderr:
 ⠙ ⠹ ⠸
A_id 44 → Computer Accessories
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 45 → External Hard Drives
⚠ Ollama stderr:
 ⠙ ⠙ ⠸ ⠸
A_id 46 → Cybersecurity Measures
A_id 47 → Display Devices
⚠ Ollama stderr:
 ⠋ ⠹ ⠹
A_id 48 → Computer Accessories

In [95]:
# Group by discovered A/B/C names and count products
grouped = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

def print_discovered_hierarchy(df_g):
    for a in df_g["A_name"].dropna().unique():
        print(f"A: {a}")
        print("=" * 80)
        tempA = df_g[df_g["A_name"] == a]

        for b in tempA["B_name"].dropna().unique():
            print(f"  B: {b}")
            tempB = tempA[tempA["B_name"] == b]

            for _, row in tempB.iterrows():
                c = row["C_name"]
                n = row["num_products"]
                print(f"    C: {c}  ({n} products)")
        print("\n")

print_discovered_hierarchy(grouped)

A: Accessories
================================================================================
  B: Device Accessories
    C: - Phone Cases -  (146 products)


A: Cable Communication
================================================================================
  B: Network Cable Products
    C: Network Cables and Adapters  (65 products)
    C: Fiber Optic Cables  (30 products)
    C: Ethernet Cables  (21 products)


A: Computer Accessories
================================================================================
  B: Electronics Peripherals
    C: Computer Components  (37 products)
    C: Display Accessories  (21 products)
  B: Input Devices
    C: Computer Keyboards  (87 products)


A: Computer Components
================================================================================
  B: Computer Hardware
    C: Computer Processors  (77 products)
  B: Computer Memory
    C: Server RAM Components  (30 products)
    C: PC Server RAM  (25 products)


A: Computer Graphics Equipment
================================================================================
  B: Computer Graphics Hardware
    C: Graphics Processors  (33 products)


A: Computer Hardware
================================================================================
  B: Laptop Computer Components
    C: Computer Components  (54 products)
    C: Acer Laptop Accessories  (29 products)
    C: Computer motherboards for laptops  (28 products)


A: Computer Hardware and Cases
================================================================================
  B: Computer Hardware Components
    C: Server Motherboards  (36 products)
    C: Graphics Cards  (31 products)
  B: Desktop Computer Enclosures
    C: Computer Case  (33 products)


A: Computer Monitors
================================================================================
  B: Computer Displays
    C: Laptop Screens  (59 products)


A: Computer Peripherals
================================================================================
  B: Computer Input Devices
    C: Computer Keyboards  (58 products)
    C: ThinkPad Keyboard Sleeves and  (46 products)
    C: Toshiba Laptop Keyboard  (27 products)
    C: Acer Keyboards  (20 products)
  B: Hardware Peripherals
    C: Computer Accessories  (30 products)


A: Computing Devices
================================================================================
  B: Personal Computers
    C: Portable Laptops  (40 products)


A: Computing Equipment
================================================================================
  B: Personal Computing Devices
    C: Laptop/Desktop Computers  (181 products)
    C: Portable Laptops  (162 products)
    C: Laptop Computers  (63 products)
    C: Desktop Computers  (31 products)


A: Computing Equipment Care
================================================================================
  B: Computer Hardware Maintenance
    C: Hardware Maintenance and Repair  (20 products)


A: Cybersecurity Measures
================================================================================
  B: Computer Security
    C: Security Software  (56 products)


A: Desk Organizers
================================================================================
  B: Desk Stands
    C: - Stand Alone Racks  (55 products)


A: Display Devices
================================================================================
  B: Computer Monitors
    C: Laptop displays  (51 products)
    C: Laptop display replacements  (36 products)


A: Display Technology
================================================================================
  B: Visual Display Systems
    C: Large Format Display Screens  (25 products)


A: Electrical Components
================================================================================
  B: Power Supplies
    C: Laptop Batteries  (83 products)


A: Electronics
================================================================================
  B: Computing Devices
    C: Laptops  (140 products)
    C: Desktops Notebooks Gaming Pavilions  (31 products)


A: Electronics Display
================================================================================
  B: Display Devices
    C: Computer Monitors  (148 products)
  B: Display Technology
    C: Laptop Displays  (39 products)


A: External Data Storage
================================================================================
  B: External Storage Devices
    C: HDD Hard Drives  (35 products)
  B: Storage Devices
    C: Hard Disk Drives  (79 products)
    C: Computer Server Hardware  (39 products)
    C: External Hard Drives and  (36 products)


A: External Hard Drives
================================================================================
  B: Portable Storage Devices
    C: External Hard Drives  (50 products)
    C: Portable USB Flash Drives  (35 products)


A: Handheld Electronic Devices
================================================================================
  B: Portable Gaming Devices
    C: Gaming Laptops  (66 products)


A: Hardware
================================================================================
  B: Computer Components
    C: Lenovo Notebooks Motherboards  (26 products)
    C: Fujitsu Replacement Parts for  (22 products)


A: Headphones
================================================================================
  B: Audio Headgear
    C: Headphones  (23 products)


A: Information Systems
================================================================================
  B: Data Management Solutions
    C: Backup Software Compression Software  (20 products)


A: Information Technology
================================================================================
  B: Business Cyber Security Solutions
    C: Antivirus Software for Businesses  (55 products)


A: Input Devices for Mobile
================================================================================
  B: Mobile Input Devices
    C: Laptop Top Cover Keyboards  (41 products)
    C: Portable Keyboards  (41 products)


A: Input/Output Devices
================================================================================
  B: Computer Peripherals
    C: Laptop Power Adapters  (62 products)


A: Laptops
================================================================================
  B: Portable Computers
    C: laptops  (142 products)
  B: Portable Personal Computers
    C: Laptops  (158 products)
    C: Laptop  (24 products)


A: Maintenance Services
================================================================================
  B: Service and Maintenance Options
    C: Hardware Repair Services  (73 products)
    C: Extended Service and Support  (41 products)


A: Mobile Computing Devices
================================================================================
  B: Portable Computer Screens
    C: Laptop Display Screens  (63 products)
    C: Laptop Displays  (22 products)
    C: Laptop displays  (20 products)


A: Mobile Electronics Accessories
================================================================================
  B: Portable Computing Devices
    C: Tablets and E-readers  (54 products)
    C: Laptops  (20 products)
  B: Portable Photography Equipment
    C: Digital Cameras  (34 products)


A: Monitor Accessories
================================================================================
  B: Display Replacement Screens
    C: Computer Components  (37 products)
    C: Laptop display replacement screens  (35 products)


A: Network Security Systems
================================================================================
  B: Endpoint Security Solutions
    C: Endpoint Antivirus Software  (21 products)


A: Product Service Management
================================================================================
  B: Product Maintenance Services
    C: Extended Warranty Services  (27 products)


A: Security Information Management
================================================================================
  B: Endpoint Security Solutions
    C: Security Software  (54 products)
    C: Endpoint Security Software  (21 products)
  B: Information Protection Systems
    C: Cyber Security Solutions  (30 products)


A: Stationery
================================================================================
  B: Office Supplies
    C: Colour Toner Cartridges  (361 products)


A: Technical Support Services
================================================================================
  B: IT Hardware Maintenance
    C: Computer Hardware Support Services  (24 products)
  B: Post-Warranty Maintenance Plans
    C: Extended Warranty Programs  (49 products)
    C: Fujitsu Premium Support Services  (46 products)

In [99]:
from anytree import Node, RenderTree

# Take unique combinations to avoid duplicate nodes
unique_paths = (
    df_clean[["A_name", "B_name", "C_name"]]
    .dropna()
    .drop_duplicates()
)

# Root node for the discovered taxonomy
root = Node("Computers & Electronics")

# Cache for created nodes to avoid re-creating them
node_cache = {}   # keys like ("A", A_name), ("B", A_name, B_name), ("C", A_name, B_name, C_name)

for _, row in unique_paths.iterrows():
    a = row["A_name"]
    b = row["B_name"]
    c = row["C_name"]

    # A level
    a_key = ("A", a)
    if a_key not in node_cache:
        node_cache[a_key] = Node(a, parent=root)

    a_node = node_cache[a_key]

    # B level
    b_key = ("B", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)

    b_node = node_cache[b_key]

    # C level
    c_key = ("C", a, b, c)
    if c_key not in node_cache:
        node_cache[c_key] = Node(c, parent=b_node)

# Pretty-print the tree
for pre, _, node in RenderTree(root):
    print(f"{pre}{node.name}")

Computers & Electronics
├── Laptops
│   ├── Portable Personal Computers
│   │   ├── Laptops
│   │   └── Laptop
│   └── Portable Computers
│       └── laptops
├── Input Devices for Mobile
│   └── Mobile Input Devices
│       ├── Portable Keyboards
│       └── Laptop Top Cover Keyboards
├── Cable Communication
│   └── Network Cable Products
│       ├── Fiber Optic Cables
│       ├── Ethernet Cables
│       └── Network Cables and Adapters
├── Computing Equipment
│   └── Personal Computing Devices
│       ├── Laptop/Desktop Computers
│       ├── Portable Laptops
│       ├── Desktop Computers
│       └── Laptop Computers
├── External Data Storage
│   ├── Storage Devices
│   │   ├── Computer Server Hardware
│   │   ├── Hard Disk Drives
│   │   └── External Hard Drives and
│   └── External Storage Devices
│       └── HDD Hard Drives
├── Computer Peripherals
│   ├── Computer Input Devices
│   │   ├── ThinkPad Keyboard Sleeves and
│   │   ├── Computer Keyboards
│   │   ├── Acer Keyboards
│   │   └── Toshiba Laptop Keyboard
│   └── Hardware Peripherals
│       └── Computer Accessories
├── Computer Accessories
│   ├── Electronics Peripherals
│   │   ├── Computer Components
│   │   └── Display Accessories
│   └── Input Devices
│       └── Computer Keyboards
├── Stationery
│   └── Office Supplies
│       └── Colour Toner Cartridges
├── Electronics Display
│   ├── Display Devices
│   │   └── Computer Monitors
│   └── Display Technology
│       └── Laptop Displays
├── External Hard Drives
│   └── Portable Storage Devices
│       ├── Portable USB Flash Drives
│       └── External Hard Drives
├── Maintenance Services
│   └── Service and Maintenance Options
│       ├── Extended Service and Support
│       └── Hardware Repair Services
├── Technical Support Services
│   ├── Post-Warranty Maintenance Plans
│   │   ├── Fujitsu Premium Support Services
│   │   └── Extended Warranty Programs
│   └── IT Hardware Maintenance
│       └── Computer Hardware Support Services
├── Handheld Electronic Devices
│   └── Portable Gaming Devices
│       └── Gaming Laptops
├── Headphones
│   └── Audio Headgear
│       └── Headphones
├── Security Information Management
│   ├── Information Protection Systems
│   │   └── Cyber Security Solutions
│   └── Endpoint Security Solutions
│       ├── Security Software
│       └── Endpoint Security Software
├── Computer Monitors
│   └── Computer Displays
│       └── Laptop Screens
├── Monitor Accessories
│   └── Display Replacement Screens
│       ├── Computer Components
│       └── Laptop display replacement screens
├── Cybersecurity Measures
│   └── Computer Security
│       └── Security Software
├── Computer Graphics Equipment
│   └── Computer Graphics Hardware
│       └── Graphics Processors
├── Mobile Electronics Accessories
│   ├── Portable Computing Devices
│   │   ├── Tablets and E-readers
│   │   └── Laptops
│   └── Portable Photography Equipment
│       └── Digital Cameras
├── Computer Hardware and Cases
│   ├── Computer Hardware Components
│   │   ├── Server Motherboards
│   │   └── Graphics Cards
│   └── Desktop Computer Enclosures
│       └── Computer Case
├── Display Devices
│   └── Computer Monitors
│       ├── Laptop displays
│       └── Laptop display replacements
├── Electronics
│   └── Computing Devices
│       ├── Laptops
│       └── Desktops Notebooks Gaming Pavilions
├── Computing Devices
│   └── Personal Computers
│       └── Portable Laptops
├── Computer Hardware
│   └── Laptop Computer Components
│       ├── Acer Laptop Accessories
│       ├── Computer motherboards for laptops
│       └── Computer Components
├── Computer Components
│   ├── Computer Hardware
│   │   └── Computer Processors
│   └── Computer Memory
│       ├── PC Server RAM
│       └── Server RAM Components
├── Hardware
│   └── Computer Components
│       ├── Fujitsu Replacement Parts for
│       └── Lenovo Notebooks Motherboards
├── Electrical Components
│   └── Power Supplies
│       └── Laptop Batteries
├── Mobile Computing Devices
│   └── Portable Computer Screens
│       ├── Laptop Displays
│       ├── Laptop displays
│       └── Laptop Display Screens
├── Input/Output Devices
│   └── Computer Peripherals
│       └── Laptop Power Adapters
├── Accessories
│   └── Device Accessories
│       └── - Phone Cases -
├── Desk Organizers
│   └── Desk Stands
│       └── - Stand Alone Racks
├── Information Technology
│   └── Business Cyber Security Solutions
│       └── Antivirus Software for Businesses
├── Network Security Systems
│   └── Endpoint Security Solutions
│       └── Endpoint Antivirus Software
├── Information Systems
│   └── Data Management Solutions
│       └── Backup Software Compression Software
├── Display Technology
│   └── Visual Display Systems
│       └── Large Format Display Screens
├── Computing Equipment Care
│   └── Computer Hardware Maintenance
│       └── Hardware Maintenance and Repair
└── Product Service Management
    └── Product Maintenance Services
        └── Extended Warranty Services

In [100]:
# Build clean A/B/C summary
abc_df = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

abc_df

,A_name,B_name,C_name,num_products
0,Accessories,Device Accessories,- Phone Cases -,146
3,Cable Communication,Network Cable Products,Network Cables and Adapters,65
2,Cable Communication,Network Cable Products,Fiber Optic Cables,30
1,Cable Communication,Network Cable Products,Ethernet Cables,21
4,Computer Accessories,Electronics Peripherals,Computer Components,37
...,...,...,...,...
71,Security Information Management,Information Protection Systems,Cyber Security Solutions,30
72,Stationery,Office Supplies,Colour Toner Cartridges,361
73,Technical Support Services,IT Hardware Maintenance,Computer Hardware Support Services,24
74,Technical Support Services,Post-Warranty Maintenance Plans,Extended Warranty Programs,49
75,Technical Support Services,Post-Warranty Maintenance Plans,Fujitsu Premium Support Services,46

In [101]:
df_clean["A_name"]
df_clean["B_name"]
df_clean["C_name"]

1072689                                Laptops
906402                      Portable Keyboards
411281                      Fiber Optic Cables
1047582               Laptop/Desktop Computers
904910                      Portable Keyboards
                          ...
231002                          Graphics Cards
978436                  Laptop Display Screens
1101608    Desktops Notebooks Gaming Pavilions
66861                    Tablets and E-readers
1121736                    - Stand Alone Racks
Name: C_name, Length: 4382, dtype: object

In [102]:
# Unique A levels
A_levels = sorted(abc_df["A_name"].unique())
print("A-level categories:")
for a in A_levels:
    print(" -", a)

# Unique B levels
B_levels = sorted(abc_df["B_name"].unique())
print("\nB-level categories:")
for b in B_levels:
    print(" -", b)

# Unique C levels
C_levels = sorted(abc_df["C_name"].unique())
print("\nC-level categories:")
for c in C_levels:
    print(" -", c)

A-level categories:
 - Accessories
 - Cable Communication
 - Computer Accessories
 - Computer Components
 - Computer Graphics Equipment
 - Computer Hardware
 - Computer Hardware and Cases
 - Computer Monitors
 - Computer Peripherals
 - Computing Devices
 - Computing Equipment
 - Computing Equipment Care
 - Cybersecurity Measures
 - Desk Organizers
 - Display Devices
 - Display Technology
 - Electrical Components
 - Electronics
 - Electronics Display
 - External Data Storage
 - External Hard Drives
 - Handheld Electronic Devices
 - Hardware
 - Headphones
 - Information Systems
 - Information Technology
 - Input Devices for Mobile
 - Input/Output Devices
 - Laptops
 - Maintenance Services
 - Mobile Computing Devices
 - Mobile Electronics Accessories
 - Monitor Accessories
 - Network Security Systems
 - Product Service Management
 - Security Information Management
 - Stationery
 - Technical Support Services

B-level categories:
 - Audio Headgear
 - Business Cyber Security Solutions
 - Computer Components
 - Computer Displays
 - Computer Graphics Hardware
 - Computer Hardware
 - Computer Hardware Components
 - Computer Hardware Maintenance
 - Computer Input Devices
 - Computer Memory
 - Computer Monitors
 - Computer Peripherals
 - Computer Security
 - Computing Devices
 - Data Management Solutions
 - Desk Stands
 - Desktop Computer Enclosures
 - Device Accessories
 - Display Devices
 - Display Replacement Screens
 - Display Technology
 - Electronics Peripherals
 - Endpoint Security Solutions
 - External Storage Devices
 - Hardware Peripherals
 - IT Hardware Maintenance
 - Information Protection Systems
 - Input Devices
 - Laptop Computer Components
 - Mobile Input Devices
 - Network Cable Products
 - Office Supplies
 - Personal Computers
 - Personal Computing Devices
 - Portable Computer Screens
 - Portable Computers
 - Portable Computing Devices
 - Portable Gaming Devices
 - Portable Personal Computers
 - Portable Photography Equipment
 - Portable Storage Devices
 - Post-Warranty Maintenance Plans
 - Power Supplies
 - Product Maintenance Services
 - Service and Maintenance Options
 - Storage Devices
 - Visual Display Systems

C-level categories:
 - - Phone Cases -
 - - Stand Alone Racks
 - Acer Keyboards
 - Acer Laptop Accessories
 - Antivirus Software for Businesses
 - Backup Software Compression Software
 - Colour Toner Cartridges
 - Computer Accessories
 - Computer Case
 - Computer Components
 - Computer Hardware Support Services
 - Computer Keyboards
 - Computer Monitors
 - Computer Processors
 - Computer Server Hardware
 - Computer motherboards for laptops
 - Cyber Security Solutions
 - Desktop Computers
 - Desktops Notebooks Gaming Pavilions
 - Digital Cameras
 - Display Accessories
 - Endpoint Antivirus Software
 - Endpoint Security Software
 - Ethernet Cables
 - Extended Service and Support
 - Extended Warranty Programs
 - Extended Warranty Services
 - External Hard Drives
 - External Hard Drives and
 - Fiber Optic Cables
 - Fujitsu Premium Support Services
 - Fujitsu Replacement Parts for
 - Gaming Laptops
 - Graphics Cards
 - Graphics Processors
 - HDD Hard Drives
 - Hard Disk Drives
 - Hardware Maintenance and Repair
 - Hardware Repair Services
 - Headphones
 - Laptop
 - Laptop Batteries
 - Laptop Computers
 - Laptop Display Screens
 - Laptop Displays
 - Laptop Power Adapters
 - Laptop Screens
 - Laptop Top Cover Keyboards
 - Laptop display replacement screens
 - Laptop display replacements
 - Laptop displays
 - Laptop/Desktop Computers
 - Laptops
 - Large Format Display Screens
 - Lenovo Notebooks Motherboards
 - Network Cables and Adapters
 - PC Server RAM
 - Portable Keyboards
 - Portable Laptops
 - Portable USB Flash Drives
 - Security Software
 - Server Motherboards
 - Server RAM Components
 - Tablets and E-readers
 - ThinkPad Keyboard Sleeves and
 - Toshiba Laptop Keyboard
 - laptops

In [103]:
print("A count:", abc_df["A_name"].nunique())
print("B count:", abc_df["B_name"].nunique())
print("C count:", abc_df["C_name"].nunique())

A count: 38
B count: 47
C count: 67

In [104]:
grouped = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

In [105]:
import re

def normalize_label(s):
    if not isinstance(s, str):
        return s
    s = s.strip()
    s = re.sub(r"\s+", " ", s)
    # basic title-case
    s = s.title()
    return s

df_clean["A_name_norm"] = df_clean["A_name"].apply(normalize_label)
df_clean["B_name_norm"] = df_clean["B_name"].apply(normalize_label)
df_clean["C_name_norm"] = df_clean["C_name"].apply(normalize_label)

grouped_norm = (
    df_clean
    .groupby(["A_name_norm", "B_name_norm", "C_name_norm"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name_norm", "B_name_norm", "num_products"], ascending=[True, True, False])
)

In [106]:
grouped_norm.to_csv("discovered_taxonomy_ABC_clean.csv", index=False)

In [107]:
df_clean["A_super"] = "Computers & Electronics"
from anytree import Node, RenderTree

# Select only unique combinations to avoid duplicate nodes
unique_paths = (
    df_clean[["A_super", "A_name", "B_name", "C_name"]]
    .dropna()
    .drop_duplicates()
)

# Create super-root
root = Node("Computers & Electronics")

# Cache to avoid duplicate nodes
node_cache = {}   # keys: ("A_super"), ("A_name", A_name), ("B_name", A_name, B_name), ...

for _, row in unique_paths.iterrows():
    a_super = row["A_super"]                # always Computers & Electronics
    a = row["A_name"]                       # discovered A
    b = row["B_name"]                       # discovered B
    c = row["C_name"]                       # discovered C

    # A_super level (root)
    super_key = ("A_super", a_super)
    if super_key not in node_cache:
        node_cache[super_key] = Node(a_super)
    super_node = node_cache[super_key]

    # A_name level
    a_key = ("A_name", a_super, a)
    if a_key not in node_cache:
        node_cache[a_key] = Node(a, parent=super_node)
    a_node = node_cache[a_key]

    # B_name level
    b_key = ("B_name", a, b)
    if b_key not in node_cache:
        node_cache[b_key] = Node(b, parent=a_node)
    b_node = node_cache[b_key]

    # C_name level
    c_key = ("C_name", a, b, c)
    if c_key not in node_cache:
        node_cache[c_key] = Node(c, parent=b_node)

# Print the hierarchy
for pre, _, node in RenderTree(super_node):
    print(f"{pre}{node.name}")

Computers & Electronics
├── Laptops
│   ├── Portable Personal Computers
│   │   ├── Laptops
│   │   └── Laptop
│   └── Portable Computers
│       └── laptops
├── Input Devices for Mobile
│   └── Mobile Input Devices
│       ├── Portable Keyboards
│       └── Laptop Top Cover Keyboards
├── Cable Communication
│   └── Network Cable Products
│       ├── Fiber Optic Cables
│       ├── Ethernet Cables
│       └── Network Cables and Adapters
├── Computing Equipment
│   └── Personal Computing Devices
│       ├── Laptop/Desktop Computers
│       ├── Portable Laptops
│       ├── Desktop Computers
│       └── Laptop Computers
├── External Data Storage
│   ├── Storage Devices
│   │   ├── Computer Server Hardware
│   │   ├── Hard Disk Drives
│   │   └── External Hard Drives and
│   └── External Storage Devices
│       └── HDD Hard Drives
├── Computer Peripherals
│   ├── Computer Input Devices
│   │   ├── ThinkPad Keyboard Sleeves and
│   │   ├── Computer Keyboards
│   │   ├── Acer Keyboards
│   │   └── Toshiba Laptop Keyboard
│   └── Hardware Peripherals
│       └── Computer Accessories
├── Computer Accessories
│   ├── Electronics Peripherals
│   │   ├── Computer Components
│   │   └── Display Accessories
│   └── Input Devices
│       └── Computer Keyboards
├── Stationery
│   └── Office Supplies
│       └── Colour Toner Cartridges
├── Electronics Display
│   ├── Display Devices
│   │   └── Computer Monitors
│   └── Display Technology
│       └── Laptop Displays
├── External Hard Drives
│   └── Portable Storage Devices
│       ├── Portable USB Flash Drives
│       └── External Hard Drives
├── Maintenance Services
│   └── Service and Maintenance Options
│       ├── Extended Service and Support
│       └── Hardware Repair Services
├── Technical Support Services
│   ├── Post-Warranty Maintenance Plans
│   │   ├── Fujitsu Premium Support Services
│   │   └── Extended Warranty Programs
│   └── IT Hardware Maintenance
│       └── Computer Hardware Support Services
├── Handheld Electronic Devices
│   └── Portable Gaming Devices
│       └── Gaming Laptops
├── Headphones
│   └── Audio Headgear
│       └── Headphones
├── Security Information Management
│   ├── Information Protection Systems
│   │   └── Cyber Security Solutions
│   └── Endpoint Security Solutions
│       ├── Security Software
│       └── Endpoint Security Software
├── Computer Monitors
│   └── Computer Displays
│       └── Laptop Screens
├── Monitor Accessories
│   └── Display Replacement Screens
│       ├── Computer Components
│       └── Laptop display replacement screens
├── Cybersecurity Measures
│   └── Computer Security
│       └── Security Software
├── Computer Graphics Equipment
│   └── Computer Graphics Hardware
│       └── Graphics Processors
├── Mobile Electronics Accessories
│   ├── Portable Computing Devices
│   │   ├── Tablets and E-readers
│   │   └── Laptops
│   └── Portable Photography Equipment
│       └── Digital Cameras
├── Computer Hardware and Cases
│   ├── Computer Hardware Components
│   │   ├── Server Motherboards
│   │   └── Graphics Cards
│   └── Desktop Computer Enclosures
│       └── Computer Case
├── Display Devices
│   └── Computer Monitors
│       ├── Laptop displays
│       └── Laptop display replacements
├── Electronics
│   └── Computing Devices
│       ├── Laptops
│       └── Desktops Notebooks Gaming Pavilions
├── Computing Devices
│   └── Personal Computers
│       └── Portable Laptops
├── Computer Hardware
│   └── Laptop Computer Components
│       ├── Acer Laptop Accessories
│       ├── Computer motherboards for laptops
│       └── Computer Components
├── Computer Components
│   ├── Computer Hardware
│   │   └── Computer Processors
│   └── Computer Memory
│       ├── PC Server RAM
│       └── Server RAM Components
├── Hardware
│   └── Computer Components
│       ├── Fujitsu Replacement Parts for
│       └── Lenovo Notebooks Motherboards
├── Electrical Components
│   └── Power Supplies
│       └── Laptop Batteries
├── Mobile Computing Devices
│   └── Portable Computer Screens
│       ├── Laptop Displays
│       ├── Laptop displays
│       └── Laptop Display Screens
├── Input/Output Devices
│   └── Computer Peripherals
│       └── Laptop Power Adapters
├── Accessories
│   └── Device Accessories
│       └── - Phone Cases -
├── Desk Organizers
│   └── Desk Stands
│       └── - Stand Alone Racks
├── Information Technology
│   └── Business Cyber Security Solutions
│       └── Antivirus Software for Businesses
├── Network Security Systems
│   └── Endpoint Security Solutions
│       └── Endpoint Antivirus Software
├── Information Systems
│   └── Data Management Solutions
│       └── Backup Software Compression Software
├── Display Technology
│   └── Visual Display Systems
│       └── Large Format Display Screens
├── Computing Equipment Care
│   └── Computer Hardware Maintenance
│       └── Hardware Maintenance and Repair
└── Product Service Management
    └── Product Maintenance Services
        └── Extended Warranty Services

In [109]:
# Build a clean summary A/B/C table with product counts
taxonomy_summary = (
    df_clean
    .groupby(["A_name", "B_name", "C_name"])
    .size()
    .reset_index(name="num_products")
    .sort_values(["A_name", "B_name", "num_products"], ascending=[True, True, False])
)

taxonomy_summary.head(20)

,A_name,B_name,C_name,num_products
0,Accessories,Device Accessories,- Phone Cases -,146
3,Cable Communication,Network Cable Products,Network Cables and Adapters,65
2,Cable Communication,Network Cable Products,Fiber Optic Cables,30
1,Cable Communication,Network Cable Products,Ethernet Cables,21
4,Computer Accessories,Electronics Peripherals,Computer Components,37
5,Computer Accessories,Electronics Peripherals,Display Accessories,21
6,Computer Accessories,Input Devices,Computer Keyboards,87
7,Computer Components,Computer Hardware,Computer Processors,77
9,Computer Components,Computer Memory,Server RAM Components,30
8,Computer Components,Computer Memory,PC Server RAM,25
10,Computer Graphics Equipment,Computer Graphics Hardware,Graphics Processors,33
12,Computer Hardware,Laptop Computer Components,Computer Components,54
11,Computer Hardware,Laptop Computer Components,Acer Laptop Accessories,29
13,Computer Hardware,Laptop Computer Components,Computer motherboards for laptops,28
15,Computer Hardware and Cases,Computer Hardware Components,Server Motherboards,36
14,Computer Hardware and Cases,Computer Hardware Components,Graphics Cards,31
16,Computer Hardware and Cases,Desktop Computer Enclosures,Computer Case,33
17,Computer Monitors,Computer Displays,Laptop Screens,59
19,Computer Peripherals,Computer Input Devices,Computer Keyboards,58
20,Computer Peripherals,Computer Input Devices,ThinkPad Keyboard Sleeves and,46