In [1]:
import os
import json
import hashlib
import random
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

from sentence_transformers import SentenceTransformer
from umap import UMAP
import hdbscan
from sklearn.cluster import AgglomerativeClustering
from anytree import Node, RenderTree

warnings.filterwarnings("ignore")

d:\git\Taxonomy_Buidling_Textual_Corpora\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_json("D:/git/Taxonomy_Buidling_Textual_Corpora/data/icecat_data_train.json")

In [3]:
df_small = df.head(1000).copy()
df_small.shape

(1000, 45)

In [4]:
df_small

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,...,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,...,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,686915-A41,[],2509,EN,Notebook Spare Parts,...,None,None,NaN,None,None,None,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,...,None,None,NaN,None,None,None,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,...,None,None,NaN,None,None,None,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,...,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392099,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37079,[],1056,EN,Flat Panel Wall Mounts,...,None,None,NaN,None,None,None,None,NaN,2833>220>1056,Computers & Electronics>TVs & Monitors>Flat Pa...
1008636,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,SIC1297184LCD0,[],2509,EN,Notebook Spare Parts,...,None,None,NaN,None,None,None,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Par...
581225,Middle Atlantic Products,,https://images.icecat.biz/img/brand/thumb/2702...,Middle Atlantic Products,https://images.icecat.biz/img/brand/thumb/2702...,WUSS14,None,1532,EN,Rack Accessories,...,None,None,1967411.0,EN,2019-04-17 12:12:17,[Holds components too wide for standard racksh...,None,NaN,2833>106>236>1532,Computers & Electronics>Computer Components>Ch...
301585,Philips,,https://images.icecat.biz/img/brand/thumb/25_b...,Philips,https://images.icecat.biz/img/brand/thumb/25_b...,55PUS6272/12,None,1584,EN,TVs,...,None,None,417921.0,EN,2018-02-01 09:50:04,"[139 cm (55""), 4K Ultra-HD LED TV, Quad Core, ...",None,NaN,2833>220>1584,Computers & Electronics>TVs & Monitors>TVs
1094976,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,4RT80EA,[],153,EN,PCs/Workstations,...,EN,690,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...

STEP 1 — Extract A, B, C Taxonomy Levels

Use a robust splitter that handles:
2-level
3-level
4+ level paths
(some Icecat paths have 4 levels!)

In [54]:
def split_taxonomy(path):
    """
    Handle 2, 3, 4+ levels in pathlist_names.
    A = root
    B = second level
    C = everything below B (joined back with '>').
    """
    if pd.isna(path):
        return pd.Series([None, None, None])

    parts = [p.strip() for p in str(path).split(">")]

    # A > B
    if len(parts) == 2:
        return pd.Series([parts[0], parts[1], None])

    # A > B > C
    if len(parts) == 3:
        return pd.Series([parts[0], parts[1], parts[2]])

    # A > B > C > D --> treat C as "C > D"
    return pd.Series([parts[0], parts[1], ">".join(parts[2:])])

In [55]:
df_small[["A", "B", "C"]] = df_small["pathlist_names"].apply(split_taxonomy)
df_small[["pathlist_names", "A", "B", "C"]].head(10)

,pathlist_names,A,B,C
1072689,Computers & Electronics>Computers>PCs/Workstat...,Computers & Electronics,Computers,PCs/Workstations
906402,Computers & Electronics>Computers>Notebook Par...,Computers & Electronics,Computers,Notebook Parts & Accessories>Notebook Spare Parts
411281,Computers & Electronics>Computer Cables>Fibre ...,Computers & Electronics,Computer Cables,Fibre Optic Cables
425903,Computers & Electronics>Computers>Handheld Mob...,Computers & Electronics,Computers,Handheld Mobile Computer Spare Parts
1047582,Computers & Electronics>Computers>PCs/Workstat...,Computers & Electronics,Computers,PCs/Workstations
904910,Computers & Electronics>Computers>Notebook Par...,Computers & Electronics,Computers,Notebook Parts & Accessories>Notebook Spare Parts
157385,Computers & Electronics>Software>Software Lice...,Computers & Electronics,Software,Software Licenses/Upgrades
934548,Computers & Electronics>Computers>Notebook Par...,Computers & Electronics,Computers,Notebook Parts & Accessories>Notebook Spare Parts
876762,Computers & Electronics>Computers>Notebook Par...,Computers & Electronics,Computers,Notebook Parts & Accessories>Notebook Spare Parts
397028,Computers & Electronics>Telecom & Navigation>M...,Computers & Electronics,Telecom & Navigation,Mobile Phone Spare Parts

In [56]:
# df_small = first 1000 rows (for now)
# and you already ran:
df_small[["A", "B", "C"]] = df_small["pathlist_names"].apply(split_taxonomy)

In [57]:
#Global counts: how many A, B, C?
print("Total A-level categories:", df_small["A"].nunique())
print("Total B-level categories:", df_small["B"].nunique())
print("Total C-level categories:", df_small["C"].nunique())

Total A-level categories: 1
Total B-level categories: 16
Total C-level categories: 143

In [58]:
#For each A: how many B and C?
# B per A
A_B_counts = (
    df_small.groupby("A")["B"]
    .nunique()
    .reset_index(name="num_B_under_A")
)

# C per A
A_C_counts = (
    df_small.groupby("A")["C"]
    .nunique()
    .reset_index(name="num_C_under_A")
)

A_summary = A_B_counts.merge(A_C_counts, on="A")
A_summary

                         A  num_B_under_A  num_C_under_A
0  Computers & Electronics             16            143

In [59]:
print("=== A-level summary (how many B and C under each A) ===")
for _, row in A_summary.iterrows():
    print(f"A: {row['A']}")
    print(f"  B-level subcategories: {row['num_B_under_A']}")
    print(f"  C-level subcategories: {row['num_C_under_A']}")
    print()

=== A-level summary (how many B and C under each A) ===
A: Computers & Electronics
  B-level subcategories: 16
  C-level subcategories: 143

In [50]:
# For each B: how many C and how many products?
# C per B (within each A)
B_C_counts = (
    df_small.groupby(["A", "B"])["C"]
    .nunique()
    .reset_index(name="num_C_under_B")
)

# products per B
B_prod_counts = (
    df_small.groupby(["A", "B"])["ProductName"]
    .count()
    .reset_index(name="num_products_under_B")
)

B_summary = B_C_counts.merge(B_prod_counts, on=["A", "B"])
B_summary

,A,B,num_C_under_B,num_products_under_B
0,Computers & Electronics,Batteries & Power Supplies,7,27
1,Computers & Electronics,Computer Cables,11,42
2,Computers & Electronics,Computer Components,14,65
3,Computers & Electronics,Computers,15,450
4,Computers & Electronics,Consumer Audio & Video Equipment,13,25
5,Computers & Electronics,Data Input Devices,3,25
6,Computers & Electronics,Data Storage,11,59
7,Computers & Electronics,Networking,7,11
8,Computers & Electronics,Office Electronics,1,1
9,Computers & Electronics,Photo & Video Equipment,8,14
10,Computers & Electronics,Printers & Scanners,16,75
11,Computers & Electronics,Projectors,7,14
12,Computers & Electronics,Software,8,55
13,Computers & Electronics,TVs & Monitors,11,46
14,Computers & Electronics,Telecom & Navigation,9,34
15,Computers & Electronics,Warranty & Support,2,57

In [61]:
print("=== B-level summary (per A) ===")
for (a, b), sub in B_summary.groupby(["A", "B"]):
    row = sub.iloc[0]
    print(f"A: {a}")
    print(f"  B: {b}")
    print(f"    #C-level subcategories: {row['num_C_under_B']}")
    print(f"    #products (total under this B): {row['num_products_under_B']}")
    print()

=== B-level summary (per A) ===
A: Computers & Electronics
  B: Batteries & Power Supplies
    #C-level subcategories: 7
    #products (total under this B): 27

A: Computers & Electronics
  B: Computer Cables
    #C-level subcategories: 11
    #products (total under this B): 42

A: Computers & Electronics
  B: Computer Components
    #C-level subcategories: 14
    #products (total under this B): 65

A: Computers & Electronics
  B: Computers
    #C-level subcategories: 15
    #products (total under this B): 450

A: Computers & Electronics
  B: Consumer Audio & Video Equipment
    #C-level subcategories: 13
    #products (total under this B): 25

A: Computers & Electronics
  B: Data Input Devices
    #C-level subcategories: 3
    #products (total under this B): 25

A: Computers & Electronics
  B: Data Storage
    #C-level subcategories: 11
    #products (total under this B): 59

A: Computers & Electronics
  B: Networking
    #C-level subcategories: 7
    #products (total under this B): 11

A: Computers & Electronics
  B: Office Electronics
    #C-level subcategories: 1
    #products (total under this B): 1

A: Computers & Electronics
  B: Photo & Video Equipment
    #C-level subcategories: 8
    #products (total under this B): 14

A: Computers & Electronics
  B: Printers & Scanners
    #C-level subcategories: 16
    #products (total under this B): 75

A: Computers & Electronics
  B: Projectors
    #C-level subcategories: 7
    #products (total under this B): 14

A: Computers & Electronics
  B: Software
    #C-level subcategories: 8
    #products (total under this B): 55

A: Computers & Electronics
  B: TVs & Monitors
    #C-level subcategories: 11
    #products (total under this B): 46

A: Computers & Electronics
  B: Telecom & Navigation
    #C-level subcategories: 9
    #products (total under this B): 34

A: Computers & Electronics
  B: Warranty & Support
    #C-level subcategories: 2
    #products (total under this B): 57

In [64]:
#For each C: how many products?
C_prod_counts = (
    df_small.groupby(["A", "B", "C"])["ProductName"]
    .count()
    .reset_index(name="num_products_under_C")
)

C_prod_counts  # inspect first 20

,A,B,C,num_products_under_C
0,Computers & Electronics,Batteries & Power Supplies,Household Batteries,2
1,Computers & Electronics,Batteries & Power Supplies,Power Adapters & Inverters,14
2,Computers & Electronics,Batteries & Power Supplies,Power Banks,1
3,Computers & Electronics,Batteries & Power Supplies,Power Distribution Units (PDUs),1
4,Computers & Electronics,Batteries & Power Supplies,Power Supply Units,3
...,...,...,...,...
138,Computers & Electronics,Telecom & Navigation,Screen Protectors,8
139,Computers & Electronics,Telecom & Navigation,Smartphones,6
140,Computers & Electronics,Telecom & Navigation,Telephony Equipment>Telephones,2
141,Computers & Electronics,Warranty & Support,IT Support Services,2
142,Computers & Electronics,Warranty & Support,Warranty & Support Extensions,55

In [62]:
print("=== C-level summary (A → B → C → #products) ===")
for (a, b), sub in C_prod_counts.groupby(["A", "B"]):
    print(f"\nA: {a}")
    print(f"  B: {b}")
    for _, row in sub.iterrows():
        print(f"    C: {row['C']}  ({row['num_products_under_C']} products)")

=== C-level summary (A → B → C → #products) ===

A: Computers & Electronics
  B: Batteries & Power Supplies
    C: Household Batteries  (2 products)
    C: Power Adapters & Inverters  (14 products)
    C: Power Banks  (1 products)
    C: Power Distribution Units (PDUs)  (1 products)
    C: Power Supply Units  (3 products)
    C: UPS Batteries  (1 products)
    C: Uninterruptible Power Supplies (UPSs)  (5 products)

A: Computers & Electronics
  B: Computer Cables
    C: Cable Interface/Gender Adapters  (4 products)
    C: Cable Protectors  (1 products)
    C: DisplayPort Cables  (1 products)
    C: Fibre Optic Cables  (7 products)
    C: HDMI Cables  (2 products)
    C: Networking Cables  (18 products)
    C: Power Cables  (3 products)
    C: SCSI Cables  (1 products)
    C: USB Cables  (3 products)
    C: Video Cable Adapters  (1 products)
    C: Wire Connectors  (1 products)

A: Computers & Electronics
  B: Computer Components
    C: Chassis Components>Computer Case Parts  (1 products)
    C: Chassis Components>Computer Cases  (2 products)
    C: Chassis Components>Computer Cooling Components  (1 products)
    C: Chassis Components>Mounting Kits  (3 products)
    C: Chassis Components>Rack Accessories  (3 products)
    C: Chassis Components>Rack Cabinets  (3 products)
    C: Interface Components>Console Servers  (1 products)
    C: System Components>Graphics Cards  (10 products)
    C: System Components>Interface Cards/Adapters  (2 products)
    C: System Components>Memory Modules  (20 products)
    C: System Components>Motherboards  (4 products)
    C: System Components>Networking Cards  (2 products)
    C: System Components>Processors  (12 products)
    C: System Components>Server/Workstation Motherboards  (1 products)

A: Computers & Electronics
  B: Computers
    C: All-in-One PCs/Workstations  (10 products)
    C: Backpack PCs  (1 products)
    C: Handheld Device Accessories  (2 products)
    C: Handheld Mobile Computer Spare Parts  (1 products)
    C: Notebook Parts & Accessories>Notebook Accessories  (3 products)
    C: Notebook Parts & Accessories>Notebook Cases  (6 products)
    C: Notebook Parts & Accessories>Notebook Docks & Port Replicators  (4 products)
    C: Notebook Parts & Accessories>Notebook Spare Parts  (202 products)
    C: Notebooks  (163 products)
    C: PCs/Workstations  (38 products)
    C: Server Barebones  (1 products)
    C: Servers  (3 products)
    C: Stylus Pens  (1 products)
    C: Tablet Cases  (3 products)
    C: Tablets  (12 products)

A: Computers & Electronics
  B: Consumer Audio & Video Equipment
    C: AV Extenders  (3 products)
    C: Audio Equipment Parts & Accessories>Headphones  (4 products)
    C: Cassette Players  (1 products)
    C: Digital Media Players  (1 products)
    C: Home Cinema Systems  (2 products)
    C: Loudspeakers  (2 products)
    C: MP3/MP4 Player Cases  (1 products)
    C: MP3/MP4 Players  (2 products)
    C: Portable Speakers  (3 products)
    C: Public Address (PA) Systems  (1 products)
    C: Radios  (1 products)
    C: Remote Controls  (2 products)
    C: Soundbar Speakers  (2 products)

A: Computers & Electronics
  B: Data Input Devices
    C: KVM Switches  (3 products)
    C: Keyboards  (17 products)
    C: Mice  (5 products)

A: Computers & Electronics
  B: Data Storage
    C: Data Storage Devices>Card Readers  (1 products)
    C: Data Storage Devices>External Hard Drives  (4 products)
    C: Data Storage Devices>Internal Hard Drives  (21 products)
    C: Data Storage Devices>Internal Solid State Drives  (16 products)
    C: Data Storage Devices>Memory Cards  (3 products)
    C: Data Storage Devices>NAS & Storage Servers  (4 products)
    C: Data Storage Devices>Optical Disc Drives  (1 products)
    C: Data Storage Devices>Tape Drives  (1 products)
    C: Data Storage Devices>USB Flash Drives  (4 products)
    C: Data Storage Mediums>Blank CDs  (2 products)
    C: Data Storage Mediums>Optical Disc Cases  (2 products)

A: Computers & Electronics
  B: Networking
    C: Network Switches  (3 products)
    C: Network Transceiver Modules  (2 products)
    C: Patch Panels  (1 products)
    C: PowerLine Network Adapters  (2 products)
    C: Remote Management Adapters  (1 products)
    C: WLAN Access Points  (1 products)
    C: Wireless Routers  (1 products)

A: Computers & Electronics
  B: Office Electronics
    C: Calculators  (1 products)

A: Computers & Electronics
  B: Photo & Video Equipment
    C: Camera Accessories>Camera Cases  (1 products)
    C: Camera Accessories>Lens Hoods  (1 products)
    C: Cameras & Camcorders>Action Sports Cameras  (1 products)
    C: Cameras & Camcorders>Camcorders  (2 products)
    C: Cameras & Camcorders>Camera/Camcorder Batteries  (1 products)
    C: Cameras & Camcorders>Digital Cameras  (4 products)
    C: Cameras & Camcorders>Webcams  (2 products)
    C: Photographic Filmmaking Supplies>Photo Paper  (2 products)

A: Computers & Electronics
  B: Printers & Scanners
    C: Print & Scan Accessories>Fusers  (1 products)
    C: Print & Scan Accessories>Printer/Scanner Spare Parts  (7 products)
    C: Print & Scan Accessories>Trays & Feeders  (4 products)
    C: Printing Equipment>Dot Matrix Printers  (1 products)
    C: Printing Equipment>Laser Printers  (6 products)
    C: Printing Equipment>Multifunctionals  (5 products)
    C: Printing Equipment>POS Printers  (1 products)
    C: Printing Media>Large Format Media  (2 products)
    C: Printing Media>Printer Labels  (2 products)
    C: Printing Media>Printing Paper  (1 products)
    C: Printing Supplies>Ink Cartridges  (16 products)
    C: Printing Supplies>Printer Kits  (3 products)
    C: Printing Supplies>Printer Ribbons  (1 products)
    C: Printing Supplies>Printer Rollers  (1 products)
    C: Printing Supplies>Toner Cartridges  (23 products)
    C: Scanning Equipment>Scanners  (1 products)

A: Computers & Electronics
  B: Projectors
    C: Data Projectors  (2 products)
    C: Projection Lenses  (1 products)
    C: Projection Screens  (4 products)
    C: Projector Accessories  (1 products)
    C: Projector Lamps  (3 products)
    C: Projector Mount Accessories  (1 products)
    C: Projector Mounts  (2 products)

A: Computers & Electronics
  B: Software
    C: Antivirus Security Software  (11 products)
    C: Computer Utilities>General Utility Software  (1 products)
    C: Computer Utilities>Printer Software  (1 products)
    C: Computer Utilities>Storage Software  (1 products)
    C: Multimedia Software>Graphics Software  (1 products)
    C: Multimedia Software>Video Software  (1 products)
    C: Networking Software>Virtualization Software  (1 products)
    C: Software Licenses/Upgrades  (38 products)

A: Computers & Electronics
  B: TVs & Monitors
    C: Computer Monitors  (8 products)
    C: Display Privacy Filters  (2 products)
    C: Flat Panel Floor Stands  (1 products)
    C: Flat Panel Mount Accessories  (1 products)
    C: Flat Panel Spare Parts  (6 products)
    C: Flat Panel Wall Mounts  (3 products)
    C: Signage Displays  (3 products)
    C: TVs  (19 products)
    C: Touch Screen Monitors  (1 products)
    C: Touch Screen Overlays  (1 products)
    C: Video Splitters  (1 products)

A: Computers & Electronics
  B: Telecom & Navigation
    C: Holders  (2 products)
    C: Mobile Device Keyboards  (1 products)
    C: Mobile Headsets  (2 products)
    C: Mobile Phone Cases  (9 products)
    C: Mobile Phone Spare Parts  (2 products)
    C: Mobile Phones  (2 products)
    C: Screen Protectors  (8 products)
    C: Smartphones  (6 products)
    C: Telephony Equipment>Telephones  (2 products)

A: Computers & Electronics
  B: Warranty & Support
    C: IT Support Services  (2 products)
    C: Warranty & Support Extensions  (55 products)

In [63]:
def print_full_hierarchy(df):
    # Loop over A-level categories
    for a in df["A"].dropna().unique():
        print(f"\nA: {a}")
        print("=" * 80)

        df_a = df[df["A"] == a]

        # Loop over B-level categories within this A
        for b in df_a["B"].dropna().unique():
            print(f"  B: {b}")

            df_b = df_a[df_a["B"] == b]

            # Loop over C-level categories within this B
            for c in df_b["C"].dropna().unique():
                df_c = df_b[df_b["C"] == c]

                print(f"    C: {c}  ({len(df_c)} products)")

                # Print product names under this C
                for pname in df_c["ProductName"].dropna().tolist():
                    print(f"        • {pname}")

            print()  # space after each B section

# Run it on the sample
print_full_hierarchy(df_small)

A: Computers & Electronics
================================================================================
  B: Computers
    C: PCs/Workstations  (38 products)
        • K31CD-IT049T
        • C30
        • UN42-M031M
        • P310
        • 875-1303ng
        • 400 G6
        • M910q
        • 3 VR7RD-037US
        • 400 G4 + EliteDisplay E223
        • ProDesk 600 G3 Desktop Mini PC
        • G11CD-FR139T
        • S2660G
        • h8-1500et
        • Compaq Presario SG3320IL Desktop PC
        • TC-710
        • XC605
        • DM500T4Z
        • M32CD-IT051T
        • A 8RC-290FR
        • Z640
        • Compaq 6200 Pro Microtower PC (ENERGY STAR)
        • Z440
        • P500
        • 550-131ns
        • 5680
        • P420 E85+
        • M83
        • 595-p0059nl
        • K20CD-KR002D
        • 690-0043ns
        • Aegis Ti3 VR7RD
        • S510 + 19.5" LED ThinkVision E2054
        • 800 G4 + LaserJet Pro M15w
        • 800 G4
        • M73
        • Y700-34ISH
        • M770
        • 690-0999nf
    C: Notebook Parts & Accessories>Notebook Spare Parts  (202 products)
        • 686915-A41
        • 659501-BB1
        • 00HT024
        • 448002-001
        • Top Cover & Keyboard (Italy)
        • 25212106
        • SIC1085866LCD0
        • P000453890
        • SIC1099842LCD0
        • 25207264
        • 756764-001
        • 18G241560006Q
        • SIC1290174LCD0
        • N8YN
        • UPPER CASE W/TP KB(ITALIAN) BACKLIGHT BLACK
        • SIC652397LCD0
        • BTP-3201
        • 90203558
        • SIC1095712LCD0
        • 60Y9610
        • 957-16FXXP-101
        • GL702VT-1A
        • 25205232
        • KB.I110A.075
        • 25201693
        • SIC1294160LCD0
        • 90006906
        • 613373-001
        • NB.VCY11.001
        • NB.VEP11.002
        • 613381-001
        • 04Y2620
        • 45N2158
        • P000549670
        • SIC1011581LCD0
        • SIC1022699LCD0
        • 25210930
        • SIC1295275LCD0
        • 927655-001
        • SIC1093741LCD0
        • KB.I110A.079
        • 924353-A41
        • 14.0 1366x768 WXGA HD LED Matte Screen - replaces 00HT943
        • NB.GVW11.005
        • SIC1020515LCD0
        • NB.G1F11.004
        • 699930-071
        • SIC1085385LCD0
        • SIC1305132LCD0
        • SIC1060751LCD0
        • SIC666158LCD0
        • SIC1100182LCD0
        • 91P8170
        • A1890825A
        • SIC1017097LCD0
        • 25201645
        • SIC1304558LCD0
        • 25200247
        • 605171-001
        • 646529-001
        • 451720-001
        • 500637-041
        • SIC1302603LCD0
        • KB.INT00.706
        • 04X0704
        • 50.NS043.E02
        • 90006568
        • SIC1071407LCD0
        • SIC652671LCD0
        • K000141740
        • SIC657786LCD0
        • SIC1302685LCD0
        • SIC1085338LCD0
        • SIC1021987LCD0
        • 17.1 WXGA+ 1440x900 CCFL1 Glossy Screen - replaces HSD170PG11
        • 25202367
        • A000081220
        • 25205278
        • 25202831
        • 590527-051
        • 682748-171
        • SIC643242LCD0
        • SIC1296391LCD0
        • SIC1290710LCD0
        • SIC1325419LCD0
        • 57.VKQD1.001
        • 10.8v, 6 cell, 49Wh Laptop Battery - replaces 42T4671
        • A000212110
        • Alchemy Series Illuminati Keyboard, DE
        • FRU13N5530
        • 04W0816
        • 25203637
        • 11.1v, 6 cell, 51Wh Laptop Battery - replaces TK330
        • 25209352
        • FP306
        • 04X1599
        • SIC1090786LCD0
        • SIC1085038LCD0
        • SIC1293913LCD0
        • 776451-B31
        • SIC1022162LCD0
        • SIC650442LCD0
        • SIC1200987LCD0
        • SIC1107360LCD0
        • 04W0429
        • SIC658649LCD0
        • 14.8v, 8 cell, 77Wh Laptop Battery - replaces 07G016HH1875
        • SIC1025562LCD0
        • BA59-02075N
        • A000243080
        • H000044460
        • 5B20G37193
        • 440709-001
        • SIC1121885LCD0
        • SIC1034305LCD0
        • NB.VCJ11.00E
        • 856804-001
        • SIC1293814LCD0
        • FRU04Y0815
        • P469J
        • 10.8v, 6 cell, 56Wh Laptop Battery - replaces HSTNN-XB2H
        • 598851-041
        • SIC1017093LCD0
        • 491587-001
        • SIC1294435LCD0
        • SIC1237104LCD0
        • SIC641387LCD0
        • SIC998584LCD0
        • 90NB0511-R31GE0
        • J050C
        • CBI0967B
        • FUJ:CP610615-XX
        • 25201889
        • 25202224
        • SIC1034948LCD0
        • 01HX354
        • K000109600
        • SIC1325189LCD0
        • SIC1297383LCD0
        • SIC1100192LCD0
        • 12084804
        • SIC1031447LCD0
        • 456622-001
        • FRU00HW856
        • 7.4v, 4 cell, 51Wh Laptop Battery - replaces 451-BBJS
        • SIC1016653LCD0
        • SIC1011473LCD0
        • 856773-FL1
        • SIC1111588LCD0
        • SIC1303562LCD0
        • SIC657749LCD0
        • SIC1209890LCD0
        • SIC1304188LCD0
        • 579033-041
        • SIC1023512LCD0
        • 312-0466
        • KB.TAT07.019
        • 15.0 XGA 1024x768 CCFL1 Matte Screen - replaces LQ150X1LHS2
        • L45091-261
        • MB.GC307.001
        • SIC1016389LCD0
        • SIC1020344LCD0
        • V000300250
        • SIC652616LCD0
        • L22562-001
        • 55.TZZ02.001
        • Battery for the Latitude C400
        • KB-7T433
        • SIC1294349LCD0
        • SIC1094219LCD0
        • SIC1201166LCD0
        • 595193-001
        • SIC1100139LCD0
        • SIC1234351LCD0
        • 649570-051
        • 813911-251
        • 584234-B31
        • SIC1302878LCD0
        • H000054400
        • 5B20F84351
        • 47.RB002.002
        • SIC1035611LCD0
        • SIC1024510LCD0
        • 11.1v, 9 cell, 76Wh Laptop Battery - replaces 2P700
        • SIC1225272LCD0
        • MB.PTT01.002
        • SIC657417LCD0
        • SIC657522LCD0
        • 50.TAXV7.011
        • FRU42T3168
        • SIC1098263LCD0
        • 719560-001
        • SIC1019334LCD0
        • 579027-001
        • 25213971
        • 809317-501
        • SIC690818LCD0
        • SIC1100635LCD0
        • SIC657084LCD0
        • SIC1021586LCD0
        • SIC1325464LCD0
        • SIC1297184LCD0
    C: Handheld Mobile Computer Spare Parts  (1 products)
        • FA889AA
    C: Notebooks  (163 products)
        • V3-371-35U2
        • GE72 2QC(Apache)-209NL
        • P2510-M-54EH
        • GF72 8RE-062X
        • 15-ay045ns
        • GX531GX-ES016T
        • 460
        • 840 G5
        • R30-A-17G
        • UX310UF-FC002T
        • C202SA-GJ0061
        • UX490UA
        • GT73VR 7RE(Titan 4K)-431IT
        • UX480FD-BE064R
        • 850 G4
        • L50-A-1CU
        • 14-ce2860no
        • F540LA-XX219T
        • 1018P-WHI050S
        • 14-dh0003no
        • 15-db0027nt
        • E5-475-57TC
        • G40-45
        • 255 G2
        • H730
        • 520
        • EliteBook 2540p Notebook PC (ENERGY STAR)
        • 6360b
        • A715-72G-5680
        • T580
        • CB3-131-C0UG
        • GT70 2QD(Dominator)-2471XES
        • 15
        • 15-bw031no
        • 17-by0175ur
        • 700-15
        • 1040 G4
        • Notebook 15-da1016ny
        • 7390
        • E560 + Warranty 3YR Onsite NBD
        • L402SA-BB01-RD
        • Pavilion 15-au078sa (ENERGY STAR)
        • 15-r232nl
        • 15-cw0526ng
        • g4-2203la
        • 15-ac120na
        • 15-dc0008nz
        • NC10-KA06UK
        • 1040 G2
        • L50-B-23G
        • 13-ah1006ur
        • X751MA-TY141H
        • S100
        • 650
        • 5570
        • P51
        • 17-e104ss
        • 17 R3
        • R3-131T-P1UH
        • Y720
        • Z930-14L
        • 15-ay165ng
        • 840 G3
        • 430 G6 + 14 Elite Notebook Portfolio Case
        • SF515-51T-73QP
        • UX331UA-EG158T-BE
        • Satellite Pro C660-1T1
        • V502UX-DM183T
        • N550JK-CN111H
        • V3-575G-58HX
        • 8570w
        • AS3750-2314G50Mnkk
        • X510UA-EJ625T
        • 15-s109ng
        • 113-M-6442
        • 720
        • X1 Carbon
        • 2000-2d00SV
        • X270
        • Z30-A-183
        • Pavilion TouchSmart 15-b153cl Sleekbook
        • 15
        • X1 Yoga
        • 900S
        • T580
        • CX61 2QF-1872XES
        • Gaming Pavilion - 15-dk0016nq
        • 15-dh0053tx
        • SF314-51-526T
        • 15-da0399ur
        • 15
        • R30-A1301
        • T440p
        • T480
        • A517-51G-54CX
        • 1020 G1
        • A315-51-330U
        • 15-bc411ns
        • Yoga 3 Pro
        • T520
        • 11
        • 15-cu0014tx
        • Gaming Pavilion - 15-dk0044tx
        • Studio G5
        • X555LN-XO275H
        • X540SC-XX041T
        • 5482
        • R50-B-11L
        • 3779
        • 15-da1011nb
        • 14 G5
        • X540MA-GO232
        • G50-30
        • VN7-571G-72FV
        • D540NA-DM109T
        • 13-ap0009nc
        • E5-551G-834B
        • 15-dc0018nf
        • X756UQ-T4131D
        • 15-da0287ur
        • E5-571G-50XE
        • SF114-32-P7WR
        • TP301UJ-DW056T
        • 530S
        • VPC-Y11V9E/S
        • 330
        • 450 G5 + Microsoft Office Home & Business 2019
        • PE70 2QE-094UK
        • 511-S03
        • T460p
        • Satellite Pro A120-174
        • GE60 2PC(Apache)-400XTR
        • UX305FA-FC007H
        • X556UQ-DM480T
        • F555UB-DM166T
        • 7548
        • 470 G4
        • 15-cx0017tx
        • LIFEBOOK E780
        • ES1-533-P0VG
        • E570
        • 15-ab010nz
        • E5450
        • 13
        • x2 G4 + Plantronics BackBeat GO 600
        • 15-bc039tx
        • GT73VR 7RE(Titan SLI 4K)-486FR
        • N551JW-CN092H
        • 15R (N5010)
        • F205TA-FD0064TS
        • 850 G1
        • 15-cx0019ne
        • m7710
        • E5420
        • T103HAF-GR021T-LU
        • GX660-251BE
        • 15-da0020nr
        • 17-f287nf
        • E5430
        • 15-db1011no
        • K551LB-XX249H
        • 15 G2
        • G751JY-T7449T
    C: Servers  (3 products)
        • x3550 M5
        • RD230
        • RX100 S7
    C: Tablets  (12 products)
        • 510
        • 10.1
        • TF303K-1B031A
        • SM-T813N
        • 10
        • XE300TZC
        • SM-T677
        • S70G10-0N
        • Tab E8
        • SM-T713N
        • 8.0
        • NEXUS7C
    C: All-in-One PCs/Workstations  (10 products)
        • C20-05
        • Z240ICGK-GC069X
        • 801
        • 27-xa0006nw
        • 24-f0098na
        • ET2311IUTH-BG006T
        • 20-c424nl
        • 24 2M-004RU
        • 23-q010in
        • 27-a254ng
    C: Tablet Cases  (3 products)
        • EFC-1H8SWEGSTA
        • SYFACILE101W
        • BC106578
    C: Notebook Parts & Accessories>Notebook Docks & Port Replicators  (4 products)
        • PA5228U-1ESU
        • S26391-F927-L100
        • LC.KBD00.004
        • ACA929EU
    C: Notebook Parts & Accessories>Notebook Accessories  (3 products)
        • 13GN561AP051-1
        • La Pazitively Hot! 15"
        • BA75-02260A
    C: Notebook Parts & Accessories>Notebook Cases  (6 products)
        • INSIGHT
        • 4X40N18009
        • 15.6" T-1211 Topload
        • Messenger Bag Blue Sky
        • Slim Professional Messenger
        • AftPack
    C: Server Barebones  (1 products)
        • SuperServer F627R3-RTB+
    C: Stylus Pens  (1 products)
        • AMM163US
    C: Handheld Device Accessories  (2 products)
        • BTBOUNCEOUTDOORD
        • Cradle f n30
    C: Backpack PCs  (1 products)
        • P1000-001nl

  B: Computer Cables
    C: Fibre Optic Cables  (7 products)
        • 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue
        • 2m LC/SC Duplex 9/125
        • 1m LC/ST 62.5/125 Multimode Fibre Cable
        • 3m LC/LC Duplex 50/125 Multimode Fiber Patch Cable
        • 10m LC/LC Plenum-Rated 9/125 Simplex Single-Mode Fiber Patch Cable
        • 15m USA 10Gb LC/ST Duplex 50/125 Multimode Fiber Patch Cable
        • 5m Duplex MM Fiber Optic Cable LC-MTRJ
    C: Networking Cables  (18 products)
        • 5m RJ-45 Cat6 UTP
        • 5m Cat6 UTP LSZH Network Patch Cable - Black
        • IGG310656
        • 7.6m RJ-45 M/M
        • Cat6a Ethernet Patch Cable - Shielded (STP) - 3 ft., Aqua
        • FB6625
        • Cat6 Patch Cable with Molded RJ45 Connectors - 20 ft. - Orange
        • Cat6 Ethernet Patch Cable with Snagless RJ45 Connectors - 5 ft., Red
        • 14ft Assembled Cat5E Crossover
        • Cat.5e U/UTP Patch Cable, 5.0m , Beige
        • Yellow 5 metre LSZH UTP CAT6 patch cable with RJ45 connectors
        • 150ft Cat5E 350MHz Assembled Patch Cable
        • Cat5E Crossover Patch Cable Black 0.5m
        • V7CAT6UTP-01M-BLU-1N
        • 50743
        • Cat6a, 20ft
        • 1 m Cat6 UTP LSZH Network Patch Cable - White
        • Fiber Cable (LC-LC) - 10m
    C: DisplayPort Cables  (1 products)
        • 175ft RapidRun
    C: Power Cables  (3 products)
        • 3ft Computer 18 AWG Power Cord Extension
        • Standard Computer Power Extension Cord, 10A, 18 AWG (IEC-320-C14 to IEC-320-C13), Orange, 0.61 m
        • Heavy-Duty Power Extension Cord Lead Cable, 15A, 14AWG (IEC-320-C19 to IEC-320-C14), 0.61 m (2-ft.)
    C: USB Cables  (3 products)
        • 37713
        • SB0005
        • 10.01.0204-BK
    C: Cable Interface/Gender Adapters  (4 products)
        • USB 3.1 Gen 1 Right-Angle USB-C to Gigabit Ethernet Network Adapter - 10/100/1000 Mbps, Thunderbolt 3 Compatible, White
        • Mini-DisplayPort to HDMI Cable Adapter (M/M), 3.66 m (12-ft.)
        • 60051
        • IDATA USB-SER-2CT
    C: Video Cable Adapters  (1 products)
        • MINI DISPLAYPORT TO HDMI® CABLE
    C: Cable Protectors  (1 products)
        • 16329
    C: HDMI Cables  (2 products)
        • 1.5m High Speed HDMI Cable – Ultra HD 4k x 2k HDMI Cable – HDMI to HDMI M/M
        • 3m High Speed HDMI® Cable with Ethernet - Ultra HD 4k x 2k HDMI Cable - HDMI to HDMI M/M
    C: Wire Connectors  (1 products)
        • RJ45 Cat5 8x8 Modular Plug for Flat Stranded Cable 10pk
    C: SCSI Cables  (1 products)
        • 470-11540

  B: Software
    C: Software Licenses/Upgrades  (38 products)
        • 00D8199
        • MSS Cisco Firepower IDP Sensor Fiber
        • ScanMail Suite f/Microsoft Exchange, RNW, GOV, 14m, 501-750u
        • SLNA0079
        • PTNN0004
        • Enterprise Security f/Gateways, RNW, 751-1000u, 33m, ENG
        • SW-UPG-PC-S200-5-25
        • SafeSync for Business, RNW, 9m, 26-50u
        • Backup Exec 2010 Central Admin Server Option, v13.0, Rewards Band A UPG + Basic Maintenance, ML
        • Enterprise Security Suite, CUPG fr/ NS, EDU, 1Y, 26-50u, ML
        • WinZip 23 Standard
        • CSM Suite f/ Microsoft Exchange Enterprise, RNW, 2Y, 251-500u, ENG
        • Worry-Free Business Security 7 Advanced, RNW, 101-250u, 33m, Win, ML
        • ScanMail Suite f/Microsoft Exchange, RNW, EDU, 7m, 51-100u
        • InterScan Messaging Security Suite, 260-500u, Win, EN
        • ATP-E-NEW-25-50-3Y
        • UPGRADE, TAB-MC-V10 TO MC-V10-500
        • Worry-Free Business Security 9 Standard, EDU, RNW, 13m, 101-250u
        • VTAS DATA INSIGHT FOR DATA LOSS PREVENTION, INITIAL SOFTWARE MAINTENANCE, 50-99
        • Enterprise Security f/Gateways, RNW, EDU, 101-250u, 15m, ENG
        • DLP-SIR-NEW-AG-5K-10K-2Y
        • CSM Suite f/ Lotus Notes Enterprise, RNW, 19m, 251-500u
        • CSM Suite f/ Microsoft Exchange Enterprise, RNW, 34m, 26-50u, ML
        • Backup Exec 2010 Remote Agent f/ Linux / UNIX Servers, v13.0, Rewards Band D Comp.Upgr.+Essential, ML
        • Worry-Free Business Security 8 Advanced, EDU, RNW, 23m, 26-50u, ML
        • LANDesk DADEA BUN 1-year Service 2K-4999 E LTU
        • Worry-Free Business Security Services 5, RNW, 101-250u, 2m, FRE
        • 6113
        • DATA LOSS PREVENTION FORM RECOGNITION ADDON, INITIAL SOFTWARE MAINTENANCE, 250-4
        • ScanMail Suite f/ IBM Domino, Windows, RNW, 751-1000u, 14m, ENG
        • WBUA0032
        • Backup Exec 2012 Windows Server Edition, 1u, 1Y Initial ES, RNW, ENG
        • Enterprise Security f/Endpoints & Mail Servers, RNW, EDU, 1m, 51-100u, ML
        • Worry-Free Business Security 8 Standard, RNW, 27m, 101-250u, ML
        • AT-8624T/2M-V2-10-NCA5
        • LIC-NCC-NSW-ZZ0004F
        • ServerProtect f/ Win/NW & Lin, RNW, 251-500u, 31m, ML
        • MSS-ASMSE-ADD-AG-2500-5K-1Y
    C: Antivirus Security Software  (11 products)
        • Norton Internet Security 2008 + Norton Antibot 1.0 (3 users)
        • Internet Security 2014, 3U, RNW, 1Y
        • Endpoint Antivirus  for Home  User 5 - 10
        • Mail Security 8340
        • Endpoint Security f/Business - Advanced, 10-14u, 3Y, Cross
        • File Security for Linux and FreeBSD User 2
        • Security f/Virtualization, Server, 5-9u, 1Y, Cross
        • Endpoint Security f/Business - Select, 15-19u, 1Y, GOV
        • Total Security
        • Security f/Mail Server, 25-49u, 3Y, Add
        • Endpoint Protection Advanced
    C: Computer Utilities>Printer Software  (1 products)
        • 301N84410
    C: Multimedia Software>Graphics Software  (1 products)
        • PaintShop Pro X6, NL/FR/IT
    C: Networking Software>Virtualization Software  (1 products)
        • VMware vCenter Server 5 Standard f/vSphere, 5H/I, 1Y
    C: Multimedia Software>Video Software  (1 products)
        • Roxio Toast 11 Titanium
    C: Computer Utilities>Storage Software  (1 products)
        • WinZip 18 Pro, 50000-99999, EDU, ML
    C: Computer Utilities>General Utility Software  (1 products)
        • WinZip 16 Standard, 1u, Win, NL

  B: Telecom & Navigation
    C: Mobile Phone Spare Parts  (2 products)
        • GH59-12969A
        • Li-Ion 3.7v 1120mAh
    C: Mobile Device Keyboards  (1 products)
        • 701428-331
    C: Smartphones  (6 products)
        • Sola
        • GSmart Roma RX
        • G398F
        • SM-A800
        • SM-G975F
        • SM-G950F
    C: Mobile Phone Cases  (9 products)
        • Premium Flip TPU Case Apple iPhone 7, iPhone 8 Black
        • TAGE3163K
        • Sensation
        • EF-FS727L
        • PocketBook
        • 200102293
        • Saffiano Wallet Case Samsung Galaxy A8 (2018) Copper
        • TPUSA829T
        • ETUISMI8190
    C: Holders  (2 products)
        • GrabTab Fun with Food Collection
        • HA-E60IO
    C: Telephony Equipment>Telephones  (2 products)
        • M3301GW/FR
        • SE8880B/12
    C: Screen Protectors  (8 products)
        • TEM0002A
        • Vikuiti ADQC27
        • OSFTAG13.5L/P-SURFB
        • CANPSSD1100S
        • Vikuiti ADQC27
        • Vikuiti ADQC27
        • ET-FN910C
        • SONDSCW300S
    C: Mobile Phones  (2 products)
        • Cookie (KP500)
        • GT-S5220
    C: Mobile Headsets  (2 products)
        • In-Ear Stereo Earbuds Green with In-line Microphone - handsfree, tangle free with flat cable design
        • Earhook Headphones SHS8100/98

  B: Printers & Scanners
    C: Printing Supplies>Toner Cartridges  (23 products)
        • 106R03527
        • ML2250
        • OC301Y-FRC
        • 6015Y-FRC
        • TK18-XL-FRC
        • SV043A
        • Yellow Laser Toner - Ricoh 841507 - For Ricoh Aficio MP C 2051 / 2551
        • 32RAN006R01526
        • 702Y R
        • TD-81K
        • Tonercartridge EP-83 rood
        • VX Toner Cartridge compatible
        • Black toner cartridge. Equivalent to Epson S050436. Compatible with Epson Aculaser M2000
        • Type C7
        • CE255X
        • 657X Mgn Contract LJ Toner Cartridge
        • Laser Toner for select HP printer - replaces CB435A
        • 111007
        • Standard Cartridge for E232 / E33x / E240 / E34x
        • 1T02LH0AS0
        • 64075SW
        • 78C20CE
        • CF380A
    C: Print & Scan Accessories>Printer/Scanner Spare Parts  (7 products)
        • PA03753-K982
        • 40X8421
        • RK2-1992-000CN
        • RM1-2721-040CN
        • RM1-1717-000CN
        • 40G0837
        • LJ0893001
    C: Printing Equipment>Laser Printers  (6 products)
        • 6510DNI
        • C511dn
        • 7400V_DN
        • CS622de
        • T640dtn
        • Color Enterprise M553n